### ISSUE TITLE
[Correction] Rename "Lightning Address" with "NodeID"

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#1005]
In Umbrel dashboard - Lightning, when you go to check node ID, from the 3 dots, it says "Lightning Address".
This term is not correct and can confuse users. Also now we have a real Lightning Address that is a total different term https://lightningaddress.com/ and should be nice to have it implement it into Umbrel OS.
It should be also more visible (many noobs don't even know about it) and renamed as "Node ID" or "Public key"
Please make a more visible button with a big label "Node ID" so new users see it.

Also the channels backup, make it more visible or intuitive. Noobs DO NOT CLICK on those 3 dots and do not make backups.
Example how would be more visible for the blind noobs...
![image](https://user-images.githubusercontent.com/56997124/135541675-ad64b00c-f1dc-4eab-af02-c8b45d46a7e6.png)

**Comment by maynn** [comment]
Good suggestion

**Comment by nmfretz** [comment]
This is now the case in the Lightning Node app. Thanks to @Darth-Coin for this suggestion!

<img width="289" alt="image" src="https://github.com/getumbrel/umbrel/assets/85373263/1c476677-449b-4506-a4b5-6d3533e83798">
