### ISSUE TITLE
[Issue] Umbrel showing funds without complete sync

### ISSUE THREAD

**Issue by proof-of-reality** [getumbrel/umbrel#1041]
Yesterday i've started my node from the scratch because of what appears to be a HDD failure after i replaced the heat sink on my raspi 4B, then i realized that my onchain funds was matching what they should be, even before i synced 100%.

![unknown](https://user-images.githubusercontent.com/43297242/136677209-b1aebe6d-7c22-4428-a207-039646a87fc5.png)

Is this working as expected? Because i thought my onchain funds would just be available only after 100% sync

**Comment by louneskmt** [comment]
This is expected and working great so why open an issue here?

**Comment by mayankchhabra** [comment]
@proof-of-reality this working as expected, no worries! Umbrel uses neutrino as the backend while Bitcoin Core is syncing for the LND wallets (think of it as light-mode) and automatically switches to Bitcoin Core once the sync is complete.
