### ISSUE TITLE
New version of elecrs is much slower.

### ISSUE THREAD

**Issue by Transisto** [getumbrel/umbrel#1046]
https://github.com/romanz/electrs/issues/539

**Comment by tlindi** [comment]
Electrs 0.9.1 coming from umbrel also suffers "Illegal instruction" and cores for example on HP Microserver N36L which CPU lacks SSE4.2 support. Issue causes electrs service to restart forever.

See following for more details

https://github.com/romanz/electrs/issues/536#issuecomment-950747379

Please consider bump electrs version to at least 0.9.2.

**Comment by tlindi** [comment]
My legacy HP Illegal instruction is fixed by: https://github.com/getumbrel/docker-electrs/pull/9#issuecomment-1004806934
