### ISSUE TITLE
Sentinel (Samurai Dojo) not showing balance/transaction history since update 0.4.4

### ISSUE THREAD

**Issue by lightningdave** [getumbrel/umbrel#1048]
Since updating to version 0.4.4 Sentinel ([link](https://code.samourai.io/wallet/sentinel-android)) shows zero balance and no transaction history,

Logging in to umbrel: Dojo Maintenance Tool, it show that all the data is synced:

![image](https://user-images.githubusercontent.com/92384389/136979590-135830ea-113e-4094-998b-29d651a93288.png)

I have reinstalled the sentinel android app.
Paired to Dojo.
Added xpub

But does not show any information on the account.
PS: I don't know how to resize images in github md...
![sentinel](https://user-images.githubusercontent.com/92384389/136980701-3995475e-0b09-4cd2-8a17-b79b1e52b143.jpeg?s=1)

I have raised this to the samurai team and they told me to submit an issue here.

**Comment by louneskmt** [comment]
Hey, did our latest release solve this issue?

**Comment by nillawafa** [comment]
This is still an issue with the current version. I sent funds to samourai wallet connected to umbrel samourai server and can't see the balance. Samourai team can't help.
