### ISSUE TITLE
Enable pruning when drive size is < 450GB

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#105]

**Comment by nolim1t** [comment]
Probably better to drop this now because of electrum

**Comment by mayankchhabra** [comment]
Good idea

**Comment by pavlenex** [comment]
@mayankchhabra was this ever added? Want to give Umbrel a try but don't have enough storage.
Also having non-pruned nodes and recommending 1TB storage could potentially mean a massive crash at some point for big portion of users as chain grows.

**Comment by mayankchhabra** [comment]
Hey @pavlenex, pruning wasn't added and for now ~600GB of free space is the minimum requirement.

We didn't implement pruning because of Electrum server (electrs), which doesn't work against a pruned node. Completely agree with you that 1TB storage at some point wouldn't be enough, and we can't expect users to keep migrating to larger drives as they run out of space.

But before that happens, we'll revisit this issue and try to support pruning in a way that doesn't break other features (such as by requesting blocks on-demand from other nodes and verifying their hashes against own node).

**Comment by nuganics** [comment]
A pruned node would be great. Im in Australia and I can't download 380 GB but would love to be able to get involved with lightning. Below were possible solutions to get Electrum working with a pruned node.

- Set up EPS, rescan your wallet, and then enable pruning.
- Set up EPS with brand new never-used-before wallets, and then rescanning is not needed.
- Set up EPS on another computer which has the full blockchain, rescan the wallet and then copy it over to your raspberry pi.

**Comment by andrestaffe** [comment]
Hi, electrs nor electrumx do support prune mode but what about bwt?
[https://github.com/bwt-dev/bwt](url)

Especially if lightning is not necessary?!

**Comment by meryacine** [comment]
> Especially if lightning is not necessary?!

Note that Core-Lightning supports running on pruned nodes already.
