### ISSUE TITLE
Lnbits and sqlite

### ISSUE THREAD

**Issue by alexander-koval** [getumbrel/umbrel#1051]
Hello guys!

I have a question. Why your Lnbits config file, uses only sqlite database. What should I do, if I want to use PostgreSQL?

**Comment by HamiltonWang** [comment]
You need to edit the .env file.

# add the database connection string to .env 'nano .env' LNBITS_DATABASE_URL=
# postgres://<user>:<myPassword>@<host>/<lnbits> - alter line bellow with your user, password and db name
LNBITS_DATABASE_URL="postgres://postgres:postgres@localhost/lnbits"
# save and exit

**Comment by nmfretz** [comment]
closing old support issue
