### ISSUE TITLE
Mempool Error after update

### ISSUE THREAD

**Issue by dm807cam** [getumbrel/umbrel#1053]
After recent update Mempool API returns error message: **Cannot GET /api/v1/address** although Mempool is running and working. Update was done more than 12 hours ago.

**Comment by dm807cam** [comment]
I noticed that this is only an issue with "address" calls other API calls work. It appears that the "v1" part of the URL is missing. 
For example:
http://umbrel.local:3006/api/v1/fees/recommended
http://umbrel.local:3006/api/address/1wizSAYSbuyXbt9d8JV8ytm5acqq2TorC

**Comment by Cajun75** [comment]
> After recent update Mempool API returns error message: **Cannot GET /api/v1/address** although Mempool is running and working. Update was done more than 12 hours ago.
