### ISSUE TITLE
Umbrel stuck during new v0.4.4 update and non-responsive

### ISSUE THREAD

**Issue by savarela88** [getumbrel/umbrel#1059]
Hi, I started updating my Umbrel node to the latest version but it's been a few hours and it seems to be stuck at ~10% and hasn't moved an inch from there

![image](https://user-images.githubusercontent.com/87943392/137644553-28c095e6-b972-4e31-bc7b-c0fa42ac5377.png)

Tried to go through the command line but could not even connect through umbrel@umbrel.local nor @ the IP address.

![image](https://user-images.githubusercontent.com/87943392/137644582-d6b1ad30-bbc4-4f45-93c2-ff7681151243.png)

Any ideas? Not sure if I should go straight to a re-flashing as I don't want to lose anything but I'm open for suggestions

**Comment by jeffreyjackson** [comment]
I had the same issue and was able to resolve by uninstalling all apps and applying the update.  after that I was able to reinstall my apps and move forward as expected.

**Comment by savarela88** [comment]
Yeah, but the issue is I cannot enter de UI at all. It's completely stuck in the update page and won't move from there. 

Cannot access through command line either so I'm literally stuck but don't want to re-flash (if possible) because my channel backup seems to be 2 months old

![image](https://user-images.githubusercontent.com/87943392/138009863-470c0bf7-e266-4d3e-8c56-c288565e81fa.png)

**Comment by nmfretz** [comment]
closing old support issue
