### ISSUE TITLE
[Feature request] Add c-Lightning docker as additional node option

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#1075]
It will be good to have an additional LN implementation, aside of existing LND instance.
Umbrel being dockerized apps server, can easily add also a docker for c-lightning instance and user can choose which one to start and / or use both in the same time, as 2 LN nodes instances, behind Tor. Or even one instance on clearnet and another one behind Tor.
I know that is working both instances using the same bitcoind node for blocks provider so this feature will be great to have for many aspects:
- balancing liquidity
- failover payment solution for merchants (if one LN node have issues, the other still able to take payments)
- routing scenarios between those 2 LN nodes
- user can have both implementations for better compatibility with other nodes and using more features

**Comment by kilrau** [comment]
@lukechilds is this something you guys would consider?

**Comment by nmfretz** [comment]
[Core Lightning app](https://apps.umbrel.com/app/core-lightning) is available now!
