### ISSUE TITLE
mempool app won't start propperly

### ISSUE THREAD

**Issue by cjvanzwol** [getumbrel/umbrel#1076]
After starting Umbrel, the mempool app won't start. The icon is stuck flashing with the "Starting..." underneath it.

The problem occurred after updating to v0.4.4. The app worked fine in v0.4.3

What i did:
- restart Umbrel
- delete-install from Umbrel webinterface
- stopping-starting from ./scripts/app
- uninstall-install from ./scripts app
- trying to find out if mariadb was the problem:
  1. ./scripts/app stop mempool
  2. rm -r apps/mempool/mysql
  3. ./scripts/app start mempool > the app shows as started in the Umbrel webinterface, but offcourse the app doesn't start propperly
  4. ./scripts/app stop mempool
  5. restored files in apps/mempool
  6. ./scripts/app stop mempool > problem returns

Debug log Umbrel for mempool says:

> web_1      | 2021/10/27 08:32:05 [emerg] 7#7: host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
> web_1      | nginx: [emerg] host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49

As far as i can see, there is nog such file in de nginx container

**Comment by aphex3k** [comment]
I seem to have the same issue as OP initially:

I see this repeating in `docker logs -f mempool_web_1`:
```
2021/11/02 23:50:16 [emerg] 7#7: host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
nginx: [emerg] host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
2021/11/02 23:51:22 [emerg] 8#8: host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
nginx: [emerg] host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
2021/11/02 23:52:28 [emerg] 7#7: host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
nginx: [emerg] host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
2021/11/02 23:53:33 [emerg] 7#7: host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
nginx: [emerg] host not found in upstream "mempool.space" in /etc/nginx/conf.d/nginx-mempool.conf:49
```

I'm on latest umbrel 0.4.6 with mempool app docker-compose file from this git repo.

- mempool/frontend:v2.2.2@sha256:515b9a3ab3cc593fe599393b316d4d016335801fbba02ef8c6bb38082597f7cc
- mempool/backend:v2.2.2@sha256:c758345017587dd9e42047528cf6cd71ceae70cebd1a09ce875959259612a2ee
- mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd

**Comment by Falci** [comment]
Same here. 

I was wondering if it could be related to PiHole, but the logs shows `mempool.space` in green/allowed

**Comment by cjvanzwol** [comment]
I have PiHole running as well. I wanted to move my PiHole out of umbrel anyway (i want PiHole tot keep running, even if i have tot restart umbrel for any reason), so i'll try to uninstall PiHole and then install Mempool again.

**Comment by cjvanzwol** [comment]
> Same here.
> 
> I was wondering if it could be related to PiHole, but the logs shows `mempool.space` in green/allowed

I had PiHole running as well. I wanted to move my PiHole out of umbrel anyway (i want PiHole tot keep running, even if i have tot restart umbrel for any reason), so I uninstalled the PiHole app and then install Mempool again.

Still mnot working...

**Comment by GalvaniObst** [comment]
This seems to be a name resolution issue. I had the same error message. After hard coding the DNS server and restarting Umbrel the app mempool worked.

This is what I did:
```1. Hardcode DNS server in docker daemon.json

Edit /etc/docker/daemon.json

{
    "dns": ["1.1.1.1", "8.8.8.8"]
}

Found this here: https://serverfault.com/a/918568
(Thanks wisbucky)

**Comment by cjvanzwol** [comment]
Tnx @GalvaniObst that solved my problem!

**Comment by lukechilds** [comment]
Users that are suffering from this, if you visit to mempool.space in your browser, does it open properly, or do you get an error?

**Comment by GalvaniObst** [comment]
When connected via ssh I was able to do a dns lookup and it resolved properly.
So yes, name resolution for mempool.space worked from the raspberry, my machine etc..

As background for my setup.
I'm running pi-hole and my DHCP propagates to use pi-hole for DNS.
Gateway 192.168.0.1
Umbrel 192.168.0.2

I think the container was told to talk to 192.168.0.2 for DNS but wasn't able to reach it.

**Comment by lukechilds** [comment]
Got it, very helpful thanks @GalvaniObst!

If anyone else can let me know too that would be great.

**Comment by gibbs19** [comment]
This worked for me too. Thanks a lot!

Note for anyone having the same issue - it's perfectly fine to create file if you don't have a `daemon.json` already in there. You can either `touch` the file first or create the file in your editor and save it as a new file.

**Comment by cjvanzwol** [comment]
Changing DNS solves it.

I changed the docker-compse for the mempool app, and added the dns for the container
```
services:
  web:
    dns:
        - "1.0.0.1"
        - "1.1.1.1"
```

But my system keeps revulting my changes after updates of docker of umbrel.

Would be nice to have a permanent solution.

**Comment by jonathanalevi** [comment]
Still having this problem, despite trying all the suggestions here in dhcpcd and daemon.json. Gonna try removing PiHole and see if that does anything.

**Comment by lukechilds** [comment]
> Would be nice to have a permanent solution.
@cjvanzwol editing the NDS settings [here](https://github.com/getumbrel/umbrel/issues/1076#issuecomment-991682514) instead of in the compose files will persist between Umbrel updates.

@jonathanalevi sorry about that, are you able to provide mempool logs so we can take a look? IF you ssh in to your Umbrel you can get the logs with:

```
~/umbrel/scripts/app compose mempool logs --tail 100
```

**Comment by nmfretz** [comment]
closing old support issue
