### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by indomitorum** [getumbrel/umbrel#1078]
Is 2FA something Umbrel is working on?. It certainly lacks more security as access to your node by a bad actor can drain your funds.

**Comment by dsbaars** [comment]
This is already mentioned in issue #985 but adding this as a separate issue might help in actually building this feature.

**Comment by indomitorum** [comment]
After the recent events. I do think that this is a priority even if Umbrel doesn't as I have been told recently.

**Comment by dsbaars** [comment]
I finished building this functionality yesterday. 
- It works with every Google Authenticator-compatible TOTP app. 
- It adds extra security to the Umbrel dashboard, which is also exposed over Tor. 
- It is optional to use.

https://user-images.githubusercontent.com/480514/142405668-1185301b-0aba-4ee2-bde7-7281f353eeb5.mp4

I'm already using it on my Umbrel mainnet environment as well, my only concern is that the `user.json` needs a manually addition at this moment. I can't seem to find any migration hooks in the update scripts, or am I missing something here?

**Comment by AaronDewes** [comment]
Can you share some code? What exactly is required to be added to user.json manually during the update script?

**Comment by mayankchhabra** [comment]
That looks very well done! Great job, @dsbaars. Thanks for taking this on!

A hook can be added to `scripts/update/01-run.sh` which will be automatically executed on the next OTA update. See for example this piece of code that stripped Lightning Terminal's password in the last OTA update:

https://github.com/getumbrel/umbrel/blob/dae920cfd84adebb42f1b35f6e8b1466c4f959e4/scripts/update/01-run.sh#L239-L244

**Comment by dsbaars** [comment]
> Can you share some code? What exactly is required to be added to user.json manually during the update script?

Here is the code:
[@dsbaars/umbrel-manager#feature/2fa](https://github.com/dsbaars/umbrel-manager/tree/feature/2fa)
[@dsbaars/umbrel-dashboard#feature/2fa](https://github.com/dsbaars/umbrel-dashboard/tree/feature/2fa)

Two keys need to be added to `user.json`:
````json
{
  "totpKey": "",
  "totpEnabled": false
}
````

**Comment by Dar1Theory** [comment]
Ok, I've downloaded 4.9. I didn't turn on 2fa on either node. However, one node works (no 2fa) the other is asking for my 2fa (which obviously I don't have since I didn't set it up). 
Please tell me what conf or json contains the "turn 2fa off" switch?

**Comment by nmfretz** [comment]
Closed by:
https://github.com/getumbrel/umbrel-manager/pull/112
https://github.com/getumbrel/umbrel-manager/pull/112
