### ISSUE TITLE
issues with recovering umbrel wallet with 24 word seeds

### ISSUE THREAD

**Issue by JoeEagle33** [getumbrel/umbrel#1089]
Hello guys, 

when i recover my umbrel wallet, i get "Error:  user already exist"
![UmbrelRecovery](https://user-images.githubusercontent.com/48148110/140171176-ad8904f9-8bc3-46d3-89a0-53c95005e2ca.png)

I run umbrel on ubuntu server 21.10 .
I was be able to recover with the 24 word phrase successfully before, but now i can't recover my wallet.  
Do you have any suggestions ?

**Comment by mikelseverson** [comment]
This error appears if the registration process has already completed.
Refreshing will navigate the user to umbrel login page, user can log in.

In this instance, there may still be an issue:
This may be an indicator seed was incorrectly entered and registration errored out
**The seed is case sensitive**

I'd advise clearing user data
> sudo systemctl stop umbrel-startup && sudo rm -rf ~/umbrel/lnd/!(lnd.conf) && sudo rm ~/umbrel/db/user.json && sudo rm ~/umbrel/db/umbrel-seed/seed && sudo systemctl start umbrel-startup

And start over the recovery process

**Comment by nmfretz** [comment]
closing old support issue
