### ISSUE TITLE
Can't connect to Sphinx: Generate Token Failed

### ISSUE THREAD

**Issue by willemsFEB** [getumbrel/umbrel#1093]
I followed this [guide](https://github.com/stakwork/sphinx-relay/wiki/Home-node-FAQ) to set up my (umbrel) node in order to use Sphinx Relay (connected channel to gameb_1 and set fees to 0).

I downloaded the android application for Sphinx Chat and scanned the QR code to connect, but I get the following error:
```
Generate token failed
```
and as a notification I get
```
Tor: Off
java.io.IOException: Tor executable file not found
```
Is there something I'm missing in the setup?

**Comment by willemsFEB** [comment]
I got an answer from the Sphinx team, apparantly the App Store app has this issue, but when you install the app manually from their releases page, it works
https://github.com/stakwork/sphinx-kotlin/releases/tag/1.0.0-alpha32

**Comment by aphex3k** [comment]
This is not an umbrel issue

**Comment by nmfretz** [comment]
closing old support issue
