### ISSUE TITLE
cannot install LN Markets

### ISSUE THREAD

**Issue by mth75** [getumbrel/umbrel#1095]
Hi,

I'm trying to install LN Markets, after clicking the INSTALL button the installation falls in a loop and shows installing ... for ever. After aborting I can Install again with the same result.

Best regard from the Netherlands!

**Comment by mth75** [comment]
and solved with the latest update.

**Comment by louneskmt** [comment]
@mth75 Thanks for the report and sorry. 

Now that it has been fixed, can you close the issue?

**Comment by mth75** [comment]
Yes, I can ...
