### ISSUE TITLE
Add a proxy server

### ISSUE THREAD

**Issue by 0xtlt** [getumbrel/umbrel#1096]
Hello!

I often use the Lightning and I would like to be able to use it much faster while keeping my node.

There is an ssh feature to create a proxy on a remote host and therefore use an external server as a bridge so as not to reveal my node directly.

The idea is to be able to connect the electrum/Lightning server of my umbrel to my application using an external server that I will pay a few dollars from any hosting providers for example to use the ip associated with a specific port to connect.

The command is as follows:

`ssh -NR 0.0.0.0:443:localhost:443 user@host`

(Thanks to @clementd64 for the tip)

What do you think?

**Comment by esackbauer** [comment]
Why would you do this when your node is already reachable via Tor?

**Comment by techtastet** [comment]
> Why would you do this when your node is already reachable via Tor?

As I said above, I want to make the connection to my node really fast, not just waiting to see my lightning..

**Comment by esackbauer** [comment]
I had this issue when e.g. BlueWallet was using its internal Tor client. Use Orbot instead, is much faster!

**Comment by techtastet** [comment]
Good idea but not working with iOS :/

**Comment by esackbauer** [comment]
Then use a VPN to the network where the Umbrel is hosted.
