### ISSUE TITLE
Can't login to the dashboard, but I can SSH. The dashboard is just frozen when I put the password in

### ISSUE THREAD

**Issue by dylanbaker12** [getumbrel/umbrel#1100]
![IMG_20211109_104448.jpg](https://user-images.githubusercontent.com/48352298/140956511-ad2f6032-a050-4b8e-a025-6b53e0e1fd70.jpg)

The login this morning out of nowhere just won't work, but I can SSH into the pi.

Any suggestions would be great.

**Comment by nmfretz** [comment]
closing old support issue
