### ISSUE TITLE
Failed to Mount External Storage - USB Freezes

### ISSUE THREAD

**Issue by tufgithub** [getumbrel/umbrel#1109]
Raspberry Pi 4 4g server (also tried 8g version)
SanDisk 64g SD Card (also tried SanDisk 16g and 32g SD Card)
Patriot 1TB USB card (also tried PNY 1TB USB card)

Hardware had been running Umbrel 4.x with described initial hardware since April without issue (normal updates, occasional reboots)

After recent reboot, system would not start.
Performed a clean install and issue began and has been persistent:

If no USB card is installed, system will boot, all USB devices function and are recognized by ls -usb (keyboard, storage if inserted)

If USB card is installed, system will boot, receive error saying (External Storage Failed to Mount), will receive Umbrel prompt, keyboard and other USB devices are not active (no lights, no response).

Appears to be Debian/Umbrel issue as when I install Raspian, there are no issues.

I have tried multiple installs, older version of Umbrel (down to 3.x), reformatting all drives from both Windows and Linux using NTFS and EX, and unformatted disk, as well as different hardware (3 Raspberries, memory cards and USB drives).

I suspect a USB setting or load order setting??

Thank you

**Comment by nmfretz** [comment]
closing old support issue
