### ISSUE TITLE
I Started the Node but it is Synchronizing all the time, never ends, 

### ISSUE THREAD

**Issue by Juanggv** [getumbrel/umbrel#1126]
I have a Rasberry Pi 4 conected by Ethernet, I am using HDD
the application said Your Umbrel is up and Running 
![imagen](https://user-images.githubusercontent.com/95034042/143450016-61af36e3-ced7-4fc5-9088-a494e9cdee50.png)

**Comment by aphex3k** [comment]
The initial step of synchronization takes a significant amount of time (hours/days) and downloads about 450GB of blockchain data to your node.

**Comment by dgbki5g** [comment]
> The initial step of synchronization takes a significant amount of time (hours/days) and downloads about 450GB of blockchain data to your node.

Hi!
My home screen looks the same. In the previous version each synced block was shown in the sync column. Now block hight and the flow animation is no longer shown for both, Bitcoin core and lightning wallet. 

Was that changed on purpose?

**Comment by Juanggv** [comment]
> 

sorry man it was about 30 days ago and stil are in 210.1 GB, can you helpme?

**Comment by nmfretz** [comment]
closing old support issue
