### ISSUE TITLE
umbrel-dev: How to test app wih Apple M1?

### ISSUE THREAD

**Issue by tiero** [getumbrel/umbrel#1129]
I have an Apple M1 and seems can't install Virtualbox

```
Error: Cask virtualbox depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
```

There is any way to test apps on Umbrel? directly on rasbperry pi?

**Comment by aphex3k** [comment]
See: https://github.com/getumbrel/umbrel-dev

**Comment by tiero** [comment]
mmm is it this needed to be merged? https://github.com/getumbrel/umbrel-dev/pull/23

**Comment by louneskmt** [comment]
You can checkout the `parallels` branch.

**Comment by nmfretz** [comment]
If anyone is making their way to this old issue, new instructions for umbrel-dev are found here:
https://github.com/getumbrel/umbrel-dev

# Deprecated

The umbrel-dev CLI is now deprecated. To virtualize a local Umbrel instance for development we recommend using [Multipass](https://multipass.run/).

Once Multipass is installed you can run an Umbrel VM with:

```shell
multipass launch --name umbrel-dev --disk 10G
multipass exec umbrel-dev -- sh -c 'curl -L https://umbrel.sh | bash'
```

You can get an interactive shell inside the VM with:

```shell
multipass shell umbrel-dev
```
