### ISSUE TITLE
Updated to latest Version 0.4.9 but not Updated in UI

### ISSUE THREAD

**Issue by AverageJoeShmo** [getumbrel/umbrel#1152]
My Umbrel Node states that it is on the latest version, yet I wasn't seeing the updated UI like everyone else was seeing. I decided to manually update the version via SSH, which was completed successfully, and still no updated UI. I finally decided to update the SD card fully, and just flash the card fresh to correct the issue, which still hasn't worked.

The Debug log tells us that the Version it is currently on is the latest 0.4.9. But as you can see with the images below, nothing has actually updated on the UI itself. 

Here is the link the the Debug: https://pastebin.com/gSi39f9T

Everything within Umbrel works as expected (Bitcoin Core, LN, Apps, etc.), it just hasn't brought me any new features like it should be.

Anyone had or are having this issue? It just seems like it tells me it is updated when it actually is not. I have posted pictures as well to show what the system UI looks like currently

![Settings Page](https://user-images.githubusercontent.com/95729238/145141110-8196f4c1-f621-4d74-aba8-dedfcb4f0d33.JPG)

![Apps](https://user-images.githubusercontent.com/95729238/145141121-f87af5a4-519e-411f-b597-aba046e2a482.JPG)

![App Store](https://user-images.githubusercontent.com/95729238/145141126-b9b7e653-d638-4461-a765-85c73a181931.JPG)

.

**Comment by hashes4merkle** [comment]
@lukechilds Any good path forward here? Seeing similar on a friend's node.

**Comment by AverageJoeShmo** [comment]
@hashes4merkle Solved the issue. Thanks.
