### ISSUE TITLE
Spinning wheel of death on start/recover

### ISSUE THREAD

**Issue by Hukuma1** [getumbrel/umbrel#1166]
Had some issues after updating my umbrel so I decided to nuke it all except the `bitcoin` folder which has my synced blockchain data.

The on-boarding starts normal and I fill in my username and password.

It's stuck on the wheel with no words or buttons to press.

<img width="868" alt="umbrelstartup" src="https://user-images.githubusercontent.com/54511555/146070993-4622760a-07f0-4476-acde-ff6add4c07ae.png">

Trying to recover wallet using the recover option also sends me to an endless loading wheel.

<img width="612" alt="umbrelrecovery" src="https://user-images.githubusercontent.com/54511555/146063815-51ce6276-3d5f-477a-aef1-62d351ae1209.png">

Latest version 0.4.10

If I re-do these steps in 0.4.9 it works just fine.

Edit: Clicking on `NOTE DOWN LATER` gives me an error of `Invalid seed length`

**Comment by michelangelato** [comment]
I also had this problem but fixed downgrading the os version to 0.4.9, then the initial setup succeed.

On RPi4, connect via ssh then:
```
sudo systemctl stop umbrel-startup
rm .env && sudo ./scripts/configure
sudo ./scripts/update/update --repo getumbrel/umbrel#v0.4.9
sudo systemctl start umbrel-startup
```

finally retry the setup.

**Comment by efrainmunoz** [comment]
Same here on raspberry pi 4. It hangs on the "note down your secret words". Pressing the "note down later" link shows "error: invalid seed length".

**Comment by user411** [comment]
See https://github.com/getumbrel/umbrel/issues/1151#issuecomment-993180224 for fix.

**Comment by Hukuma1** [comment]
That's not really a fix, that's just a workaround to stick to older version. D:

**Comment by bluefake101** [comment]
I tried several versions, but none worked. Still the wheel.

**Comment by user411** [comment]
Admittedly a workaround. I had to

1. Remove all the existing failed umbrel-dev containers in VirtualBox
2. `sudo scripts/update/update --repo getumbrel/umbrel#v0.4.9`
3. umbrel-dev reload
3. Login and set password
4. sudo scripts/update/update --repo my-repo
5. scripts/app install my-project
6. umbrel-dev reload

Now, there was another caveat as well with the current umbrel-dev, I needed to add to the default Vagrantfile to keep from erroring out while building:

```
  # Update package lists
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y build-essential libssl-dev libffi-dev python-dev
  SHELL
```

Probably something will be wrong with these directions - I spent hours dinking around with this.

**Comment by rsteckler** [comment]
30 days and it's not possible to actually start the software?  Not confidence inspiring.

Here's the javascript console:
```
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'length')
    at t.value (app.9ac66e45.js:1)
    at o.updateText (app.9ac66e45.js:1)
    at o.mounted (app.9ac66e45.js:1)
    at ne (chunk-vendors.3aa820c1.js:63)
    at En (chunk-vendors.3aa820c1.js:63)
    at Object.insert (chunk-vendors.3aa820c1.js:63)
    at z (chunk-vendors.3aa820c1.js:63)
    at o.__patch__ (chunk-vendors.3aa820c1.js:63)
    at o.Yn.t._update (chunk-vendors.3aa820c1.js:63)
    at o.r (chunk-vendors.3aa820c1.js:63)
ae @ vue.runtime.esm.js:1888
warn.js:13 [BootstrapVue warn]: tooltip - Unable to find target element in document.
a @ warn.js:13
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'length')
    at t.value (app.9ac66e45.js:1)
    at o.updateText (app.9ac66e45.js:1)
    at o.mounted (app.9ac66e45.js:1)
    at ne (chunk-vendors.3aa820c1.js:63)
    at En (chunk-vendors.3aa820c1.js:63)
    at Object.insert (chunk-vendors.3aa820c1.js:63)
    at z (chunk-vendors.3aa820c1.js:63)
    at o.__patch__ (chunk-vendors.3aa820c1.js:63)
    at o.Yn.t._update (chunk-vendors.3aa820c1.js:63)
    at o.r (chunk-vendors.3aa820c1.js:63)
ae @ vue.runtime.esm.js:1888
user.js:84 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'password')
    at app.9ac66e45.js:1
    at u (chunk-vendors.3aa820c1.js:218)
    at Generator._invoke (chunk-vendors.3aa820c1.js:218)
    at Generator.forEach.t.<computed> [as next] (chunk-vendors.3aa820c1.js:218)
    at r (chunk-vendors.3aa820c1.js:41)
    at s (chunk-vendors.3aa820c1.js:41)
    at chunk-vendors.3aa820c1.js:41
    at new Promise (<anonymous>)
    at chunk-vendors.3aa820c1.js:41
    at v.getSeed (app.9ac66e45.js:1)
```

**Comment by Hukuma1** [comment]
Did they rugpull their recent seed raise? lol. Hope everyone is okay. Kind of weird and desolate here after so much gung-ho.

**Comment by mayankchhabra** [comment]
Sorry about the issue guys. This bug should be specific to new installs on Umbrel 0.4.10 and the fix has already been merged which will be included in the next release. Meanwhile, installing Umbrel 0.4.9 from scratch and updating to 0.4.10 successfully bypasses the bug (we've updated installation links and instructions to point to 0.4.9 instead).

So if you're currently facing the issue, please try this:

**For Raspberry Pi installs:**
1. Turn off your Pi
2. Re-flash [Umbrel OS 0.4.9](https://github.com/getumbrel/umbrel-os/releases/tag/v0.4.9) on the microSD card
3. Format the SSD attached to the Pi using your computer in any format type
4. Connect everything and turn on the Pi
5. Continue the setup


**For non-Raspberry Pi installs:**
1. Stop Umbrel and delete existing Umbrel directory
2. Restart your machine (this is important to stop any background processes spun by Umbrel)
3. Install Umbrel 0.4.9 in a new directory
4. Continue with setup

**Comment by Hukuma1** [comment]
`0.4.11` seems to work! I'll close this out in the next few days unless someone else chimes in with problems?

**Comment by mjcagency** [comment]
Hi all, I now have this same exact issue with 0.5.3 (on raspberry pi). I tried downgrading to all previous versions and other fixes listed but no luck. 

Thanks in advance
