### ISSUE TITLE
Removal of the thebitcoinmachine sponsorship due to being a scam

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [getumbrel/umbrel#1173]
Hi there,
Obviously, I ain't directly related to the team developing and maintaining the Umbrel software, but that's especially why I'm here.
I'm simply suggesting cutting connections with the doido team which are manufacturing and developing the ”bitcoinmachine” due to being scammed more than $500 on one of their rpi4 units.
I've ordered, with difficulties (Due to their CB payment not accepting my credit card at all) the 14 November, one of their units.
```
On 3 Nov 2021, at 3:39 PM, The Bitcoin Machine <support@doido.in> wrote:
Hi Gk,

Sorry we missed your earlier email. 
We will check and get back to you shortly. 

Thank you. 


On 3 Nov 2021, at 3:34 PM, GK <MY@MAIL> wrote:

﻿
I am relaunching my request, how i am unable to pay via Stripe on your website ?
On nov. 1 2021, at 9:57 am, GK <MY@MAIL> wrote:
Hi there,
I've been trying two times to pay for a Bitcoin Machine (The Machine with Umbrel - 2TB SSD, Black) with this same e-mail address (MY@MAIL).
However, despite the proceeding working on my own bank end, It seems to refuse each time. Due to myself, not using Bitcoin as a paiement method (Preferring, more modern, better conceived and managed crypto-currencies like Etherum, Dash or even Bitcoin Cash) , I'm stuck unable to pay for an unit.
Could you check if everything worked well on your end ?
In addition, due to the current happening hardware chips shortage, which has been causing the Raspberry Pi foundation itself to slow their stocks, do you have actually, in stocks Bitcoin machines ? Or will it be made per command ?
Because I'm afraid of the delay of the later solution for me.
Thanks.
```
![command](https://user-images.githubusercontent.com/13170204/147230523-ff6b7074-a421-4504-933b-5a0b5f8d80c3.jpg)

However, after the 30 processing days *(In which, I stupidly believed in, due to the actual issues with the rpi4 processing having issues these days)*, My command has been stuck on ¨processing¨.
And now, here we are, with me, sending mails to their support address for more than one week, trying to get an answer from them, with no success.
```
Wed, 22 Dec 2021 15:38:06 +0000 (22/12/2021 16:38:06)
Hi there.
I'm contacting you, since i haven't yet received my command on your website.
May i ask for your help ?
There's no other support place on it, other than your e-mail.

Sun, 19 Dec 2021 09:29:45 +0000 (19/12/2021 10:29:45)
Again, relaunching my demand.
Why is my command still processing ?

Wed, 15 Dec 2021 21:00:25 +0000 (15/12/2021 22:00:25)
Hi there,
After checking again my command tracking on the website, the command #7067 is still indicated as being processed despite the 31 days waiting for it.
May i have an explanation of such wait ?
```
And as I've waited more than 30 days, I can't cancel the paiement with my bank obviously, being scammed on one of their units.

So, what I'm suggesting with this Git issue, is to cut advertising their company and product through your website, to prevent potential other customers from being scammed of their money, and even potentially, accusing you of such scam in the future.

**Comment by mayankchhabra** [comment]
Really sorry about your frustrating experience, @PoorPocketsMcNewHold! I hear you. This isn't the type of experience we'd want anyone who places an order with our partner to have.

I can assure you that your order will be shipped. TBM's team has been struggling to keep up with the demand, and their processing time has slipped to about ~6 weeks. I've passed on your order number to them so they can get back to you with its status.

Really appreciate you making the effort to notify us about your experience. Please reach out to me personally at mayank@getumbrel.com if you face any further issues or if you don't receive your order within the next 4 weeks.

**Comment by PoorPocketsMcNewHold** [comment]
Thanks for your answer. Sorry, for having to rely on speaking out about my concerns on the project there. I've only noticed that some have actually received their units a couple of weeks ago on the Umbrel forum, only after I've opened this issue.  
However, I would still prefer to keep the issue opened, as a way to collect potential other customers having this issues and wasn't aware of the prolongated processing time, and also, as a way to update it.  
_You are, of course, free, of requesting to move or duplicate my issue with doido, on the Umbrel forum, and/or to close this issue regardless._

**Comment by mayankchhabra** [comment]
No worries at all. We can keep this issue open and close it once you receive your unit.

**Comment by PoorPocketsMcNewHold** [comment]
After a long wait, I've managed to get the confirmation of my unit being shipped, and a proper tracking number.
Following my message from 15 december that i posted here : 

> Wed, 15 Dec 2021 21:00:25 +0000 (15/12/2021 22:00:25)
> Hi there,
> After checking again my command tracking on the website, the command #7067 is still indicated as being processed despite the 31 days waiting for it.
> May i have an explanation of such wait ?

I've received an answer the 27 december.

> Hi GK,
> 
> We are currently processing orders till November 13th and yours will processed in the coming days.
> 
> Your machine will reach you in 14 -16 days.
> 
> Thanks.

Than, I've asked for an another update the 17 january, in which, i received a fast answer, the day after.

> Hello,
> I'm asking again so updates on my shipping, after the past weeks.
> With no order-tracking, I have no way to know if it's still not sent, or indeed, currently being delivered.
> Can I have a confirmation when it will be shipped, and if a tracking number will be provided?

> Hi,
> 
> Your order is in export document clearance.
> 
> We will mail the Tracking details along order ID soon.
> 
> Thanks.

And indeed, the 28 January, I finally received a final order invoice, with a proper tracking number from UPS
![image](https://user-images.githubusercontent.com/13170204/151700930-cb181af0-e416-411d-b539-86145d27f5bf.png)
I'll close this issue once I receive my unit, but you can understand that a three-month wait without much of transparency input from them is pretty tricky, to not call it as deceiving.

**Comment by PoorPocketsMcNewHold** [comment]
Received. Took long enough, but the unit is here, with 130€ of additional shipping taxes (!).

**Comment by daydreamwe** [comment]
Hope mine arrives as well 🙂
