### ISSUE TITLE
`APP_SEED` is a 32 bytes hex string (256 bit) and not 16 bytes (128 bit)

### ISSUE THREAD

**Issue by bonomat** [getumbrel/umbrel#1180]
The documentation says that `APP_SEED` is a 128 bit hex string: 

https://github.com/getumbrel/umbrel/blob/9f34ed7c62666228ce3e4842ebeed0dadf0453d6/apps/README.md?plain=1#L155

However, in the code a sha256 is used to generate `APP_SEED` which ends up in 32 bytes (256 bit): 

https://github.com/getumbrel/umbrel/blob/2f6e5357eb9248d647004aa10e35d46705f4e90d/scripts/app#L56

Am I missing something or is the documentation wrong?

**Comment by lukechilds** [comment]
Yeah sorry that's a little confusing. `$APP_SEED` is derived determinsitically from the master Aezeed Umbrel seed which contains 128 bits of entropy. So while the hex string is 256 bits long, it only provides 128 bits of entropy.

The reasoning is that we will likely change to a different master seed format at some point which provides 256 bits of entropy and the derivation function can't be changed without breaking all existing apps, so 256 bits was chosen in advance so we don't break existing apps when we make that change.

**Comment by bonomat** [comment]
Gotya. Thanks for the explanation. I've created a PR to update the description.
