### ISSUE TITLE
electrs update to 0.9.4 breaks container startup cause changed logging

### ISSUE THREAD

**Issue by tlindi** [getumbrel/umbrel#1183]
After PR9 (https://github.com/getumbrel/docker-electrs/pull/9#issuecomment-1005280930) "docker logs electrs" says
Error: please use log_filters to set logging verbosity

Changing: umbrel/templates/electrs-sample.toml

-verbose = 2
+log_filters = "INFO"

update to 0.9.4 needs change also to docker-composer.yml

        electrs:
             container_name: electrs
             "-"             image: getumbrel/electrs:v0.9.1@sha256:cf196695423fd5139ccde08e6bb1d7b6b1c9093333c879037801af3a18229c32
             "+"             image: getumbrel/electrs:v0.9.4@sha256:b1590ac6cfb0e5b481c6a7af7f0626d76cbb91c63702b0f5c47e2829e9c37997
             volumes:

with these changes 0.9.4 works for me

**Comment by prusnak** [comment]
Sent PR in https://github.com/getumbrel/umbrel/pull/1184

Out of curiosity: how to obtain the hash `b1590ac6cfb0e5b481c6a7af7f0626d76cbb91c63702b0f5c47e2829e9c37997` for `getumbrel/electrs:v0.9.4` ?

**Comment by lukechilds** [comment]
`docker pull` is the simplest way to get it:
```
$ docker pull getumbrel/electrs:v0.9.4
v0.9.4: Pulling from getumbrel/electrs
Digest: sha256:b1590ac6cfb0e5b481c6a7af7f0626d76cbb91c63702b0f5c47e2829e9c37997
Status: Image is up to date for getumbrel/electrs:v0.9.4
docker.io/getumbrel/electrs:v0.9.4
```

It's the hash of the multiarch manifest. If we pin to one of the image hashes tht you see on Docker Hub then it pins to that arch, so app installation will break on any other arch.

**Comment by lukechilds** [comment]
Thanks a lot for your help guys!
