### ISSUE TITLE
SSH password doesn't match UI password

### ISSUE THREAD

**Issue by balboah** [getumbrel/umbrel#1220]
Setting a password in the UI to `foo\barfoo\bar` works fine, you can use this for logging into the UI and for confirmation when changing to a new password.

However, trying to use the same password for SSH, will not work.
I'm guessing the escape sequence `\b` gets interpreted somewhere along the scripts.

Setting a password that does not contain the \b makes SSH work as expected.

Version: 0.4.11

**Comment by nmfretz** [comment]
closing old support issue
