### ISSUE TITLE
I got 2 misterious invoices of 1 BTC each to pay

### ISSUE THREAD

**Issue by tifDev** [getumbrel/umbrel#1223]
![image](https://user-images.githubusercontent.com/39730484/152127506-a5b74088-4dbc-4fea-97fa-adffc873da19.png)

This is a new wallet that I've created and I haven't used it yet (nor shared it). How is it possible that I have these invoices?

Thanks

**Comment by lukechilds** [comment]
The SatSale app creates these invoices when it starts up to check the connection with LND is working: https://github.com/nickfarrow/SatSale/issues/35
