### ISSUE TITLE
Problem with Nextcloud

### ISSUE THREAD

**Issue by pjbassel** [getumbrel/umbrel#1231]
Hi,

I've setup Umbrel on an old PC on top of Ubuntu.

I've loaded the NextCloud app.

I get this message:

![image](https://user-images.githubusercontent.com/99040404/152574624-47cf9367-5d7b-44b4-9192-f3678881e144.png)
  or in text:

Access through untrusted domain
Please contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php.

Further information how to configure this can be found in the [documentation](https://docs.nextcloud.com/server/22/go.php?to=admin-trusted-domains).

It seems the set up files needs to be updated so I can get to the app.

Please help.

Thanks

**Comment by bovcan** [comment]
well, it is writen everthing, did you check documentation?
 in config.php search for 
'trusted_domains' =>
  array (
   0 => 'localhost',
   1 => 'server1.example.com',
   2 => '192.168.1.50',
   3 => '[fe80::1:50]',
),

and add you local ip = 10.0.0.22

**Comment by ASOwnerYT** [comment]
When I use Tailscale, I have this issue. But I was able to fix it by editing the config.php to add the Tailscale assigned IP to the trusted domains. Maybe the Umbrel devs can make it so it does that automatically when connected via tailscale.

**Comment by nmfretz** [comment]
closing old support issue

**Comment by iMonZ** [comment]
> well, it is writen everthing, did you check documentation? in config.php search for 'trusted_domains' => array ( 0 => 'localhost', 1 => 'server1.example.com', 2 => '192.168.1.50', 3 => '[fe80::1:50]', ),
> 
> and add you local ip = 10.0.0.22

That comment does not make any sense. Its a container, so as soon as you rebuild it, this file will be newly generated from the compose file

**Comment by asmaier** [comment]
This problem is unsolved and should be reopened. If umbrel wants to make installation easier for beginners, they should not force the user to edit cryptic config files. I found the `config.php` file at the following path:

    $ cd app-data/nextcloud/data/nextcloud/config
    $ nano config.php

I edited it like

    array (
        0 => 'localhost',
    ...
        6 => 'nextcloud_web_1',
        7 => '<my domain>',
      )

Hope that helps.
