### ISSUE TITLE
Ubuntu Set up on old laptop

### ISSUE THREAD

**Issue by pjbassel** [getumbrel/umbrel#1232]
Hi,

FYI, I have set up Umbrel on an old HP laptop on top of Ubuntu.

Setup seems to have gone fine using the instructions from https://umbrelinfo.gitlab.io/getting-started.html#using-a-normal-pclaptopnuc . Thanks to the creator of those instructions.

My Umbrel is now downloading the bitcoin chain.

What I find interesting is that despite only using 20-30% of the CPU and 60-70% of ram (4GB).  Doing anything on the laptop through the Gnome interface is very slow.  Even logging in is slow.  Also the web interface on another computer through a browser varies from OK to slow.

I'm more than happy to make my laptop visible to the developers now or in the future, if it helps, as I am still in testing mode. 

Just trying to help out however I can.  I'm not a programmer (anymore) so I can't help on that side but happy to see how I can help in other ways.

I'm also about to setup a bitcoin miner farm and thought I should also setup hosted Umbrel.  I can do individual Raspberry Pis but I think it would be better to do it on a server and setup virtualized Ubuntu servers and then Umbrel on top of that.  While Raspberry Pis are fine for a bitcoin node, wallets etc, if people want to add NextCloud they are going to need more disk space.  In hosted mode on a server we should be able to provide that easily.  There will be a cost, likely less than the cost of buying a Raspberry Pi, disk and box to put it in.  I'll do my best to keep them as low as possible as this is more a value add service than a huge profit opportunity.  I'm just trying to give back to the community.

I'd also like to work with someone who knows about Lightning and how best to advise users to network on it.  I would think we should be able to get lots of new Umbrel installations and therefore lots more people adding to the spread of the Lightning network.  The good thing about this approach is that our guidance can be focused on optimizing the spread of the network not just connecting to the high volume Lightning nodes. In that way our client Umbrel nodes can be more beneficial to the network and themselves. 

Hope this helps.

Thanks

Regards

Peter Bassel
Peter.Bassel@gmail.com
+1 647-298-6297

**Comment by Darth-Coin** [comment]
@pjbassel Yes, I am the writer of that guide, but is quite old and Umbrel is not using that page anymore and will not be updated with more information.
I strongly suggest you to use [Umbrel Community Forum - Guides section](https://community.getumbrel.com/c/guides/14/l/top/all) where you can find more extensive guides about how to use your new Umbrel node.
There you can post more experiences and discuss them with other "umbrelians" in a nice fashion. On here on Github is better to keep more only real issues only related to Umbrel software.

**Comment by pjbassel** [comment]
Hi DarthCoin,

Thanks for your reply.  If ever I can help the project by donating
computers / Raspberry Pis to the cause, please advise and I will try to
help out.

As a side note, I did post something on the Discord group and was called a
scammer/spammer.  I had no intention of doing either.  While I am VERY NEW
to the crypto/blockchain world, I was surprised at the reception to my
request.  I asked if another wallet could be added to the node.  This is
for a CPU mined coin which is Asic resistant. I was told this was from a
scammer.  At that time, I did not have a go retort but now I have learned
there are a number of credible mined coins.  Monero being one of them.  I
understand that Monero is over 7 years old and there are a number of forks
off of that project.

I would have been OK with a reply that the coin I mentioned is too small or
too far afield despite being a fork of Bitcoin.  I have "no dod in the
game", so I don't need to push it further.  I only mention it to you
because I was surprised by the response from the Discord channel.

No matter what, thanks 1) for your reply and 2) for your contribution to
the project.

All the best.

Regards

Peter Bassel

***@***.***

+44 7 399-837-177 (Only on WhatsApp)

+1 647-298-6297
