### ISSUE TITLE
umbrel-middleware - Unable to get payments, Received message larger than max (10188411 vs. 4194304)

### ISSUE THREAD

**Issue by miceliomad** [getumbrel/umbrel#1245]
Hi, seeing this msg coming out from an Umbrel node when trying to access the web ui. 

Has been the case at least since 0.4.11 and still happening with 0.4.13

Umbrel logs
-----------

Attaching to middleware, manager
middleware           | umbrel-middleware
middleware           | Unable to get payments, Received message larger than max (10188411 vs. 4194304)
middleware           | /v1/lnd/lightning/payments
middleware           | LndError: Unable to get payments
middleware           |     at /app/services/lnd.js:69:18
middleware           |     at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1210:9)
middleware           |     at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
middleware           |     at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
middleware           |     at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)

Result is that the LND umbre web UI is not listing any payments and gets into a loop keeping the CPU busy for long time. Any hint how to get rid of it or resolve it? 

Node is working properly, so this does not affect LND itself but just the Umbrel Web UI which becomes unsuable. Listing payments with lncli does not throw any particular error, neither with RTL or other tools. 

thanks in advance for looking into it

**Comment by louneskmt** [comment]
Hey, do you have a large transactions history?

**Comment by miceliomad** [comment]
Indeed, plus 9k

**Comment by stuartstarrs** [comment]
Same issue, same versions, same larger than max error with different values.
