### ISSUE TITLE
Umbrel 0.4.14 still has an older version of LNBITS in App Store

### ISSUE THREAD

**Issue by jchames** [getumbrel/umbrel#1253]
I have installed the Umbrel version of LNBITS in v0.4.14. However I notice that the version currently on Umbrel, doesn't have the **LNURLDevice** extension, amongst others e.g the admin extension. 
According to Ben Arc, [10 Feb 2022 at 11:49:40] the new tag to use is  **0.6.0**

And: _"Tell them I will give a bounty if they need to pay someone to sort it"_

**Comment by Darth-Coin** [comment]
@louneskmt is it possible to change the yml docker file for lnbits to point to another repository?
Or this is will be included in a new Umbrel feature that allow users to update manually each Umbrel app?

**Comment by louneskmt** [comment]
@Darth-Coin Ulbrel currently includes LNbits latest version so there is no need to change the repo
