### ISSUE TITLE
unable to install btcpay-sever

### ISSUE THREAD

**Issue by ParmuSingh** [getumbrel/umbrel#1263]
I've installed umbrel os on my raspberry pi 4 with a 2TB HDD.

only thing I did differently was instead of connecting rpi to an ethernet cable I connected it to wifi. Because of the docker wasn't installed on the first boot so I later installed it manually using ```sudo apt install docker```.

Everything works, IBD is happening as expected. Only problem is every time I install BTCPay Server from the store it gets stuck at "installing".

To debug I ssh-ed into my rpi and tried installed btcpay server manually like this: ```~/umbrel/scripts/app install btcpay-server```.

This is the output:

```
umbrel@umbrel:~/umbrel $ sudo ./scripts/app install btcpay-server
Setting up data dir for app btcpay-server...
sending incremental file list

sent 160 bytes  received 16 bytes  352.00 bytes/sec
total size is 2,595  speedup is 14.74
Pulling images for app btcpay-server...
Pulling nbxplorer ... done
Pulling postgres  ... download complete
Pulling web       ... done

ERROR: for postgres  failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/87d10fe1ad0e511cb430087b36c330e082c0e31b33e9443429952e6594ce776c/merged: too many levels of symbolic links
ERROR: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/87d10fe1ad0e511cb430087b36c330e082c0e31b33e9443429952e6594ce776c/merged: too many levels of symbolic links
```

I'm not sure why this is happening. I've tried reinstalling docker but it didn't fix it. How should I fix this?

**Comment by wizni-ParmuSingh** [comment]
solved: https://community.getumbrel.com/t/unable-to-install-btcpay-sever/6651/14?u=parmusingh

**Comment by redyetirecords** [comment]
Was this ever solved? Having the same issue. Thanks.

**Comment by nmfretz** [comment]
closing old support issue
