### ISSUE TITLE
user.json getting deleted

### ISSUE THREAD

**Issue by dkelly60** [getumbrel/umbrel#1272]
I have a problem where the user data goes missing. 
My setup Pi4, 8GB ram, 2TB SSD with powered hub, Official powersupply, Umbrel 0.4.14 and argon fan hat.

I recently upgraded to 0.4.14. Everything seemed fine at first. However I shutdown via the web consol to make some case changes. On reboot the start screen presented instead of the login. I flashed a new SD but could not resolve this. So I went through the setup and restored the wallet. I had removed the fan hat so I shut down via consol and added the hat. On reboot I again lost the user and was at the startup screen.  Again I went through the setup and restored the wallet. while the core was syncronising I installed the fan hat control software and rebooted. Again the user data was gone and I have to start new. What could be causing the user.json file to be missing?

**Comment by nmfretz** [comment]
closing old support issue
