### ISSUE TITLE
[Add new app] RoboSats P2P exchange

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#1277]
### Decription:
Convert any Umbrel node machine into a P2P exchange over LN, with RoboSats.
[Running the RoboSats tool](https://github.com/Reckless-Satoshi/robosats/) as an application inside Umbrel,  over Tor, P2P.

RoboSats is a simple and private way to exchange bitcoin for national currencies. Robosats simplifies the peer-to-peer user experience and uses lightning hold invoices to minimize custody and trust requirements. The deterministically generated avatars help users stick to best privacy practices.

Please collaborate with @Reckless-Satoshi into introducing this new app, can very useful. Maybe a future federated type of servers that can communicate each others through RoboSats. This could have a huge potential in exchanging sats in a truly private and decentralized way.

### Example:
http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/book/

**Comment by mmzgc776** [comment]
I was thinking that could be cool to have an option to choose between having a full instance of RoboSats in your node or the frontend only, in the second option we could get some benefits like reduce the frontend dispatching load from the official RoboSats server, while we only query it for the offers over the same tor instance of our node.

**Comment by zehks** [comment]
An awesome idea to integrate RoboSats into an Umbrel's app.

For the end-user, it would be very easy and straight-forward to fully complete an order with just a two or three clics on Umbrel's frontpage. 

- Auto-generate the invoices and give them to RoboSats backend with a single clic
- Pay the counter part's invoice with a single clic

I think the full buy-trade could be completed with two clics:

1. Take the selling order and automatically pay the bond invoice. Without user's interaction, the payment invoice is generated and given to the backend.
2. The chat is open now, FIAT payment is being discussed. Once it is done, user clics on "FIAT sent" button.

When the counterpart confirms the FIAT payment, the sats would be on your Umbre's LN wallet.

**Comment by ibertario** [comment]
RoboSats is a gamechanger app to add! Nothing more to add about the benefits, so:

Using Umbrel's node to perform trades can be great:

> @decentralizedb perform the entire trade from your node using LN
> @zehks  For the end-user, it would be very easy and straight-forward to fully complete an order with just a two or three clics on Umbrel's frontpage.

The UI way can be at least the first step to integrate and help RoboSats.

> @mmzgc776 ... the frontend only, in the second option we could get some benefits like reduce the frontend dispatching load from the official RoboSats server ...

This can be done? Sounds like the best option to improve the network and prevent possible attack vectors:

> @Darth-Coin Maybe a future federated type of servers that can communicate each others through RoboSats. This could have a huge potential in exchanging sats in a truly private and decentralized way.

**Comment by PeterMcBTC** [comment]
Robosats in umbrel would be awesome!

**Comment by Reckless-Satoshi** [comment]
Opened a PR to add a RoboSats client as an Umbrel App https://github.com/getumbrel/umbrel-apps/pull/122

It closely resembles option 2 described above by @mmzgc776 more info here https://github.com/Reckless-Satoshi/robosats/pull/216
