### ISSUE TITLE
Missing instructions in "Connect wallet" - Sparrow

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#1283]
@mayankchhabra Please add instructions how to connect Tor service in Sparrow section "connect wallet".
Users still don't know that are the same instructions as for Electrum desktop.
Sparrow also works with local IP of the node, will be good to be mentioned in those instructions.

Also would be nice to add the instructions using Tailscale VPN (integrated in Umbrel).

**Comment by bitpaint** [comment]
+1, 

> it would be nice to add the instructions using Tailscale VPN (integrated in Umbrel) / 

or choose network in a menu: 
- Tor
- Tailscale
- Local
