### ISSUE TITLE
Fedora: installation failure: URLs given don't work

### ISSUE THREAD

**Issue by ethindp** [getumbrel/umbrel#1294]
Ran this on fedora 35, and no go. Everything appeared to go swimmingly until the end. It gave me my servers IP addresses; no hidden tor service appeared to be created. I'm not sure what went wrong. I'd love to test this out but I can't access it, not even through localhost, and even if I open the ports in the firewall on a temporary basis I still am unable to connect.

**Comment by nmfretz** [comment]
closing old support issue
