### ISSUE TITLE
Password problems with RTL (Ride the Lightning) app after Upgrade on a running Umbrel system

### ISSUE THREAD

**Issue by Gravity-87** [getumbrel/umbrel#1298]
After upgrading a running Umbrel system (with RTL installed on it) to v0.4.15, a user set password for RTL-Login is lost/dropped. During the upgrade installation, obviously there is a new default password set, which won't be displayed, because the Umbrel is shutting down and restarting. The only solution is: Uninstall the RTL app in Umbrel apps and reinstall it from the app store. Within this procedure, you 'll get the new default password displayed. In addition: It seems as there is neither the possibility to re-change the password from the new default password to an individual password string within the RTL app, nor to change it on the Umbrel shell level.

This issue is in reference to:
https://github.com/Ride-The-Lightning/RTL/issues/968

**Comment by lukechilds** [comment]
In the latest version RTL now respects the default password as higher priority than a user supplied password. You shouldn't have to re-install the app, just simply using the password from the RTL app store page should allow you to login to RTL without having to reinstall the app.

**Comment by primadonnaa** [comment]
@lukechilds Why is this choosen to respects the default password over a better user-supplied password?
Is 2FA still activated then?

**Comment by empewoow** [comment]
So, the user password is overwritten to the app default password when Umbrel or RTL is updated. Is that how it works now? How can one change the default password again..?

**Comment by saubyk** [comment]
@lukechilds @mayankchhabra 
Would love to get your thoughts on this. The current setup is not providing an optimal UX.

Our take on this is that, since Umbrel is the orchestrator of authentication, Umbrel should provide that flexibility to the user to change the password, and that control should not be with the individual applications.

cc: @ShahanaFarooqui

**Comment by lukechilds** [comment]
Agreed the current solution is suboptimal UX wise, it was implemented as a temporary measure to quickly add some additional security. We're working on a much cleaner solution.
