### ISSUE TITLE
Joinmarket (JAM) on Umbrel connects to IRC servers over clearnet.

### ISSUE THREAD

**Issue by johnnywonder1** [getumbrel/umbrel#1300]
This can allow IRC servers, LE, and other parties to deanonymize UTXOs and can put many users at risk.
Umbrel should make sure all Joinmarket connections are made over Tor.

**Comment by mccolister1017** [comment]
really ?

**Comment by lukechilds** [comment]
Thanks for reporting! The JoinMarket implementation on Umbrel (Jam) is an independent project, it's not something we're directly involved in. Let me ping the people involved.

cc @dergigi @theborakompanioni

I assume this is probably a mistake but FWIW the app is labeled as pre-alpha so they may already be aware of this behaviour and just haven't implemented it for the intial release.

**Comment by lukechilds** [comment]
Although looking at [this](https://github.com/getumbrel/umbrel/blob/80a1b5ffe47c2f189320a7d57960ed6c068e739b/apps/jam/docker-compose.yml#L19-L20) they are passing in the Umbrel Tor proxy connection details so maybe there's a bug in Jam or the Jam container that isn't correctly using the Tor proxy.

**Comment by lukechilds** [comment]
@johnnywonder1 might be useful for Jam devs if you're able to post steps on how you verified the IRC connecions aren't made through Tor.

**Comment by theborakompanioni** [comment]
> @johnnywonder1 might be useful for Jam devs if you're able to post steps on how you verified the IRC connecions aren't made through Tor.

The project tries to change as little as possible to the default setting. Default settings for IRC are apparently not over Tor. See also https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1049

It is of course possible to maintain an adapted config and it seems to be necessary now. Docker image should already take a custom config file in `data/joinmarket/` into account. See also: https://github.com/joinmarket-webui/joinmarket-webui/wiki/Configuration:-UI-Settings-&-joinmarket.cfg

**Comment by johnnywonder1** [comment]
> @johnnywonder1 might be useful for Jam devs if you're able to post steps on how you verified the IRC connecions aren't made through Tor.

Sure.
`running docker exec <jam container> curl ifconfig.me`
returns my actual IP address, confirming the docker container itself is not routed through Tor.
The other proof is that the Joinmarket config in the installation points to the clearnet address of the IRC servers and specifies that a socks5 proxy will not be used, this was also confirmed in the Jam telegram chat. 

The fix is simple: make sure that the Joinmarket config uses Umbrel's socks5 Tor proxy, and preferably point to the .onion address of the IRC servers.

**Comment by theborakompanioni** [comment]
Will be adapted and a fix is developed in https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/25
Thanks everyone for reporting and trying Jam in such an early stage. :orange_heart: 

> Sure. `running docker exec <jam container> curl ifconfig.me` returns my actual IP address, confirming the docker container itself is not routed through Tor. 

So that I leave no doubt and no misunderstanding, executing a curl request via `running docker exec <jam container> curl ifconfig.me` will not be proxied through tor with these changes. Do other Umbrel apps implement such kind of a system wide tor proxying?

**Comment by aphex3k** [comment]
> Sure.
> `running docker exec <jam container> curl ifconfig.me`
> returns my actual IP address, confirming the docker container itself is not routed through Tor.

This is actually not a valid test if you ask me.

**Comment by aphex3k** [comment]
From #1301 

> All 4 IRC server configured in the `joinmarket.conf` will connect to the cleartext servers instead of utilize tor by default!
> 
> In the current configuration the JAM app will leak your node's IP address to the IRC servers it uses for market coordination.
> 
> This behavior can be changed by manually editing the conf file but it should be the default as Umbrel should use TOR by default for everything.
> 
> ```
> J<redacted>.log:2022-03-03 05:56:41,426 [MainThread  ] [DEBUG]  (unhandled) noticed:  irc-us-east-2.darkscience.net * *** Found your hostname (<redacted>.cox.net)
> ```
> 
> (redaction by me)

the configuration file generated by the image configures `socks5 = false` for all 4 IRC connections bypassing the TOR proxy available to umbrel entirely.

**Comment by aphex3k** [comment]
I rectified the situation on my own node by doing the following:

1. use actual onion addresses for 3 of the 4 IRC servers which are handily provided in the configuration, they just need to be uncommented
2. The onion address for IRC server 1 seems unreachable so I left the dns configured but routed it through TOR by at least enabling `socks5 = true` in the config.

After restarting the container I can confirm that my nodes IP is not showing up in the jam logs anymore.
