### ISSUE TITLE
JAM app will connect to cleartext IRC instead of TOR by default!

### ISSUE THREAD

**Issue by aphex3k** [getumbrel/umbrel#1301]
All 4 IRC server configured in the `joinmarket.conf` will connect to the cleartext servers instead of utilize tor by default!

In the current configuration the JAM app will leak your node's IP address to the IRC servers it uses for market coordination. 

This behavior can be changed by manually editing the conf file but it should be the default as Umbrel should use TOR by default for everything.

```log
J<redacted>.log:2022-03-03 05:56:41,426 [MainThread  ] [DEBUG]  (unhandled) noticed:  irc-us-east-2.darkscience.net * *** Found your hostname (<redacted>.cox.net)
```

(redaction by me)

**Comment by louneskmt** [comment]
Hey @aphex3k! Thanks for your concern, this issue can already be tracked in #1300, so I'm closing this for now.
