### ISSUE TITLE
Enabling HTTPS with sudo tailscale cert

### ISSUE THREAD

**Issue by mccolister1017** [getumbrel/umbrel#1317]
any away to enable https with tailscale ? i can't  '' sudo tailscale cert " if there's anything i can do or somebody can help me to do i will be happy thank you guys 

sudo: "tailscale: command not found" is the error .

**Comment by ryenski** [comment]
The command must be invoked via docker: 

```
sudo docker exec -it tailscale_web_1 tailscale cert umbrel.[TAILSCALE SUBDOMAIN]
```

**Comment by ProTechEx** [comment]
```
umbrel@umbrel:~ $ sudo -s
root@umbrel:/home/umbrel# tailscale cert
bash: tailscale: command not found
root@umbrel:/home/umbrel# sudo docker exec -it tailscale_web_1 tailscale cert umbrel.xxxxxx.ts.net
Wrote public cert to umbrel.xxxxxx.ts.net.crt
Wrote private key to umbrel.xxxxxx.ts.net.key
root@umbrel:/home/umbrel# ^C
root@umbrel:/home/umbrel# ~/umbrel/scripts/app rstart gitea
bash: /root/umbrel/scripts/app: No such file or directory
root@umbrel:/home/umbrel# exit
exit
umbrel@umbrel:~ $ ~/umbrel/scripts/app restart tailscale
Stopping app tailscale...
   "tailscale"
   "tailscale": "https://github.com/getumbrel/umbrel-apps.git",
Stopping tailscale_tor_server_1 ... done
Stopping tailscale_web_1        ... done
Going to remove tailscale_tor_server_1, tailscale_web_1
Removing tailscale_tor_server_1 ... done
Removing tailscale_web_1        ... done
Starting app tailscale...
   "tailscale"
   "tailscale": "https://github.com/getumbrel/umbrel-apps.git",
Warning: "tailscale" has no 'app_proxy' defined
        "tailscale" needs this to generate Tor HS
   "tailscale"
   "tailscale": "https://github.com/getumbrel/umbrel-apps.git",
Creating tailscale_tor_server_1 ... done
Creating tailscale_web_1        ... done
```

I have installed SSL so far, but have still no access per https.  
Whats the problem ?

**Comment by eurbasius** [comment]
I have the same problem. Any ideas where to dig deeper to find out the root cause of it?

**Comment by IT4Bitcoin** [comment]
AFAIK this is because you only generated the SSL certificate and unless the Umbrel Web Server is https compatible this is not going to be enough. Tailscale is not a webserver per se, if so you would not be able to browse via port 80 when using the VPN.

I guess you can still tweak the web server yourself,  you can start by running `sudo docker inspect nginx` and taking a look but is not gonna be that easy.

**Comment by tarsiec** [comment]
Is this supposed to take some time after being ran? The command executed succesfully but no luck connecting via https still
