### ISSUE TITLE
Can't access node.

### ISSUE THREAD

**Issue by CoderBoogs** [getumbrel/umbrel#1321]
After updated to the latest umbrel  release I am unable to access my node via ssh or umbrel.local. I already reflashed the micro SD card but still can't access my node. Is my node dead? Or is there something I can do to troubleshoot from here

**Comment by mccolister1017** [comment]
not a big deal just add  your computer local ip ( 192.168.1.XX umbrel.local  ) to your host file if you or on windows or just use the umbrel pi local IP you can found it on your router .....

**Comment by CoderBoogs** [comment]
Host file on my node? How? Hook a monitor to it ?

**Comment by mccolister1017** [comment]
> Host file on my node? How? Hook a monitor to it ?

not your node your computer ......... the windows host file

**Comment by mccolister1017** [comment]
> > Host file on my node? How? Hook a monitor to it ?
> 
> not your node your computer ......... the windows host file

https://community.getumbrel.com/t/how-to-set-a-static-ip-for-your-umbrel-machine/845

**Comment by CoderBoogs** [comment]
Thanks for the guide but I know the IP address of my node but I can't SSH in. It gets stuck on connecting all the solution in the thread assume you can access the node but I just can't.

**Comment by CoderBoogs** [comment]
Got help on plebnet. After connecting a monitor and getting no signal I was told to do a power disconnect and watch the node reboot. Once I did umbrel access came back it seems intact. All of my channels are offline and a few peers closed some channels but it appears I can access my node again.
