### ISSUE TITLE
Removal of the thebitcoinmachine doido sponsorship due to being a scam

### ISSUE THREAD

**Issue by lucky4udanny** [getumbrel/umbrel#1340]
Previously opened issue #1173 was closed by the author, but the real issue has not been addressed.

I'm suggesting cutting connections with the doido team which are manufacturing and developing the ”bitcoinmachine” due to ongoing misleading information and failure to deliver.

- 2021-12-23: I ordered a unit and received confirmation.
- 2022-02-23: I requested an update from The Bitcoin Machines <info@doido.in> since the order was now 2 months old. They promised delivery in 12 days time.
- 2022-03-15: I requested an update again.
- 2022-03-19: I received a UPS tracking code from The Bitcoin Machines <support@thebitcoinmachines.com>. When I click on it, it shows a label has been created, but nothing has shipped.
- 2022-03-23: Three months had passed. I requested an update and got no response.

It is now April 4. It has been 102 days since I ordered. The tracking code still shows label has been created, but nothing has shipped. I understand there could be supply chain issues, but if that's the case, why the misleading communication?

Thanks for your attention.

**Comment by Saddhbh** [comment]
I also have the same issue with this company. Purchased a node in November 2021 and have been asking for a refund since February 2022. Customer support told me that I would also receive my product within 12 days but that was a lie. Inquiries in March and April were met with very sincere apologies but I still didn't get my node nor a refund.

I then messaged the company on Twitter for a refund and they told me to expect a refund within 24 hours. That never happened so I asked again and then they wanted my bank account information.

I have now concluded that The Bitcoin Machines are a total scam.

**Comment by mayankchhabra** [comment]
My apologies @lucky4udanny and @Saddhbh for such an incredibly frustrating experience. @lucky4udanny, are you still waiting for your order (or a refund)? If so, please let me know your order number and I'll escalate it with their team. 

@Saddhbh, same for you. Please let me know your order number and I'll check with them asap.

**Comment by Saddhbh** [comment]
@mayankchhabra,

Thank you for  your help. Please tell the team that if they are still having "issues" with refunding my credit card, I will also accept BTC and ETH. Order #6972.

![JAN_23_2022](https://user-images.githubusercontent.com/109828590/181756289-810517f8-0f82-4685-8483-c8df6ae260e6.png)
![JUL_29_2022](https://user-images.githubusercontent.com/109828590/181756331-b0772203-36b7-4998-a085-3d25ae96f456.png)

**Comment by mayankchhabra** [comment]
Thanks, @Saddhbh. I've shared the details with TBM. Expect to hear back soon.

**Comment by Saddhbh** [comment]
Thank you so much!

**Comment by lucky4udanny** [comment]
I did finally receive my order. Thanks for the follow up - even though it
is a very late follow up.
Cheers.
