### ISSUE TITLE
No new update found

### ISSUE THREAD

**Issue by Covalent5** [getumbrel/umbrel#1345]
My node tells me that the latest version is still 0.4.16. I tried rebooting but the problems still persists.

**Comment by nevets963** [comment]
@Covalent5 Is this still an issue?

**Comment by Covalent5** [comment]
> @Covalent5 Is this still an issue?

Yes.

**Comment by Covalent5** [comment]
@nevets963 any update?

**Comment by louneskmt** [comment]
You can update manually by executing the following command in a terminal:
```
ssh -t umbrel@umbrel.local "sudo ~/umbrel/scripts/update/update --repo getumbrel/umbrel#v0.4.17"
```
Both passwords are your dashboard password.
