### ISSUE TITLE
[Feature request] Select which apps to be updated

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#1351]
### Description
When Umbrel is updated, is also coming with a bunch of other apps.
But not everybody are using them at all. So not really necessary an update.

### Actual behavior
Recently LNBits had an update that has a bug. Some users found it and until LNbits will fix it, they will have to wait until will be included in a new Umbrel update.

But other users that still didn't update Umbrel with that wrong LNbits version, could just update Umbrel without that "bad LNbits" and still can use the old version with no problem.

Or maybe there's an update of LND and many other apps that the user do not use them at all. Can just skip those ones and select only core functionalities and LND.

### Possible solution
So a simple option of selection of which apps the user want to update (if are not core components). Could be in the manual mode, with a simple "Y/N" stop in installation mode and user can decide yes or no for each installation step.

If is in the GUI mode, the update can simply indicate to the user the apps that are in the update package and some checkboxes top be marked for each app the user want to use.

EDIT: would be really appreciated if in the release notes will see more details about which apps and core components were updated and fixes.

**Comment by nmfretz** [comment]
apps have been removed from this repo and are now downloaded on demand from the app store: https://github.com/getumbrel/umbrel-apps
