### ISSUE TITLE
UX Issue:  New users don't know when electrs has finished initial indexing

### ISSUE THREAD

**Issue by relativisticelectron** [getumbrel/umbrel#1360]
After blockchain sync a new user will likely go to "Connect Wallet" and follow the instructions. However typically electrs will take longer than this message indicates:
![image](https://user-images.githubusercontent.com/60378539/164942581-700a80b9-7afe-4801-a401-75d67a369915.png)

Is it possible to make an api call to electrs, looking up an address (e.g. 17SkEw2md5avVNyYgj6RiXuQKNwkXaxFyQ ) and see if we get an error or if the call was successful?  That way umbrel could give the user better instructions, like "**electrs finished sync, try connecting your wallet now**", or "**Sync not finished, please check again in 24 hours.**".

**Comment by nmfretz** [comment]
Electrs now shows sync progress
<img width="900" alt="image" src="https://github.com/getumbrel/umbrel/assets/85373263/c3751227-1782-476c-b5b1-34604cf1636c">
