### ISSUE TITLE
My userid is not 1000, can I not use Umbrel on Ubuntu?

### ISSUE THREAD

**Issue by ChiefJoep** [getumbrel/umbrel#1363]
I'd like to install Umbrel on my Ubuntu server, but the [installation instructions](https://github.com/getumbrel/umbrel#-installation) say: Make sure your User ID is 1000.
Unfortunately mine is 1001. Does that mean I cannot use Umbrel? Or can I overcome this by simply changing 1000 into 1001 on a few places?

**Comment by mayankchhabra** [comment]
Unfortunately it's indeed required to have the 1000 User ID currently. We'll drop this requirement in a release over the next month. Meanwhile, switching UIDs = switching user accounts. 1000 UID is the first (or default) user account on all Linux distros. So if you can switch to that user and install Umbrel, it should run perfectly.
