### ISSUE TITLE
Remove volumes when app is uninstalled

### ISSUE THREAD

**Issue by woofbotapp** [getumbrel/umbrel#1372]
I'm working on an app that uses Mongodb, which needs a separated docker volume (instead of binding a directory).
I've tried using a simple binding to the /data/db directory in my docker-compose.yml, just like in the Mariadb and Redis examples, but Mongodb does strange file-locking, calls `fdatasync`, etc.

Everything works great with the volume, except that it's not deleted when the app is uninstalled.
This could be fixed if you add a '-v' flag to the `compose down` command here: https://github.com/getumbrel/umbrel/blob/master/scripts/app#L188

See: https://docs.docker.com/compose/reference/down/#:~:text=%2Dv%2C%20%2D%2Dvolumes%20%20%20%20%20%20%20%20%20%20%20Remove%20named%20volumes%20declared%20in%20the%20%60volumes%60%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20section%20of%20the%20Compose%20file%20and%20anonymous%20volumes%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20attached%20to%20containers.

Thanks

**Comment by louneskmt** [comment]
Hey! I'm quite sure you can setup a mongodb container and persist data using a bind mount instead of a docker volume. Did you face any issue trying that?

**Comment by woofbotapp** [comment]
If you have a docker-compose.yml example with a `mongo:5.0.8` image and a binding like `${APP_DATA_DIR}/data-db:/data/db` that works in umbral-dev and doesn't go into a restart loop, and actually saves the files in the `data-db` directory, please let me know.

I haven't tried it yet on a real raspberry-pi - first I want to make sure everything works in umbrel-dev...

**Comment by woofbotapp** [comment]
I now have a bigger problem with MongoDB: https://www.mongodb.com/community/forums/t/core-dump-on-mongodb-5-0-on-rpi-4/115291/14

I'm actually considering switching to MariaDB like all the other apps... FML.

**Comment by woofbotapp** [comment]
Hi @louneskmt ,
The [mongo:4.4.6-bionic](https://hub.docker.com/layers/mongo/library/mongo/4.4.6-bionic/images/sha256-d9ddf3df31941d30ee486ad5d2337283f0a02f68dbc5092319e24d3a541dbddd) image works on my Raspberry Pi 4 directly with binding and without an additional volume. However, on my umbral-dev environment the mongodb docker fails repeatedly with "IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db".
Should I submit the app as-is, with the docker-compose.yml that works on my Raspberry Pi? Or should I keep trying to make it work in the virtual-box umbrel-dev? It is also possible that I broke something in my umbral-dev environment, so maybe you guys will manage to run it.

Thanks!

P.S. it would nice to have instructions for how to revert the [scripts/update/update](https://github.com/getumbrel/umbrel/tree/master/apps#:~:text=2.%20Next%2C%20we%27ll%20switch%20the%20Umbrel%20installation%20to%20our%20fork%20and%20branch%3A) operation, and refollow the main branch instead of the fork.

**Comment by louneskmt** [comment]
If you bind `$APP_DAT_DIR/data/db` to `/data/db`, you need to create `$APP_DAT_DIR/data/db` beforehand. Otherwise Docker will do it as root and your container user may not have the permissions to edit it. 

To refollow the main branch, just update to `getumbrel/umbrel#master` or `getumbrel/umbrel#v0.4.17` (latest version).

**Comment by woofbotapp** [comment]
Creating all the subdirectories solved the issue (not only /data/db, but also /data/db/diagnostic.data and /data/db/journal)

FYI: https://github.com/getumbrel/umbrel/pull/1383
