### ISSUE TITLE
Tor configuration

### ISSUE THREAD

**Issue by helpau** [getumbrel/umbrel#1394]
I was excited to try out Umbrel in a virtual machine. I was able to download apps from the App Store, but the blockchain synchronization(regtest) did not happen. I think it's about the use of Tor: in my country (Russia) it works with problems. I think it is necessary to add to the settings the ability to specify the type of Tor bridges.

**Comment by nmfretz** [comment]
Hi @helpau. When you're running Bitcoin Core in `regtest`, it's designed to be a private Bitcoin blockchain that you control entirely. In regtest mode, new blocks aren't created automatically -- you have to create them manually so you would not have seen any synchronization.

Our Bitcoin Node app now has `Advanced Settings` that can be accessed through the UI. From here you can change the netwoek (mainnet, regtest, etc) and also control wether or not you connect to peers over Tor:

<img width="824" alt="image" src="https://github.com/getumbrel/umbrel/assets/85373263/e9af0dfa-e210-4043-ab7b-e57a452274b7">
