### ISSUE TITLE
Getting an error with my umbrel, channel not synching and node not synching

### ISSUE THREAD

**Issue by Lightning8Count** [getumbrel/umbrel#1398]
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 108)
middleware           | Unable to list pending channels, failed to connect to all addresses

**Comment by nmfretz** [comment]
closing old support issue
