### ISSUE TITLE
My Umbrel node is down - after the recent upgrade, my block synch has been stuck on: (737,455 of 737,546 blocks) no where near the current block height!

### ISSUE THREAD

**Issue by Lightning8Count** [getumbrel/umbrel#1400]
Hi All

I need some help.  My Umbrel node is down - after the recent upgrade, my block synch has been stuck on: (737,455 of 737,546 blocks) no where near the current block height!

##### Here are my debug files: 

[umbrel-1653742990600-dmesg.log](https://github.com/getumbrel/umbrel/files/8791161/umbrel-1653742990600-dmesg.log)
[umbrel-1653739321600-debug.log](https://github.com/getumbrel/umbrel/files/8791165/umbrel-1653739321600-debug.log)
[debug file .pdf](https://github.com/getumbrel/umbrel/files/8791171/debug.file.pdf)

Any help will be really appreciated.  Also if it turns out that that I need to re-flash my sd:
- will this require my static channel backup (SCB)? 
- I have downloaded by SCB straight from Umbrel, but it's a bunch of encrypted stuff which looks like garble.  Not sure if that is what I should expect to see, if not then what am I doing wrong?
Thanks for any help offered!

**Comment by nmfretz** [comment]
closing old support issue
