### ISSUE TITLE
RBF tx counted n times.

### ISSUE THREAD

**Issue by artdesignbySF** [getumbrel/umbrel#1406]
When sending a single tx to my Umbrel node and using RBF n number of times, the total balance increases by n times the total amount of the single tx. 

So if I send 100k sats and proceed to RBF it 3 times I see 3 incoming tx's of 100k and the Balance on Umbrels mainpage is increased by 300k sats.

This may be used against newbies. 

Edit: 
I now realise this is not Umbrel specific. MyNode has this too, also RTL and Thunderhub.

Edit:
I wonder if this can be used to break front-end stuff via RBF until balance gets so huge stuff goes wrong...?! idk I'm a non-technical idiot.

Edit: 
This issue may be moot. Please excuse me if that is the case.

Cheers,

SF

**Comment by artdesignbySF** [comment]
I know realise this is not Umbrel specific. MyNode has this too, also RTL and Thunderhub.

**Comment by artdesignbySF** [comment]
This issue may be moot. Please excuse me if that is the case.

**Comment by louneskmt** [comment]
When you do a RBF, you broadcast a newer version of the transaction but paying more fees. Usually, softwares check the Mempool for incoming transactions and add the amount of the unconfirmed transactions to the balance. Some specify that it is unconfirmed, some others not really. If the software sees a transaction and its RBF transaction (that theoretically replaces it), it may think they are two different transactions.

**Comment by artdesignbySF** [comment]
That makes sense. I discussed it with some fellow runners and we came to this conclusion.  Should have maybe done that before posting here 😅 Thank you for taking your time and effort explaining!

**Comment by louneskmt** [comment]
My pleasure!
