### ISSUE TITLE
Update Specter Desktop 

### ISSUE THREAD

**Issue by relativisticelectron** [getumbrel/umbrel#1409]
The version of Specter Desktop in umbrel is quite old. 

But how do you build the docker container? I see no Dockerfile in https://github.com/getumbrel/umbrel/tree/master/apps/specter-desktop
There is only the https://github.com/getumbrel/umbrel/blob/master/apps/README.md 

Can you use https://github.com/cryptoadvance/specter-desktop/pkgs/container/specter-desktop ?  It is build using [Dockerfile](https://github.com/cryptoadvance/specter-desktop/blob/master/Dockerfile)

**Comment by relativisticelectron** [comment]
@k9ert : Do you have expertise how to update the umbrel specter docker container?

**Comment by k9ert** [comment]
The default docker-container from @nolim1t is used. Here is a commit with the last update: https://github.com/getumbrel/umbrel/commit/da9e7acf3fe3e16c9d5a24350ac9d505e9d3111b
Seems like some people took care of that. Last time it was @louneskmt

**Comment by nolim1t** [comment]
The specter containers are always up to date.

However I'm not updating Umbrel projects anymore due to lack of open source licensing.

It's up to them as a funded company to do so.

RunCitadel is the way to go forward. It gets updated faster

**Comment by relativisticelectron** [comment]
> It's up to them as a funded company to do so.

Ok, that sounds logical.

@lukechilds : Would you consider updating Specter Desktop? Specter Desktop 1.9.1 of https://github.com/getumbrel/umbrel/commit/da9e7acf3fe3e16c9d5a24350ac9d505e9d3111b is quite old.

**Comment by relativisticelectron** [comment]
Cool I just saw it was updated https://github.com/getumbrel/umbrel-apps/blob/fb3e468beb9400d455acacd5eeb7300bd6bd91e4/specter-desktop/umbrel-app.yml#L5

**Comment by Alex71btc** [comment]
Hi guys, since there are several updates of specter desktop out again, would you mind updating the app to specter 2.1.7?
Also I am maintainer of the startos repo of specter, if you want I could also maintain the umbrel app...
