### ISSUE TITLE
When pasting public local URL pointing to app/service it re-directs to "Login" page for App

### ISSUE THREAD

**Issue by wksantiago** [getumbrel/umbrel#1412]
When pasting a public local URL pointing to app/service it re-directs to "Login" page for App

Example
When going to:
http://Internet_IP_Address:3006/

It then goes to:
"http://Internet_IP_Address:2000/?origin=host&app=mempool&path=%2F"

Then it re-directs to:
http://Internet_IP_Address:3006/

Before the last update it worked without requiring authentication.

Is there a setting that can be enabled to allow for a link to an app/service without authenticating?

Thanks,

**Comment by wksantiago** [comment]
The idea is to provide the local community with a local mempool version of  (https://mempool.space/)

Thanks,

**Comment by nevets963** [comment]
Hi @wksantiago

You can disable the authentication for an installed app by adding a file called `.env.app_proxy` inside the installed application folder. e.g. inside `~/umbrel/app-data/mempool` with the following contents:

```
PROXY_AUTH_ADD=false
```

And then restart the application, e.g.
```
~/umbrel/scripts/app stop mempool
~/umbrel/scripts/app start mempool
```

This will then have the same behaviour as before the 0.5 Umbrel update.

I hope that helps!

**Comment by wksantiago** [comment]
Awesome thanks
