### ISSUE TITLE
[Feature] Bring back config file

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel#1414]
I had a lot of customizations in my `bitcoin.conf` and in the latest Umbrel release this file is replaced by commandline parameters.

This makes it really difficult to make changes (one would need to edit the docker configuration), difficult to backup certain settings, and also difficult to read since everything is in one line.

I am not sure what the advantage was of this change, but I really would like the possibility to just use a `bitcoin.conf` file.

EDIT: It seems instead of modying the container config, you can edit `exports.sh` instead. But this is still unhandy. Normally you could edit the `bitcoin.conf` and just restart the container to apply the settings. With `exports.sh` you have to restart the whole Umbrel after a change. 

Also because the file has a completely different structure than a normal `bitcoin.conf` it becomes impossible to copy-paste from other sources or to easily comment out a line.

EDIT: The third option seems to be to place a `bitcoin.conf` in the datadir like before. The only problem is that the commandline parameters override the options specified in the config file. But in my case I am mostly adding settings and not changing the existing ones except for `dbcache`, so this is a good workaround for now.

**Comment by nevets963** [comment]
Hi @kroese 

The third option is what we now suggest people do. As you say, within the bitcoin data directory (`~/umbrel/app-data/bitcoin/data/bitcoin`), you can create a `bitcoin.conf` file that will store the specific settings. You're right, in that the command line arguments take precendence but I think the defaults that we're setting are reasonable for the vast majority of users and we tried to keep those to an absolute minimum allowing for maximum customisation.

Once you create a `bitcoin.conf` file in that folder, don't forget to restart the "Bitcoin Node" app using:
```
~/umbrel/scripts/app stop bitcoin
~/umbrel/scripts/app start bitcoin
```

The same technique also applies to LND (called "Lightning Node") and Electrs
