### ISSUE TITLE
Installed on RockPro64 but did not recognize NVMe drive

### ISSUE THREAD

**Issue by PLK2** [getumbrel/umbrel#1415]
- Fresh install of Debian Bullseye on my RockPro64.
- Attached NVMe drive via PCIe (didn't mount it or anything).
- Inserted microSD with 0.5.0 Umbrel install and went through installation process.
- All went well except it didn't recognize the NVMe drive. How to make that happen?

**Comment by nevets963** [comment]
@PLK Currently Umbrel OS will automatically setup external/additional drives that are connected **via USB**. ie we automatically detect them, format and partition it, etc, etc.

I have no idea when we'll have the same functionality for NVMe, however what you could do is; format your NVMe and setup eg a EXT4 file system on it, and then run our installation script and set the path to install to as your NVMe-based partition running e.g. `curl -L https://umbrel.sh | bash -s -- --install-path /mynvme/path`

I hope that helps!

**Comment by PLK2** [comment]
Thanks!
