### ISSUE TITLE
[README] Step-by-step link leads to wrong url

### ISSUE THREAD

**Issue by voletro** [getumbrel/umbrel#1416]
The link that leads to the step-by-step instructions in the README.md here

> Step-by-step installation intructions can be found [here](https://umbrel/#start).

leads to 

[https://umbrel/#start](https://umbrel/#start)

instead of 

[https://umbrel.com/#start](https://umbrel.com/#start)

meaning users can't use this link to access the installation instructions on the Raspberry Pi.

**Comment by johnpc** [comment]
This should be fixed by https://github.com/getumbrel/umbrel/pull/1419

**Comment by mayankchhabra** [comment]
Thanks @voletro and @johnpc! Fixed by #1419 indeed.
