### ISSUE TITLE
karen is getting triggered! for Tailscale in 0.5.0

### ISSUE THREAD

**Issue by mccolister1017** [getumbrel/umbrel#1417]
Can't use the app can't install it .

Generating hidden services for tailscale...
No such service: app_proxy
Got signal: debug
karen is getting triggered!

**Comment by johnpc** [comment]
I am also experiencing the same. When I attempt to install Tailscale, the installation fails and this appears in `~/umbrel/logs/karen.log`:

```
Got signal: app-install-tailscale
karen is getting triggered!
Setting up data dir for app tailscale...
sending incremental file list

sent 170 bytes  received 13 bytes  366.00 bytes/sec
total size is 1,444  speedup is 7.89
Pulling images for app tailscale...
Pulling tor_server ...
Pulling web        ...
Pulling web        ... pulling from tailscale/tailscale
Pulling tor_server ... pulling from lncm/tor
Pulling web        ... digest: sha256:a8f3198bccfb3d2817...
Pulling web        ... status: image is up to date for t...
Pulling web        ... done
Pulling tor_server ... digest: sha256:3c4ae833d2fefbea7d...
Pulling tor_server ... status: image is up to date for l...
Pulling tor_server ... done
Starting app tailscale...
Generating hidden services for tailscale...
No such service: app_proxy
```

**Comment by johnpc** [comment]
this appears to be the same issue: https://github.com/getumbrel/umbrel/issues/1413

**Comment by lukechilds** [comment]
Thanks guys, very helpful! Can recreate, looking into it now.

**Comment by johnpc** [comment]
Not sure if there's a relevant difference between `app_proxy` and `app-proxy`

**Comment by lukechilds** [comment]
Hey guys I've pushed a fix that should resolve the issue https://github.com/getumbrel/umbrel-apps/pull/11

Are you able to let me know if it works for you?

It will take ~15 minutes for your Umbrel to pull down the latest changes to the app repo.

If you want to test right away you can run:

```
ssh -t umbrel@umbrel-fresh.local "sudo ~/umbrel/scripts/repo update"
```

This won't update any apps, it just gives you the latest changes to the installable apps in the app store.

**Comment by mccolister1017** [comment]
fortunately it's all good now thank you so much , it was fast  @lukechilds

**Comment by lukechilds** [comment]
Ah yes the command was only needed if you wanted to test within ~15mins of me posting the fix so you'd need to manually sync the latest app store changes.

Glad it worked, thanks for reporting back!
