### ISSUE TITLE
Uptime is wrong

### ISSUE THREAD

**Issue by ybaidiuk** [getumbrel/umbrel#1425]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/11969255/172687281-323a14f9-ec22-4142-89bf-42580979fafe.png">
I did today restart but Uptime is 3 days_ ) should be reseted.

**Comment by nevets963** [comment]
@esackbauer Yep correct, we read the uptime from the OS every 15 seconds. A full restart of the system will reset this. FWIW, most Umbrel updates will not reset this, as most of the time a reboot is not required.

@ybaidiuk Are you still having an issue?

**Comment by nevets963** [comment]
Closing for now. Please re-open if you continue to have a problem.
