### ISSUE TITLE
Home Assistant Restore Backup

### ISSUE THREAD

**Issue by akeslo** [getumbrel/umbrel#1430]
Is it possible to restore a backup of Home Assistant via the app published in Umbrel?

**Comment by mayankchhabra** [comment]
We've never tried it, but I assume it should work. One thing that I can think of is that HomeAssistant on Umbrel isn't the supervised version of HomeAssistant, so if you're using the supervised version, the restore might not work. No harm in trying I guess.

**Comment by Xosten** [comment]
> Is it possible to restore a backup of Home Assistant via the app published in Umbrel?

If you do a backup of Home Assistant and go through the restore function of it, then yes. I've published today a PR to update HASS to the latest version and you have the backup/restore function. It has been merged recently ;) https://github.com/getumbrel/umbrel-apps/pull/26. 

Check it out :)

**Comment by akeslo** [comment]
Thanks!!
