### ISSUE TITLE
v0.5.0+ suggestions

### ISSUE THREAD

**Issue by Hukuma1** [getumbrel/umbrel#1438]
Awesome release. Thank you for making it! Looks very clean.

I was thinking to make it even cleaner you could remove the light/dark mode button entirely. Feels like it should be a toggle under settings? And the logout button should go probably where the background change button is maybe? Background change should also probably be under settings.

And the decoupling of the apps that we can install from Umbrel releases is huge. Is it possible to bring in changelogs into the updates? So users can see what the update brings?

**Comment by nevets963** [comment]
@Hukuma1 In Umbrel v0.5.1 we added the changelogs into the UI for app updates :)

**Comment by tlindi** [comment]
Is changelog available somewhere before update?
