### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel#1441]
When I manually run:

`./scripts/repo update`

it will update all apps just fine.

But according to the code this should already be done automaticly on a 15 minute time schedule:

`./scripts/status-monitor repo 900 &>> "${UMBREL_LOGS}/status-monitor.log"`

However this not work for me on Ubuntu 22.04

**Comment by nevets963** [comment]
@kroese Is there anything useful within `${UMBREL_LOGS}/status-monitor.log` as to why this might be failing?
