### ISSUE TITLE
feature request: add multiple repos as source for App Store

### ISSUE THREAD

**Issue by losh11** [getumbrel/umbrel#1444]
**Motivation:** Currently users are able to swap to a custom repository for the Umbrel App Store or use `DEFAULT_UMBREL_APP_REPO_URL`. Users who are running external apps may wish to add custom repositories whilst still being able to access the default apps.

**Comment by nmfretz** [comment]
This can now be done with Community App Stores! https://github.com/getumbrel/umbrel-community-app-store
