### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by MagicLike** [getumbrel/umbrel#1450]
When I try to install Umbrel on Debian via the install script, I get the following error message
`main: Line 126: yq_sha256[$system_arch] is not set.`.

**Comment by nevets963** [comment]
What architecture do you have?

**Comment by MagicLike** [comment]
Intel x86

**Comment by nevets963** [comment]
Can you run these commands and post here what returns?

`dpkg --print-architecture`
`cat /etc/os-release`
`bash --version`

**Comment by MagicLike** [comment]
`dpkg --print-architecture`: `i386`

`cat /etc/os-release`:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

`bash --version`:
`GNU bash, Version 5.0.3(1)-release (i686-pc-linux-gnu)`

**Comment by nevets963** [comment]
Ah, you're running 32 bit which is not supported. You might have accidentally installed a 32 bit version of Debian? When downloading and installing Debian you should look for the `amd64` version - which I know is confusing as it has `amd` in there and you're running Intel :) But this should work unless, your hardware is over ~20 years old and is actually only 32 bit.

**Comment by MagicLike** [comment]
I think I self discovered the issue:
I am running RpiOS Desktop (only 32-bit) for testing and now that I know 32 is not supported, that is a verry simple issue to solve.
Thank you for you help and kindness!

**Comment by nevets963** [comment]
You’re welcome!
