### ISSUE TITLE
Deoes Umbrel support armhf?

### ISSUE THREAD

**Issue by stpnwf** [getumbrel/umbrel#1451]
Does Umbrel support **32 bit** Armbian 22.02 with **armhf** architecture (Debian Bullseye based)?

I get the error `main: line 126: yq_sha256[$system_arch]: unbound variable` when running this script.
I think it is bc `$system_arch` returns `armhf` and that is not available under the `yq` releases.

Is there anything I can do to get it working?

Thanks in advance

**Comment by lukechilds** [comment]
No unfortunately 32 bit arm is not a supported platform. Even if you could compile `yq` to get through the install process, we only distribute `arm64` and `amd64` variants of all the Docker images.

**Comment by stpnwf** [comment]
All good, thanks for the reply
