### ISSUE TITLE
Thunderhub connection issue since 0.5 upgrade

### ISSUE THREAD

**Issue by andysmithdev** [getumbrel/umbrel#1454]
Since upgrade to Umbrel 0.5, Thunderhub automatically logs out after about a minute. Other apps experiencing similar issues include RTL and LNDg but Thunderhub is by far the worst. Assume this is something to do with the new authentication method? 

Several other users have reported the same issue on the community forum and Telegram group.

Attempting to log in again then results in following error:

![Screenshot 2022-06-22 at 13 38 32-1](https://user-images.githubusercontent.com/3636754/175032021-573122c3-812c-4371-913b-4b0e8122f93e.png)

After leaving for a while user is able to eventually able to login again.

All working fine before 0.5 upgrade.

**Comment by SeafireGit** [comment]
Same here

**Comment by lukechilds** [comment]
@SeafireGit are you on Umbrel 0.5.0 or 0.5.1?

**Comment by andysmithdev** [comment]
> @SeafireGit are you on Umbrel 0.5.0 or 0.5.1?

0.5.1 seemed to improve the situation a lot for me although it still happens occasionally.

**Comment by lukechilds** [comment]
Is it the same error?

This was a known issue in Umbrel 0.5.0 where the app proxy server could time out for slow requests. In 0.5.1 we removed the timeout so this should not be happening anymore.

**Comment by andysmithdev** [comment]
It appeared to be the same issue. However it seems to have been fixed completely since installing the updated Thunderhub from the app store.
