### ISSUE TITLE
Umbrel apps can access LAN?

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel#1456]
I always thought that `umbrel_main_network` was a`bridge` network that was a private and isolated. So that containers can only communicate with other containers in the same network, and with the host.

But when installing the 'Home Assistant' app, to my surprise I noticed it could communicate with my 'Hue Bridge' just fine. This is weird, because this machine is not part of `umbrel_main_network`, but just a device in my local LAN. To further investigate, I tried to ping some other machines in my LAN from inside the bitcoin container, and this also succeeded.

I am not sure if the reason for this is in the configuration for `umbrel_main_network` or if its specific to my docker settings. The only non-default docker setting is that I disabled the `userland-proxy`, but it might be the culprit.

So can other people also reproduce this behaviour? Because when it's the same for everybody, it can be considered a severe security risk.

**Comment by Falci** [comment]
AFAIK, those network settings protect the container to be accessed from external devices, not the other way around.
Like you computer can access any server in the internet, but they can access your computer.
