### ISSUE TITLE
Restore without formatting SSD

### ISSUE THREAD

**Issue by ElucGeek** [getumbrel/umbrel#1466]
Hello,
I have a problem with my Umbrel after months of working fine, suddently it was unreachable, it looks like it's not starting properly as it never get an IP on the network (wired, RJ45 has light ON on both sides). There might be a power shortage at some point, one longer than my UPS can handle, it might be the reason (or not). Nevertheless I check the SSD and SD card from a PC and both looks fine, thus I suspect that if it's not booting and not getting an IP it's a problem with the OS on the SD. I prepare a new SD with a freshly flashed OS but I didn't start it yet as the step by step tutorial mention that it will format automatically my SSD on boot. Of course I don't want that, I want to recover from the data on the SSD.

How can I do that? I tried to read on the community but all restore scenarios assume a complete fresh start with new SD and SSD (and so I guess I complete Bitcoin sync to do and so on).
Is what I try to achieve doable? Is there an documentation for that?

**Comment by louneskmt** [comment]
Hey! Usually a reflash of the microSD solves this kind of issue. Reflashing the microSD won't format the SSD automatically if it detects an Umbrel install on it (and it will detect one in this case). Try this, and report back 😁

**Comment by ElucGeek** [comment]
> Hey! Usually a reflash of the microSD solves this kind of issue. Reflashing the microSD won't format the SSD automatically if it detects an Umbrel install on it (and it will detect one in this case). Try this, and report back grin

Hi @louneskmt thank you very much, I was afraid to try this because of what says the tutorial, would have been great to have this mention somewhere. Node was back online within a couple of minutes, syncing the backlog of blocks.
