### ISSUE TITLE
External storage mounter failed on the first boot

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#147]
```
umbrel@umbrel:~ $ systemctl status umbrel-external-storage.service
● umbrel-external-storage.service - External Storage Mounter
   Loaded: loaded (/etc/systemd/system/umbrel-external-storage.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-08-15 18:14:38 UTC; 25min ago
 Main PID: 361 (code=exited, status=1/FAILURE)

Aug 15 18:14:38 umbrel systemd[1]: Starting External Storage Mounter...
Aug 15 18:14:38 umbrel external storage mounter[361]: Running external storage mount script...
Aug 15 18:14:38 umbrel external storage mounter[361]: No block devices found
Aug 15 18:14:38 umbrel external storage mounter[361]: Exiting mount script without doing anything
Aug 15 18:14:38 umbrel systemd[1]: umbrel-external-storage.service: Main process exited, code=exited, status=1/FAILURE
Aug 15 18:14:38 umbrel systemd[1]: umbrel-external-storage.service: Failed with result 'exit-code'.
Aug 15 18:14:38 umbrel systemd[1]: Failed to start External Storage Mounter.
umbrel@umbrel:~ $ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 931.5G  0 disk 
`-sda1        8:1    0 931.5G  0 part 
mmcblk0     179:0    0  29.8G  0 disk 
|-mmcblk0p1 179:1    0   256M  0 part /boot
`-mmcblk0p2 179:2    0  29.6G  0 part /
```

**Comment by mayankchhabra** [comment]
Can confirm this didn't happen after a restart.

**Comment by mayankchhabra** [comment]
Ah, this is probably unrelated to the first boot, and can happen any time when systemd starts the `umbrel-external-storage.service` **before** the USB device is available.

**Comment by lukechilds** [comment]
Is there some service we can add to `Requires` or `After` in the external storage service that will ensure block devices have been enumerated before it runs?

If not, maybe we could add a special check that on the condition there are zero block devices, keeps retrying every second a total of n times before giving up.

**Comment by mayankchhabra** [comment]
> Is there some service we can add to Requires or After in the external storage service that will ensure block devices have been enumerated before it runs?

From my little bit of research, it seems we can't do that unless we know the exact path to the device (which we don't). I really like your idea on this:

If not, maybe we could add a special check that on the condition there are zero block devices, keeps retrying every second a total of n times before giving up.

Makes sense!

**Comment by lukechilds** [comment]
Ok, do we need this implemented for beta launch?

**Comment by mayankchhabra** [comment]
Only if it doesn’t take more than 15 minutes to fix haha, otherwise we can fix it later no worries!
