### ISSUE TITLE
installing  on parrot os  shows error   Operating System: Parrot OS 5.0 (Electric Ara)

### ISSUE THREAD

**Issue by synackred** [getumbrel/umbrel#1470]
![image](https://user-images.githubusercontent.com/93832969/177790157-80412128-361f-4611-8c4f-2111847a31b9.png)
Hit:4 https://deb.parrot.sh/parrot parrot-backports InRelease                                                      
Ign:5 https://download.docker.com/linux/debian parrot InRelease                      
Hit:6 https://cli.github.com/packages stable InRelease                               
Err:7 https://download.docker.com/linux/debian parrot Release  
  404  Not Found [IP: 2600:9000:213c:c000:3:db06:4200:93a1 443]
Get:8 http://packages.microsoft.com/repos/code stable InRelease [10.4 kB]
Get:9 http://packages.microsoft.com/repos/code stable/main armhf Packages [93.1 kB]
Get:10 http://packages.microsoft.com/repos/code stable/main arm64 Packages [93.3 kB]
Get:11 http://packages.microsoft.com/repos/code stable/main amd64 Packages [92.4 kB]
Reading package lists... Done                               
E: The repository 'https://download.docker.com/linux/debian parrot Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by hari5556** [comment]
Is this issues solved Or not aa bro

**Comment by hari5556** [comment]
If it solves pls help me to solve this problem bro

**Comment by mayankchhabra** [comment]
Sorry for the issue, @synackred and @hari5556. Umbrel is officially only supported and tested on Ubuntu/Ubuntu Server and Debian OS. Even if this issue can be fixed, we wouldn't recommend installing it on Parrot OS because there could be potential problems in the future.

**Comment by hari5556** [comment]
👍
