### ISSUE TITLE
Tailscale will not install

### ISSUE THREAD

**Issue by BirbEXE** [getumbrel/umbrel#1474]
Heya

Tried to install tailscale recently, but I hit install and every time I refreshed the page, the install button was right where I left it

after a bit more tinkering, I tried to install it via the umbrel CLI, but that also failed:

![image](https://user-images.githubusercontent.com/60234159/179345993-967fde34-bc05-4f2a-a670-95b7e3eb6f3e.png)

any ideas guys?

I'm running umbrel on a pi4, on top of ubuntu.

**Comment by BirbEXE** [comment]
note: all other app installs seem to work fine. It's just this one that wants to be a little bit finicky

**Comment by lukechilds** [comment]
Thanks for the detailed report @BirbEXE, I think I know what the issue is, will try to get a patch out asap I'll keep you posted!

**Comment by lukechilds** [comment]
OK @BirbEXE this should resolve your issue: https://github.com/getumbrel/umbrel-apps/pull/77

It might take ~15 minutes for your Umbrel to pull down the latest app store changes. Once you see the option to install Tailscale `1.26.2-build-2` instead of `1.26.2` it should install correctly.

Please let me know if you still experience issues!

**Comment by BirbEXE** [comment]
thanks, I'll give it a go!

**Comment by BirbEXE** [comment]
yeah, seems to work great now.

thanks for your help!

**Comment by BirbEXE** [comment]
@lukechilds just found the same issue with pi-hole 🤦🏻

**Comment by EpsilonCommunity** [comment]
I'm having the same issue:

Warning: "tailscale" has no 'app_proxy' defined
         "tailscale" needs this to generate Tor HS

**Comment by nevets963** [comment]
@EpsilonCommunity Can you confirm which version of Umbrel you're using?
