### ISSUE TITLE
Pi-hole cannot start - bind: address already in use

### ISSUE THREAD

**Issue by BirbEXE** [getumbrel/umbrel#1475]
Running umbrel on top of ubuntu - hardware: rpi4

When I try and install pi-hole, it will install, but it cannot start.
It appears that the address pi-hole tries to bind to is already in use by ubuntu.
Not sure if this would be a very easy fix, but it'd involve probably modifying the pi-hole docker-compose file to change the ports.

CLI log:
![image](https://user-images.githubusercontent.com/60234159/179350975-17dfa738-3062-4c2c-bf4c-43f690dd2ac1.png)

thanks

**Comment by dlq84** [comment]
Figure out what program is running on port 53 already on the host by doing something like this: `sudo netstat -tunlp | grep 53`

**Comment by BirbEXE** [comment]
Sorry, I didn't clarify.
I already know what's running on port 53. Ubuntu has systemd-resolved listening on port 53 by default, which is what's blocking pihole from starting.

You can fix it by either using a different port, or changing `/etc/systemd/resolved.conf`

**Comment by lukechilds** [comment]
Ahh you'll probably be having conflicts with Ubuntu's `systemd-resolve` package which runs a DNS proxy on port 53. @BirbEXE can you try this: https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu

Looks like your options are modify the `systemd-resolve` config to not run a DNS server, or disable the service entirely, depending on how you want to configure your system.

Let me know if this resolves your issue and we can look into automating this patch on Ubuntu hosts when pi-hole is installed.

**Comment by lukechilds** [comment]
>Not sure if this would be a very easy fix, but it'd involve probably modifying the pi-hole docker-compose file to change the ports.

We unfortunately can't run pi-hole on a non-standard port since very few clients will connect to a DNS server that doesn't run on port 53. Due to this, to run pi-hole successfully, you'll need to be running Umbrel on a system that has port 53 free.
