### ISSUE TITLE
i2p and bitcoin-core

### ISSUE THREAD

**Issue by awholegnuworld** [getumbrel/umbrel#1476]
Currently the bitcoin-core implementation runs on IPv4, IPv6, and Onion. Will i2p be integrated? Screenshot of the Bitcoin RPC Explorer app:
![Screen Shot 2022-07-16 at 15 21 43](https://user-images.githubusercontent.com/56049227/179371168-9046a84b-da42-4b4b-9bd8-181eaf10a364.png)

**Comment by nmfretz** [comment]
The Bitcoin Core app now has I2P integrated. You can manage connection settings in `Advanced Settings` within the app:

<img width="831" alt="image" src="https://github.com/getumbrel/umbrel/assets/85373263/74daf104-0c1c-4b43-9f24-a6f84e4991c0">
