### ISSUE TITLE
Update Electrs to v0.9.7

### ISSUE THREAD

**Issue by SoundMoneyWins** [getumbrel/umbrel#1477]
Umbrel v0.5.1 is currently running electrs v0.9.4 which was released on 1/3/22. Current release of electrs is v.0.9.7 released on 4/30/22. 

https://github.com/romanz/electrs/releases

**Comment by super-e** [comment]
0.9.4-build-2 is affected by https://github.com/romanz/electrs/issues/783 as of 1st Nov 2022 node is stuck in "Waiting for Bitcoin Node to finish syncing...". Umbrel should update to the latest version.

**Comment by nevets963** [comment]
An update for Electrs v0.9.9 rolled out about 30 minutes ago. Can you install v0.9.9 and see if the problem still persists?

**Comment by super-e** [comment]
Updated to v0.9.9 and within a minute it was 100% synchronized.  We can close this, thanks.
