### ISSUE TITLE
umbrel & miners 

### ISSUE THREAD

**Issue by hpx127** [getumbrel/umbrel#1479]
Inside Umbrel software ,they run both lightning node /full(bitcoin) node so my questions are

1. if Umbrel "**provide**" mining functionality  then Umbrel how to mine send and receive transection  block....? 
2. If not then Umbrel use any third party miners ...?
3. How to connect Full node with any Miner pool ....?

**Comment by esackbauer** [comment]
Full node and mining are 2 completely separate functionalities. For a good reason.
You need to learn how mining and full nodes work together.

**Comment by hpx127** [comment]
Take a example i have Umbrel full node so how to connect any third party memory pool....like f2pool,slashpool ...it is possible....?

**Comment by esackbauer** [comment]
And now you bring in a 3rd topic (LIghtning Network) you obviously don't understand, because it has nothing to do with mining Bitcoin.
