### ISSUE TITLE
changing the alias name in 0.5.1

### ISSUE THREAD

**Issue by abubakralhaj** [getumbrel/umbrel#1484]
Does anyone have an idea how I can change the Alias name in umbrel 0.5.1 
- the umbrel/lnd/lnd.conf  (doesn't exist anymore)
- new location file is empty

**Comment by nevets963** [comment]
@abubakralhaj The Umbrel v0.5 update moved several apps (including LND) to the App Store. The config. file you're now looking for lives here: `~/umbrel/app-data/lightning/data/lnd`.

I hope that helps!
Steve
