### ISSUE TITLE
help

### ISSUE THREAD

**Issue by roblox34** [getumbrel/umbrel#1485]
This is a SOCKs proxy, not an HTTP proxy.
It appears you have configured your web browser to use this Tor port as an HTTP proxy.

This is not correct: This port is configured as a SOCKS proxy, not an HTTP proxy. If you need an HTTP proxy tunnel, use the HTTPTunnelPort configuration option in place of, or in addition to, SOCKSPort. Please configure your client accordingly.

See https://www.torproject.org/documentation.html for more information.

**Comment by nevets963** [comment]
Hi @roblox34 Can you provide some context with what this is related to?

**Comment by roblox34** [comment]
umbrel on codespaces

> Hi @roblox34 Can you provide some context with what this is related to?
