### ISSUE TITLE
Lightning App doesn't load after upgrade

### ISSUE THREAD

**Issue by aphex3k** [getumbrel/umbrel#1486]
After upgrading to latest Umbrel v0.5.1 and installing the lnd and bitcoin apps from the store, the bitcoin app seems to work fine but the lightning app is stuck at load on http://umbrel.local:2101.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/433270/185535170-1b15b426-b95a-4e48-ab36-a4a1d8571722.png">

The loading bar doesn't continue past this point. In the Chrome dev tools and in the `lightning_app_1` logs it shows umbrel-middleware continuously checking for seed-exists...

```
umbrel-middleware
Checking LND status...
LND already unlocked!
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:28 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:30 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:32 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:34 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:36 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:38 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:40 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:42 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:44 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:46 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:48 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:50 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:52 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"

umbrel-middleware
::ffff:10.21.0.11 - - [Fri, 19 Aug 2022 03:16:54 GMT] "GET /v1/system/seed-exists HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"
```

The lnd container seems to operate just fine though as thunderhub works normally.

**Comment by lukechilds** [comment]
It looks like a migration step has failed to complete that normally runs directly after updating. Can you try to logout and logging in to your Umbrel dashboard, then check again?

Also did you have to manually install the apps? You shouldn't have to do this, they should be migrated over from your previous install.

**Comment by aphex3k** [comment]
I was updating from v0.4.14. 

1. I shut down umbrel and all the apps via `sudo scripts/stop`
2. I took a complete backup of the ~umbrel home folder via rsync to an external disk
3. I started the node back up via `sudo scripts/start`
4. In the UI I clicked the "Update button"

This is where my troubles began...

After a while I received an email from my node that disk space was used by 80% and I noticed that the bitcoin data folder has moved to a different location. The problem is that my bitcoin folder was a mount to an external 2GB HDD and the update script moved all 500+ GB to the internal SSD storage. 

1. I stopped the node again, 
2. deleted the bitcoin data folder at the new location in `app-data`, 
3. changed mounting arrangements
4. restored the entire 500GB back to the external drive from my backup
5. I also noticed that the lnd data folder moved to `app-data` but I didn't worry about it or did anything with it.
6. I started the node again and logging in on umbrel.local presented me with the new v0.5.0 UI.
7. I was able to log in with my password and 2FA
8. All but one apps showed as "Starting..." for over 5 minutes so I started investigating further...
    - I had the following apps installed at this point:
    - Bitcoin
    - BlueWallet
    - Electrs
    - Lightning Node
    - Lightning Terminal
    - mempool
    - Samourai Server
    - Specter Desktop
    - Tallycoin Connect
    - Thunderhub
    - Tor Snowflake
    - Ride The Lightning
9. Tor Snowflake was the only app that "wasn't starting"
10. `docker ps` showed that all other containers where in varying status of "Restarting"...
11. For good measure, I uninstalled all apps so that my list of installed apps showed 0 and my app-data directory was empty
    - This also deleted all 500 GB bitcoin data from my external HDD again... So I restored it a once more
12. I wanted to re-install all apps one-by-one so I started with Bitcoin
13. I installed the app via `scripts/app install bitcoin`
14. stopped the `bitcoin` app via scripts
15. fixed the mounting situation after all 500GB restored
16. restarted the bitcoin app using the script
17. In the `bitcoin_bitcoind_1` log I could see the node starting up correctly
18. I was able to via the bitcoin app in umbrel.local correctly and connect with Sparrow and Bisq to the node successfully so I assume it working properly
19. I then progressed the same way across all the apps
    1. install the next app in the list
    2. stop the app after successful installation
    3. restore the apps data folder from my backup drive
    4. restart the app and monitor the docker logs

It seems like BlueWallet and Electrum got new tor hidden service URLs and some of the apps (like Thunderhub and Lightning Terminal) deterministic passwords are now different from before but I was able find the updated ones in the app store UI.

**Comment by aphex3k** [comment]
@lukechilds based on [apps/backend/routes/v1/system/index.js#L59](https://github.com/getumbrel/umbrel-lightning/blob/b47042cb4f743abff36f54395ff896bbc9481296/apps/backend/routes/v1/system/index.js#L59) my installation is missing a `data/state.json` file. I can not find that on my disk or in my backup.

**Comment by lukechilds** [comment]
Do you have your LND seed handy?

We run a migration during update that migrates the old LND wallet data into the new app structure. It seems like somewhere along the stop you took you lost this migrated data. If you uninstalled the Lightning app and then reinstalled it, it will have created a new wallet.

If you still have your original LND data dir you can just drop that in and then manually create the `app-data/lightning/data/lightning/state.json` file with the contents:

```
{
  "seed": "your lnd seed here"
}
```

If you don't have a backup of the previous LND install then you'll need to reinstall the latest version of the app which now supports automatic recovery. You can enter your seed and all on-chain funds will be recovered and old Lightning channels will be force closed and recovered on-chain.

To prevent something like this happening again I would strongly suggest running the entire Umbrel install from the same mount. Otherwise any migrations we run in the future could potentially trigger a similar issue.

**Comment by aphex3k** [comment]
I have the 24 word seed phrase when first installing Umbrel. I don't think I have a separate Lightning seed phrase.

> If you still have your original LND data dir you can just drop that in and then manually create the `app-data/lightning/data/lightning/state.json` file with the contents:

Is this a separate or different seed?

**Comment by lukechilds** [comment]
It's the same seed you were given when you originally installed Umbrel.

**Comment by aphex3k** [comment]
That worked.
