### ISSUE TITLE
Installing BTCPay server plugins is not possible

### ISSUE THREAD

**Issue by slaapyhoofd** [getumbrel/umbrel#1495]
When you install a plugin in BTCPay server you get the message:

_Plugin scheduled to be installed._ 
_You need to restart BTCPay Server in order to update your active plugins._

And an action is scheduled to be installed
![image](https://user-images.githubusercontent.com/90801537/187996193-28dde62b-e0d4-42c8-b799-b8afe8a6fcb3.png)

I tried different ways of restarting BTCPay:

1. docker restart container
2. ~/umbrel/scripts/app restart btcpay-server

According to the BTCPay server manual there should be 2 other options:
https://docs.btcpayserver.org/FAQ/ServerSettings/#how-to-restart-btcpay-server

1. Maintenance option in the Server Settings menu, which is not there. (Maintenance feature is removed long ago so manual is not up-to-date) 
2. btcpay-restart.sh script, I looked in the BTCPay docker container via docker exec -it mycontainer /bin/bash but the script does not exist

Is there a correct way to restart BTCPay server so the plugins will be installed?

**Comment by leesalminen** [comment]
> When you install a plugin in BTCPay server you get the message:
> 
> _Plugin scheduled to be installed._ _You need to restart BTCPay Server in order to update your active plugins._
> 
> And an action is scheduled to be installed ![image](https://user-images.githubusercontent.com/90801537/187996193-28dde62b-e0d4-42c8-b799-b8afe8a6fcb3.png)
> 
> I tried different ways of restarting BTCPay:
> 
> 1. docker restart container
> 2. ~/umbrel/scripts/app restart btcpay-server
> 
> According to the BTCPay server manual there should be 2 other options: https://docs.btcpayserver.org/FAQ/ServerSettings/#how-to-restart-btcpay-server
> 
> 1. Maintenance option in the Server Settings menu, which is not there. (Maintenance feature is removed long ago so manual is not up-to-date)
> 2. btcpay-restart.sh script, I looked in the BTCPay docker container via docker exec -it mycontainer /bin/bash but the script does not exist
> 
> Is there a correct way to restart BTCPay server so the plugins will be installed?

Please see my comment on this issue: https://github.com/btcpayserver/btcpayserver/issues/4094

**Comment by nmfretz** [comment]
Plugin installation now works on BTCPay Server on Umbrel
