### ISSUE TITLE
How to add external storage?

### ISSUE THREAD

**Issue by hex** [getumbrel/umbrel#1497]
How to add external storage to the existing Umbrel install? I tried changing the user's home directory on the external drive, but nothing changed storage-wise.

**Comment by JimSB** [comment]
Using multiple drives for an Umbrel installation is not yet officially tested or supported yet.  But right this second for your second drive I would suggest reinstalling on the external drive you intend to use or sticking with whichever has more storage space - whichever drive you intend to use for Umbrel to avoid any errors.  Installing again should only take a few moments, and shouldn't be a problem if you haven't started the Bitcoin sync yet.

You can install Umbrel on the other drive by using this installation command for installing Umbrel on the other drive:

`curl -L https://umbrel.sh | bash -s -- --install-path path/to/external/drive`

Replacing `path/to/external/drive` to the directory you'd like to install in, if you leave it as `drive` Umbrel will install in its root.

(There is also a way [here ](https://github.com/getumbrel/umbrel-os/issues/119#issuecomment-691949967)to migrate Bitcoin blockchain data) Though stay tuned, the Umbrel team is hard at work on making migration much easier in the very very near future! 

As always feel free to make a post in the Telegram for immediate assistance! https://t.me/getumbrel/207765

**Comment by tmsgm** [comment]
hey, how do i know the path to the drive conected to the pc with umbrel?
