### ISSUE TITLE
Backup for uninstalling applications (like c-lightning etc.)

### ISSUE THREAD

**Issue by NuiceT** [getumbrel/umbrel#1503]
Like 30 minutes ago I uninstalled c-lightning, and I didn't have the seedphrase (btw there's literally no option to show it, the except hsm-secret file). So because of that I lost 0.01 btc and there's no uninstall backup.

Maybe it'd be an option to include that, if you uninstall something without your mind (like me).

**Comment by yashwanthambati** [comment]
You can retreive your sats through hsm file. Check out core-lightning backup docs
