### ISSUE TITLE
how to change network ip set by NETWORK_IP in .env?

### ISSUE THREAD

**Issue by ziofil** [getumbrel/umbrel#1505]
If I try to modify the .env file, it resets automatically 🤔

**Comment by JimSB** [comment]
Hey @ziofil !!  

If you're still having any issues hop into the Telegram anytime for realtime assistance!  https://t.me/getumbrel/207765

Changes were made after v0.5+ for settings in regards to this, or it may also also depend on your use-case or what application you are using 

If there's still anything you need currently the Telegram is a great option where you can share anything you're still trying to accomplish and to get an answer quickly, or you can always drop us a line anytime using the message box on [Umbrel.com](https://www.umbrel.com)!
