### ISSUE TITLE
Installing umbrel on ubuntu when tor already installed

### ISSUE THREAD

**Issue by benthecarman** [getumbrel/umbrel#1506]
I am trying to install umbrel on ubuntu with tor and bitcoind already installed. I am getting this error. Is there a way around this besides shutting down tor?

```
ERROR: for tor_proxy  Cannot start service tor_proxy: driver failed programming external connectivity on endpoint tor (f48d083175b141d5b347a99d2e0fe8dfec2ed4a04656d0a4ccb1669013ba0bc9): Error starting userland proxy: listen tcp4 127.0.0.1:9050: bind: address already in use
```

**Comment by nmfretz** [comment]
Hey @benthecarman, in case you haven't solved this already, see here for explanation on why a separate Tor instance cannot be run in addition to Umbrel: https://github.com/getumbrel/umbrel/issues/1576#issuecomment-1380281168
