### ISSUE TITLE
Small delay (5 - 7s) when loading any app from the dashboard after not accessing apps for several minutes

### ISSUE THREAD

**Issue by taranjlu** [getumbrel/umbrel#1511]
I have the following setup:
- Proxmox installed on a Thinkpad T580
-  Ubuntu 22.04 LTS server VM
- Installed Umbrel via the installation script
- Installed several Umbrel apps via the App Store (Gitea, Invidious, Nitter, Whoogle, etc.)

All of the apps that I have installed work, but there is always a short 5 - 7 second delay when launching any of them if it has been several minutes since I have done so. After the initial delay, all of the apps seem to load quickly, and it doesn't seem to matter which app is the one that is first loaded.

This is very annoying, since many of these apps are expected to be responsive, and it kind of kills the usability of something like Invidious if I have to suddenly wait 5 -7 seconds after watching a video to get back to the main page.

I am wondering if there is something going on with the containers being spun-up/down?

**Comment by nmfretz** [comment]
Hey @taranjlu, if you are still having this issue please reach out for support through [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/).
