### ISSUE TITLE
Impossible update to 0.5.0

### ISSUE THREAD

**Issue by Doppiab** [getumbrel/umbrel#1516]
HI there, I have a Pine Quartz64 model A with Armbian (a version of Debian dedicated to this machine), I am unable to update my version of Umbrel. I have installed the v. 0.4.18, but when I update everything stays as it is. I also tried manual updating but when I reboot my version is still 0.4.18 and Umbrel offers me to install 0.5.0. What can I do? 

Thank You!

**Comment by hugomd** [comment]
I ran into the same problem and had to go through the manual update process.

From the [troubleshooting guide](https://community.getumbrel.com/t/umbrel-troubleshooting-guide/3632):

> If you have error that a specific Umbrel App do not start or it keeps staying in “installing”, maybe the docker container for that app it wasn’t installed correctly or it hangs.
>
> Step 1 - Enter using SSH into your Umbrel node:
> 
> Step 2 - stop Umbrel node with:
>
> ```
> cd umbrel
> ```
>
> Normal Linux OS use `sudo ./scripts/stop`
> UmbrelOS (RPi) use `sudo systemctl stop umbrel-startup`
> 
> Step 3 - clean / reconfigure the broken container:
> 
> ```
> sudo rm .env && sudo ./scripts/configure
> ```
> 
> Step 4 - apply latest Umbrel update (replace the version number with the latest):
> 
> ```
> sudo ./scripts/update/update --repo getumbrel/umbrel#v0.51
> ``` 
>
> Restart your node:
> 
> Normal Linux OS use `sudo ./scripts/start`
> UmbrelOS (RPi) use `sudo systemctl start umbrel-startup`
> 
> You can open Umbrel dashboard, but wait until latest blocks are catching up and also electrs is synced. All txs and channels will appear after a while.

**Comment by golosinskiyjosh** [comment]
@Doppiab Have you tried re-flashing the SD Card to the updated version 0.5.0 and check if that will update your Umbrel instance? That will often get the update to go through if automatic updates are not working.

**Comment by Doppiab** [comment]
> I ran into the same problem and had to go through the manual update process.
> 
> From the [troubleshooting guide](https://community.getumbrel.com/t/umbrel-troubleshooting-guide/3632):
> 
> > To manually update your node using SSH access.
> > Make a channels backup. Go to Umbrel dashboard - Lightning and on the right top side, 3 dots, save backup on your local PC.
> > **A. For Rasp Pi users:**
> > Enter using SSH into your Umbrel node, then run:
> > `cd ~/umbrel && sudo ./scripts/update/update --repo getumbrel/umbrel#v0.5.1`
> > Replace v0.5.1 with the version you want to update to.
> > If the update was stuck in update, run this before the above command:
> > `sudo rm statuses/update-in-progress`
> > `sudo rm statuses/update-status.json`
> > Restart your node if is done OK:
> > `sudo reboot`
> > **B. For normal Linux OS users:**
> > 
> > * Make a channels backup. Go to Umbrel dashboard - Lightning and on the right top side, 3 dots, save backup on your local PC.
> > * Stop Umbrel node: `sudo ./scripts/stop`
> > * Save your lnd.conf file if you edited (add color, name or specific features to your node). How to edit lnd.conf in Umbrel. More details about what you can add to a [lnd.conf file here](https://www.lightningnode.info/advanced-tools/lnd.conf). After version 0.4.0 this file is not overwritten anymore with a default one, but just in case, make a backup.
> > * Update system: `sudo apt update` and then `sudo apt upgrade`
> > * Restart system
> > * Update Umbrel (replace version with the latest release):
> >   `cd ~/umbrel && sudo ./scripts/update/update --repo getumbrel/umbrel#v0.4.8`
> > * Replace lnd.conf file with the one you save it before update (After version 0.4.0 this file is not overwritten anymore with a default one)
> > * Start Umbrel: `sudo ./scripts/start`
> > * Leave the node to catch up with blocks and logs, usually takes several minutes, be patient. Now you can enter into dashboard Umbrel
> > 
> > C. Just re-flash the mSD card with the latest Umbrel OS version, like you did when you install it first time.

Hi hugomd, thanks for the reply! I managed to update my Umbrel version to 0.5.0, but once updated the blockchian is no longer synchronized despite having 560Gb of data on my ssd. Can you help me solve the problem? Thank you.

**Comment by Doppiab** [comment]
> @Doppiab Have you tried re-flashing the SD Card to the updated version 0.5.0 and check if that will update your Umbrel instance? That will often get the update to go through if automatic updates are not working.

Hi golosinskiyjosh, thanks for the answer, but with my system I can't flash Umbrel directly on the sd. My version runs under Armbian.

**Comment by nmfretz** [comment]
Hi @Doppiab, if you are still having this issue, please reach out for support through our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/).
