### ISSUE TITLE
Starting new containers hangs

### ISSUE THREAD

**Issue by Space-Matrix2** [getumbrel/umbrel#1518]
When I start the node I have the errors:
WARNING: The APP_MEMPOOL_PORT variable is not set. Defaulting to a blank string.
WARNING: The APP_MEMPOOL_HIDDEN_SERVICE variable is not set. Defaulting to a blank string.
Node is up and running with Thunderhub and Ride the lightning but the umbrel UI not start in Browser

https://community.getumbrel.com/t/starting-new-containers-hangs/9596?u=space-matrix

**Comment by nmfretz** [comment]
closing old support issue
