### ISSUE TITLE
Verify all files has been backed up before deleting on update from 4.8 to 5.1

### ISSUE THREAD

**Issue by proof-of-reality** [getumbrel/umbrel#1520]
While updating my umbrel from version 0.4.8 to 0.5.1 verify all files has been sucessefully backed up.

After an unsucessful update to v5 via dashboard I tried updating my umbrel via the script update with the param --repo#v0.5.1 and it failed again. No problem at all. Afer that I restarted the node, cleaned up some files with old state from /statuses and tried the same update command again. I saw that the update was too fast and that the script was deleting all content from bitcoin/blocks (heart beat increases - but I thought evertything had been backed up) but unfortunetely it was not case

**Comment by dawalama** [comment]
Ugh... umbrel update script deleted all the files in my folder. What a disaster.

**Comment by nmfretz** [comment]
This issue has been fixed in [NETWORK_IP](https://github.com/getumbrel/umbrel/releases/tag/v0.5.3)
