### ISSUE TITLE
Why some containers restarting continually & I can access nothing ?

### ISSUE THREAD

**Issue by aboulaboul** [getumbrel/umbrel#1521]
here is what is returned by docker ps -a
[umbrel_containers.txt](https://github.com/getumbrel/umbrel/files/9821771/umbrel_containers.txt)

**Comment by aboulaboul** [comment]
Thank you for this quick answer
[debug.txt](https://github.com/getumbrel/umbrel/files/9833374/debug.txt)

**Comment by GalvaniObst** [comment]
From the log:
`There is probably issue with your power supply. We recommend using the official power supply to avoid this issue`
Are you using an official power supply for a Pi4 ?

**Comment by aboulaboul** [comment]
Yes I am

**Comment by aboulaboul** [comment]
I have tried with another raspberry and an other genuine power supply, still the same problem, anybody with any idea ?
80b7787d6d49   lightninglabs/lnd:v0.16.2-beta      "lnd --configfile=/d…"   5 hours ago   Restarting (2) 1 second ago                                                                            lightning_lnd_1
e7c9346706e1   getumbrel/bitcoind:v24.0.1          "bitcoind -port=8333…"   5 hours ago   Restarting (1) 48 seconds ago                                                                          bitcoin_bitcoind_1

**Comment by aboulaboul** [comment]
Finally 
1 I uninstalled bitcoin node and lightning
2 reinstall bitcoin node and now I can see it syncing the blockchain, mayby it's the solution

**Comment by aboulaboul** [comment]
it's definitely the solution :-)
