### ISSUE TITLE
AMP received transactions on Umbrel do not appear as listed on transactions list

### ISSUE THREAD

**Issue by bitcoinuser** [getumbrel/umbrel#1522]
Hi,

I linked my Zeus wallet with Umbrel and created an AMP invoice on Zeus and paid with Breez.

What I expected:

See the transaction received listed on Umbrel

What happens:

I'm able to receive the AMP transaction on Umbrel but the transaction is not listed on Umbrel transaction list.

**Comment by nmfretz** [comment]
This has been fixed by https://github.com/getumbrel/umbrel-lightning/commit/f3f1ab497da9c2c632a4e82465135e5fa63a96cb
