### ISSUE TITLE
Umbrel 0.5.2 not updateable

### ISSUE THREAD

**Issue by Ruppsn** [getumbrel/umbrel#1526]
I am starting the update but it stops after 3 sec with a message that the update was successfull. 

> == Begin Update Script 01-run.sh ==
> 
> =======================================
> =============== UPDATE ================
> =======================================
> =========== Stage: Install ============
> =======================================
> 
> Configuring new release
> 
> ======================================
> =========== RECONFIGURING ============
> ========= UMBREL (mainnet) ===========
> ======================================
> 
> Configuring permissions...
> 
> Configuration successful
> You can now start Umbrel by running:
>   sudo ./scripts/start
> 
> Pulling new containers
> [+] Running 5/5
>  ⠿ nginx Pulled                                                                                                                                           0.6s
>  ⠿ auth Pulled                                                                                                                                            0.7s
>  ⠿ tor_proxy Pulled                                                                                                                                       0.7s
>  ⠿ dashboard Pulled                                                                                                                                       0.7s
>  ⠿ manager Pulled                                                                                                                                         0.7s
> Saving current Umbrel Docker images to clean up later
> Reading file: /mnt/DATA/umbrel/docker-compose.yml
> usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
>           [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
>           [--indentless-lists] [--in-place] [--version]
>           [jq_filter] [files ...]
> yq: error: argument files: can't open '.services | map(select(.image != null)) | .[].image': [Errno 2] No such file or directory: '.services | map(select(.image != null)) | .[].image'
> == End Update Script 01-run.sh ==
> 
> 
> == Begin Update Script 02-run.sh ==
> 
> =======================================
> =============== UPDATE ================
> =======================================
> ========= Stage: Post-update ==========
> =======================================
> 
> == End Update Script 02-run.sh ==
> 
> 
> == Begin Update Script 03-run.sh ==
> 
> =======================================
> =============== UPDATE ================
> =======================================
> =========== Stage: Success ============
> =======================================
> 
> Removing backup
> Successfully installed Umbrel 0.5.2
> == End Update Script 03-run.sh ==
> 
> Deleting cloned repository
> Removing lock

How can i debug this?

**Comment by nevets963** [comment]
Could you confirm a couple of things for me?

Is Umbrel installed on a custom server? (ie not a Pi)
Can you check if this file exists: `/mnt/DATA/umbrel/docker-compose.yml` using e.g. `ls /mnt/DATA/umbrel/docker-compose.yml`
Can you post back what this returns? `yq --version`

**Comment by IMPranshu** [comment]
You can refer to the discussion here https://github.com/getumbrel/umbrel/issues/1527.

Also what you can do is try to ssh into Umbrel and stop it manually and then try to see if any containers are still running in the background and then force stop them. The commands for doing the same are:
```
ssh umbrel@umbrel.local /umbrel/scripts
sudo ./stop
docker ps
docker rm -f {put container_id}
```
Then start using
```
sudo ./start
```
Then try to update your Umbrel.

**Comment by 21Bensh** [comment]
> You can refer to the discussion here #1527.
> 
> Also what you can do is try to ssh into Umbrel and stop it manually and then try to see if any containers are still running in the background and then force stop them. The commands for doing the same are:
> 
> ```
> ssh umbrel@umbrel.local 
> cd /umbrel/scripts
> sudo ./stop
> docker ps
> docker rm -f {put container_id}
> ```
> 
> Then start using
> 
> ```
> sudo ./start
> ```
> 
> Then try to update your Umbrel.

Hello, I can't update to 0.5.2 and 0.5.3 too. There are no containers that are still running. When I run the update via SSH the Update is successfull, but when I'm logged in the Version ist still 0.5.1. 

Is there another way to fix this?

**Comment by lestephane** [comment]
> Could you confirm a couple of things for me?
> 
> Is Umbrel installed on a custom server? (ie not a Pi) Can you check if this file exists: `/mnt/DATA/umbrel/docker-compose.yml` using e.g. `ls /mnt/DATA/umbrel/docker-compose.yml` Can you post back what this returns? `yq --version`

Seeing as noone answered your question until now, I will provide answers for my situation, which is a 0.5.1 on Pi, so not quite the same as the original submitter, but close enough. My umbrel has been unupgradeable for a while. The last version update that worked was to 0.5.1.

```
umbrel@umbrel:~ $ cd ~/umbrel && sudo ./scripts/update/update --repo getumbrel/umbrel#v0.5.3
...
======================================
=========== RECONFIGURING ============
========= UMBREL (mainnet) ===========
======================================

Configuring permissions...

Configuration successful
You can now start Umbrel by running:
  sudo ./scripts/start

Pulling new containers
Pulling tor_proxy ... done
Pulling dashboard ... done
Pulling manager   ... done
Pulling nginx     ... done
Pulling auth      ... done
Saving current Umbrel Docker images to clean up later
Reading file: /home/umbrel/umbrel/docker-compose.yml
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files [files ...]]
yq: error: argument files: can't open '.services | map(select(.image != null)) | .[].image': [Errno 2] No such file or directory: '.services | map(select(.image != null)) | .[].image'
== End Update Script 01-run.sh ==
== End Update Script 01-run.sh ==


== Begin Update Script 02-run.sh ==

=======================================
=============== UPDATE ================
=======================================
========= Stage: Post-update ==========
=======================================

== End Update Script 02-run.sh ==


== Begin Update Script 03-run.sh ==

=======================================
=============== UPDATE ================
=======================================
=========== Stage: Success ============
=======================================

Removing backup
Successfully installed Umbrel 0.5.3
== End Update Script 03-run.sh ==

Deleting cloned repository
Removing lock
```
Then
```
umbrel@umbrel:~ $ yq --version
yq 3.1.0
```

Plainly, the yq invocation error is not caught, because of a missing check. More defensive command expansions with checks like `"x$(yq ...)" != "x"`` would be needed. Once this is in place, the failure of the command can be spotted, and the full command can be displayed, for users to troubleshoot. In this case, it looks like the wrong arguments (or arguments in the wrong order) are provided.
