### ISSUE TITLE
Update the link for RasPi devices

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel#1536]
This link still points to `v0.5.1`. This needs to be updated.
![image](https://user-images.githubusercontent.com/43396684/199526581-08f68e3c-c119-45e0-886d-273b96136ba1.png)

![image](https://user-images.githubusercontent.com/43396684/199527011-4f65102a-405e-48af-a595-71e230798d96.png)

**Comment by enricopro** [comment]
Try to clear the cache, in my browser it's downloading v0.5.3

**Comment by IMPranshu** [comment]
Yeah. You are right
