### ISSUE TITLE
after upgrade bitcoin container fails to start due to app script start bug

### ISSUE THREAD

**Issue by pseudozach** [getumbrel/umbrel#1538]
On the GUI, there's no indication but there's basically no `bitcoin` docker container running. There should be a check to make sure if a container is actually starting, otherwise user will just keep waiting forever. GUI just shows glowing bitcoin icon.

when trying to manually start everything from CLI
`sudo ./script/start` gives an error:
`/home/umbrel/umbrel/scripts/../scripts/app: line 298: /home/umbrel/umbrel/app-data/bitcoin/torrc: Is a directory`
which is due to /home/umbrel/umbrel/app-data/bitcoin/torrc being a folder and the template is actually inside this folder.

offending line is: 
`cat "${APP_TEMPLATE_INPUT_FILE}" | envsubst > "${APP_TEMPLATE_OUTPUT_FILE}"`

solution is to move or remove /home/umbrel/umbrel/app-data/bitcoin/torrc folder so a new one can be created.

**Comment by nevets963** [comment]
This suggests that the `torrc.template` was not templated correctly and the Tor container created a directory (instead) on the host.

Can you confirm a couple of things for me? What version of Umbrel are running? And is this running on a Pi of a custom debian/ubuntu based server?

**Comment by pseudozach** [comment]
this happened during upgrade from v0.5.2 to latest v0.5.4 - it's a raspi.

**Comment by nmfretz** [comment]
Hi @pseudozach, if you are still having this issue, please reach out for support through our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/)
