### ISSUE TITLE
updating mempool github link for custom Pull request

### ISSUE THREAD

**Issue by gladwinput** [getumbrel/umbrel#1542]
I'd like to update mempool's git address in order to use a custom fork of the project. But I can't figure out where to do this, could you assist?

**Comment by mayankchhabra** [comment]
Hey @gladwinput. All apps are Dockerized images, so you'd need to create a custom Docker image for a fork of mempool. Once you do that, you can create your own Community App Store, add your fork of mempool app to it, and run it. Here are the docs for Community App Store: https://github.com/getumbrel/umbrel-community-app-store
