### ISSUE TITLE
After Updating umbrel to 0.5.3 bitcoin node app just hangs.

### ISSUE THREAD

**Issue by Dan201210** [getumbrel/umbrel#1544]
I run umbrel on ubuntu 22.04, umbrel told me there was an update available so I updated to version 0.5.3. After doing so everything seemed to be fine until I tried to open the bitcoin node app. It opens but just doesn't do anything except for the loading bar goes back and forth indefinitely. No connections, no sync percentage, no mempool ever populates. Tried to restart everything a couple times to no avail. So I ran the troubleshoot and the bitcoin portion gives me an error: 
 
2022-11-08T00:11:46Z Fatal LevelDB error: Corruption: not an sstable (bad magic number)
bitcoind_1    | 2022-11-08T00:11:46Z : Error opening block database.
bitcoind_1    | Please restart with -reindex or -reindex-chainstate to recover.
bitcoind_1    | 2022-11-08T00:11:46Z Aborted block database rebuild. Exiting.
bitcoind_1    | 2022-11-08T00:11:46Z Shutdown: In progress...
bitcoind_1    | 2022-11-08T00:12:07Z scheduler thread exit
bitcoind_1    | 2022-11-08T00:12:08Z Shutdown: done

Not sure if thats the proper order or not becuase it repeats 3 or so times so idk where the start and finish is to be honest, all the other apps report connection issues. So I dont know if its a tor issue or a docker issue or what all I know is it ran fine for months before this recent update prompt.

**Comment by JimSB** [comment]
To resolve this issue and successfully reindex on Umbrel v0.5 and later please SSH in and run the following,

`echo reindex=1 >> ~/umbrel/app-data/bitcoin/data/bitcoin/bitcoin.conf `

Then we'll need to restart Bitcoin after patching bitcoin.conf via this command:
`~/umbrel/scripts/app restart bitcoin`

Then once you're synced at 100% you can run this to stop from reindexing again:
`sed -i "s/reindex=1//g;" ~/umbrel/app-data/bitcoin/data/bitcoin/bitcoin.conf `

Then you'll need to restart Bitcoin again after that last edit once more:
`~/umbrel/scripts/app restart bitcoin`

Also, remember to change ~/umbrel to your Umbrel's installation directory on non-raspberry pi installs.

and that should work!

**Comment by rustyb78** [comment]
I get "permission denied" when I run the first command.

> To resolve this issue and successfully reindex on Umbrel v0.5 and later please SSH in and run the following,
> 
> `echo reindex=1 >> ~/umbrel/app-data/bitcoin/data/bitcoin/bitcoin.conf `
> 
> Then we'll need to restart Bitcoin after patching bitcoin.conf via this command: `~/umbrel/scripts/app restart bitcoin`
> 
> Then once you're synced at 100% you can run this to stop from reindexing again: `sed -i "s/reindex=1//g;" ~/umbrel/app-data/bitcoin/data/bitcoin/bitcoin.conf `
> 
> Then you'll need to restart Bitcoin again after that last edit once more: `~/umbrel/scripts/app restart bitcoin`
> 
> Also, remember to change ~/umbrel to your Umbrel's installation directory on non-raspberry pi installs.
> 
> and that should work!

**Comment by flix1** [comment]
Similar problem here. Umbrel works, but Bitcoin node is stuck "starting".

It worked fine before...

![image](https://user-images.githubusercontent.com/4233784/217522903-fa483d83-38cb-453a-a31d-b9dc2171a4d9.png)

**Comment by flix1** [comment]
![image](https://user-images.githubusercontent.com/4233784/217784751-b5a5fcea-d9a3-4572-bcf7-40f5e8d592f8.png)

I uninstalled and installed again. It seems to be working now... just a lot of time wasted downloading the entire blockchain again... Let's see if I can get it to 100% this time.

**Comment by BorjaRuizReverter** [comment]
I run into the same issue.

Few months before, when I installed umbrel and synced my bitcoin node everything went well. But when I resumed these days I stumbled on this issue. Tried to update the node and restart, but it didnt resolve. 

I then tried the suggestion from @JimSB about reindexing the bitcoin.conf file and it seems to work by now. 

Just be aware guys (@rustyb78) that only way of editing this file is by logging from terminal as root. Your default user likely doesnt belong to the root group. That is why sudo doesnt resolve the permission to edit.

Anyway, thanks @JimSB!

**Comment by will-notgiveup** [comment]
> ![image](https://user-images.githubusercontent.com/4233784/217784751-b5a5fcea-d9a3-4572-bcf7-40f5e8d592f8.png)
> 
> I uninstalled and installed again. It seems to be working now... just a lot of time wasted downloading the entire blockchain again... Let's see if I can get it to 100% this time.

Thanks, it fixed the problem. Yes, it needs to download the entire blockchain again!

**Comment by gdlfr** [comment]
To fix this:
1. Login through ssh to your node
2. Stop Bitcoin:
```~/umbrel/scripts/app stop bitcoin```
3. Then, you need to remove peers.dat file (or rename it with ```mv``` command if you wish to have a backup):
```rm /home/umbrel/umbrel/app-data/bitcoin/data/bitcoin/peers.dat```
4. After that, run app again:
```~/umbrel/scripts/app start bitcoin```
5. Now wait 10-15 minutes (or longer), and you can open Bitcoin Node app dashboard and see It's syncing.

**Comment by JimSB** [comment]
Hey y'all just wanted to share some guidance here as some people were referencing this post for different issues recently and reindexing (which is a long process) when they might not have needed to. 

For original poster it is likely it was a corrupt chainstate issue, those look like this: 

```
bitcoind_1     | 2023-03-09T01:39:11Z LevelDB read failure: Corruption: block ch                                                                             ecksum mismatch: /data/.bitcoin/chainstate/2104298.ldb
bitcoind_1     | 2023-03-09T01:39:11Z Fatal LevelDB error: Corruption: block che                                                                             cksum mismatch: /data/.bitcoin/chainstate/2104298.ldb
```

With the block sometimes there's a different number there, but those full steps on what to do for reference are listed now as well in our official FAQ guide under "Resolving Corrupted Blockchain Issues" here: https://community.getumbrel.com/t/official-umbrel-troubleshooting-guide-and-faq/9873

Let me know if that had worked [Dan201210](https://github.com/Dan201210) and you're all good to go! :) 

Alternatively if your app is just stuck on "Starting" and not loading you can run this command:  `sudo ~/umbrel/scripts/stop && sudo ~/umbrel/scripts/start`
or you can System > Restart which should accomplish the same thing then wait ~5 minutes

Then the peers.dat instructions are for the "`Error: Invalid or corrupt peers.dat`" error specifically.  

If @Dan201210 is all set going to close this issue after another couple days!  :)

**Comment by rizalrenaldi** [comment]
I have the same problem with my umbrel stuck on the "starting" screen exactly like the screenshot from @flix1. Tried the method mentioned by @gdlfr but had no luck. Restarting Umbrel manually also had no effect.

Running troubleshooting via umbrel setting GUI I notice this line on bitcoinid:
```
bitcoind_1     | Error: Failed loading settings file:
bitcoind_1     | - Unable to parse settings file /data/.bitcoin/settings.json
```
Does this has something to do with being stuck on "starting"?

p.s: should I open a new issue?

**Comment by JimSB** [comment]
@rizalrenaldi If you see that error:
```
"Error: Failed loading settings file:
bitcoind_1 | - Unable to parse settings file /data/.bitcoin/settings.json"
```


To resolve, first connect to your Umbrel device by following the instructions in *How to SSH into Umbrel on a Raspberry Pi* in our official FAQ guide [here](https://community.getumbrel.com/t/official-umbrel-troubleshooting-guide-and-faq/9873) or by accessing a terminal on your Linux machine 


This command is the quickest way to resolve the error, by deleting the file first:

`rm ~umbrel/app-data/bitcoin/data/bitcoin/settings.json`

Then you should restart Bitcoin:
`~/umbrel/scripts/app restart bitcoin`

If for any reason when attempting to delete the file you face a permission or other errors that prevent you from doing so, we can also edit the file with this command:
`sudo nano umbrel/app-data/bitcoin/data/bitcoin/settings.json`


Then it will take you to a blank file and just type and add two lines like this, with the two curly braces


```
{
}
```


then hit CTRL+X to exit, Y to save, and enter to continue.


After completing the edit don’t forget the last step of restarting Bitcoin (clicking Save and Restart node in the Bitcoin Node app or performing a reboot via System > Restart also accomplishes this):
`~/umbrel/scripts/app restart bitcoin`


Upon restarting wait ~5 minutes and this will resolve the error with the settings.json file.

**Comment by flix1** [comment]
> To fix this:
> 
> 1. Login through ssh to your node
> 2. Stop Bitcoin:
>    `~/umbrel/scripts/app stop bitcoin`
> 3. Then, you need to remove peers.dat file (or rename it with `mv` command if you wish to have a backup):
>    `rm /home/umbrel/umbrel/app-data/bitcoin/data/bitcoin/peers.dat`
> 4. After that, run app again:
>    `~/umbrel/scripts/app start bitcoin`
> 5. Now wait 10-15 minutes (or longer), and you can open Bitcoin Node app dashboard and see It's syncing.

So it happened again... node stuck on "starting". Tried this, did not work.

**Comment by JimSB** [comment]
Hey @flix1 do you want to share with me your recent debug log?  
You can send it to me on telegram too if you prefer for real-time assistance https://t.me/usernameisJim

**Comment by JairoMarques** [comment]
Hi @JimSB, I'm trying to sync my node with 0.5.3 version but without success. It hangs in 9.2% now (I reinstall many times, none of them pass 13%).
I'm checking the code and I don't understand why when i call:
http://<<mylocalipaddress>>:2100/v1/bitcoind/info/sync  it always result in:
{
    "chain": "main",
    "percent": 0.09201023501817562,
    "currentBlock": 364613,
    "headerCount": 364613,
    "pruned": false
}

Where "headerCount" is updated? I thing that for any reason, that I'm not figuring out, this data is not updated and then the node is not syncing.

Any help will be very appreciated.

**Comment by JimSB** [comment]
Hey @JairoMarques it would help to see your Bitcoin logs from the full debug log it will contain the last 50 lines of bitcoin and likely any errors there

**Comment by bitcoinmichi** [comment]
Ufff.....I am far away from my umbrel node which is at my brother place. Travelling all year around. Cant reindex via TOR.

Would be cool to have a reindex feature via TOR access.

**Comment by JimSB** [comment]
> Ufff.....I am far away from my umbrel node which is at my brother place. Travelling all year around. Cant reindex via TOR.
> 
> Would be cool to have a reindex feature via TOR access.

You would need to have SSH access so you can add reindex=1 to your bitcoin.conf file, since you're remote it's not generally advised to SSH when not on the local network, one way around this I usually recommend is if you can TeamViewer onto a computer on the same locan network as your Umbrel

Then you can follow the steps under "Resolving Corrupted Blockchain Issues" [here](https://community.getumbrel.com/t/official-umbrel-troubleshooting-guide-and-faq/9873)

Keeping this closed so as per https://github.com/getumbrel/umbrel/issues/1544#issuecomment-1548586033

Feel free to hop into the [Telegram](https://t.me/getumbrel/207765) for real-time assistance!

**Comment by oscarparedez** [comment]
> To resolve this issue and successfully reindex on Umbrel v0.5 and later please SSH in and run the following,
> 
> `echo reindex=1 >> ~/umbrel/app-data/bitcoin/data/bitcoin/bitcoin.conf `
> 
> Then we'll need to restart Bitcoin after patching bitcoin.conf via this command: `~/umbrel/scripts/app restart bitcoin`
> 
> Then once you're synced at 100% you can run this to stop from reindexing again: `sed -i "s/reindex=1//g;" ~/umbrel/app-data/bitcoin/data/bitcoin/bitcoin.conf `
> 
> Then you'll need to restart Bitcoin again after that last edit once more: `~/umbrel/scripts/app restart bitcoin`
> 
> Also, remember to change ~/umbrel to your Umbrel's installation directory on non-raspberry pi installs.
> 
> and that should work!

Doing this forces me to re download the blockchain?
