### ISSUE TITLE
[Feature Request] Ability to migrate everything from SD card to SSD 

### ISSUE THREAD

**Issue by IMPranshu** [getumbrel/umbrel#1546]
I am trying to add a feature to Umbrel that will automatically migrate the install files from the SD card to the SSD and then we can remove the SD card altogether if we want to after the first boot. 

I got the idea from [this video](https://www.youtube.com/watch?v=pto45lMgH5w) and it will also be a great feature to have long-term reliability as SSD are far more durable than small SD cards.

**Comment by PeterMcBTC** [comment]
Me too I would like to get rid of microSD failures and boot from SSD. Any news about this @mayankchhabra ?

**Comment by IMPranshu** [comment]
An Umbrel wizard has answered this https://github.com/getumbrel/umbrel/issues/1639
