### ISSUE TITLE
The repository ‘https://download.docker.com/linux/debian 7 bookworm Release’ does not have a Release file.

### ISSUE THREAD

**Issue by metrolan** [getumbrel/umbrel#1550]
I've been trying to install Umbrel in a Linux Mint 21, with `curl -L https://umbrel.sh | bash` and get the mentioned error.

**Comment by mayankchhabra** [comment]
Sorry for that. We haven't tested installations outside Ubuntu and Debian. Is there a chancy you could try installing it one of those two OS'es?

**Comment by mhadam** [comment]
@metrolan the docker install script is failing here. You can bypass by changing a `ID` in `/etc/os-release`.

Set `ID` to either `ubuntu` or `debian`, for example:
```
ID=ubuntu
```

I'm using KDE Neon & changed `ID` from `neon` to `ubuntu`.

**Comment by nimafanniasl** [comment]
I got the same issue on debian sid, but just installed debian stable :)))
