### ISSUE TITLE
Umbrel on WSL 2 looks like it is downloading blockchain on my 2TB SSD but really filling my 500MB PC hard drive

### ISSUE THREAD

**Issue by edjanx** [getumbrel/umbrel#1551]
So I've tried installing now three times, with the dashboard showing my 2.1 TB of my external SSD available and the blockchain downloading four days only to see it actually filling up my PC hard drive when the blockchain reaches about 400 GB.  I am on a 16 GB Windows 11 PRO with a USB3 connection to the SSD, running WSL 2 and Ubuntu 22.04.  I am also running the latest docker.  I just tried again after mounting the external drive in WSL with the following command. "wsl --mount \\.\PHYSICALDRIVE1 --partition 1 -t ext4"

Any help getting this to work as it should be greatly appreciated.

edjanx

**Comment by JimSB** [comment]
We need to confirm Umbrel is installed on the external drive, for non-pi systems we'll need to install on the external drive itself so it doesn't utilize your Windows 11 PC at all.  

To do this on your external installation of Ubuntu we'll need to use this installation command
`curl -L https://umbrel.sh | bash -s -- --install-path path/to/external/drive`

**Comment by edjanx** [comment]
That was the issue indeed. Thank you very much

Ed Jankauskas

**Comment by mayankchhabra** [comment]
Glad you were able to solve the issue @edjanx! Thanks for your help, @JimSB.
