### ISSUE TITLE
Error when running the following from iMac Terminal: cd ~/umbrel && sudo ./scripts/update/update --repo getumbrel/umbrel#v0.5.3

### ISSUE THREAD

**Issue by dtarver** [getumbrel/umbrel#1555]
What can I do to fix this error?

![Screen Shot 2022-11-17 at 7 25 52 PM](https://user-images.githubusercontent.com/5572630/202588529-f3669078-8339-416a-a4a7-13bc0c0a1e92.png)

The following are the name servers. Is this correct?
![Screen Shot 2022-11-17 at 7 27 17 PM](https://user-images.githubusercontent.com/5572630/202588727-7f2ec7ea-77fb-467c-b520-f715d298c39e.png)

Thank you,
Dora

**Comment by JimSB** [comment]
Hey @dtarver I believe this issue was resolved after switching from Wi-Fi to ethernet, is that right?

**Comment by nevets963** [comment]
@dtarver Are you still experiencing this issue?

**Comment by nmfretz** [comment]
closing old support issue
