### ISSUE TITLE
Outdated Wasabi Wallet logo on main website

### ISSUE THREAD

**Issue by jesseaam** [getumbrel/umbrel#1557]
[Wasabi Wallet 2.0](https://wasabiwallet.io) has a new logo. The new logo looks like this:

<img width="187" alt="Screen Shot 2022-11-18 at 10 07 34 PM" src="https://user-images.githubusercontent.com/18119820/202831348-16cb7d6e-960a-40b6-9fda-22cd65d0b696.png">

<details>
<summary>Larger Wasabi Wallet 2.0 logo</summary>

![logobase_vectorgraphic_wasabi-01--2--1](https://user-images.githubusercontent.com/18119820/202831195-3dc8b6e6-930a-43bf-8e0d-f6d900b722d3.png)
</details>

<br><br><br>

The image below from the main website (https://umbrel.com) needs to be updated. 

## image with outdated logo for Wasabi Wallet

![](https://uploads-ssl.webflow.com/62966b49981ba146f4842f45/62966b49981ba1567c842fd3_wallets-p-800.jpeg)

cc @yahiheb

**Comment by yahiheb** [comment]
ACK

**Comment by mayankchhabra** [comment]
Apologies for the delay on this, folks. Thanks for the shout! We've just updated the logo on the website.
