### ISSUE TITLE
Umbrel doesn't display updates for apps in community stores

### ISSUE THREAD

**Issue by ShonP40** [getumbrel/umbrel#1564]
Hello, after setting up my own repo, I've noticed that Umbrel doesn't allow me to update my installed apps through the web UI even though it shows the updated version number on each app's store page.

The only way to update these apps at the moment is to run the app install command.

Is there any way to get Umbrel to show these updates on the UI like it does for normal apps?

**Comment by nevets963** [comment]
@ShonP40 Can you confirm your current process when you update an app in your community app store?

**Comment by ShonP40** [comment]
It's automated at the moment, but here's a commit on the repo updating an app: https://github.com/ShonP40/umbrel-apps/commit/b378f8393c111ba2987ac93b0f1e6f5c1104e012

**Comment by nevets963** [comment]
@ShonP40 That commit looks good to me - the most important detail is changing the `version` property inside `umbrel-app.yml` (which you've done). I've root caused the issue to a bug and I worked on a PR yesterday. That will get rolled out in the next version of Umbrel.

**Comment by ShonP40** [comment]
Alright, thank you!

**Comment by knorrium** [comment]
@nevets963 can you share more context on the issue you have fixed? I believe I'm running into the same problem while working on the mempool app update. After adding my forked `umbrel-apps` repo to the list, the script prioritizes the `getumbrel/umbrel-apps` app definition whenever I try to update, reinstall or install the mempool app.

**Comment by ShonP40** [comment]
Guessing that this was fixed with the latest update, but don’t have a way to check as I stopped using Umbrel a while ago.

So just going to close this issue as completed.
