### ISSUE TITLE
can't access my fresh node.

### ISSUE THREAD

**Issue by SequoiaB** [getumbrel/umbrel#1566]
Hello, I changed the ubuntu version on my pc, and by doing so I erased everything on it.
I successfully reinstalled umbrel on my new os, but now I cannot access it...

the message it displays is Connection denied by ***.***.*.**   (my IP)

any tips on how to resolve this?

![image](https://user-images.githubusercontent.com/91783696/208457502-a31ea4bd-2bf7-44ca-827e-4828479bdb37.png)

**Comment by nevets963** [comment]
@SequoiaB Can you SSH onto the server and check that Umbrel is running? When you run `docker ps` do you see any containers there?

**Comment by SequoiaB** [comment]
> @SequoiaB Can you SSH into the server and check that Umbrel is running? When you run `docker ps` do you see any containers there?

I tried `ssh umbrel@umbrel.local` and it gave me `Could not resolve hostname umbrel.local: Name or service not known.`

As for the containers I see` getumbrel/dashboard` and `getumbrel/tor`

**Comment by nevets963** [comment]
Do you have your system hostname set to `umbrel`? It looks like from your screenshot you have `edos-node` as your hostname, right? It's maybe easier to work out the IP address of your computer and use that for SSH.

Are those the only containers that you see running?

**Comment by SequoiaB** [comment]
yes you are correct, hostname is  edos-node.
yes those are the only containers I see running.

Do you suggest going for `sudo ssh (ip)`?

Il giorno lun 19 dic 2022 alle ore 16:34 Steven Briscoe <
***@***.***> ha scritto:

**Comment by nevets963** [comment]
If you already access via the hostname, then that should be good enough.

Can you run `sudo ~/umbrel/scripts/start` (or run this `start` script from where you have Umbrel installed) and report back any errors?

**Comment by SequoiaB** [comment]
> If you already access via the hostname, then that should be good enough.
> 
> 
> 
> Can you run `sudo ~/umbrel/scripts/start` (or run this `start` script from where you have Umbrel installed) and report back any errors?
![image](https://user-images.githubusercontent.com/91783696/208468051-a48e56cf-63f0-4051-bbb7-3d41f8e51f02.jpeg)

**Comment by nevets963** [comment]
It's failed to start because there is another process on your server already listening on port `2000` which is needed by Umbrel. Can you find out what that is by running: `netstat -tulpn | grep :2000`?

**Comment by SequoiaB** [comment]
the command runs, but doesn't give me anything

Il giorno lun 19 dic 2022 alle ore 17:30 Steven Briscoe <
***@***.***> ha scritto:

**Comment by nmfretz** [comment]
Hey @SequoiaB, I'm closing this old issue. Please reach out on [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/) if you are still troubleshooting this, and reference this GitHub Issue.
