### ISSUE TITLE
 main: line 136: yq_sha256[$system_arch]: unbound variable

### ISSUE THREAD

**Issue by adispi** [getumbrel/umbrel#1567]
root@raspberrypi:/home/pi# dpkg --print-architecture
armhf
root@raspberrypi:/home/pi# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@raspberrypi:/home/pi# bash --version
GNU bash, version 5.1.4(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

i do not want to use the prebuilt os, as when i tried, the desktop is broken and i cannot get it to work, and the wifi MAC address changed in every boot and flooded my DHCP.
so i tried the install script curl -L https://umbrel.sh | bash 
and run into the error:  main: line 136: yq_sha256[$system_arch]: unbound variable

**Comment by adispi** [comment]
was on 32bit os instead of 64. fixed.

**Comment by cronusfortunam** [comment]
how did you fix it? i updated to aarm64 and i still get this same line on install please help
