### ISSUE TITLE
Does Umbrel support Bullseye?

### ISSUE THREAD

**Issue by freddyal0x01** [getumbrel/umbrel#1570]
Given that buster is already end of life, does umbrel have support for debian bullseye or is it in the works?

**Comment by nimafanniasl** [comment]
Yes it does. i installed it on bullseye 2 days ago and it works perfectly!

**Comment by freddyal0x01** [comment]
Do you have a script or an article link to upgrade umbrel over to bullseye by chance? I want to make sure that I follow the right steps.

**Comment by nimafanniasl** [comment]
No, i don't know how to upgrade it, i installed it fresh on bullseye :)
