### ISSUE TITLE
Texts always being lowercase!

### ISSUE THREAD

**Issue by nimafanniasl** [getumbrel/umbrel#1571]
Hi, this is my first home lab and i installed umbrel on it and its soooo amazing!
but there is a little bug that i hope gets fixed.

Ok. First look at the text in the homepage, app store and etc, its always lowercase! when i checked the html, i found that the text is generated correctly, but the problem is the text-lowercase class that is everywhere! if that gets deleted, it could be very nice! thanks :)

![image](https://user-images.githubusercontent.com/76901932/210155492-65d49eac-8464-4595-a52d-bf206df62571.png)

![image](https://user-images.githubusercontent.com/76901932/210151494-bed2bf79-aaa4-448f-ba80-ef6b7d802d0e.png)
![image](https://user-images.githubusercontent.com/76901932/210151422-0b664b6f-554c-4a5a-88ce-dc292bfa7fac.png)

**Comment by Sven-Sve** [comment]
Maybe you can fix it with looking at the code of Umbrel?

**Comment by nimafanniasl** [comment]
Hi, opened a pull request on the umbrel-dashboard repo :)

**Comment by nimafanniasl** [comment]
umbrel ded lol

**Comment by nmfretz** [comment]
Hey @nimafanniasl, thanks for submitting a PR to https://github.com/getumbrel/umbrel-dashboard/! I can confirm we are not ded, just disgustingly busy. Sorry for the delay in getting back to you.

`good evening <username>` is intentionally lowercase as a design choice. Other instances of this include the headers for the settings and app store modals. Admittedly, there are instances where we have accidentally strayed from this design-choice. We will be fixing these soon.

**Comment by nimafanniasl** [comment]
Hey! Thanks! I'm happy that umbrel is still in development :)
Thank you so much :)
