### ISSUE TITLE
umbrel.local’s DNS address could not be found

### ISSUE THREAD

**Issue by agslai** [getumbrel/umbrel#1574]
I don't know what to do with this error message. it was working fine but now it populates this error message. please help. thanks

**Comment by nevets963** [comment]
It's important to note that accessing `umbrel.local` will work on your local network, so using via Tailscale, etc. will not work. Are you still able to access your Umbrel server via its IP address?

**Comment by nmfretz** [comment]
Hey @agslai, I am closing this issue. Please reach out on [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/) if you are still having this issue.
