### ISSUE TITLE
Remote Tor access (tor browser) to Umbrel UI not any more working

### ISSUE THREAD

**Issue by pjw65** [getumbrel/umbrel#1580]
My Umbrel is on Ubuntu 22.04

in v0.5.3 **remote tor access** is not any more possible (using newest tor browser).
`The debug script did not automatically detect any issues with your Umbrel.`

I did a rollback (`sudo ~/umbrel/scripts/update/update --repo getumbrel/umbrel#v0.5.0`) and found out, that in v0.5.0 it works fine.

**Comment by JimSB** [comment]
Hi can I confirm @pjw65 that when you were on v0.5.3 there was no Tor remote address being populated at all?  Or you were unable to connect to the onion address in your settings?

Do you still have the debug logs to share prior to the rollback?  

If you decide to update to latest again and want to share logs as well I'm happy to go through some quick troubleshooting to help resolve.  I can help in real-time over telegram chat if you'd like too, my Telegram is: [https://t.me/usernameisJim](https://t.me/usernameisJim)

**Comment by pjw65** [comment]
Tor browser access of Umbrel UI is broken on v0.5.2, 
v0.5.1 is working. 
LNbits over tor browser still works.

Could it has to be something to do that my local instance not using port 80?
I connect with: http://umbrel.local:10555/

**Comment by pjw65** [comment]
**docker ps**
v0.5.2/v0.5.3 gives 
...
cace81ed61b2   getumbrel/tor:0.4.7.8                 "tor"                    11 minutes ago   Up 11 minutes   127.0.0.1:9050->9050/tcp                                                                                                              tor_proxy

v0.5.1 gives
...
406fc1dbb5d0   lncm/tor:0.4.7.8                      "tor"                    10 minutes ago   Up 9 minutes    9051/tcp, 127.0.0.1:9050->9050/tcp, 29050-29051/tcp                                                                                   tor

**Comment by nevets963** [comment]
@pjw65 could you check whether there are any errors for the tor container responsible for serving the Web UI by running this:
```
docker logs -f --tail 100 tor_server
```

**Comment by pjw65** [comment]
No errors, just some warnings  and lot of notes ([notice] Closed 15 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.)

docker logs $(docker ps | grep tor_proxy | cut -d' ' -f1) | egrep -i '(error|warn)'
```
Jan 28 09:26:58.232 [warn] You have a ControlPort set to accept connections from a non-local address.  This means that programs not running on your computer can reconfigure your Tor.  That's pretty bad, since the controller protocol isn't encrypted!  Maybe you should just listen on 127.0.0.1 and use a tool like stunnel or ssh to encrypt remote connections to your control port.
Jan 28 09:26:58.233 [warn] You have a ControlPort set to accept connections from a non-local address.  This means that programs not running on your computer can reconfigure your Tor.  That's pretty bad, since the controller protocol isn't encrypted!  Maybe you should just listen on 127.0.0.1 and use a tool like stunnel or ssh to encrypt remote connections to your control port.
Jan 28 09:31:41.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed].
Jan 28 11:12:52.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [19 similar message(s) suppressed in last 6120 seconds]
Jan 28 11:43:55.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed].
Jan 28 12:15:09.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [8 similar message(s) suppressed in last 1920 seconds]
Jan 28 13:01:11.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [2 similar message(s) suppressed in last 2760 seconds]
Jan 28 13:17:12.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [7 similar message(s) suppressed in last 960 seconds]
Jan 28 13:28:34.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed].
Jan 28 13:50:02.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [1 similar message(s) suppressed in last 1320 seconds]
Jan 28 14:42:34.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [2 similar message(s) suppressed in last 3180 seconds]
Jan 28 15:28:00.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [1 similar message(s) suppressed in last 2460 seconds]
Jan 28 15:46:38.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed].
Jan 28 16:37:10.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [5 similar message(s) suppressed in last 3060 seconds]
Jan 28 17:44:01.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [4 similar message(s) suppressed in last 4020 seconds]
```

**Comment by nmfretz** [comment]
Hi @pjw65, I am closing this old issue. Please reach out to our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/) if you are still having issues or run in to this again.
