### ISSUE TITLE
Can't install Umbrel in Debian Bullseye

### ISSUE THREAD

**Issue by andergama** [getumbrel/umbrel#1581]
Hello everyone!

Anyone had the error below while trying to install Umbrel in Debian 11:

root@linux-PC:/home/user# curl -L https://umbrel.sh | bash -s -- --install-path ./Umbrel/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    41  100    41    0     0     41      0  0:00:01 --:--:--  0:00:01    41
100  7541  100  7541    0     0   4827      0  0:00:01  0:00:01 --:--:-- 20660
About to install Umbrel in "./Umbrel/".
If you would like to install somewhere else you can specify a custom location with:

  curl -L https://umbrel.sh | bash -s -- --install-path /some/path

Waiting for 10 seconds...

You may press Ctrl+C now to abort the install.

Hit:1 http://deb.debian.org/debian bullseye InRelease
Ign:2 http://deb.debian.org/debian-security bullseye-updates InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease               
Hit:4 https://packages.microsoft.com/repos/edge stable InRelease            
Hit:5 http://deb.debian.org/debian-security bullseye-security InRelease
Err:6 http://deb.debian.org/debian-security bullseye-updates Release
  404  Not Found [IP: 146.75.90.132 80]
Reading package lists... Done
E: The repository 'http://deb.debian.org/debian-security bullseye-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Thank you for the help!

**Comment by andergama** [comment]
Had to do a fresh install of debian with standard sources list then it worked.

**Comment by JimSB** [comment]
Thanks for sharing @andergama 

It does look like this stems from a bug where `bullseye/updates main` was deprecated and should now be located at `bullseye-security main` so it's not reading a release file... Updating Debian looks like it is the resolution!
