### ISSUE TITLE
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

### ISSUE THREAD

**Issue by smartm0use** [getumbrel/umbrel#1583]
I run `curl -L https://umbrel.sh | bash` on Ubuntu 20.04 but installation fails with this error:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```

Here is what I have already tried to do:

```
~# systemctl start docker
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

~# service docker start
 * Starting Docker: docker                                                                                                                                                                                  [ OK ] 

~# service docker status
 * Docker is not running

~# dockerd
[...]
grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
failed to start daemon: Devices cgroup isn't mounted
```

What's wrong?

**Comment by JimSB** [comment]
Can you try all the steps [here](https://phoenixnap.com/kb/cannot-connect-to-the-docker-daemon-error)?

Try the troubleshooting there ending with method 4, using this command:
`sudo usermod -aG docker [username]`

If the problem persists, to gather mroe information is this a recent fresh install of Ubuntu 20.04 in a Virtual Machine, is it a setup in the cloud or locally on what kind of computer?

**Comment by pynixis** [comment]
I normally start Umbrel using the startup script provided under the Umbrel directory.

**Comment by nmfretz** [comment]
Hi @pynixis, I am closing this old support issue. Please reach out to our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/) if you are still having issues or run in to this again.
