### ISSUE TITLE
Password not required to access Lightning Node

### ISSUE THREAD

**Issue by dubdam** [getumbrel/umbrel#1588]
When accessing the Umbrel Lightning Node via the browser using the IP address followed by port 2101 (e.g., IP:2101), I am able to access the node without being prompted for a password. However, if I just enter the Umbrel IP address, it prompts me for a password.

**Comment by mayankchhabra** [comment]
Hey @dubdam, it's due to the dual-authentication system we currently have in place, whereby authentication for apps have a longer timeout period than Umbrel login. Prior discussion can be found here: https://github.com/getumbrel/umbrel/issues/1549. Closing this issue for now.
