### ISSUE TITLE
Outdated BTCPay server

### ISSUE THREAD

**Issue by antonio-fr** [getumbrel/umbrel#1590]
In the Umbrell system, the available BTCPay service provided is 1.7.5. This was released a month ago. Since this release, there was 7 new releases. The latest is 1.7.12. The issue is not to be on the bleeding edge update, but there were many many issues fixed, and we think that our service is affected by one of the fixed bugs since. So we really to have the latest version, it may fix the API issue we are facing. Please update the BTCPay service.

**Comment by JimSB** [comment]
Discussion here on last update: https://github.com/getumbrel/umbrel-apps/pull/402 
Opened new PR for 1.7.12: https://github.com/getumbrel/umbrel-apps/compare/master...Update-BTCPay-Server-to-1.7.12
@nevets963 @nmfretz

**Comment by nmfretz** [comment]
@antonio-fr @Azdrian3 sorry I missed this last week. There was a BTCPay Server update pushed 4 days ago. Can you please upgrade and let me know whether or not that resolves your issue?

**Comment by antonio-fr** [comment]
Thank you. From my side, turns out finally that the issue was not in BTCPay. Anyway, considering there was lot of BTCPay version released, it's better to have it updated.
