### ISSUE TITLE
Not showing apps

### ISSUE THREAD

**Issue by hex-developer** [getumbrel/umbrel#1593]
I installed Umbrel with the install script and when accessing my homepage AFTER installing some apps, I see none, but I can see the manage apps button.

**Comment by JimSB** [comment]
Hey @hex-developer were you able to resolve this?

Navigate to your app store to see if it is on the "installing" button or if it allows you to reinstall after a reboot

If not you can use these commands via SSH to uninstall and reinstall, it will let you know if the app is indeed installed or not and provide any errors, feel free to share any outputted errors to further troubleshoot

To uninstall: 

`~/umbrel/scripts/app uninstall nostr-relay`

Install:

`~/umbrel/scripts/app install nostr-relay`

Replace "nostr-relay" with the name of the app in umbrel-apps listed here: https://github.com/getumbrel/umbrel-apps

If you are on Pi 4 rebooting or reflashing MicroSD card, or rebooting your Linux system also often fixes this issue.

**Comment by hex-developer** [comment]
OK. I gave up before, but I was going to reflash the SD card anyway, so I'll try again. What I want to do is make umbrel sort of a dashboard for the pi, so that I also have 'apps' that when clicked on link to the app I'm hosting without umbrel. For example, I'll be hosting portainer, so I want a fake app that opens portainer. Is that possible?

**Comment by nmfretz** [comment]
Hey @hex-developer I am closing this old issue. Please reach out to our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/) if you are still having this problem and link this GitHub Issue.
