### ISSUE TITLE
LND config parsing

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel#1594]
I noticed that I can no longer use multiple`externalip` entries in `lnd.conf`, it seems like they get discarded, and only the last one is kept.

At first I thought it was some bug introduced in LND, because multiple entries worked fine in the past.

But then I discovered that Umbrel since recently parses the `lnd.conf` and converts it into `umbrel-lnd.conf`. And I suspect the code responsible for this incorrectly assumes that you cannot set the same parameter twice, and discards all double entries?

So is it possible that this bug is due to Umbrel parsing the config file wrongly?

**Comment by nmfretz** [comment]
Thanks for this @Kroese. You are correct, it looks like `externalip` is missing from our list of whitelisted config options that can have multiple entries. We will fix this for the next Lightning Node update.
