### ISSUE TITLE
Is there a stop app feature?

### ISSUE THREAD

**Issue by gutenye** [getumbrel/umbrel#1595]
I want to stop using an app, but don't want to uninstall it, because that will remove all the app data. Is this feature available?

I can use the CLI to stop it, but it shows `Starting` on the dashboard, and restarting the server starts the app again.

Perhaps add a new section called `Stopped Apps` on the dashboard that lists all apps stopped by the user?

**Comment by nmfretz** [comment]
Thanks for this suggestion @gutenye. Stopping individual apps from the dashboard is on our development roadmap. Stay tuned 😉

**Comment by atomantic** [comment]
Looking forward to this! I have manually stopped apps that continuously fade-blink with "Starting..." even though they are in a stopped state. Would be awesome to either have 2 sections for apps that are Running / Stopped or some other indicator.
