### ISSUE TITLE
Support for non-arm64 architectures

### ISSUE THREAD

**Issue by leandro21b** [getumbrel/umbrel#1599]
I tried to run command to install Umbrel on my Linux Mint 21 Cinnamon but it says not support because my processor is not arm64

Result:
```
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://packages.linuxmint.com vanessa InRelease' doesn't support architecture 'arm64'

N: Skipping acquire of configured file 'upstream/binary-arm64/Packages' as repository 'http://packages.linuxmint.com vanessa InRelease' doesn't support architecture 'arm64'

N: Skipping acquire of configured file 'import/binary-arm64/Packages' as repository 'http://packages.linuxmint.com vanessa InRelease' doesn't support architecture 'arm64'

N: Skipping acquire of configured file 'backport/binary-arm64/Packages' as repository 'http://packages.linuxmint.com vanessa InRelease' doesn't support architecture 'arm64'
```

My processor: Intel Core i3-7100

When will umbrel support non-arm64 architectures?

**Comment by leandro21b** [comment]
Has it been tested on Linux Mint 21? Is there any other minimum hardware or software requirement then?

**Comment by leandro21b** [comment]
I did the `apt update` test, and it really gave the same error. I'll take a look at this problem

**Comment by nmfretz** [comment]
Hey @leandro21b, I am closing this old support issue. Please reach out through [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/) if you are still having the same problem and reference this GitHub issue.
