### ISSUE TITLE
Runing on MAC M1 

### ISSUE THREAD

**Issue by matigumma** [getumbrel/umbrel#1604]
Hi there i try to run umbrel under mac m1
and get some issues including dockerizing a debian like os.

as result here is how i did:

~ ```brew install multipass```
🍺  multipass was successfully installed!

~ ```multipass version```
multipass   1.11.1+mac
multipassd  1.11.1+mac

~ ```multipass find```
Image                       Aliases           Version          Description
18.04                       bionic            20230322         Ubuntu 18.04 LTS
20.04                       focal             20230209         Ubuntu 20.04 LTS
...
~ ```multipass launch 22.04```
Launched: actual-crab
~ ```multipass list```
```
Name                    State             IPv4             Image
actual-crab             Running           192.168.64.3     Ubuntu 22.04 LTS
```
~ ```multipass shell```
```
Launched: primary
Mounted '/Users/admin' into 'primary:Home'
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-67-generic aarch64)
...
...
ubuntu@primary:~$ sudo apt update
...
ubuntu@primary:~$ sudo passwd ubuntu
...
passwd: password updated successfully
```

and last but not less
execute
~ ubuntu@primary:~$ ```curl -L https://umbrel.sh | bash```
```
Umbrel is now accessible at
  http://primary.local
  http://192.168.64.4
Skipping status update when not on Umbrel OS

Umbrel has been sucessfully installed!
```

hope it help anybody. ty

**Comment by nmfretz** [comment]
Amazing, thanks for posting this @matigumma!  We have also updated our development instructions to use multipass: https://github.com/getumbrel/umbrel-dev

**Comment by vitinhoc1** [comment]
nossa me ajudou demais, tava quebrando cabeça até agora de como instalar o umbrel no imac. muito obrigado pela dica

**Comment by eliasmelgaco** [comment]
great, thanks!

it works for apple M2 👍🏽

**Comment by SimonHaas** [comment]
@MS00-GitIt I have added arm64 support https://www.simonhaas.eu/blog/posts/umbrel-arm64/
