### ISSUE TITLE
Payment expiry is too close to the current block height for safe handling by the relaying node

### ISSUE THREAD

**Issue by vicalrez** [getumbrel/umbrel#1610]
Hi, I have some problems with my umbrel node. I have been trying to make a payment from one of my light wallet (Phoenix) to my node, but it fail because error: payment expiry is too close to the current block height for safe handling by the relaying node.

Could somebody can help me with that?

**Comment by nmfretz** [comment]
Hi @vicalrez, are you still having this issue? If so, please reach out through our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/).
