### ISSUE TITLE
My lightning node does not show QR code to connect a externa wallet

### ISSUE THREAD

**Issue by vicalrez** [getumbrel/umbrel#1611]
Hi, I have tried to connect my zap wallet to my umbrel lightning node but my LN does not show the connect URL QR code.

**Comment by nmfretz** [comment]
Hey @vicalrez, sorry for the repeat instructions from your other issue:

If you are still having issues, please contact support through [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/).
