### ISSUE TITLE
 Umbrel keeps overwriting umbrel-lnd.conf

### ISSUE THREAD

**Issue by d4n74** [getumbrel/umbrel#1614]
Hi, I have setup Umbrel in hybrid mode (Tor + Clearnet IP) but each time Umbrel restarts, it overwrites /home/user/umbrel/app-data/lightning/data/lnd/umbrel-lnd.conf and I lose the hybrid configs in that file.  To fix it, I have to manually overwrite umbrel-lnd.conf with a previously saved umbrel-lnd.conf that has all the configurations I need. Not user friendly.

I have tried a watch for modifications on the file with inotifywait but it is just a workaround and it is annoying. 

Thank you

**Comment by nmfretz** [comment]
Thanks @kroese. @d4n74 for the TOR/Clearnet config, you can change these settings via the UI by going to `Advanced Settings`. Over time, all config options will be available through the UI.

**Comment by jvxis** [comment]
@nmfretz I can't find the lnd.conf, only the umbrel-lnd.conf. I also can't find the TOR/Clearnet config in Advanced Settings.
Can you help me?
Thanks
Jvx

**Comment by Krtekcze** [comment]
> @nmfretz I can't find the lnd.conf, only the umbrel-lnd.conf. I also can't find the TOR/Clearnet config in Advanced Settings. Can you help me? Thanks Jvx

You might need to create lnd.conf file

```
cd /home/umbrel/umbrel/app-data/lightning/data/lnd/
touch lnd.conf
chmod 777 ./lnd.conf
```

Based on your hybrid mode setup adjust lnd.conf file, more details here: https://community.umbrel.com/t/lnd-tor-clearnet-how-to-setup-hybrid-mode/6133
```
cat > lnd.conf
externalip=YOUR_EXTERNAL_PUBLIC_IP:9735
listen=0.0.0.0:9735
[tor]
tor.active=true
tor.v3=true
tor.streamisolation=false
tor.skip-proxy-for-clearnet-targets=true
```
