### ISSUE TITLE
torq-app_proxy-1  | Error wating for port: "The address 'torq_web_1' cannot be found"

### ISSUE THREAD

**Issue by mateusgalasso** [getumbrel/umbrel#1616]
I getting this error on a lot of different apps 

torq-db-1  | 
torq-db-1         | PostgreSQL init process complete; ready for start up.
torq-db-1         | 
torq-db-1         | 2023-04-20 13:00:59.323 UTC [1] LOG:  starting PostgreSQL 14.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
torq-db-1         | 2023-04-20 13:00:59.323 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
torq-db-1         | 2023-04-20 13:00:59.323 UTC [1] LOG:  listening on IPv6 address "::", port 5432
torq-db-1         | 2023-04-20 13:00:59.399 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
torq-db-1         | 2023-04-20 13:00:59.518 UTC [57] LOG:  database system was shut down at 2023-04-20 13:00:58 UTC
torq-db-1         | 2023-04-20 13:00:59.630 UTC [1] LOG:  database system is ready to accept connections
torq-db-1         | 2023-04-20 13:00:59.635 UTC [63] LOG:  TimescaleDB background worker launcher connected to shared catalogs
torq-app_proxy-1  | Retrying...
torq-app_proxy-1  | Error wating for port: "The address 'torq_web_1' cannot be found"
torq-app_proxy-1  | Retrying...
torq-app_proxy-1  | Error wating for port: "The address 'torq_web_1' cannot be found"
torq-app_proxy-1  | Retrying...
torq-app_proxy-1  | Error wating for port: "The address 'torq_web_1' cannot be found"
torq-app_proxy-1  | Retrying...
torq-app_proxy-1  | Error wating for port: "The address 'torq_web_1' cannot be found"
torq-app_proxy-1  | Retrying...
torq-app_proxy-1  | Error wating for port: "The address 'torq_web_1' cannot be found"
torq-web-1  | {"level":"fatal","error":"start cmd: default database connect: dial tcp: lookup torq_db_1 on 127.0.0.11:53: no such host","time":"2023-04-20T13:00:51Z"}
torq-web-1        | Starting Torq v0.20.3 | 6b30909 | Thu Apr 13 14:23:25 UTC 2023
torq-web-1        | Connecting to the Torq database
torq-web-1        | {"level":"fatal","error":"start cmd: default database connect: dial tcp: lookup torq_db_1 on 127.0.0.11:53: no such host","time":"2023-04-20T13:00:58Z"}
torq-web-1        | Starting Torq v0.20.3 | 6b30909 | Thu Apr 13 14:23:25 UTC 2023
torq-web-1        | Connecting to the Torq database
torq-web-1        | {"level":"fatal","error":"start cmd: default database connect: dial tcp: lookup torq_db_1 on 127.0.0.11:53: no such host","time":"2023-04-20T13:01:14Z"}
torq-web-1        | Starting Torq v0.20.3 | 6b30909 | Thu Apr 13 14:23:25 UTC 2023
torq-web-1        | Connecting to the Torq database
torq-web-1        | {"level":"fatal","error":"start cmd: default database connect: dial tcp: lookup torq_db_1 on 127.0.0.11:53: no such host","time":"2023-04-20T13:01:41Z"}

on ThunderHub too The address 'XXXXXXX' cannot be found

**Comment by nmfretz** [comment]
@mateusgalasso if you are still having this issue can you please reach out to support through [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/)?
