### ISSUE TITLE
Can not reach POS or CROWD from BTCPAYSERVER from Clearnet 

### ISSUE THREAD

**Issue by RoHoss** [getumbrel/umbrel#1626]
Hi to all:

I use Reverse Proxy to reach BTCPAY Server in Umbrel.

![BTC-ISSUE](https://github.com/getumbrel/umbrel/assets/67509786/ca203f06-0983-4515-9155-0d05ba13cedd)

SSL is in Use but see the photo.

I can reach BTCPAY POS and Crowd App. But If I will start POS no answer. Same from Crowd.

Seems the BTCPAYSERVER on umbrel is not the best solution?

Login is not possible too ???

Why? Any solution?

Regards

**Comment by JimSB** [comment]
Hey @RoHoss! 

This step here solves this error: https://github.com/getumbrel/umbrel/issues/1428#issuecomment-1184584190

If you have any other issues ongoing with getting this to work hop into the [Telegram support channel](https://t.me/getumbrel/207765) and drop a line!   

If you prefer to you can also use the message icon on the official website at [Umbrel.com ](https://www.umbrel.com)

**Comment by RoHoss** [comment]
Wow - thank you vm. It runs now perfect

**Comment by RoHoss** [comment]
> Hey @RoHoss!
> 
> This step here solves this error: [#1428 (comment)](https://github.com/getumbrel/umbrel/issues/1428#issuecomment-1184584190)
> 
> If you have any other issues ongoing with getting this to work hop into the [Telegram support channel](https://t.me/getumbrel/207765) and drop a line!
> 
> If you prefer to you can also use the message icon on the official website at [Umbrel.com ](https://www.umbrel.com)

THANK YOU
