### ISSUE TITLE
Ghostfolio server can't reach database

### ISSUE THREAD

**Issue by YellowWords** [getumbrel/umbrel#1630]
I tried to install Ghostfolio, but out of the box it doesn't seem to work. I had a look at the container logs, and it looks like the server can't reach the database for some reason. The database seems to be running though. I'm attaching the log files.

[ghostfolio-server-1-2023-05-20T15-21-44.log](https://github.com/getumbrel/umbrel/files/11522636/ghostfolio-server-1-2023-05-20T15-21-44.log)
[ghostfolio-postgres-1-2023-05-20T15-22-21.log](https://github.com/getumbrel/umbrel/files/11522637/ghostfolio-postgres-1-2023-05-20T15-22-21.log)

**Comment by nmfretz** [comment]
Hey @YellowWords, sorry to hear that Ghostfolio didn't work for you seamlessly. Are you still having this issue?

I just tested installing Ghostfolio fresh without issue and did not run into the relevant error shown in your server log:
`Error: P1001: Can't reach database server at ghostfolio_postgres_1:5432`. 

If you are still having this issue can you please first try:
- uninstalling ghostfolio
- restarting your server
- reinstalling ghostfolio

If you still have issues I'm happy to keep helping here, or if you prefer you can reach out for support on our [Telegram](https://t.me/getumbrel), or via the help chat on our [website](https://umbrel.com/).

**Comment by YellowWords** [comment]
Aha, it must be something on my end then. I'll close the issue and try to troubleshoot it.

**Comment by YellowWords** [comment]
Hello, I managed to track down what it was. The problem is that the docker-compose file assumes you get a docker host name like `ghostfolio_postgres_1` but my docker gives it `ghostfolio-postgres-1`. Setting an explicit host name fixed everything.
