### ISSUE TITLE
Implement Dark Mode on all the Umbrel Apps

### ISSUE THREAD

**Issue by JimSB** [getumbrel/umbrel#1632]
Currently on Dashboard > System > App Store as well as many Applications including Nostr Relay and ChatBot UI

Implement for Bitcoin Node and Lightning Node

**Comment by nmfretz** [comment]
Thanks @JimSB, dark mode is much needed on the official Umbrel apps! I have moved this issue to the umbrel-apps repo here https://github.com/getumbrel/umbrel-apps/issues/552
