### ISSUE TITLE
Widgets for the homepage?

### ISSUE THREAD

**Issue by jackablett** [getumbrel/umbrel#1633]
Hi, Devs at Umbrel

I'm writing for an idea which could be helpful, this is widgets, widgets could work from the *MANAGE APPS* part and have a button next to it for widgets, it then brings up a sidebar like the wallpapers, where you can drag and drop widgets and while dragging could move icons out of the way, widgets allow you to possibly interact with the apps or open them in a new tab and can be used to show stats or information from the app. 

Thanks, I hope you consider the widget function and maybe draggable home icons in edit mode!

**Comment by nmfretz** [comment]
Hey @jackablett, thanks for the suggestion! We will definitely consider adding widget functionality. Stay tuned for updates!

**Comment by jackablett** [comment]
Thanks I'm looking forward to see the updates in the future!
