### ISSUE TITLE
Umbrel fails to update apps

### ISSUE THREAD

**Issue by dorveille** [getumbrel/umbrel#1640]
Workflow: See badge on app store indicating updates available -> open app store -> update one or more apps.
Result: updating button oscillates in brightness, never completes. Log shows `yq` printing usage info.

```
==> karen.log <==
Got signal: app-update-thunderhub
karen is getting triggered!
Updating 'thunderhub' from: https://github.com/getumbrel/umbrel-apps.git
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.services | map(select(.image != null)) | .[].image': [Errno 2] No such file or directory: '.services | map(select(.image != null)) | .[].image'
```

**Comment by IMPranshu** [comment]
There's problem with the updated app store.

**Comment by dorveille** [comment]
I've since discovered that seemingly all my issues involving something printing `yq` usage in the logs and failing was because I was using system package manager `yq` and not the latest stable github version from the umbrel installer.
