### ISSUE TITLE
Keysend Disabled?

### ISSUE THREAD

**Issue by yaeloss** [getumbrel/umbrel#1644]
Hey all, I have UmbrelOS running on a normal Linux computer.

Tried to set up my node to receive V4V payments (podcasting 2.0 boostgrams) as I wasn't receiving any.

When someone tried to keysend to my node (using the id) from another node, I got the message that "This node doesn't accept keysend payments"

I SSHed into the umbrel files and edited the umbrel-lnd.conf file to add "accept-keysend=true"

After a restart, it worked. Now I can see the individual keysend payments Thunderhub and via the Helipad app.

It seems that on Raspberry Pi's Umbrel OS, it is enabled by default, but I had some issue on the Umbrel instance installed via Linux.

**Comment by mayankchhabra** [comment]
Hey @yaeloss, keysend should be enabled in the Lightning Node. Can you please confirm you're on the latest version of the Lightning Node app?

**Comment by yaeloss** [comment]
Yes, I was. the "node doesn't accept keystend payments" was a message I could see from another node in Thunderhub. Again, not sure of the issue, but I was able to solve it. Thanks!

**Comment by mayankchhabra** [comment]
Gotcha, thanks for letting us know and glad you were able to solve it!

**Comment by hsdredgun** [comment]
I got the same issue but instead of accepting the TRUE after I reboot the file reset itself to original value and keystone is disable again?
