### ISSUE TITLE
Tag 0.5.4 vs v0.5.4, failure downloading umbreld

### ISSUE THREAD

**Issue by the-nando** [getumbrel/umbrel#1655]
While updating an existing installation from 0.5.3 to 0.5.4 using the update script, the update fails while downloading the umbreld assets' tarball:

```bash
~ ./umbrel/scripts/update/update --repo getumbrel/umbrel#v0.5.4
[...]
Detected architecture: amd64
Installing umbreld to "/home/umbrel/umbrel/bin/umbreld"
Downloading umbreld from "https://github.com/getumbrel/umbrel/releases/download/0.5.4/umbreld-0.5.4-amd64.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
[...]
```

This seems to be caused by the new version being set to `RELEASE=0.5.4` by the update script, which is then passed to [bootstrap-run.sh](https://github.com/getumbrel/umbrel/blob/v0.5.4/scripts/update/bootstrap-run.sh#L54) but the assets are instead published under tag `v0.5.4` and the curl fails with 404.

**Comment by mayankchhabra** [comment]
Hey @the-nando, sorry for the issue. the `update --repo` isn't a supported update method, as it's only intended for development. Updating through the UI will handle the tag correctly. Would you be able to try that?

**Comment by the-nando** [comment]
I was actually running the upgrade with the CLI to troubleshoot why my previous attempt via the UI was hanging.
Just for my knowledge: Is it there another supported way to trigger an update via the CLI?

**Comment by mayankchhabra** [comment]
Ah unfortunately there isn't a way to trigger it via CLI. However, you can do:

```
tail -f ./umbrel/logs/karen.log
```

And start the update process via UI and monitor the log output of the update process in CLI.
