### ISSUE TITLE
Upgrade to 0.5.4 fails

### ISSUE THREAD

**Issue by handelaar2** [getumbrel/umbrel#1658]
Cannot upgrade from 0.5.3 to 0.5.4 (raspberry PI4b)
Running: `sudo ./umbrel/scripts/update/update --repo getumbrel/umbrel#v0.5.4`
(also pressing install on web-gui fails)
![image](https://github.com/getumbrel/umbrel/assets/28559038/7da56efc-1545-4c94-9a7b-bf3da3e215ea)

**Comment by lukechilds** [comment]
The `update --repo` behaviour is not really intended to be used by end users, it's an internal development tool.

You can trigger a real (non-development) update to 0.5.4 from the CLI by doing this:

```
cd ~/umbrel && echo '{"state": "success", "progress": 100, "description": "Successfully installed Umbrel v0.5.3", "updateTo": "v0.5.4"}' | sudo tee statuses/update-status.json && sudo scripts/update/update --ota
```

This will trigger an update that behaves the same way as if it was requested from the UI.

**Side note for anyone else that ends up here:** It's only safe to run this command if you're already on 0.5.3, triggering this command from the CLI updates directly to 0.5.4 without additional checks that updating from the UI performs. These checks ensure that you're on a version that can jump directly to 0.5.4 without intermediate updates and migrations.

**Comment by handelaar2** [comment]
Thanks @lukechilds That worked!
it remains strange however why the web-gui install button did not work for me
In any case, thanks for your very fast response!!

**Comment by lukechilds** [comment]
Glad you're sorted!

We're aware of the UI updates occasionally failing issue. We're currently migrating the background jobs to a new architecture to resolve this.
