### ISSUE TITLE
Feature: Internationalization 

### ISSUE THREAD

**Issue by Psycarlo** [getumbrel/umbrel#1659]
### Overview

_At the moment, Umbrel only supports English.
In the dashboard, all strings are hardcoded in english.
Would be awesome to support multiple languages which would give better user experience to users across the globe._

#### Code

Use the [vue-i18n](https://kazupon.github.io/vue-i18n/introduction.html) plugin for Vue 2

Users could select their desire language in Settings: Settings > System > Language

The select would show the supported languages.
Vue-i18n would default and fallback to english `en`

We would store the languages under `src/locales` folder:

```
 - src
 --- locales
 ------ en.json
 ------ pt.json
```

I would try to come up with the best possible json format to keep things organized.

#### Languages

For now, I can do
- English
- Portuguese

Next, we can easily add more languages.

#### Design

Changing language would be possible in the Settings Modal under the SYSTEM tab.

Could look something like this:
![](https://i.imgur.com/jpOonxE.png)

**_Should I open a PR for this?_**

**Comment by IMPranshu** [comment]
It would be great feature. I would use it surely if your PR gets merged

**Comment by Skythrew** [comment]
Seems nice, can't wait for your PR to get merged :+1:

**Comment by Psycarlo** [comment]
Still no feedback on this Issue

**Comment by mayankchhabra** [comment]
Hey folks, apologies for the delay. Thanks for the elaborate implementation overview and for being open to work on this @Psycarlo. We are actually going through a major refactor of the UI, which isn't based on Vue.js. But happy to confirm that we're working on internationalization in this refactor.

**Comment by Psycarlo** [comment]
Closing because of: https://github.com/getumbrel/umbrel/issues/1659#issuecomment-1694186834
