### ISSUE TITLE
node /backend/package/index.js high cpu usage

### ISSUE THREAD

**Issue by mountassir** [getumbrel/umbrel#1662]
Hello, 

I am running the latest version of umbrelOs 0.5.4 on Ubuntu server 22.04.2 LTS. I am seeing constant high CPU usage and it is mostly used by "node /backend/package/index.js", this process seems to run all the time and I am not sure what it is doing.

Any idea what this process is for? And why it is taking too much CPU?

Thanks!

**Comment by Psycarlo** [comment]
This should be the main main backend process 
How much CPU is it using? What are the specs of your machine?

**Comment by mountassir** [comment]
It is running in a vm on proxmox with a Xeon E5 2680 v4, the vm has four cores and 8GB RAM, the cpu type passed into the vm is "host" so it should have access to all the instructions.

The CPU usage seem to swing between 20% to 80%, with regular spikes over 100%.

**Comment by IMPranshu** [comment]
Can you try Umbrel logs to see if it's a Umbrel issue or not?

**Comment by mountassir** [comment]
I checked docker stats and found this was caused by the mempool_api container. I uninstalled Mempool and the system is now idling most of the time.
