### ISSUE TITLE
BTCpay server (and other app) not updated

### ISSUE THREAD

**Issue by ElucGeek** [getumbrel/umbrel#1668]
Hello,
I had issue with BTCPay server and figured out my issue was solved with an update but Umbrel is stuck with an old version from February. How do you manage update in the store? Why is it so much lagging? Is there a way to manually update an app?

**Comment by IMPranshu** [comment]
> How do you manage update in the store? Why is it so much lagging? Is there a way to manually update an app?

You can manually manage the apps you want but may run into issues in the log term by doing so, I am saying from experience.

In the umbrel-apps repo you can see all the apps and try updating the app you want, test run it and then open a PR accordingly. It's best 👌.

**Comment by ElucGeek** [comment]
OK it turned out that ma Umbrel couldn'd update the repo and I was late of several update since ar least May.

Reason was that 2 apps that I uninstalled had a modified docker-compose.xml files and it stops the repo update with an error. Deleting the 2 files solved the issues.
