### ISSUE TITLE
how do i uninstall on ubuntu

### ISSUE THREAD

**Issue by Yn-Skr** [getumbrel/umbrel#1693]

**Comment by Yn-Skr** [comment]
solved
Stop all containers on Docker.
docker stop $(docker ps -a -q)

Stop service umbrel
sudo systemctl stop umbrel-startup.service

Disable service umbrel
sudo systemctl disable umbrel-startup.service

Remove service on systemd

cd /etc/systemd/system/
sudo rm umbrel-startup.service
Remove umbrel directory
<img width="656" alt="Screenshot 2023-08-29 at 6 50 15 PM" src="https://github.com/getumbrel/umbrel/assets/88967181/e32e10ae-92ca-476c-af13-cccc18348e49">

**Comment by rafaelmaia8384** [comment]
I would recommend:

```
#Stop all containers
docker stop $(docker ps -a -q)

#Delete all containers
docker rm $(docker ps -a -q)

#Delete all images
docker rmi $(docker images)

#Stop service umbrel
sudo systemctl stop umbrel-startup.service

#Disable service umbrel
sudo systemctl disable umbrel-startup.service

#Remove service on systemd
cd /etc/systemd/system/
sudo rm umbrel-startup.service

#Remove umbrel directory
```
