### ISSUE TITLE
Weird numbers on per app RAM usage

### ISSUE THREAD

**Issue by vmartrix** [getumbrel/umbrel#1709]
I am running Umbrel 0.5.4 on Ubuntu 23.10 and when I go to the setting and take a look on the RAM usage, this is what it shows:
![image](https://github.com/getumbrel/umbrel/assets/25043383/54a05350-873c-4dd0-aeaf-1ba97462c75f)

**Comment by warioishere** [comment]
nobody umbrel is answering anymore. Umbrel doesnt care about users anymore, They rather concentrate on fancy apps in umbrel store and to sell their umbrel computers. Thats what happens when a company turns out to set money in priority instead of the user. Getyourself raspiblitz or citadel

**Comment by highghlow** [comment]
> nobody umbrel is answering anymore. Umbrel doesnt care about users anymore

Please don't insult the developers, they have a ton of backlogged stuff and are releasing this OS for free. Contribute, ask for help, show respect or leave. 

> They rather concentrate on fancy apps in umbrel store and to sell their umbrel computers.

They don't make most of Umbrel's apps. Look at https://github.com/getumbrel/umbrel-apps/pulls

> and to sell their umbrel computers.

Because that's the only way they could make any money, which they need to survive.

**Comment by highghlow** [comment]
> I am running Umbrel 0.5.4 on Ubuntu 23.10 and when I go to the setting and take a look on the RAM usage, this is what it shows

Since they released v1.0 on custom hardware, try installing it and checking if the issue persists.

**Comment by mayankchhabra** [comment]
Hey folks, memory, CPU and storage calculations should be very precise and accurate with the release of umbrelOS 1.2.0. So closing this issue for now!
