### ISSUE TITLE
Bitcoin app ram usage wrong format bug

### ISSUE THREAD

**Issue by f321x** [getumbrel/umbrel#1715]
The ram usage of the Bitcoin app is shown weird after restarting my freshly installed umbrel node, the blockchain was copied with scp to the node just before, idk if this can  be related. Otherwise Bitcoin seems to be working fine.

![Bildschirmfoto vom 2023-11-10 20-52-02](https://github.com/getumbrel/umbrel/assets/51097237/6ae7575c-b91f-4260-87b2-d92286cc7818)

**Comment by warioishere** [comment]
same here, applied 8GB on Proxmox Hypervisor, Umbrel shows 8.6GB

**Comment by highghlow** [comment]
Please try on the new version of umbrel and close the issue if it is fixed.

**Comment by f321x** [comment]
fixed with new dashboard in UmbrelOS 1
