### ISSUE TITLE
MFA code fields allow pasting of text strings

### ISSUE THREAD

**Issue by shawnyeager** [getumbrel/umbrel#1720]
I received my Umbrel Home this week. Fantastic out-of-the-box experience. Bravo, guys.

I just signed in again from Mobile Safari, and when prompted for my MFA code, I had a paragraph of text in the clipboard, instead of my 6-digit code. When I went to paste into the first of the 6 fields, Umbrel accepted the entire text into that first field. So, it appears that field validation is missing or buggy. 

Cheers.

**Comment by markmiro** [comment]
Fixed in 1.0!
