### ISSUE TITLE
Update stuck on "Downloading Umbrel v1.0.0" [debian]

### ISSUE THREAD

**Issue by highghlow** [getumbrel/umbrel#1781]
Update to v1.0.0 on Debian is stuck on 

```json
{
    "state":"installing",
    "progress":10,
    "description":"Downloading Umbrel v1.0.0",
    "updateTo":"v1.0.0"
}
```

That's all. I have no idea how to access logs.

**Comment by mayankchhabra** [comment]
Hey sorry @highghlow. Can you share how you started the update process? Right now the 1.0 update isn't available for Ubuntu/Debian. Although the system says there's an update available (because pre 1.0 we had no way to differentiate between device types to show update alerts), it should just immediately error out (safely) if you try it  to install it.

**Comment by highghlow** [comment]
> Can you share how you started the update process?

Settings > Check for updates > Install

> Right now the 1.0 update isn't available for Ubuntu/Debian.

It had thrown an error about that when I tried to update the day before, but now it got stuck on the update screen

**Comment by lukechilds** [comment]
@highghlow would you be able to share the log file at `~/umbrel/logs/karen.log`.

If you are for some reason stuck in the updating state you should be able to forcefully reset the state by running

```shell
sudo rm ~/umbrel/statuses/update-in-progress
echo '{"state": "success", "progress": 100, "description": "", "updateTo": ""}' | sudo tee ~/umbrel/statuses/update-status.json
```

Let me know if that helps

**Comment by dragonfire1119** [comment]
Is UmbrelOS 1.0 supported on Ubuntu or Debian? As the website says, April 2024. So if it's not supported yet, is that why the update doesn't seem to work?

**Comment by highghlow** [comment]
> would you be able to share the log file at `~/umbrel/logs/karen.log`.

Yes, I can
[karen.log](https://github.com/getumbrel/umbrel/files/14898096/karen.log)

I did all the things you told me. The update screen disappeared. Now I have a new problem, no apps start! (That will probably be a different issue)

**Comment by highghlow** [comment]
> Is UmbrelOS 1.0 supported on Ubuntu or Debian? As the website says, April 2024.

They have time until 30th of April to release the update

**Comment by zorrobyte** [comment]
What I don't get is that they run a Debian like OS for their amd64 hardware product. Of course, driver packages, etc are customized for it specifically, but it sounds like they intentionally kneecap x86 support and could release an OS like Home Assistant. But I get it, people need to eat.
