### ISSUE TITLE
Scripts folder missing after v1.0

### ISSUE THREAD

**Issue by ElChopChop** [getumbrel/umbrel#1792]
The Scripts folder is referred to in documentation, but it appears to have been moved following the v1.0 update.

Where has it moved to?

https://www.reddit.com/r/getumbrel/s/KgGwXqbBaX

**Comment by highghlow** [comment]
I think they updated the docs to not use the scripts folder. Mark the issue as closed if it is resolved.

**Comment by mayankchhabra** [comment]
Hey @ElChopChop — @highghlow is correct, scripts has been deprecated with umbrelOS 1.x. So I'll go ahead and close this issue for now. In case you needed any particular CLI command, please let us know!
