### ISSUE TITLE
Home Assistant Persistent Media Storage

### ISSUE THREAD

**Issue by TowyTowy** [getumbrel/umbrel#1800]
Please add persistent media storage for Home Assistant 🙏 
Currently, I need to edit the docker compose file on each system update / update to HA, to be able to upload media files, which is not ideal.

**Comment by highghlow** [comment]
Can you post what edits you make to your docker-compose?

**Comment by TowyTowy** [comment]
Sure!

```
    volumes:
      - /path/to/your/local/media/folder:/config/media
```

I added a new volume as such.

**Comment by highghlow** [comment]
I've started working on this request

**Comment by highghlow** [comment]
Now for longest part. Waiting for the PR to get merged. BTW, congrats on getting 1800 as the issue id
