### ISSUE TITLE
UmbrelOS 1.0 Boot USB Wifi

### ISSUE THREAD

**Issue by meneergroot** [getumbrel/umbrel#1811]
I installed a fresh copy of Umbrel 1.0 on my 67GB RAM NUC. But how does one set wifi since I can't get access to umbrel.local

Wifi needs to be set from the terminal, but what are the steps? Set wifi should be included into the installation, not afterwards.

**Comment by highghlow** [comment]
I think they should include NetworkManager/iw/wpa_supplicant on the system by default, so that you don't need internet to enable internet.

**Comment by mayankchhabra** [comment]
Hey folks, happy to report that [umbrelOS 1.2](https://github.com/getumbrel/umbrel/releases/tag/1.2.0) officially brings Wi-Fi support! So I'll go ahead and close this issue for now.

**Comment by nilskp** [comment]
I don't see any mention of WiFi in the instructions.

https://github.com/getumbrel/umbrel/wiki/Install-umbrelOS-on-x86-systems

**Comment by raphipod** [comment]
The WiFi support is only available after umbrelOS is installed with an Ethernet connection. You have to access the WebUI and set the WiFi connection there, not in the installer. That's what #1828 and this thread wanted.
