### ISSUE TITLE
Update wiki page to link to 1.1.2 release

### ISSUE THREAD

**Issue by Skivling** [getumbrel/umbrel#1819]
The page https://github.com/getumbrel/umbrel/wiki/Install-umbrelOS-on-x86-systems on the wiki still links to 1.1.1 for download even though 1.1.2 was released 15 or so hours ago.

I suggest make this part of the dev workflow when releasing versions.

**Comment by mayankchhabra** [comment]
Good shout, thanks so much! We've updated it, and will likely just create a `latest` download link that needs no updating and auto-downloads the latest installer.
