### ISSUE TITLE
Feature request: SSH access after init - UmbrelOS 1.0+

### ISSUE THREAD

**Issue by maximtitovich** [getumbrel/umbrel#1824]
Currently you can only login and ssh into the system before you "initialize" it, after installation with umbrel login and password. Would be nice to keep that or get to know umbrel and root user password after you "initialize" Umbrel.
That said than it is easier to edit docker files and adjust the configuration of different apps. For example I would like to disable authentication on some containers, as my installation is local and I use reverse proxy.
On the other hand, I would like to passthrough devices to jellyfin for example for decoding.
Anyways, is there a way to know your "new" umbrel or/and root user password?

**Comment by maximtitovich** [comment]
> The new password is you umbrel password you set during onboarding (username: `umbrel`)

Oh, I haven't tried it. I tried root and my new username with the password, but not the umbrel user. That is a little bit confusing. Does it still have root access?
The reason I'm asking is that I want to migrate some of my containers manually with moving the data folders for them on this new umbrel os installation. Or they would be encrypted and inaccessible?

**Comment by highghlow** [comment]
> Does it still have root access?

Yes, you can use `sudo`. Here's how to disable the sudo password prompt: https://askubuntu.com/questions/334318/sudoers-file-enable-nopasswd-for-user-all-commands



> I want to migrate some of my containers manually with moving the data folders for them on this new umbrel os installation. Or they would be encrypted and inaccessible?

I think application data is stored in `~/umbrel/app-data/<appid>/data` (where ~ is your user's home dir, `/home/umbrel` on Umbrel v1), though some weird applications might use docker volumes, which are much harder to migrate (you can check by opening their docker-compose.yml file in https://github.com/getumbrel/umbrel-apps and searching for `volumes:` at the bottom). The data is not encrypted.

**Comment by highghlow** [comment]
Please mark the issue as closed
