### ISSUE TITLE
Is the Umbrel install by script coming back any time?

### ISSUE THREAD

**Issue by pablote** [getumbrel/umbrel#1826]
After having my personal Umbrel down for a while, I'm trying to set it up again in a new system. Tried installing it today and...

```
With the release of umbrelOS 1.0, umbrelOS now needs to be installed directly as the operating system on your device's internal storage, not on top of an existing OS like Debian or Ubuntu. Check out our step-by-step guide at https://umbrel.com/umbrelos#install
```

Well, that's depressing. Every guide is about how you can image an SD from scratch or similar. That's just not an option for me, to give it a full system, I need to be able to install it on an existing one. Is the option to install by script in an existing system ever coming back? or am I out of Umbre for good? thanks

**Comment by JulianTV123** [comment]
I also hope the old installation will come back, because with the new instructions it's a headache, there's not even an ISO to install :/

**Comment by highghlow** [comment]
I think it could be possible. The img file copies a ter.gz file with a debian installation inside it to the drive. I think they use a script to install umbrel on a fresh debian installation, package it up, add an installer and publish. But it's just a theory

**Comment by highghlow** [comment]
I checked, it's true:
https://github.com/getumbrel/umbrel/blob/5a042334e36e65128058f512c29e7af422f4be0c/packages/os/usb-installer/overlay/opt/custom-tty#L44

Maybe it's possible to make an installer

**Comment by highghlow** [comment]
They get the rootfs by exporting a debian docker container:
https://github.com/getumbrel/umbrel/blob/master/packages/os/usb-installer/run.sh#L5

https://github.com/getumbrel/umbrel/blob/master/packages/os/usb-installer/usb-installer.Dockerfile

**Comment by pablote** [comment]
@highghlow if you can figure this out that would be great

**Comment by highghlow** [comment]
> @highghlow if you can figure this out that would be great

I have figured out the steps needed to install umbrel manually. If everything goes to plan (Which is highly unlikely) the script might be done today (timezones...)

**Comment by highghlow** [comment]
Here you go:
https://github.com/highghlow/umbrel-install-script

Important info:
You should have a separate partition mounted to `/data`. In my testing the root partition used up 7GB. I would recommend shrinking the OS partition to 7.5GB and the making a partition for `/data` in the remaining space (700MB used on a base install). The `/data` partition should be added to fstab. Everything not in `/data` will be lost on update.

**Comment by highghlow** [comment]
@pablote

**Comment by pablote** [comment]
Thanks, I'll give it a try soon

**Comment by Digital39999** [comment]
Out of curiosity, would it be possible to avoid all that and just host umbrel as a container using docker compose?

**Comment by highghlow** [comment]
> Out of curiosity, would it be possible to avoid all that and just host umbrel as a container using docker compose?

I thought about that. It maybe is possible, but mill require large-scale rewrites of umbreld.

**Comment by highghlow** [comment]
Please mark the issue as closed. It now exists unofficially and it can't exist officially.

**Comment by mayankchhabra** [comment]
Unfortunately as @highghlow noted, we have decided not to support it in favor of offering increased system reliability and stability. Here's the full reasoning from our [community forum post](https://community.umbrel.com/t/how-to-update-from-umbrelos-0-5-to-umbrelos-1-1-on-linux-devices/16704) so let's close this issue for now:

> You may remember installing umbrelOS 0.5 using the command curl -L https://umbrel.sh | bash on your device. This method layered umbrelOS on top of your underlying operating system (i.e. Ubuntu or Debian) using a series of scripts and system services.
>
> umbrelOS 1.0 brings a complete architectural overhaul, and it’s been rebuilt as a standalone operating system that installs directly onto your device’s internal storage. This change is crucial because umbrelOS now handles low-level operations like disk partitioning and file-system management. And by operating in a fully controlled environment, it increases the security, performance, and stability of the entire system.
>
> We could not deploy umbrelOS 1.0 as an over-the-air update for devices running Ubuntu/Debian because it involves replacing the entire underlying operating system.That said, with the introduction of umbrelOS 1.0, future updates will be delivered over-the-air.
>
> umbrelOS 1.0 implements a robust A/B partitioning scheme that enables OTA updates with rollback capabilities, allowing us to update the entire OS image, including drivers and the Linux kernel. This ensures we can deliver critical security updates reliably and safely — a limitation we faced previously.
>
> As a result of the new OTA update architecture, any modifications made to the umbrelOS system (host OS) manually via ssh/terminal will not be saved across software updates. If you’re looking to run custom software in a Linux environment, consider using the Portainer app available in the Umbrel App Store.

Closing the issue for now.

**Comment by casabitcoin1** [comment]
@kroese for being an absolute champion. Can't be using Umbrel OS - offers no ability to encrypt the drive and then proceeds to store bitcoin private keys in PLAIN TEXT LOL. 

Umbrel, WAKE UP and start listening to your user base.
