### ISSUE TITLE
Tailscale Security Update

### ISSUE THREAD

**Issue by Jack1424** [getumbrel/umbrel#1831]
Tailscale released a critical security update (v1.66.0) last week, but the latest version available from the Umbrel app store is still v1.62.1 (released almost 2 months ago). 

The vulnerability that v1.66.0 fixes ([TS-2024-005](https://tailscale.com/security-bulletins#ts-2024-005)) is quite major, and it affects any devices being used as exit nodes, subnet routers, or app connectors, which are probably popular uses for anyone running Tailscale on UmbrelOS.

It seems like the Umbrel team manually adds Tailscale updates to the Umbrel app store. Is there any way to automate these updates so we can access critical security and feature updates without opening an issue or PR? Tailscale's built-in auto-update feature does not seem to work on UmbrelOS.

**Comment by highghlow** [comment]
I don't know if it's possible to automate, but I've started working on this.

**Comment by highghlow** [comment]
Awaiting merge
