### ISSUE TITLE
What about the iso image¡¡¡¡¡

### ISSUE THREAD

**Issue by jmtj84** [getumbrel/umbrel#1836]
Has anyone manage to install it in vmware or virtualbox? I use to test the new realease like this in vmware or virtualbox but I cannot do it because the image format. I tried to burn the image into a flash memory but the booting does not work on this kinds of platforms.

Does anyone to give me a tips abouit?

Thanks in advance.

**Comment by highghlow** [comment]
You can use my install script: https://github.com/highghlow/umbrel-install-script
I'm working on an iso and a docker image for umbrel, but there're not ready yet
Duplicate: #1818

**Comment by jmtj84** [comment]
thanks for your reply I appreciate it so much.

**Comment by highghlow** [comment]
Also, please close the issue since it's a duplicate
