### ISSUE TITLE
Migration from other nodes such as myNode or Raspiblitz

### ISSUE THREAD

**Issue by pepinto** [getumbrel/umbrel#185]
It would be awesome if some user of myNode or Raspiblitz could migrate to Umbrel, in a simple process while keeping all relevant data, (blockchain and LN channels)

**Comment by mayankchhabra** [comment]
I agree it'd indeed be super handy. This is something we've considered in the past but dropped the idea eventually as there can be a lot of inconsistencies between drive formats, partition tables, the installed node implementations plus their versions etc, making the feature hard to maintain. Happy to reconsider if there's a significant demand for it.

**Comment by nolim1t** [comment]
Here is a [reference point for raspibliz migration](https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/config.scripts/blitz.datadrive.sh).

You'll need to be able to read the `btrfs(1)` filesystem which has some nice management features.

**Comment by Head** [comment]
imho one could edit https://github.com/getumbrel/umbrel/blob/40a45360d674bf52ed1ad5693818ef642c7e2328/scripts/umbrel-os/external-storage/mount#L163 and add `if [[ -f "${EXTERNAL_UMBREL_ROOT}"/.mynode ]]; then`
not exactly sure what to do in that case. For sure skip the format command. Maybe it would be enough to do the `Copying Umbrel install to external storage` and after that exchange the `/bitcoin/` folder with a symlink to `/mynode/bitcoin/`

**Comment by nmfretz** [comment]
Closing this old issue as we are currently not considering this due to the points noted by Mayank above. Please reopen if you feel strongly about making a case for this.
