### ISSUE TITLE
Update form version 1.2 to 1.2.1 failed.

### ISSUE THREAD

**Issue by NinjaMat9** [getumbrel/umbrel#1869]
I started the update and the normal update screen appeared, after a few minutes it stopped and the message "Error: failed to update" appeared.

Sorry. I'm a newbie. I hope this helps.

**Comment by monkey-jsun** [comment]
mine failed to upgrade from v1.1.2 to v1.2.1.  The symptom is a little different.  It kept spinning on the interface forever.  I had to ssh into the machine and reboot it.  After reboot, it stays back at v1.1.2, but everything still works fine.

**Comment by NinjaMat9** [comment]
Now it worked for whatever reason.
