### ISSUE TITLE
Unable to update 1.2.2

### ISSUE THREAD

**Issue by mikropsoft** [getumbrel/umbrel#1886]
Once the update process is complete, I log in to umbrel again and I keep getting the notification '1.2.2 update available'. I've updated it a couple of times, but it still doesn't update.

**Comment by a4004** [comment]
Hey @mikropsoft 👋 

Could you try the following and see if that helps:

### Manual update with `mender`

> For x86 umbrelOS
```
sudo mender install https://github.com/getumbrel/umbrel/releases/download/1.2.2/umbrelos-amd64.update
```

> For Raspberry Pi umbrelOS
```
sudo mender install https://github.com/getumbrel/umbrel/releases/download/1.2.2/umbrelos-pi.update
```

If you get any error or warning messages, please can you share them here? If the update appears to succeed can you then run:

```
sudo mender commit
```

and then reboot your Umbrel and see if that does the trick.

---

### After rebooting

 You should be able to see the version of `umbreld` after the reboot by running:

```
sudo journalctl -ru umbrel.service
```

and looking for something like this in the output:

```
            [umbreld  ] ☂️ Starting Umbrel v1.x.x
```

#### If this doesn't resolve the issue, we can go through it with you in a live setting on the Umbrel Discord, if you'd like: https://discord.gg/efNtFzqtdx

Let me know if you have any other questions / need further help! 🫂

**Comment by mikropsoft** [comment]
> Hey @mikropsoft 👋 
> 
> Could you try the following and see if that helps:
> 
> ### Manual update with `mender`
> 
> > For x86 umbrelOS
> ```
> sudo mender install https://github.com/getumbrel/umbrel/releases/download/1.2.2/umbrelos-amd64.update
> ```
> 
> > For Raspberry Pi umbrelOS
> ```
> sudo mender install https://github.com/getumbrel/umbrel/releases/download/1.2.2/umbrelos-pi.update
> ```
> 
> If you get any error or warning messages, please can you share them here? If the update appears to succeed can you then run:
> 
> ```
> sudo mender commit
> ```
> 
> and then reboot your Umbrel and see if that does the trick.
> 
> ---
> 
> ### After rebooting
> 
>  You should be able to see the version of `umbreld` after the reboot by running:
> 
> ```
> sudo journalctl -ru umbrel.service
> ```
> 
> and looking for something like this in the output:
> 
> ```
>             [umbreld  ] ☂️ Starting Umbrel v1.x.x
> ```
> 
> #### If this doesn't resolve the issue, we can go through it with you in a live setting on the Umbrel Discord, if you'd like: https://discord.gg/efNtFzqtdx
> 
> Let me know if you have any other questions / need further help! 🫂 

I did a clean installation, but thanks for the solution. By the way, umbrel gets heavier after every update. I recommend most users do a clean install every 6 months.

**Comment by githare** [comment]
I'm reopening this issue cause I've got the same one.
Here are the mender debug logs:
https://bin.infini.fr/?2a6a6e16eac51452#C6dNu9okxcjyhfbg6aCUK3kjML7CH7gcbK9LJZbbaMe5

**Comment by a4004** [comment]
> I'm reopening this issue cause I've got the same one. From the UI, I still have the update notification to go to 1.2.2. So I try from the cli, and still have the same issue too. I have checked for badblocks on sda5/sda6 and sda7. Here are the mender debug logs: https://bin.infini.fr/?2a6a6e16eac51452#C6dNu9okxcjyhfbg6aCUK3kjML7CH7gcbK9LJZbbaMe5

Hey @githare

There's been multiple reports of this happening with Raspberry Pi's, not too sure what the exact cause is yet, as I don't presently have a Pi to test with, but it does seem like an issue with Rugpi and the way the A/B partition scheme works for updates.

If you're running umbrelOS from the SD card and using an external drive for data storage, I recommend you just flash the latest version of the umbrelOS on the SD card in order to update this time. Hopefully this issue gets resolved soon.

Any questions, feel free to ask!

**Comment by githare** [comment]
Sad this issue isn't resolved for umbrelOS, but I've done what you said, and the update is done for me.

**Comment by nostitos** [comment]
Same problem on rPi

**Comment by borracho-mejor** [comment]
Same issue on an RPi4, manual update instructions above did not work either, but I only have the two warning messages below:

```
WARN[0000] No server URL(s) specified in mender configuration.
WARN[0000] Server entry 1 has no associated server URL.
```

I'll wait for a hopeful moment I can update remotely.
