### ISSUE TITLE
Unable to install any applications

### ISSUE THREAD

**Issue by M-topu** [getumbrel/umbrel#1894]
Installing Umbrel using LattePada cannot install any apps
[umbrel-1723397946862.log](https://github.com/user-attachments/files/16575590/umbrel-1723397946862.log)
Aug 11 17:37:58 umbrel umbreld[769]: [apprepository] Checking for update for https://github.com/getumbrel/umbrel-apps.git
Aug 11 17:38:02 umbrel umbreld[769]: [apprepository] https://github.com/getumbrel/umbrel-apps.git is already up to date
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=info msg="State transition: inventory-update-retry-wait [Sync] -> inventory-update [Sync]"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="Returning artifact name from /etc/mender/artifact_info file. This is a fallback, in case the information can not be retrieved from the database, and is only expected when an update has never been installed before."
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=info msg="Device unauthorized; attempting reauthorization"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=error msg="Failed to authorize with \"\": failed to build authorization request: failed to obtain authorization message data: failed to obtain identity data: failed to call /usr/share/mender/identity/mender-device-identity: fork/exec /usr/share/mender/identity/mender-device-identity: no such file or directory"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="Reauthorization failed with error: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=error msg="Failed to submit inventory data: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=error msg="inventory submit failed: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="Failed to refresh inventory: failed to submit inventory data: inventory submit failed: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=info msg="State transition: inventory-update [Sync] -> inventory-update-retry-wait [Sync]"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=info msg="Handle update inventory retry state try: 9"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="Returning artifact name from /etc/mender/artifact_info file. This is a fallback, in case the information can not be retrieved from the database, and is only expected when an update has never been installed before."
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=info msg="Device unauthorized; attempting reauthorization"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=error msg="Failed to authorize with \"\": failed to build authorization request: failed to obtain authorization message data: failed to obtain identity data: failed to call /usr/share/mender/identity/mender-device-identity: fork/exec /usr/share/mender/identity/mender-device-identity: no such file or directory"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="Reauthorization failed with error: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=error msg="Failed to submit inventory data: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=error msg="inventory submit failed: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="Failed to refresh inventory: failed to submit inventory data: inventory submit failed: transient error: authorization request failed"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="RetryPollIntervalSeconds is not defined"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=warning msg="RetryPollIntervalSeconds is not defined"
Aug 11 17:38:37 umbrel mender[532]: time="2024-08-11T17:38:37Z" level=info msg="Wait 5m0s before next inventory update attempt in 4m59.999879048s"

**Comment by M-topu** [comment]
Find a solution and replace the Docker image source on the command line

**Comment by M-topu** [comment]
issue

**Comment by M-topu** [comment]
issue

**Comment by M-topu** [comment]
> 在命令行上找到解决方案并替换 Docker 镜像源

**Comment by CaverneCrypto** [comment]
Hi! I'm running almost the same error while trying to upgrade my umbrel from 1.3 to 1.4.

How did you manage with the file /usr/share/mender/identity/mender-device-identity?
