### ISSUE TITLE
Bitcoin node app is not working

### ISSUE THREAD

**Issue by hertzsol** [getumbrel/umbrel#1905]
After i have installed the umbrel ios and try to install the Bitcoin node,but it not working.as a result i couldn't create the node.

**Comment by Clarevero1** [comment]
@hertzsol You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[bitcoin live support](https://thedappsupport.web.app) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by Official-Support010** [comment]
> After i have installed the umbrel ios and try to install the Bitcoin node,but it not working.as a result i couldn't create the node.

Have you been attended to @hertzsol ?
