### ISSUE TITLE
How to take backup of Umbrel?

### ISSUE THREAD

**Issue by jjmmbb** [getumbrel/umbrel#1916]
There is a way to take a backup of Umbrel device and restore everything in case of disk failure for example? I have no found a backup solution to protect Umbrel device.

**Comment by al-lac** [comment]
They are still working on an official way to do it, see the thread here: https://community.umbrel.com/t/how-can-i-backup-my-umbrel-node/13737/19

A guide on how to do it now was also posted here: https://community.umbrel.com/t/diy-backup-soltution-without-usage-of-the-cli/18889

**Comment by jjmmbb** [comment]
Thanks!
