### ISSUE TITLE
Cleanup compose file to make things easier to maintain

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel#198]
I propose that we move as much as possible the fixed configurable items (environment variables) to `config/` (example please discuss) and use [`env_file`](https://docs.docker.com/compose/compose-file/#env_file) directive instead.

That way upgrades are less painful to script.

**Comment by mayankchhabra** [comment]
Thanks, @nolim1t. Closing this now as we did indeed switch to using a `.env` file.
