### ISSUE TITLE
Neutrino 🔁 Bitcoin Node Automatic Switching

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#2]
### Issue

- The user cannot start using his lightning or bitcoin wallet until `bitcoind` has fully synchronized. This adds a lot of friction due to the long delay, creating a very frustrating experience.

- If `bitcoind` lags behind for some reason, such as when the user had his node turned off for a few days/weeks, the same problem reoccurs.

### Solution

Neutrino filters can solve this problem. We need an automatic, recurring way to switch lnd's bitcoin mode to `neutrino` from `bitcoind` as soon as `bitcoind` lags behind by a certain number of blocks from its best header.

### Ideas

Perhaps it's a good idea to create a new service that runs 24x7 via a container called `lnd-switch`  that uses the following environment variables:

```
BITCOIN_HOST: "0.0.0.0"
BITCOIN_RPC_PORT: "8332"
BITCOIN_RPC_USER: "umbrel"
BITCOIN_RPC_PASSWORD: "1234567890"
LND_CONFIG_FILE: "/home/umbrel/lnd/lnd.conf"
SWITCH_TO_NEUTRINO: "144" (switch to neutrino when bitcoind is *at least* 144 blocks behind)
SWITCH_TO_BITCOIND: "3" (switch to bitcoind when bitcoind is *at max* 3 blocks behind)
```

Considering the above example variables, `lnd-switch` will update the bitcoin node in `LND_CONFIG_FILE`  from `bitcoin.node=bitcoind` to `bitcoin.node=neutrino` as soon as `bitcoind`'s `headers - blocks >= 144` and update it from `bitcoin.node=neutrino` to `bitcoin.node=bitcoind` as soon as `bitcoind`'s `headers - blocks <= 3`. It also needs a way to restart the `lnd` container after every config file change.

I'm not sure if this is the right approach or not. If it is, then `lnd-switch` can be a tiny FOSS project on its own that (I think) many more people will find useful.

cc @nolim1t @meeDamian

**Comment by igorbastosib** [comment]
I know it is an old discussion here, I couldn't find anything new about the subject.

Is it still possible to use 100% LND + Neutrino?

I mean, I have a Device (not Umbrel) with a synched BitcoinCoreNode running, I'd like to prepare several Umbrel devices with LND and want to link them to my external BitcoinCoreNode (external just because it is not on the same device, but all on the same Network)

Is yes, could someone please share how?
