### ISSUE TITLE
Remove the check for UID=0 for scripts/stop ?

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel#201]
https://github.com/getumbrel/umbrel/blob/e5fcedf56fe4d8bd21020e7004f97656bdc45daf/scripts/stop#L6

Not sure why we need root to stop this?

**Comment by nmfretz** [comment]
I believe we need to run as root because the script is killing background services (which may be running as root) and controlling Docker services, which requires root access.

Closing issue.
