### ISSUE TITLE
Allow user to disable automatic backups

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#202]
Currently, the toggle switch on the settings page is disabled and there's no way to turn off the backups.

**Comment by AaronDewes** [comment]
I have a (hopefully working) manager API and host API, @louneskmt said he'll build the dashboard integration later, so you can mark this as "In progress"

**Comment by nmfretz** [comment]
Moved this to https://github.com/getumbrel/umbrel-lightning/issues/11 because the Lightning Node app was extracted from getumbrel/umbrel.
