### ISSUE TITLE
Allow user to recover from a backup

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#203]
After the user enters 24 words, we need to check if there's an existing backup stored on our servers by deriving the backup ID, and if so, let the user recover from it.

**Comment by bettyvschmartz** [comment]
It would be great, for sovereign usage, if the back up location could be chosen by the user rather than trusting storage of this to your servers.

**Comment by louneskmt** [comment]
> It would be great, for sovereign usage, if the back up location could be chosen by the user rather than trusting storage of this to your servers. 

One will be enable to disable automatic backups in the next update (or the update after).

I recommend [this Twitter thread](https://twitter.com/lukechilds/status/1341315501356531712?s=21) by @lukechilds on the subject.

**Comment by nmfretz** [comment]
Closing this old issue. This recovery feature was implemented.
