### ISSUE TITLE
OTA update stuck at "downloading"

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#205]
This has, in all cases, been reported by users on manual Umbrel installations.

**Comment by jgmontoya** [comment]
I'm having this issue as well. Also manual installation. ¿How should one go about updating without losing information?

**Comment by snapo** [comment]
same here, manual installation (ubuntu 20.04) upgrade from 26 or so to 28 stuck at downloading ... as i have no funds yet on it i play a bit around. maybe i figure it out

**Comment by mayankchhabra** [comment]
As a temporary fix, if your update is stuck at downloading, you can run `cd` into the umbrel directory and run the following to reset:

```
rm statuses/update-status.json && echo "{\"state\": \"success\", \"progress\": 100, \"description\": \"\", \"updateTo\": \"\"}" >> statuses/update-status.json
```

**Comment by jgmontoya** [comment]
If anyone want's to update on the meantime this worked for me: `sudo ./scripts/update/update --repo getumbrel/umbrel#v0.2.8`

I don't think it matters but at least I had my instance stopped at the time of updating.

**Comment by snapo** [comment]
> If anyone want's to update on the meantime this worked for me:
> `sudo ./scripts/update/update --repo getumbrel/umbrel#v0.2.8`
> 
> I don't think it matters but at least I had my instance stopped at the time of updating.

That worked absolutely superb...

**Comment by jgmontoya** [comment]
I could update using the dashboard normally from v0.2.8 to v0.2.9 without any problem whatsoever.

I think this issue can be closed :tada:

**Comment by mayankchhabra** [comment]
Well, that makes it more complex because I can replicate the issue on http://testnet.getumbrel.com lol which runs a manual Umbrel installation on Ubuntu 18.04.

An interesting discovery is that the OTA update doesn't log to `syslog` when it's triggered through the UI gets stuck. And if you try to redirect the log output to another file, the update doesn't get stuck anymore. Crazy.

**Comment by mayankchhabra** [comment]
Still the same issue on https://testnet.getumbrel.com when trying to update to v0.2.10:

![image](https://user-images.githubusercontent.com/10330103/92639112-fe457f00-f2f8-11ea-8011-3e05d3fa9049.png)

**Comment by lukechilds** [comment]
>If anyone want's to update on the meantime this worked for me:
>`sudo ./scripts/update/update --repo getumbrel/umbrel#v0.2.8`
>
>I don't think it matters but at least I had my instance stopped at the time of updating.

Just a quick word of warning, this is something we use internally for development. It bypasses all semver range checks.

e.g If you're doing a big jump, say going from v0.1.2 to v1.2.3 there might be some incremental steps you need to do, like update to v0.5.0 first, then update to v1.2.3. This is all handled automatically when updating via the dashboard, but it isn't if you update directly with the `update` command.

It will just directly install whatever version/branch/commit you specify over your current installation.

It's fine to do in this case, and in the future if you understand the risks and check that you're updating between supported ranges.

But do be careful!

**Comment by vindard** [comment]
Great news, I was able to replicate the issue as well and found that it was a quirk with `karen` trying to run the `update` script multiple times and mistakenly updating `update-status.json` even after the update is finished if the `update` file is left in the `triggers` dir. 

Fix should be to simply make sure the `signals/update` file gets deleted as part of the update process. Before I do that explicitly though, do you all already have a way of cleaning up files in the `signals/` folder after each successful trigger for other triggers? I couldn't seem to find any in the code.

**Comment by lukechilds** [comment]
Awesome, thanks for looking into this @vindard!

>Before I do that explicitly though, do you all already have a way of cleaning up files in the signals/ folder after each successful trigger for other triggers? I couldn't seem to find any in the code.

No, currently the status files are just removed when the scripts finish executing which is problematic. Really we need some sort of `trap` condition that correctly handles any way a script can fail and ensures status files are cleaned up. See this comment for more details: https://github.com/getumbrel/umbrel/pull/188#discussion_r479740992

>As an aside, running umbrel locally is tricky because there's no easy way to kill persistent processes kicked off in start script (karen, monitor, decoy-trigger). We could probably include killing those somehow as part of the stop script as well.

Yes, ideally those services should be stopped as part of `stop`. However the update process is spawned by `karen` and calls `stop`, so we need to make sure that's implemented in a way that OTA updates don't kill themselves halfway through updating.

**Comment by mayankchhabra** [comment]
> It was a quirk with karen trying to run the update script multiple times and mistakenly updating update-status.json even after the update is finished if the update file is left in the triggers dir

@vindard Are you sure about that this is indeed the case? Because:

- `events/signals/update` file shouldn't cause `karen` to trigger if it's just sitting there. It needs to be touched again (or updated/modified in some way).

- `update-status.json` reflecting incorrect update status means that in reality the update went through, but is just stuck in the UI. However, that has not been the case in my testing. The update never went through (as verified by version checks in `info.json`).

**Comment by vindard** [comment]
Hmm, ok I this is what I was able to replicate so far. Let me know how consistent this is with you all's experiences.

My steps from my testing were:

0. **Have the repo open in VS code and a terminal running where I ran `sudo ./scripts/start`**
    I was able to see `karen` logs from that terminal

1. **Kick off an update from the UI (I did 0.2.9 to 0.2.10)**
    My update completed successfully and I was briefly able to get back into the dashboard and observe everything looking ok

2. **Leave everything open to observe. Notice the `update` script get triggered again**
    In my terminal I started to see 3 types of signals even after the update happened: `''`, `'.gitkeep`', `'update'`. I suspect this may be something to do with VSCode being open and creating fswatch events somehow but when the `update` trigger got re-run I saw:
    - the exact error from comment above (https://github.com/getumbrel/umbrel/issues/205#issuecomment-687167339)
    - the `update-status.json` file get erroneously changed to be in a downloading state
    - the `Downloading...` screen (after the `update-status.json` change) from this comment (https://github.com/getumbrel/umbrel/issues/205#issuecomment-689741078) when I try to log back in (I assume because the `update-status.json` file is now wrong)

The thing I was able to replicate was I was able to get the update to happen but then quickly after the `update` was triggered again which triggered the error messages in the logs and put the dashboard into that inconsistent Downloading state by changing the `update-status.json` file incorrectly (even though the update had already happened and was fine at the fs level).

Since this has only been happening on non-Pi installs, I was wondering if there may be something other than the initial `touch` that could trigger `signals/update` fswatch events and lead to the `triggers/update` being re-run illegitimately and producing that error state I described :point_up_2:  :thinking:

**Comment by vindard** [comment]
I submitted a [partial fix](https://github.com/getumbrel/umbrel/pull/239) for this issue for the cases that I was able to replicate that lead to these types of errors.

The fix should stop the `update-status.json` from getting to the "10% Downloading" inconsistent state from the `update` script, as described by some of the logs/comments above
