### ISSUE TITLE
Keep up the good work!!!!

### ISSUE THREAD

**Issue by junderw** [getumbrel/umbrel#207]
Come on guys, if we get 7,777 contributions in 1 year we unlock rainbow road.

![image](https://user-images.githubusercontent.com/11246316/91718450-529c8080-ebce-11ea-9ca1-27313fc9974c.png)

⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️
https://gist.github.com/junderw/babd914d06de7c90ac1099791188f276
⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️⛏️

**Comment by lukechilds** [comment]
![](https://media.giphy.com/media/lB0vWF9au9XRC/giphy.gif)

**Comment by mayankchhabra** [comment]
0 contributions or 7,777, GitHub's rainbow road is fair for everyone 🎉

![image](https://user-images.githubusercontent.com/10330103/91737254-78c12100-ebcc-11ea-93dc-3874b320ee00.png)

**Comment by nolim1t** [comment]
Trippy
