### ISSUE TITLE
Add Watchtower support

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel#212]
For safety reasons of course when the node goes offline momentarily.

There is multiple parts to this.

- [ ] Switch on config for creating a tower and connecting to a tower
- [ ] Create middleware / manager bindings to host a tower. It needs to create a `tor` forwarding for `9911` and then also add a towerip setting for the tor address
- [ ] Create middleware bindings to connect to a tower
- [ ] Create a User interface to interface with the manager / middleware bindings

**Comment by nolim1t** [comment]
Are we planning on having this implemented

**Comment by lukechilds** [comment]
I definitely think we should support this but since we are still in beta and don't have many features yet this seems pretty low priority in comparison to things that users have been actively requesting like better external wallet support, built in block explorer etc.

**Comment by nolim1t** [comment]
Happy to take this on.

Ensuring that people's funds are SAFU is good for building and maintaining trust. Especially for UX.

Opinions?

**Comment by nolim1t** [comment]
Can bring in external wallet / btcpayserver / explorer support if there is infrastructure in place for plugins.

I don't think these should bloat the default install as the above aren't useful during IBD.

**Comment by mayankchhabra** [comment]
I agree with @lukechilds. We should support watchtowers, but eventually. Have moved this to medium/long-term todo.
