### ISSUE TITLE
Installing v0.2.10 Update - Not Clear If Update is Progressing or Not - Stuck on  "STARTING UPDATE"

### ISSUE THREAD

**Issue by paulo03** [getumbrel/umbrel#229]
1. Click "INSTALL NOW" on Settings page
2. Pop up is displayed, including button for downloading channel backup and summary of update
3. Click "INSTALL NOW"
4. Button changes wording to "STARTING UPDATE"
5. Stuck in this state (However, I can click the "X" in top right corner of pop up to dismiss it)
6. Not synchronized across devices (I can access umbrel.local from another device and start the process over, as if I didn't already go through the steps above)
7. No ability to visually understand progress of the update (Although I'm assuming my update never began)

Screen-shots from 2 devices, showing that initializing the update is not synchronized across instances of accessing umbrel.local

![Image from iOS (26)](https://user-images.githubusercontent.com/45669122/92821458-eebd4900-f37f-11ea-8bad-0980fed94337.png)
![Screen Shot 2020-09-10 at 4 06 29 PM](https://user-images.githubusercontent.com/45669122/92821731-39d75c00-f380-11ea-9b7e-58d969155c2d.png)

**Comment by jgmontoya** [comment]
Hi! 
Is this Umbrel OS or is it a manual install?

**Comment by paulo03** [comment]
> Hi! 
> 
> Is this Umbrel OS or is it a manual install?

Hey there, its Umbrel OS

**Comment by lukechilds** [comment]
Thanks for the detailed repot @paulo03.

Do you have a way we can contact you privately? It would be great if you could share some logs with us but not publicly.

I'm interested specifically in the output of:

```
journalctl -u umbrel-startup.service

**Comment by paulo03** [comment]
> Thanks for the detailed repot @paulo03.
> 
> 
> 
> Do you have a way we can contact you privately? It would be great if you could share some logs with us but not publicly.
> 
> 
> 
> I'm interested specifically in the output of:
> 
> 
> 
> ```
> 
> journalctl -u umbrel-startup
> 
> ```
> 
> 
> 
> and
> 
> 
> 
> ```
> 
> journalctl -u umbrel-external-storage
> 
> ```

Sure, no problem. I see your gmail on your profile. Is it best to contact you there?

**Comment by lukechilds** [comment]
Twitter or Telegram DM (@lukechilds) might be a little easier but email is also fine if you don't have access to them.

**Comment by lukechilds** [comment]
The issue was a bug in Umbrel OS v0.2.9 that prevented Umbrel from being able to run system commands (update/shutdown/restart) on it's first boot.

You can resolve the issue by rebooting via SSH. You can run this on a machine connected to the same local network as your Umbrel:

```
ssh -t umbrel@umbrel.local sudo reboot
```

Password: moneyprintergobrrr

Once your Umbrel comes back online (give it a couple of minutes) you should then be able log in to the dashboard and update as normal.
