### ISSUE TITLE
[Feature Request] Migration script

### ISSUE THREAD

**Issue by jgmontoya** [getumbrel/umbrel#230]
It seems like a lot of people already have a raspberry pi with either raspiblitz or mynodebtc installed and would like to try umbrel out.

It would be cool to have a script that allows for an easier transition by:
1) Detecting whether there is already a Bitcoin Node on the storage
2) Saving the `chainstate` and `blocks` from the previous install to avoid having to sync from scratch

Maybe there could be an option upon first boot to run that script

**Comment by mayankchhabra** [comment]
Yeah, that'd be neat to have and has been requested a few times (#230). Not sure if it's worth the effort due to the security risks, inconsistencies and maintenance.

**Comment by jgmontoya** [comment]
Yeah you're probably right. It would also make more sense as a stand-alone script rather than to bloat it inside umbrel itself now that I think about it.

Thanks, closing!
