### ISSUE TITLE
Can't withdraw funds or open channels on testnet

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#231]
No matter what amount you pick, it always throws this error **only on testnet** when returning fee estimates (for both channel open txs and btc withdrawals):

> Mempool reject low fee transaction. Increase fee rate.

![image](https://user-images.githubusercontent.com/10330103/93080312-1d526100-f6ab-11ea-8d55-1f149f7d80a5.png)

This may very well be an issue with umbrel-middleware.

**Comment by diogopms** [comment]
I'm having this issue on the testnet :)

I don't know how to start debugging but I will try it :)

**Comment by mayankchhabra** [comment]
Oops, looks like our minimum fee check logic was off (#69). @diogopms if you'd like to help test the fix, you can update the following docker image in `docker-compose.yml` to `mayankchhabra/middleware:testnet` and then restart Umbrel:

https://github.com/getumbrel/umbrel/blob/771affe0e595ff1b46f58898562de8f758fbd1b0/docker-compose.yml#L131

**Comment by diogopms** [comment]
Yes I will test it tomorrow morning and update this thread. Thanks
