### ISSUE TITLE
Toggle between mainnet and testnet (Bitcoin)

### ISSUE THREAD

**Issue by diogopms** [getumbrel/umbrel#241]
Hi, first of all congratulations for this project :)

All the setup went smooth, but I would like to ask a feature or update the docs.

What is the best way to configure the pi3/4 using btc testnet?

**Comment by lukechilds** [comment]
This is documented in the installation instructions:

```
# To use Umbrel on mainnet, run:
sudo ./scripts/start

# For testnet, run:
sudo NETWORK=testnet ./scripts/start

# For regtest, run:
sudo NETWORK=regtest ./scripts/start
```
https://github.com/getumbrel/umbrel#step-2-run-umbrel

You should do this on a fresh installation, running this on your existing mainnet installation will likely cause issues.
