### ISSUE TITLE
Allow create more than one account on Umbrel

### ISSUE THREAD

**Issue by bitcoinuser** [getumbrel/umbrel#245]
Hi,

I would like to create an account to my brother on the same Umbrel. So we can have the funds separated.

Thanks.

**Comment by fiatjaf** [comment]
I don't know if this is possible, but that could be achieved by running a service like https://lnbits.org/ on Umbrel.

**Comment by louneskmt** [comment]
Would be really cool for bitcoiners families that set up an Umbrel node at home! Don't know either if it's possible, but I gonna make a few researches.

**Comment by mayankchhabra** [comment]
I agree with the intended use-case. This would be accomplished by using LNDHub once we add support for it (very soon).
