### ISSUE TITLE
Integrate Electrs

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#246]
Add Electrum Server and display the hidden service URL for relevant wallets that support it.

Will be resolved by #242.

**Comment by maltokyo** [comment]
Don't you already maintain ElectrumX docker @lukechilds ?  I thought it was superior performance-wise.   Any possibility to have a choice? ;)

**Comment by lukechilds** [comment]
@maltokyo It is superior performance wise, however it also requires txindex in Bitcoin Core and takes considerably longer to build the initial index, electrs is really fast to build the index.

We think electrs makes the most sense to ship by default in Umbrel and its performance is more than adequate for personal use. Once we build out app infrastructure anyone is free to publish an ElectrumX app and users would be free to install that if they need a higher performance Electrum server.

Alternatively, if we get lots of complaints from users that the Electrum server is too slow then we can look at swapping out the default Electrum server in Umbrel from electrs to ElectrumX.

**Comment by maltokyo** [comment]
Thank you @lukechilds - appreciated and understood

**Comment by lukechilds** [comment]
Resolved via #242
