### ISSUE TITLE
Allow NGINX to run on a custom port

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#253]
I have my own RP running on port 80/443 already that handles all SSL termination.

When umbrel starts up it tries to bind to port 80 which is already taken.

Maybe some option to stop Nginx binding to the host's port 80 would be helpful. 

For now, I could work around it by commenting out these lines in docker-compose:
```
                # ports:
                #     - "80:80"
```

**Comment by nolim1t** [comment]
probably easily fixed with a custom port for outgoing

**Comment by maltokyo** [comment]
agree, hardcoding something on port 80 is probably not a good idea.

**Comment by nolim1t** [comment]
for a complete solution its ok. But for custom solutions which interact with other setup I can see what you mean.

**Comment by nolim1t** [comment]
I might have a fix for this, am testing something out

**Comment by nolim1t** [comment]
Fix appears to work

**Comment by maltokyo** [comment]
Thanks for this!  Great

**Comment by lukechilds** [comment]
This is now implemented in https://github.com/getumbrel/umbrel/pull/562
