### ISSUE TITLE
Ran out of disk space and deleted electrs directory

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#258]
My SSD ran out of space, so to regain control I deleted electrs directory entirely.  
Everything else was synched fully.  Any ideas on how I can "reset" electrs so it starts to sync again?
Sorry to ask, I couldn't find how.

**Comment by nolim1t** [comment]
you have only a 500 GB SSD right?

I think because of the electrum requirement and by default, this changes a lot of things as electrum data and txindex. So the new requirements should be at least 1 TB -> Refer to #254

**Comment by maltokyo** [comment]
I have 1TB. But it had some other stuff on there. Now it has enough room. How can I reset? 😅

**Comment by nolim1t** [comment]
Close your channels, remember the seed and the install it again.

**Comment by maltokyo** [comment]
I don't want to resync bitcoin though. How can I just reset electrs or at least avoid resynching bitcoin in this case?

**Comment by mayankchhabra** [comment]
Ah, you can try recreating the electrs dir and reconfiguring the install. This wouldn't delete your existing data:

In the Umbrel directory, run:
```
sudo scripts/stop
mkdir -p electrs
sudo NETWORK=mainnet scripts/configure
sudo scripts/start
```

**Comment by maltokyo** [comment]
Thank you! Giving it a try now.

**Comment by mayankchhabra** [comment]
Hi @maltokyo, did that work for you?

**Comment by maltokyo** [comment]
It did, thank you, and sorry to bother!

>
