### ISSUE TITLE
Partitioning failed on a new SSD

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#26]
Tried to debug an Umbrel for a friend over TeamViewer. It wouldn't start, so I checked the `rc.local` status for any errors and found this:

<img width="1126" alt="Screen Shot 2020-07-10 at 12 20 41 AM" src="https://user-images.githubusercontent.com/10330103/87118813-f8500500-c299-11ea-84a4-62c19aa2c0e1.png">

He used a brand new SSD, so it had no partition (no `sda1`, only `sda`).

![paste (3)](https://user-images.githubusercontent.com/10330103/87118847-0f8ef280-c29a-11ea-80ba-4c7671fa45f2.png)

**Comment by nolim1t** [comment]
whats the partition structure of the drive?

**Comment by nolim1t** [comment]
Also the files/directories in there

**Comment by mayankchhabra** [comment]
It's a brand new drive with no partitions and files.

**Comment by mayankchhabra** [comment]
Does the partitioner check if the drive has partitions? Because if not, we may have to create a partition first.

**Comment by nolim1t** [comment]
All brand new drives come formatted for FAT32 at least

**Comment by nolim1t** [comment]
Would be interested to know the manufacturer too..

**Comment by mayankchhabra** [comment]
It's a Kingston A400 960GB

**Comment by mayankchhabra** [comment]
@nolim1t I think you can replicate this bug by removing all partitions from your existing drive and then trying to run partitioner tool on it.

**Comment by mayankchhabra** [comment]
Closed by #29
