### ISSUE TITLE
Web GUI stuck Loading LND...

### ISSUE THREAD

**Issue by st4cks4ts** [getumbrel/umbrel#280]
Took a look at the log and found this:

`[ERR] LTND: unable to load TLS credentials: tls: failed to find any PEM data in certificate input`

**Comment by lukechilds** [comment]
Thanks for reporting @st4cks4ts.

I've just helped a user out with a similar issue.

If you do `ls -lah ~/umbrel/lnd` are the `tls.cert` and `tls.key` files both 0 bytes?

If so, can you try deleting them and restarting LND with:

```
cd ~/umbrel
rm lnd/tls.cert lnd/tls.key
docker-compose restart lnd
```

Let us know how you get on!

**Comment by st4cks4ts** [comment]
Thanks Luke, yes they were. I ended up just wiping the hard drive and reinstalling. Since the boot checks are required to access the settings page, would you ever consider allowing settings to be accessed without passing the checks, so a user could see the status of the containers, view logs, perhaps reindex and reinstall docker containers, just the most common errors a user will face going forward?

**Comment by lukechilds** [comment]
We probably wouldn't be able to give access to the dashboard since most of the dashboard requires access to Bitcoin Core/LND to function.

However we definitely should provide some sort of minimal interactive web UI in the event of an error that explains to the user what's gone wrong and how they can resolve the situation.

**Comment by CoderBoogs** [comment]
Having same issue currently (Trying to re purpose my casa node first gen.   to fix this, where do i run this command:

cd ~/umbrel
rm lnd/tls.cert lnd/tls.key
docker-compose restart lnd

do i connect a keyboard and screen to my casa node and run it on the command line? 

Thanks.

**Comment by louneskmt** [comment]
@CoderBoogs If you're using UmbrelOS, you can connect to your Umbrel via SSH : `ssh -t umbrel.local`, password `moneyprintergobrrr`.

**Comment by CoderBoogs** [comment]
Thanks

**Comment by CoderBoogs** [comment]
@louneskmt Thanks

**Comment by CoderBoogs** [comment]
I restarted lnd twice using the above commands and the browser is still stuck on loading LND.

**Comment by murtyjones** [comment]
Dealing with the same issue which the commands above don't seem to resolve.

```
LND logs
--------

Attaching to lnd
lnd                  | unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:31.514 [ERR] LTND: unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:31.514 [INF] LTND: Shutdown complete
lnd                  | 2021-01-17 16:40:34.907 [INF] LTND: Version: 0.11.1-beta commit=v0.11.1-beta, build=production, logging=default
lnd                  | 2021-01-17 16:40:34.907 [INF] LTND: Active chain: Bitcoin (network=mainnet)
lnd                  | 2021-01-17 16:40:34.907 [INF] LTND: Opening the main database, this might take a few minutes...
lnd                  | 2021-01-17 16:40:34.907 [INF] LTND: Opening bbolt database, sync_freelist=false
lnd                  | 2021-01-17 16:40:35.341 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
lnd                  | 2021-01-17 16:40:35.342 [INF] LTND: Database now open (time_to_open=434.401983ms)!
lnd                  | 2021-01-17 16:40:35.994 [ERR] LTND: unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:35.995 [INF] LTND: Shutdown complete
lnd                  | unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:40.998 [INF] LTND: Version: 0.11.1-beta commit=v0.11.1-beta, build=production, logging=default
lnd                  | 2021-01-17 16:40:40.998 [INF] LTND: Active chain: Bitcoin (network=mainnet)
lnd                  | 2021-01-17 16:40:40.999 [INF] LTND: Opening the main database, this might take a few minutes...
lnd                  | 2021-01-17 16:40:40.999 [INF] LTND: Opening bbolt database, sync_freelist=false
lnd                  | 2021-01-17 16:40:41.080 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
lnd                  | 2021-01-17 16:40:41.081 [INF] LTND: Database now open (time_to_open=81.739687ms)!
lnd                  | 2021-01-17 16:40:41.962 [ERR] LTND: unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:41.963 [INF] LTND: Shutdown complete
lnd                  | unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:50.180 [INF] LTND: Version: 0.11.1-beta commit=v0.11.1-beta, build=production, logging=default
lnd                  | 2021-01-17 16:40:50.180 [INF] LTND: Active chain: Bitcoin (network=mainnet)
lnd                  | 2021-01-17 16:40:50.180 [INF] LTND: Opening the main database, this might take a few minutes...
lnd                  | 2021-01-17 16:40:50.181 [INF] LTND: Opening bbolt database, sync_freelist=false
lnd                  | 2021-01-17 16:40:50.294 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
lnd                  | 2021-01-17 16:40:50.295 [INF] LTND: Database now open (time_to_open=114.382205ms)!
lnd                  | 2021-01-17 16:40:51.344 [ERR] LTND: unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | unable to initialize neutrino backend: unable to create neutrino light client: EOF
lnd                  | 2021-01-17 16:40:51.344 [INF] LTND: Shutdown complete
```

**Comment by GBKS** [comment]
Same issue here, but probably a different error. From the logs:

`ENOENT: no such file or directory, open '/lnd/tls.cert'`

Is Umbrel supposed to create the needed certificates on startup automatically?

**Comment by GBKS** [comment]
Alright, another user error on my side. I flashed the SD card with the downloaded ZIP file, instead of unpacking it and flashing it with the contained IMG. Resulted in nested `umbrel` folders which apparently mess with the creation of the certificates.
