### ISSUE TITLE
Unofficial Guide for Umbrel on RockPro64 (pine64 hardware)

### ISSUE THREAD

**Issue by thunderbiscuit** [getumbrel/umbrel#283]
Hey guys! I've been working on getting Umbrel to work on a [RockPro64](https://www.pine64.org/rockpro64/) and making that process reproducible for myself and other folks.

My current solution and scripts are described/hosted [in this GitHub gist](https://gist.github.com/thunderbiscuit/e7f83cb62619e1368d6728e42949d21d).

With this issue I'm looking to figure out two things:
1. Do you think a github gist is an optimal format for this sort of thing?
2. Do you think the general approach for the guide is right? I'm happy to get feedback to optimize the scripts.

**Comment by BitcoinLabrador** [comment]
Thanks for the guide! It helped me figure out what I missed while setting it up on my Rock Pi. 

I'd say this could be added to the install guide, but it shouldn't rely on importing your scripts via curl. There's not much complicated going on, so the guide should simply provide the commands the user has to type / copy. I'll make sure to test the guide through on a number of distros and re-write the guide to not rely on external scripts. Don't trust, verify :)

**Comment by thunderbiscuit** [comment]
@BitcoinLabrador thanks! I see your point about not relying on curl. Just published the guide as a [blog post here](https://thunderbiscuit.com/umbrel-rockpro/). The scripts are provided there in full too so readers can use them line by line. My experience with that though is that there is often typos or people forget one of the lines, and then the stuff doesn't work and they don't know why. Using curl offers an alternative where you can get the scripts, verify them, and then just run them as one-liners.

I'm thinking of keeping both options there (the way the article is currently written). What do you think? Happy to take feedback and even remove if curl is really seen as a security risk.

**Comment by thunderbiscuit** [comment]
Also to the maintainers: this issue is ready to be closed (pending bitcoinlabrador's comments). I have built the guide, [the link is here](https://thunderbiscuit.com/umbrel-rockpro/), feel free to use it/link to it as you wish, and I'll be keeping an eye out for when you make `umbrel-os` RockPro compatible!

Thanks for the amazing node.

**Comment by mayankchhabra** [comment]
Thanks a lot, @thunderbiscuit! Sorry it took us a while to check it out. Your guide looks great!

I agree with @BitcoinLabrador's concern about curling down scripts, but your approach in the blog post looks good:

> I describe two scripts that together install the requirements for Umbrel. I provide these two scripts as as GitHub Gist and explain how to download them using curl for extra convenience, but you absolutely do not need to go that route.

Thanks again, we'll share it with people looking to run Umbrel on RockPro64.
