### ISSUE TITLE
Electrum cant connect to Electrs (http nor tor)

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#284]
I am on macos, and using electrum.  I run ElectrumX server on another machine on the same network, it connects fine from Electrum wallet on port 50002.  But when I try to connect to Electrs (fully synched umbrel node) I get the dreaded red traffic like, and just cannot connect at all (on port 50001 or 50002).

What do I miss, how can I debug this?

**Comment by louneskmt** [comment]
Do you use your Tor proxy ?

**Comment by maltokyo** [comment]
Yes. Setup tor proxy in system settings on localhost 9050 and started tor.
Then tried to connect. I'm looking for logs or anything that can tell me
what's going on

**Comment by louneskmt** [comment]
No need to setup the proxy in your system preferences. Just have the Tor service running in background is enough. If you install Tor via Brew (`brew install tor`), it will automatically create and launch a service. You can check if the Tor service is running with this command : `brew services list`.

**Comment by maltokyo** [comment]
Oh, I think that was the issue.  I deleted that setup and just use tor in the background.  I thought it would need that proxy setting.  Strange. Thank you so much, very nice of you to help - sorry to use your time.  Hope others who do what I did will find this resolution.

In addition, initially, I was using the tor URL to the main Umbrel dashboard, but of course, that doesn't work - you need to go into bitcoin core settings and select connect wallet, and choose Electrum (or your wallet) from dropdown..
