### ISSUE TITLE
Show Electrs status in the UI

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#285]
Is it supposed to show in the dashboard with the beautiful UI like the other components of the stack?  The only way I can interact with Electrs is through cli.  Is it normal?

**Comment by mayankchhabra** [comment]
Hey @maltokyo, they should be available in Bitcoin Core > ... > Connect Wallet > Electrum

**Comment by maltokyo** [comment]
Hi @mayankchhabra - Connection with electrum wallet worked!  

However, I was after more of a status page, showing the sync status and other details about electrs, and any errors etc..

**Comment by mayankchhabra** [comment]
Great! 

Agree, that'd be useful. I've added it to our long-term roadmap. Thanks!

**Comment by nioncode** [comment]
@mayankchhabra would you mind re-opening this issue until this is implemented?

I tried to connect with electrum to my fully synced node, but it just fails and there is no indication why this might be happening (i.e. there is no message like 'your Electrum server is still syncing, please try again later' or whatever on client side and also nothing in umbrel's ui). I then went through the system logs and saw that electrs is still indexing, so this explains the problem.
It would be great to have some kind of status indicator in the ui to show whether electrs is 'ready' (does not necessarily have to be 0-100% progress indicator, which would be even better obviously).

I also opened https://github.com/romanz/electrs/issues/309 to maybe make this less confusing for an end user.

**Comment by aantonop** [comment]
I would like to add my voice to this request. Electrs sync status affects a number of apps that depend on it, such as the block explorer and connection of external wallets. After a short period of downtime the Bitcoin Core catches up quickly but the Electrs daemon is still syncing, indexing and compacting databases. On an underpowered CPU this takes the longest time and several important services fail (e.g. Connecting an Electrum wallet or the block explorer) with no indication as to why they are failing or when they will stop failing.

It would be great if the dashboard showed that Electrs (call it "transaction detailed indexing") is still in progress and how far it has to go.

**Comment by lukechilds** [comment]
Yeah we know this is definitely needed. It hasn't been super high priority since we only had wallets before, but since we now have apps depending on electrs it's definitely more important.

One issue is that electrs doesn't really expose a clean way to get the sync progress (afaik). We'll have to do something dirty like parse the logs coming from stdout to figure out what electrs is doing.

That or switch to ElectrumX which I think does expose a rich RPC that returns this data.

**Comment by maltokyo** [comment]
@lukechilds you maintain the best ElectrumX docker image yourself...! I've been an avid user. I still use it instead of electrs for exactly this reason, and that it's just simply more robust and less resource intensive, imo.

**Comment by lukechilds** [comment]
Yeah, a big pro for electrs is that it doesn't require txindex, and we didn't have txindex enabled in Umbrel when we were adding it.

However now we need to have it enabled for most apps so there's very little reason to use electrs over ElectrumX.

**Comment by maltokyo** [comment]
If I make a PR to add ElectrumX, would you accept it, and help me to `Umbrel'ise` it?

**Comment by softsimon** [comment]
Many people that are using the Mempool Explorer get the error "Connection to server lost, please retry" when they are querying addresses and asking us what is the problem. We could improve our error message, but the Electrum Server sync status should be visible in the UI as many people are confused by this and asking how to see when it is done syncing.

**Comment by maltokyo** [comment]
I still maintain that switching to electrumx would be better for this, and general usability.

**Comment by mattsk** [comment]
$ ./electrs-progress.sh 
Total blocks = 2674
Current block = 1429
Progress is 53%

$ cat electrs-progress.sh
#!/bin/sh
blocks=$(docker logs electrs 2>&1 | awk '/INFO - indexing/{print $4}')
current=$(docker logs electrs 2>&1 | awk '/TRACE - indexed/{a=$0}END{print $a}'| sed -n 's/.*blk0\(....\).*/\1/p')
echo Total blocks = $blocks
echo Current block = $current
echo Progress is $((current*100/blocks))%

**Comment by hernangr2** [comment]
I cannot connect electrum (in windows) to my umbrel node in ubuntu. the node is synchronized and electrs too. I followed the instructions but I can't connect.
could it be something about the ports?

**Comment by nmfretz** [comment]
Closing this old issue. There is now an electrs app with a UI that displays sync status:
https://apps.umbrel.com/app/electrs
https://github.com/getumbrel/umbrel-electrs
