### ISSUE TITLE
Make wallet connector more accessible

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#287]
### Issue

Currently, the wallet connector UI is divided into two sections; Bitcoin and Lightning, both hidden inside the meatballs menus on the respective pages which isn't a very obvious place. Next, different wallets require different kinds of steps (eg. some need a Tor proxy on the system), use different kinds of nomenclature (eg. some say "host", others say "address"), etc. The process is far from standard between multiple wallets.

### Solution

1. Consolidate the Bitcoin and Lightning wallets into a single wallet connector UI (h/t @lukechilds), and move the "Connect wallet" link to the navbar in place of the "Settings" link by shifting "Settings" underneath "Lightning".

2. Add precise step-by-step instructions to wallet connect UI for every wallet. For example, if the user chooses "Specter Desktop" they'd see the following instructions:
    1. Make sure Tor is installed and running on your system ([click here](https://github.com/getumbrel/umbrel/blob/master/Tor.md) for instructions to set up Tor).
    2. Open Specter Desktop and click **"Configure Node"**.
    3. Disable **"Auto-detect"**.
    4. In the **"Username"**, enter `umbrel`.
    5. In the **"Password"**, enter `9wQN3UbG7hp3L2MB2Mz8gsC0V9ezQdJiUcyt2Wu_CIw`.
    6. In the **"Host"**, enter `http://ubrouzrcygw4vx6tfmpnywv43jjcfo4nsnvywacjmrcqkabopsd5rvid.onion`
    7. In the **"Port"**, enter `8332`.
    8. Click **"Test"** to verify if Specter is able to connect to your Umbrel.
    9. After verifying, click **"Save"**.
    10. Congratulations! You've successfully connected Specter Desktop to your Umbrel.

**Comment by louneskmt** [comment]
Working on it!

**Comment by AaronDewes** [comment]
I think this issue can be closed.

**Comment by lukechilds** [comment]
Closed via https://github.com/getumbrel/umbrel-dashboard/pull/267
