### ISSUE TITLE
Error "Unable to unlock wallet, invalid passphrase for master public key" after full sync

### ISSUE THREAD

**Issue by petrhejna** [getumbrel/umbrel#292]
After few days of syncing I last checked at 98.8% of blockchain.

Now, when I want to check again (assuming my node is fully synced) I cannot login into the Umbrel. 

I am 100% sure I am putting right password, but it rejects it with error: 
`Unable to unlock wallet, invalid passphrase for master public key`

**Comment by mayankchhabra** [comment]
Hi @petrhejna! Are you using Umbrel OS (Raspberry Pi) or a manual Umbrel installation? 

Also, by any chance did you copy an existing lnd wallet? Or did you use the default lnd wallet created by Umbrel?

**Comment by petrhejna** [comment]
I had it on Rasbery Pi. When I copied blockchain manually to backup it I found that it was not finished (like ~98.5℅) was finished.

I haven't used anything I was just w8 for sync.

**Comment by petrhejna** [comment]
So yes, I was using what was generated.

**Comment by mayankchhabra** [comment]
Sorry @petrhejna, I missed this issue. Did you resolve the issue?

**Comment by petrhejna** [comment]
Sadly no, honestly I have migrated to Raspiblitz.

Hiwevwr/I am still very interested about umbrell because it may bring full nodes to the mases.

**Comment by mayankchhabra** [comment]
Sorry to hear that! Hope you're able to give it another shot sometime
