### ISSUE TITLE
Add mempool.space dashboard to available services

### ISSUE THREAD

**Issue by h1d3m3** [getumbrel/umbrel#295]
It would be amazing to have [mempool.space](https://mempool.space/) dashboard and explorer added to this project ([github](https://github.com/mempool/mempool)).

**Comment by louneskmt** [comment]
That's planned! Umbrel team is currently working on application structure, then it will be easier for them and third party developers to package new apps/extensions for Umbrel, installable in just a few clicks. A Mempool.space app (either by Umbrel or other contributors) will likely be available. Can't wait!

**Comment by mayankchhabra** [comment]
Yep, it'd be available once we rollout the the app framework!
