### ISSUE TITLE
Out-of-memory issues with electrs

### ISSUE THREAD

**Issue by nioncode** [getumbrel/umbrel#298]
I'm running a custom umbrel install on an Odroid N2 with 4gb of RAM, with no swap configured.

With the default configuration of umbrel, the electrs container starts up, but after a few minutes (usually 3-10min), my system got out of memory and started to kill electrs, which was then restarted again automatically through docker and the cycle repeated.

To fix this, I added the following configuration items to electrs.toml as recommended by electrs itself (https://github.com/romanz/electrs/blob/master/doc/usage.md) for low resource devices:
```
index_batch_size = 10
jsonrpc_import = true
```
This makes electrs request all blocks through bitcoind's RPC interface instead of parsing the block data files directly, which seems to scale far better on low end devices. This setup is now running for 11 hours without any problems. The only downside is that indexing of electrs takes longer.

Would it make sense to add these values as default for all umbrel installs to ensure that electrs does not run out-of-memory? It is better to have a slow sync compared to having potentially no working sync at all.

**Comment by mayankchhabra** [comment]
Thanks, @nioncode. This issue will most likely be fixed when we implement #309. @lukechilds has helped a couple of users reduce their `dbcache` manually because Bitcoin Core was eating too much RAM after IBD, leaving not much room for Electrs to be able to generate indexes.

**Comment by nioncode** [comment]
Just reducing `dbcache` did not work on my system and electrs still got killed by out-of-memory killer. The only thing that helped was to apply the configuration that I outlined in my initial post.

**Comment by lukechilds** [comment]
Oh wow. Thanks for reporting that @nioncode. We have 4GB swap on Umbrel OS so that's probably why you're the first to encounter this issue.

Did you by any chance notice how much memory Bitcoin Core/LND/electrs where utilising when it crashed? How far did you reduce `dbcache` by? I tested `dbcache=20` with another custom install user and it seemed to work for them.

Also, do you keep track of roughly how long a full sync takes with the low memory params?

Worth noting that this will likely be resolved via the upcoming `--low-memory` flag in electrs: https://github.com/romanz/electrs/issues/308

(I haven't had time to test that build out yet but it's sounding very promising)

**Comment by nioncode** [comment]
I did not really measure the memory consumption of core/lnd/electrs. I just noticed electrs getting killed all the time, so it most likely consumed 2-3gb and then it was killed.

I completely uncommented `dbcache` parameter from `bitcoin.conf`, so bitcoind now uses the default, which is 600mb iirc. At the moment (fully synced), lnd uses ~500mb, bitcoind ~800mb, electrs ~900mb.

I think the full index took roughly 1 day, I don't really remember, could also be longer. If you want to, I can run it again, but I don't know if it is helpful without having a reference of the 'normal' electrs parameters on my system. Are you planning to use `--low-memory` when it is available in electrs by default?

**Comment by lukechilds** [comment]
Yeah, that PR branch looks very interesting for Umbrel.

Smaller index size, faster query performance AND lower memory requirements!

**Comment by bakaoh** [comment]
i run into this error too, the electrs always got killed at this line

```
...
TRACE - indexed "/data/.bitcoin/testnet3/blocks/blk00011.dat": 0 rows
TRACE - indexed "/data/.bitcoin/testnet3/blocks/blk00012.dat": 1838116 rows
TRACE - indexed "/data/.bitcoin/testnet3/blocks/blk00013.dat": 2180448 rows
TRACE - indexed "/data/.bitcoin/testnet3/blocks/blk00014.dat": 2680658 rows
```

Using Digital Ocean server, Ubuntu 20.04 (2 vCPUs, 4GB)

**Comment by lukechilds** [comment]
@bakaoh creating a swapfile should help resolve the issue as a workaround for now.

Please also note that Umbrel is intended to be installed on a secure local network. It's not safe to run on a VPS directly connected to the internet with no firewall.

**Comment by nmfretz** [comment]
Close by https://github.com/getumbrel/umbrel/issues/309
