### ISSUE TITLE
Dashboard fails to load when containers are down / not responding

### ISSUE THREAD

**Issue by nioncode** [getumbrel/umbrel#299]
This comes up quite frequently in the Telegram group, so this just serves as a reference documentation of this problem.

To me it seems like that the dashboard does not load (or rather it loads, but then displays 'Loading Bitcoin Core' / 'Loading LND' and hangs there) when either bitcoind or lnd are not started at all (this can be tested by shutting down the lnd container for example) or simply do not respond to rpc requests (e.g. when bitcoind was not shut down cleanly and it has to replay blocks on startup, which might take a while).

It would be great if the dashboard would always load successfully, independently to whether bitcoind or lnd are available, and then show their status as 'offline' or 'synchronizing' etc. on the dashboard. This way the user has a clear indication what is going on and does not sit in front of a seemingly frozen UI.

**Comment by wahl-kanzlei** [comment]
Fully agree, same issues. If the dashboard is not opening, the user does not know, what is going on, and why he is not seeing any progress.

My impression is, that it should be made more clear, that, if the system is loading exclusively over Tor, it is a long journey. If this method is preferred, and, if the dashboard cant be reached, than there is no "get up and running in 5 minutes".

Lukechilds writes: "Also if we are doing initial sync over clearnet, we need to make that clear. I agree it's a sensible default and the correct choice for most users. However if the user lives somewhere where using Bitcoin is illegal, they may want the entire sync to happen over Tor so it's not obvious to their ISP they're using Bitcoin. "

My question: why not presenting the user at the beginning a switch "IBD over clearnet" or "IBD over Tor". Thus he is aware of why everything takes so long; his choice.
Honestly, in my case - umbrel is now busy for over one week and it is still not synced.

**Comment by nioncode** [comment]
> Honestly, in my case - umbrel is now busy for over one week and it is still not synced.

This seems a bit weird. During regular IBD, the dashboard should load just fine and you will see the progress of IBD in the dashboard. If the dashboard does not load at all, then bitcoind might be busy with replaying blocks, but this should not take a week, but rather maximum a few hours.

So it seems like your bitcoind is busy with something (unclear with what exactly without checking your logs) which is NOT the IBD by itself and that prevents your dashboard from loading.

**Comment by nmfretz** [comment]
Closing issue as no longer relevant since the structure of umbrel and the apps have changed.
