### ISSUE TITLE
Upgrade from CLI

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#300]
How to upgrade (the official way?) from CLI?  I can't find any hints in the README or Wiki.  Would it be better to add?

**Comment by maltokyo** [comment]
Added PR in case it would be useful for others https://github.com/getumbrel/umbrel/pull/301

**Comment by lukechilds** [comment]
There is no official way to upgrade via CLI. You need to upgrade via the UI.

It's possible to use these commands to upgrade via CLI: https://github.com/getumbrel/umbrel/issues/205#issuecomment-691475831

However this is intended for development use only and is completely unsupported.
