### ISSUE TITLE
Can't login via Tor browser

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#304]
Documenting this until it's fixed. Some users can't get past the login screen on a Tor-enabled browser (login button fades in and out endlessly). 

Restarting Umbrel via the settings page (accessed via the local network on `http://umbrel.local/settings` or `http://<ip-address>/settings`) permanently fixes the issue and prevents it from happening again.

The reason why this happens is that on the first Umbrel run, dashboard's hidden service file doesn't exist, and thus the hidden service URL is not whitelisted by manager/middleware APIs for CORS. We can fix it by starting the manager/middleware containers after checking for existence of the hidden service file using a custom start script.

**Comment by pcarballeda** [comment]
I am also having problems connecting my node remotely with Tor browser, but in my case I am getting "Not allowed by CORS" error.

**Comment by mayankchhabra** [comment]
@pcarballeda have you tried a restart (from http://umbrel.local/settings)?

**Comment by pcarballeda** [comment]
> @pcarballeda have you tried a restart (from http://umbrel.local/settings)?

I tried but when I hit restart it gets stuck on the screen where it tells me that it is restarting, I wait for hours and nothing happens.

On the other hand I am not able to install the latest update (0.2.15), the same thing happens, it gets stuck and nothing happens. It would be nice to incorporate some kind of feedback for users like a progress bar or similar.

**Comment by mayankchhabra** [comment]
Ah, looks like some background services aren't running. Could you please try a restart via SSH? That would probably fix all the issues.

```
ssh -t umbrel@umbrel.local "sudo reboot"
```

Password: `moneyprintergobrrr`

**Comment by pcarballeda** [comment]
I have restarted the node by the less recommendable way (disconnect the current) and when restarting I have been able to do everything, thanks for the help. I write down the command for the next one. Thank you very much for answering so quickly!
