### ISSUE TITLE
choose path instead of $pwd

### ISSUE THREAD

**Issue by GPConnect** [getumbrel/umbrel#317]
Hello, 
i know we need to run the script inside the directory we which to install umbrel but how could i choose the path myself ? 
Thanks

**Comment by mayankchhabra** [comment]
Hi @GPConnect, what is your specific use-case?

If you'd like to run Umbrel from a specific path, then you should install Umbrel at that specific path. The common use-case is to install and run on an external drive, which is pretty straightforward.

**Comment by GPConnect** [comment]
to push the data to an s3 bucket service like wasabi.com for example !

**Comment by mayankchhabra** [comment]
Are you trying to do a full cloud backup? If so, you can do that by zipping and uploading the Umbrel installation directory. 

If I'm misunderstanding your use-case, can you please elaborate on what data you are trying to push and for what reason exactly?

**Comment by mayankchhabra** [comment]
I'd suggest installing Umbrel in the path where you want it to be installed in the first place. Alternatively, you can move over the entire Umbrel installation directory to a new path and it'd work without a problem. 

Closing this issue now, but feel free to reopen with more details if you think I misunderstood your issue.
