### ISSUE TITLE
504 Gateway timeout errors with LND

### ISSUE THREAD

**Issue by CharlesFr** [getumbrel/umbrel#324]
After entering amount and clicking "Create Invoice", the QR code computess for a while d the returns to this page with following error.

Despite this, after checking Lighting page it appears the invoice is correctly created.

```
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.17.8</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```

![image](https://user-images.githubusercontent.com/16102087/96925620-5a7cf080-14ac-11eb-869d-0d0cf52d56c6.png)

**Comment by vinniejames** [comment]
Seeing the same when opening a LN channel :/

**Comment by Minituff** [comment]
I have also been experiencing 504 gateway timeouts. I'm guessing that's why Umbrel has been running so slow. Any ideas on how to fix?

![2021-02-12 20_09_14-Desktop](https://user-images.githubusercontent.com/8152401/107841246-36506280-6d6e-11eb-9411-c1caee889578.jpg)

**Comment by nmfretz** [comment]
Closing this old, out-of-date issue
