### ISSUE TITLE
Add system stats to the settings page

### ISSUE THREAD

**Issue by fanismichalakis** [getumbrel/umbrel#325]
Monitor (and display) health status of the Raspberry Pi for non techie users, including :
- temperature
- vcgencmd get_throttled, which returns various pieces of information regarding present and past cpu throttling, reached temperature levels, incoming power, etc, but in an hex format that has to be converted for it to be valuable to the end user.

Could be a new panel accessible from the settings in the dashboard. Could be interesting to provide some advices (ex: use a heatsink case/fans in case of high temperature, use another alim in case of power problems, etc.).

**Comment by nmfretz** [comment]
Closing as completed.
