### ISSUE TITLE
Container hostname change on Docker install

### ISSUE THREAD

**Issue by seljuck** [getumbrel/umbrel#326]
Hello,

I'm installing Umbrel on a ProxMox Virtual Machine running Docker. I already have Docker running with other containers on this machine.

I'm running into similar COR issues as reported here https://github.com/getumbrel/umbrel/issues/319

I'm wondering if there is a way to force the hostname to what I want at startup? I already have a DNS server and domain name for my network. So anything .local is not searchable on my network.

I also don't want to use the hostname of the Virtual machine for the Umbrel container.

Right now on startup Umbrel reports the network name as  VirtualMachine.local. In addition I'm getting CORS errors when trying access the dashboard for the first time.

Thanks,
Daniel

**Comment by AaronDewes** [comment]
It needs to be the hostname of the whole VM, on most distros this works if you're root.
`echo umbrel > /etc/hostname`

**Comment by mayankchhabra** [comment]
> I already have a DNS server and domain name for my network. So anything .local is not searchable on my network.

If your VM is already resolvable by a domain name, you can try setting the hostname to the domain name like Aaron pointed out above:

```sh
echo $domain_name > /etc/hostname
```

Then restart Umbrel and see if you can access the dashboard on the domain name without the CORS issue.

**Comment by mayankchhabra** [comment]
Closing this as the issue was solved on Telegram

![image](https://user-images.githubusercontent.com/10330103/100894086-1d137600-34e2-11eb-9327-e04cc127abe9.png)

**Comment by seljuck** [comment]
> 
> 
> > I already have a DNS server and domain name for my network. So anything .local is not searchable on my network.
> 
> If your VM is already resolvable by a domain name, you can try setting the hostname to the domain name like Aaron pointed out above:
> 
> ```shell
> echo $domain_name > /etc/hostname
> ```
> 
> Then restart Umbrel and see if you can access the dashboard on the domain name without the CORS issue.

I'm a little confused. My other containers can have their own hostname, they don't need to be called by the VM's hostname.

**Comment by seljuck** [comment]
> 
> 
> Closing this as the issue was solved on Telegram
> 
> ![image](https://user-images.githubusercontent.com/10330103/100894086-1d137600-34e2-11eb-9327-e04cc127abe9.png)

Can I create an .env file with the DEVICE_HOSTS variable assigned, so it's persistent? If so, what should the name of the .env file be?

**Comment by lukechilds** [comment]
We do have some `.env` files but if you edit them they'll be overwritten if you do an OTA update.

I'd suggest however you're starting Umbrel on startup on your custom setup, just first export `DEVICE_HOSTS`.

**Comment by seljuck** [comment]
To be clear. The only way to start up Umbrel is with the script 

./scripts/start

Is there anyway to have it daemonized? Like docker-compose umbrel -d

I don't have a problem doing the export, but it would be nice to have umbrel startup on boot.

Thanks,
Daniel

**Comment by mayankchhabra** [comment]
> but it would be nice to have umbrel startup on boot.

You can create a systemd service on your VM that does that automatically on boot. Check out our [systemd startup service](https://github.com/getumbrel/umbrel/blob/master/scripts/umbrel-os/services/umbrel-startup.service) that's installed on Umbrel OS by default and runs Umbrel on boot.

**Comment by seljuck** [comment]
I apologize for dragging out this thread, but I'm still having issues.

I've tried editing /etc/hostname to the name I want umbrel to use, umbrel.mydomain.com
I've also tried exporting the DEVICE_HOSTS=umbrel.mydomain.com

Neither of these settings changes the domain name umbrel uses on startup. It always sets it to umbrel.local

I'm doing both of these before running ./scripts/start

Thanks

**Comment by lukechilds** [comment]
Can you share your start script?

**Comment by seljuck** [comment]
Do you mean the umbrel startup script? I'll include it below.

I have not made an additional startup script for the export variable. I'm just manually adding it for testing at the moment.

`#!/usr/bin/env bash
set -euo pipefail

# Start Umbrel

if [[ $UID != 0 ]]; then
    echo "Umbrel must be started as root"
    echo "Please re-run this script as"
    echo "  sudo ./scripts/start"
    exit 1
fi

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      echo "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

# Check system's dependencies
check_dependencies readlink dirname ip docker docker-compose

# Check karen's dependencies
check_dependencies fswatch

# Check OTA update scripts' dependencies
check_dependencies rsync jq curl

UMBREL_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/.."
UMBREL_LOGS="${UMBREL_ROOT}/logs"

if [[ ! -d "$UMBREL_ROOT" ]]; then
  echo "Root dir does not exist '$UMBREL_ROOT'"
  exit 1
fi

# Configure Umbrel if it isn't already configured
if [[ ! -f "${UMBREL_ROOT}/statuses/configured" ]]; then
  NETWORK="${NETWORK:-mainnet}" "${UMBREL_ROOT}/scripts/configure"
fi

echo
echo "======================================"
echo "============= STARTING ==============="
echo "============== UMBREL ================"
echo "======================================"
echo

echo "Setting environment variables..."
echo

# Whitelist device IP, hostname and hidden service for CORS
DEVICE_IP="$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')"
DEVICE_HOSTNAME="$(hostname)"
DEVICE_HOSTS="http://${DEVICE_IP},http://${DEVICE_HOSTNAME}.local,https://${DEVICE_HOSTNAME}.local,http://${DEVICE_HOSTNAME},https://${DEVICE_HOSTNAM>
if [[ -f "${UMBREL_ROOT}/tor/data/web/hostname" ]]; then
    hidden_service_url=$(cat "${UMBREL_ROOT}/tor/data/web/hostname")
    DEVICE_HOSTS="${DEVICE_HOSTS},http://${hidden_service_url}"
fi
export DEVICE_HOSTS=$DEVICE_HOSTS
export DEVICE_HOSTNAME="${DEVICE_HOSTNAME}.local"

# Increase default Docker and Compose timeouts to 240s
# as bitcoin can take a long while to respond
export DOCKER_CLIENT_TIMEOUT=240
export COMPOSE_HTTP_TIMEOUT=240

cd "$UMBREL_ROOT"

echo "Starting karen..."
echo
./karen &>> "${UMBREL_LOGS}/karen.log" &

echo "Starting backup monitor..."
echo
./scripts/backup/monitor &>> "${UMBREL_LOGS}/backup-monitor.log" &

echo "Starting decoy backup trigger..."
echo
./scripts/backup/decoy-trigger &>> "${UMBREL_LOGS}/backup-decoy-trigger.log" &

echo
echo "Starting Docker services..."
echo
docker-compose up --detach --build --remove-orphans
echo

echo "Umbrel is now accessible at"
echo "  http://${DEVICE_HOSTNAME}"
echo "  http://${DEVICE_IP}"
if [[ ! -z "${hidden_service_url:-}" ]]; then
    echo "  http://${hidden_service_url}"
fi`

**Comment by seljuck** [comment]
Just had another detail that might be helpful.
I'm playing around with Sparrow Wallet, and trying to connect it to Umbrel. With the above etc/hostname and exported variables set, I could not connect.

When I reset them to their previous setting, I could get Sparrow to connect to Umbrel.

I'm thinking, maybe the Umbrel Startup Script is just reporting the wrong URL, i.e.  http://umbrel.local

**Comment by seljuck** [comment]
Umbrel is adding .local to any hostname I use.
I'm using the systemd command hostnamectl to change the hostname to

umbrel.mydomain.com

Once umbrel is started it's changing the name to 

umbrel.mydomain.com.local

**Comment by seljuck** [comment]
Everything appears to be working, and I can login using umbrel.mydomain.com. It seems that just the startup script is reporting the wrong URL.

Thank you everyone for the help!
