### ISSUE TITLE
Lost/Forgot Password flow

### ISSUE THREAD

**Issue by walsh2000** [getumbrel/umbrel#327]
Inevitably someone is going to forget their password to the dashboard, or maybe some kind of copy/paste error will set the password to something other than what the owner intends and signing in becomes impossible.

It would be nice if the sign in page had some links to permit resetting the umbrel, either with a set of previously saved 24 seed words, or to create a new wallet from scratch.

I'm sure this poses some security risk with respect to the remote access (especially while this cannot be turned off), but perhaps this could be enabled only for the umbrel.local access point rather than over the tor link.

If it isn't reasonable to add tools to reset/restore the umbrel based upon seed words, perhaps some kind of help text to tell the user how to go about resetting the device without losing/reformatting the hard drive full of the blockchain (if this is possible)

**Comment by mayankchhabra** [comment]
I agree, right now there's no obvious way to reset the dashboard password if you forget it, other than doing a clean install and recovering from your 24 words.

We can't offer the ability to reset password without any sort of authentication (as that would allow anyone on the same network to wipe/reset your Umbrel). However, we could offer the ability to generate a new password as long as you have your seed phrase (as the hashed seed is stored on the device, which we can match against). This would also allow the user to not lose any data, including the synced blockchain, open payment channels, etc — unlike recovering on a fresh install.

**Comment by hashtag-gakusei** [comment]
> I agree, right now there's no obvious way to reset the dashboard password if you forget it, other than doing a clean install and recovering from your 24 words.
> 
> We can't offer the ability to reset password without any sort of authentication (as that would allow anyone on the same network to wipe/reset your Umbrel). However, we could offer the ability to generate a new password as long as you have your seed phrase (as the hashed seed is stored on the device, which we can match against). This would also allow the user to not lose any data, including the synced blockchain, open payment channels, etc — unlike recovering on a fresh install.

Why not create a reset password script for the dashboard that can be ran from bash?

**Comment by AaronDewes** [comment]
> > I agree, right now there's no obvious way to reset the dashboard password if you forget it, other than doing a clean install and recovering from your 24 words.
> > We can't offer the ability to reset password without any sort of authentication (as that would allow anyone on the same network to wipe/reset your Umbrel). However, we could offer the ability to generate a new password as long as you have your seed phrase (as the hashed seed is stored on the device, which we can match against). This would also allow the user to not lose any data, including the synced blockchain, open payment channels, etc — unlike recovering on a fresh install.
> 
> Why not create a reset password script for the dashboard that can be ran from bash?

With the current default SSH password on Umbrel OS everyone on the same net could reset it, and when making that the same as the user password you can't log in to reset it, so it would only help on manual installs

**Comment by nmfretz** [comment]
closing this issue due to points raised above by Mayank and Aaron
