### ISSUE TITLE
User incorrectly registered during a restore attempt with invalid seed

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#335]
![image](https://user-images.githubusercontent.com/10330103/102015637-d7c53300-3d82-11eb-92f1-57b2a9ea1ff4.png)

**Comment by slashbinslashnoname** [comment]
bug still there

**Comment by Adlai-Holler** [comment]
Yeah, extremely annoying bug when trying to start off with Umbrel.

**Comment by nmfretz** [comment]
Closing old resolved issue
