### ISSUE TITLE
electrs hits disk everytime

### ISSUE THREAD

**Issue by olafmarcos** [getumbrel/umbrel#347]
Is this normal that electrs is reading constantly at ~36 MB/s rate?

_Total DISK READ:        38.04 M/s | Total DISK WRITE:         0.00 B/s
Current DISK READ:      38.04 M/s | Current DISK WRITE:      42.75 K/s
TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
1989 be/4 olaf      242.28 K/s    0.00 B/s  0.00 % 99.75 % lnd
2073 be/4 olaf       **37.21 M/s**    0.00 B/s  0.00 % 95.87 % electrs [bulk_read]_

**Comment by olafmarcos** [comment]
Is it possible it is still indexing blockchain?

> sudo docker-compose logs --tail=50 electrs
Attaching to electrs
electrs              | Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Never }, network_type: bitcoin, db_path: "/data/db/mainnet", daemon_dir: "/data/.bitcoin", blocks_dir: "/data/.bitcoin/blocks", daemon_rpc_addr: V4(10.11.1.1:8332), electrum_rpc_addr: V4(0.0.0.0:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 2, tx_cache_size: 10485760, txid_limit: 100, server_banner: "Umbrel v0.2.15", blocktxids_cache_size: 10485760 }
electrs              | DEBUG - Server listening on 127.0.0.1:4224
electrs              | DEBUG - Running accept thread
electrs              | WARN - reconnecting to bitcoind: {"code":-28,"message":"Loading block index..."}
electrs              | WARN - reconnecting to bitcoind: {"code":-28,"message":"Loading block index..."}
electrs              | WARN - reconnecting to bitcoind: {"code":-28,"message":"Verifying blocks..."}
electrs              | WARN - reconnecting to bitcoind: {"code":-28,"message":"Verifying blocks..."}
electrs              | WARN - reconnecting to bitcoind: {"code":-28,"message":"Verifying blocks..."}
electrs              | WARN - reconnecting to bitcoind: {"code":-28,"message":"Verifying blocks..."}
electrs              | INFO - NetworkInfo { version: 200100, subversion: "/Satoshi:0.20.1/", relayfee: 0.00001 }
electrs              | INFO - BlockchainInfo { chain: "main", blocks: 661909, headers: 661909, verificationprogress: 0.99999174400499, bestblockhash: "000000000000000000019f7cfd519e595eeac52fef169f5f37bf0074b26d2a36", pruned: false, initialblockdownload: false }
electrs              | DEBUG - opening DB at "/data/db/mainnet"
electrs              | TRACE - latest indexed blockhash: 000000000000000000034081513af83c620fc974fef1f5d3b4d72476c7755a59
electrs              | DEBUG - applying 661878 new headers from height 0
electrs              | INFO - listing block files at "/data/.bitcoin/blocks/blk*.dat"
electrs              | INFO - indexing 2368 blk*.dat files
electrs              | DEBUG - found 661878 indexed blocks
electrs              | TRACE - downloading 100000 block headers
electrs              | TRACE - downloading 100000 block headers
electrs              | TRACE - downloading 100000 block headers

**Comment by mayankchhabra** [comment]
Hi @olafmarcos! Yes, it looks like Electrs is still creating index, which usually takes 8-16hrs after Bitcoin Core has synched to the tip of the chain. Would recommend checking back in a few hours to confirm.

**Comment by olafmarcos** [comment]
Thanks @mayankchhabra !

Mistery resolved. My electrs was crashing over and over due to lack of space. I guess in the (auto-)compaction process it needs more than double space than it finally occupies:

> electrs              | TRACE - indexed "/data/.bitcoin/blocks/blk02368.dat": 230835 rows
> electrs              | DEBUG - last indexed block: best=00000000000000000003a9441fe23ee7592fad66e5c5e9a985cef8f8e293e62e height=662050 @ 2020-12-19T14:02:10Z
> electrs              | INFO - starting full compaction
> electrs              | INFO - finished full compaction
**> electrs              | INFO - enabling auto-compactions
> electrs              | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "Result incomplete: IO error: No space left on deviceWhile appending t**
> o file: /data/db/mainnet/001066.sst: No space left on device" }', src/libcore/result.rs:1188:5
> electrs              | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> electrs              | TRACE - closing DB at "/data/db/mainnet"
> electrs              | Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Never }, network_type:
>  bitcoin, db_path: "/data/db/mainnet", daemon_dir: "/data/.bitcoin", blocks_dir: "/data/.bitcoin/blocks", daemon_rpc_addr: V4(10.11.1.1:8332), electrum_rpc_addr: V4(0.0.0.0:50001), monitori
> ng_addr: V4(127.0.0.1:4224), jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 2, tx_cache_size: 10485760, txid_limit: 100, server_banner: "Umbrel v0.2.15", blocktxids_cache
> _size: 10485760 }
> electrs              | DEBUG - Server listening on 127.0.0.1:4224
> electrs              | DEBUG - Running accept thread

127 GB Free space for electrs and crashing:

> S.ficheros     Tamaño Usados  Disp Uso% Montado en
> /dev/sdb1        138G   4,5G  **127G**   4% /

Electrs in other drive for it and finally compacted:

> /dev/sdc5        393G    **66G**  308G  18% /discousb2

P.D. May be I will try to move the electrs to the sdb1 partion now that is compacted and it has a lot of space to grow. But i don't know if the compaction process takes every time the electrs is stopped and started....   :S

**Comment by olafmarcos** [comment]
Compacted electrs DB moved and working fine... No more crashes and plenty of disk space:

> /dev/sdb1        138G    70G   62G  54% /

Thanks... Issue closed.
