### ISSUE TITLE
Typo in Connect Wallet URL's

### ISSUE THREAD

**Issue by seljuck** [getumbrel/umbrel#351]
Hello,

I was playing around with various wallets. Any of them that have a single onion URL in Umbrel, have a typo in them.

For example, when selecting Sparrow wallet, a URL similar to this is given

U763cj4hkkqrb23youdr73dzc5n2edlpi4qroazdrxt2hn4k7tplfoq6ad.onion:50001:t

Notice the :t at the end. That appears on every URL offered.

**Comment by louneskmt** [comment]
This is an Electrum connection string. :t for TCP, :s for SSL over TCP.

**Comment by seljuck** [comment]
Noted! Thanks for explaining it.
