### ISSUE TITLE
Allow custom backup server

### ISSUE THREAD

**Issue by searsaw** [getumbrel/umbrel#352]
While digging into the backups stuff, I realized that the backups are sent to an Umbrel server somewhere in AWS. I find it kind of against the Bitcoin ethos to trust someone with backups of my system, even though it appears by looking at the script that lots of measures are taken to keep the backups encrypted and the owner disguised. I'd prefer the ability to configure a custom location for the backups so I can store them somewhere I control instead of a central location not under my control.

**Comment by mayankchhabra** [comment]
Thanks, @searsaw! I understand your concerns, and would really recommend reading [this twitter thread](https://twitter.com/lukechilds/status/1341315501356531712?s=20) from @lukechilds.

Re:
> I'd prefer the ability to configure a custom location for the backups so I can store them somewhere I control instead of a central location not under my control.

Once we get around to implementing disabling of automatic backups, you'll be able to rely on just manual backups and store them wherever you like. The channel backup file is already available for download at Lightning > 3-dot menu on the "Payment Channels" card > Download Channel Backup.
