### ISSUE TITLE
Can't connect to umbrel.local

### ISSUE THREAD

**Issue by GBKS** [getumbrel/umbrel#354]
Umbrel also doesn't show up in Angry IP Scanner. Plugging the Raspberry Pi into my TV shows a lot of [OK] messages and a login prompt, no sign of any errors. What could the issue be? How can I debug? If I need to log in, what are the username and password? Could not find any info here or on Telegram.

Thanks in advance for your help, I'd really like to try out Umbrel.

**Comment by mayankchhabra** [comment]
Hey, @GBKS! Can you please try to SSH into it?

```
ssh umbrel@umbrel.local
```
Password: `moneyprintergobrrr`

Then run the following script to debug and paste the link it outputs at the end:

```
wget https://raw.githubusercontent.com/getumbrel/umbrel/4603b0357ae5f118847787cd8f4032b99e7947da/scripts/debug  -O ~/umbrel/scripts/debug && chmod +x ~/umbrel/scripts/debug && ~/umbrel/scripts/debug --upload
```

If you're unable to SSH in, can you also please make doubly sure that you're on the same network as the Raspberry Pi?

**Comment by GBKS** [comment]
Thanks for the reply. The issue was that I tried to use wi-fi via the recommendation [here](https://github.com/getumbrel/umbrel-os/issues/141). Went to the basement, dug out a network cable, plugged it in and then it worked just fine.

As a person who doesn't understand networking very much, is there a reason why cable would work then wi-fi doesn't? For example, a difference in security models? Or was this just a configuration issue?

And from a user-experience side, would it be possible to indicate at the end of the boot-up sequence whether it could correctly connect to a network? Something like "Umbrel connected to your wi-fi network ABC, but in order to access it from other computers in your network you need to XYZ."

**Comment by louneskmt** [comment]
> Hey, @GBKS! Can you please try to SSH into it?
> 
> 
> 
> ```
> 
> ssh umbrel@umbrel.local
> 
> ```
> 
> Password: `moneyprintergobrrr`
> 
> 
> 
> Then run the following script to debug and paste the link it outputs at the end:
> 
> 
> 
> ```
> 
> wget https://raw.githubusercontent.com/getumbrel/umbrel/4603b0357ae5f118847787cd8f4032b99e7947da/scripts/debug  -O ~/umbrel/scripts/debug && chmod +x ~/umbrel/scripts/debug && ~/umbrel/scripts/debug --upload
> 
> ```
> 
> 
> 
> If you're unable to SSH in, can you also please make doubly sure that you're on the same network as the Raspberry Pi?

The following instructions are no longer accurate since Umbrel version 0.3.0. 

If you read this closed issue looking for a fix, please run this instead of the second command :

```
~/umbrel/scripts/debug --upload
```

**Comment by cvb27** [comment]
Hi @everyone, @mayankchhabra, @louneskmt.

I have exactly the same problem with my Umbrel described for @GBKS:


"Umbrel also doesn't show up in Angry IP Scanner. Plugging the Raspberry Pi into my TV shows a lot of [OK] messages and a login prompt, no sign of any errors. What could the issue be?"


The only difference, it is that this began to happen to me since I changed my internet router for a new one that the internet company sent me.

If someone can help me please I will be very grateful.

Thank you very much in advance.
