### ISSUE TITLE
Loading from USB stick

### ISSUE THREAD

**Issue by Mr-Rog** [getumbrel/umbrel#359]
Hello
since the Raspberry can also load from USB stick I wanted to try this, but without success, I get the message that the disc cannot be mounted, as well as the umbrel service is not started.
Has anyone tried this, I have tried it 10 times, always the same problem.

as soon as I try it with the SD card everything works, however I find USB better than SD card

**Comment by mayankchhabra** [comment]
Sorry, we don't support booting from USB device. Only SD card is supported at the moment.

When you run Umbrel OS, the OS itself runs on the SD card, but Umbrel lives and runs on the external drive. Which means you can also reflash Umbrel OS anytime or switch SD cards, plug in the same external drive, and it'd continue to work from where it left.
