### ISSUE TITLE
Existing Umbrel drive doesn't work with a clean install of Umbrel OS

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#36]
Our [partitioning utility](https://github.com/getumbrel/umbrel/blob/master/contrib/partitioner/partitioner.py) needs to be fixed to support existing Umbrel drives, so even if the user re-flashes Umbrel OS on their SD card, they can continue where they left-off.

**Comment by nolim1t** [comment]
what happens.. it should already not wipe anything unless specified

**Comment by mayankchhabra** [comment]
Yeah you're right, it doesn't wipe the data. But there's still some data loss. Eg. `docker-compose.yml` is stored on the SD card, but when the SD card is re-flashed, it doesn't work with the existing drive.

**Comment by nolim1t** [comment]
I think we'll need to copy the docker-compose file to the drive too

**Comment by mayankchhabra** [comment]
Yeah, but we should perhaps redo some of the logic in the partitioner. Eg. if a user connects a drive with an existing `bitcoin` directory, it still wouldn't work with Umbrel because the RPC credentials in that `bitcoin` directory wouldn't match the ones we generate. 

IMO we should completely nuke the drive in all cases, as long as there is no `.umbrel` file in the drive's root.

**Comment by nolim1t** [comment]
Don't want to nuke the drive by default... that would be mean to make people sync the blockchain again. Especially if someone pays for bandwidth.

**Comment by mayankchhabra** [comment]
I understand, but then we need to a create a foolproof partitioning logic.

It can be something like this (on the first boot):

- Check if the drive is an existing Umbrel drive by looking for a `.umbrel` file in drive's root.
- If yes, don't touch anything on the drive and just setup all the required symlinks.
- If no `.umbrel` file is present, check if it has `bitcoin/blocks` and `bitcoin/chainstate` directories. 
- If not, nuke it.
- If yes, nuke everything other than `bitcoin/blocks` and `bitcoin/chainstate` (as we only need to preserve blockchain data and nothing else).

**Comment by nolim1t** [comment]
Maybe better to check for other data files too and also try to preserve docker-compose

**Comment by nolim1t** [comment]
But I'd rather not put too much install specific stuff inside a compose file to be honest and use config files for each container  instead. 

That way containers are more configurable and we don't have to restart the whole docker-compose when something changes.

**Comment by mayankchhabra** [comment]
> Maybe better to check for other data files too and also try to preserve docker-compose

If we check for `.umbrel` first, we won't have to explicitly check for any other files or directories. We can straightaway assume that it's an Umbrel drive.

However, if there's no `.umbrel` file, then checking for other files or directories isn't helpful. Eg. even if there's an `lnd` directory on the drive with a pre-existing wallet, it's not going to work with Umbrel (because we store the encrypted seed and use the same `lnd` password for `umbrel-dashboard`).

**Comment by nolim1t** [comment]
No need to check for .umbrel, but I have a fix for this

https://github.com/getumbrel/umbrel/pull/54
