### ISSUE TITLE
Shutdown was not Working

### ISSUE THREAD

**Issue by Mr-Rog** [getumbrel/umbrel#362]
I try this for 3 Times, also for Days
Wait to 100% sync, then I use the Shutdown Button on the website umbrel.local, wait, the page say OK remove fro Power.
But when I check on monitor, Raspi was runing.
I try on Raspi command Promt ShutDown,
After I Power ON Again, the Website was not Loding, so I try manualy
umbrel@umbrel:~/umbrel $ sudo ./scripts/start

Error's
Sure I can begin from scratch and wait 3 Days for snyc, but when Shutdown is not working 200% make's no fun
Its a Raspberyy 4 8 GB, 
is it a problem on my side?

Error's
ERROR: for tor  Cannot start service tor: OCI runtime create failed: container_l                                                                                             inux.go:349: starting container process caused "process_linux.go:449: container                                                                                              init caused \"rootfs_linux.go:58: mounting \\\"/home/umbrel/umbrel/tor/torrc\\\"                                                                                              to rootfs \\\"/var/lib/docker/overlay2/6c46b771aba66886e182391d3e1a7095e3c91cd0                                                                                             e5317dced6a43c69664e0c53/merged\\\" at \\\"/var/lib/docker/overlay2/6c46b771aba6                                                                                             6886e182391d3e1a7095e3c91cd0e5317dced6a43c69664e0c53/merged/etc/tor/torrc\\\" ca                                                                                             Starting frontail  ... done
to a file (or vice-versa)? Check if the specified host path exists and is the ex                                                                                             Starting dashboard ... done

ERROR: for tor  Cannot start service tor: OCI runtime create failed: container_l                                                                                             inux.go:349: starting container process caused "process_linux.go:449: container                                                                                              init caused \"rootfs_linux.go:58: mounting \\\"/home/umbrel/umbrel/tor/torrc\\\"                                                                                              to rootfs \\\"/var/lib/docker/overlay2/6c46b771aba66886e182391d3e1a7095e3c91cd0                                                                                             e5317dced6a43c69664e0c53/merged\\\" at \\\"/var/lib/docker/overlay2/6c46b771aba6                                                                                             6886e182391d3e1a7095e3c91cd0e5317dced6a43c69664e0c53/merged/etc/tor/torrc\\\" ca                                                                                             used \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory on                                                                                             to a file (or vice-versa)? Check if the specified host path exists and is the ex                                                                                             pected type

**Comment by Mr-Rog** [comment]
I try
$ sudo ./scripts/stop
and then 
$ sudo ./scripts/start
Looks everithign was starting.

Creating network "umbrel_net" with the default driver
Creating frontail  ... done
Creating tor       ... done
Creating dashboard ... done
Creating manager   ... done
Creating middleware ... done
Creating lnd        ... done
Creating nginx      ... done
Creating bitcoin    ... done
Creating electrs           ... done
Creating neutrino-switcher ... done

Umbrel is now accessible at
http://umbrel.local
but when Im login to the site I see the image and
Loading LND...
for more then 1 hour,?

**Comment by Mr-Rog** [comment]
I get the Feedback start Script on an Raspberry Kills the Installation, so I install again.
But how is the Shutdonw script working

**Comment by mayankchhabra** [comment]
Running start/stop scripts manually on Raspberry Pi isn't recommended, as they can run Umbrel on the SD card instead of SSD/HDD. 

Can you please try to do a clean installation with [Umbrel OS v0.3.0](https://github.com/getumbrel/umbrel-os/releases/tag/v0.3.0) to rule out any existing issues?

If you still face issues, please SSH into your Umbrel and run:

```
~/umbrel/scripts/debug --upload
```

And paste the links it provide.

**Comment by nmfretz** [comment]
Closing old support issue
