### ISSUE TITLE
Can't connect umbrel node with Ledger Live!

### ISSUE THREAD

**Issue by gongyj0948** [getumbrel/umbrel#363]
Hi Team,

I tried to connect umbrel (on a Pi) with a Ledger Live (on a Mac), after entering PRC Username, PRC Password, and Address (Tor with and w/o :8332), it returned this

![Screen Shot 2020-12-27 at 9 12 59 PM](https://user-images.githubusercontent.com/29460794/103185093-da4a8100-4888-11eb-95a9-ef36a08bdde7.png)

is there something I missed?

**Comment by louneskmt** [comment]
Ledger Live and SatStack don't support Tor at the moment. 

A workaround I found is to install the tool called `socat` and bind a local port to the Umbrel onion address. 

Here is the command:
`socat TCP4-LISTEN:8332,reuseaddr,fork SOCKS4A:127.0.0.1:<umbrel-rpc-onion-URL>:8332,socksport=9050`. (Assuming your Tor proxy runs on port 9050)

Then you just have to specify `127.0.0.1:8332` in Ledger Live.

**Comment by gongyj0948** [comment]
Great, Thank you.
