### ISSUE TITLE
Cannot connect to Electrs via Tor

### ISSUE THREAD

**Issue by esackbauer** [getumbrel/umbrel#368]
I was wondering why I cannot connect via Tor to my Electrum node.
It seems docker-compose.yml gets somehow created in a wrong way:

ports:
                  - "50001:50001"
              networks:
                  net:
                      ipv4_address: 10.11.4.0

I guess the .0 IP address is the problem. Happens both with electrs and frontail. The other services have proper IP addresses.

I installed umbrel on a fresh install inside a VM:
Debian 10.7 AMD64
Docker 20.10.1 (via debian repository)
docker-compose 1.27.4
Umbrel 0.2.15

**Comment by lukechilds** [comment]
Apart from the formatting that all looks correct. Are you sure you're connecting through a Tor proxy and that electrs has finished indexing?

**Comment by esackbauer** [comment]
Ok it seems there are no /24 subnets, only one big /16 net, so IPs are fine.

Yes, I can connect with orbot to Tor in general and have selected the Electrum wallet app.
On my Windows desktop, I can connect locally to the port 50001 with the Windows Electrum app and its working.

**Comment by esackbauer** [comment]
Connecting to the web interface via onion address works fine via Tor.
The onion address of the Bitcoin Core node seems to also not work. I have checked access with bitnodes.io, they also support onion addresses.

**Comment by Vilas1979** [comment]
Same problem, conecting to the web interface via onion address works. But node is invisible for bitnodes.io and no success connecting wallets using Bitcon Core P2P or Bisq.

**Comment by louneskmt** [comment]
Are you sure you use a Tor proxy running on your devices? Did you setup a Tor proxy service (with either Homebrew on macOS, Chocolatey on Windows or a normal package manager on Linux)?

You also need to configure your app proxy. For example, in Electrum, you need to go to the "Proxy" tab and enable "Use Tor proxy on port 9050".

**Comment by mayankchhabra** [comment]
Umbrel uses Tor v3 for Bitcoin Core, and both Bitnodes and Bisq support Tor v2, so none of them can connect to your node. This is expected to change after the upcoming Bitcoin Core v0.21.0 release which brings official Tor v3 support.

**Comment by louneskmt** [comment]
Good to know, thanks @mayankchhabra!

**Comment by esackbauer** [comment]
@mayankchhabra Thanks for clarification! 
It seems that Orbot is only using Tor V2 for now, maybe that is the reason:
https://github.com/guardianproject/orbot/pull/415

**Comment by esackbauer** [comment]
Problem solved.  I had in Android general connection setting "Private DNS" activated. This is not working properly with Orbot.
I switched it off, and everything was connecting properly via Orbot.
