### ISSUE TITLE
No out of space warning or message

### ISSUE THREAD

**Issue by greerso** [getumbrel/umbrel#383]
When the 'data' volume runs out of space (as my 512G USB flash drive did) umbrel.local just shows 'loading Bitcoin Core, this can take a while...' instead of letting the user know that they're out of space.

<img width="569" alt="Screen Shot 2020-12-30 at 8 21 45 PM" src="https://user-images.githubusercontent.com/13854262/103395902-6f09e480-4afe-11eb-99be-92237c0a5770.png">

**Comment by mayankchhabra** [comment]
Thanks, @greerso. We've mentioned the disk space requirement on both the [website](https://getumbrel.com/#start), and [Umbrel](https://github.com/getumbrel/umbrel#installation-requirements) and [Umbrel OS](https://github.com/getumbrel/umbrel-os#instructions) repositories. 

The issue will be further mitigated when we add disk usage statistics to the settings page (#325), so I'm closing this issue for the time being.
