### ISSUE TITLE
Add a note on apps that have funds access

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#386]
We should add a note somewhere with high visibility in the app store for apps that have access to the LND wallet, because users may not realize that. It's especially important for new apps that may not have a lot of eyes on their codebase.

**Comment by nmfretz** [comment]
@mayankchhabra does the addition of app dependencies now close this issue? Or would you like to keep this open?
![image](https://github.com/getumbrel/umbrel/assets/85373263/23ab70c8-bc78-4b4d-97de-1451235c7198)

**Comment by mayankchhabra** [comment]
It sure does!
