### ISSUE TITLE
Links in Lit App initial Tour

### ISSUE THREAD

**Issue by olafmarcos** [getumbrel/umbrel#389]
In the first slide, the WALKTHROUGH link fails. The correct one is: https://github.com/lightninglabs/lightning-terminal/blob/master/doc/WALKTHROUGH.md

**Comment by mayankchhabra** [comment]
Thanks for reporting this, @olafmarcos! Would you please be able to open this issue on the [LiT repository](https://github.com/lightninglabs/lightning-terminal) instead?

cc @guggero

**Comment by olafmarcos** [comment]
Done!
