### ISSUE TITLE
not allowd by CORS when logging in on public domain

### ISSUE THREAD

**Issue by grmkris** [getumbrel/umbrel#398]
For easier demoing to others I decided to host umbrel on a vps.  
The vps itself is managed by plesk and is running centos.  

I managed to setup and sucessfully run umbrel. I also connected to it via public address (umbrel.payserver.org)
When trying to login with a password I get the following error:   

```
umbrel-manager
Not allowed by CORS
/v1/account/login
Error: Not allowed by CORS
    at origin (/app/middlewares/cors.js:14:23)
    at /app/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/app/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/app/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
```

**Comment by AaronDewes** [comment]
To run Umbrel on a custom domain, change Line 57 of scripts/start to include your custom domain

**Comment by grmkris** [comment]
I did that.. I changed that to:
`DEVICE_HOSTS="http://${DEVICE_IP},http://${DEVICE_HOSTNAME}.local,https://${DEVICE_HOSTNAME}.local,http://${DEVICE_HOSTNAME},https://${DEVICE_HOSTNAME}"`  

`DEVICE_HOSTS="http://${DEVICE_IP},http://${DEVICE_HOSTNAME}.local,https://${DEVICE_HOSTNAME}.local,http://${DEVICE_HOSTNAME},https://${DEVICE_HOSTNAME},https//umbrel.payserver.org/,umbrel.payserver.org"`

**Comment by grmkris** [comment]
This is the ouput if I exec into docker container (umbrel manager)
`http://95.111.230.23,http://vmi379479.contaboserver.net.local,https://vmi379479.contaboserver.net.local,http://vmi379479.contaboserver.net,https://vmi379479.contaboserver.net,https//umbrel.payserver.org,umbrel.payserver.org,http://iklh767cjiqpnnht5mlyyqbib6xhopu3dqf7zjdczsdfujy7t5njhjyd.onion`

How could I debug or change to logic of cors funtion? without rebuilding a docker image and redeploying ?

**Comment by grmkris** [comment]
Hello... yeah I just noticed this. I am so sorry for wasting your time..  
I was already debugging the container and starting / restarting it... when I noticed the missing `:`...

Website is up and running :D can't wait to start using it

**Comment by louneskmt** [comment]
No worries 😁

**Comment by maciozo** [comment]
Apologies for hijacking, but I had a similar issue where CORS would reject if nginx was configured to run on a different port. I configured mine listen on 81 instead of 80.

Adding `http://${DEVICE_IP}:81` etc. to line 57 solved the problem.

Just posting in case anyone else runs in to trouble running on a different port.

**Comment by phenomeus** [comment]
`sudo nano ~/umbrel/scripts/start`

`CTRL+_` > 57

I added this: 
`DEVICE_PORT=8000` (your desired nginx port you edited in docker-composer.yml, I know, its hardcoded and the team is already working on .env, it will be obsolete soon)

and edited the line underneath to this: 
`DEVICE_HOSTS="http://${DEVICE_IP}:{DEVICE_PORT},http://${DEVICE_HOSTNAME}:{DEVICE_PORT}.local,https://${DEVICE_HOSTNAME}.local:{DEVICE_PORT},http://${DEVICE_HOSTNAME}:{DEVICE_PORT},https://${DEVICE_HOSTNAME}:{DEVICE_PORT}"`

save, and stop & restart with `sudo ./start`

**Comment by phenomeus** [comment]
update for version 0.3.4.

`sudo nano ~/umbrel/scripts/start`

`CTRL+_ > Line 57`

`CTRL+K` to delete Line 57

paste this, i changed it to port 8000 also in '~/umbrel/docker-compose.yml' on line 33 '8000:80'

`DEVICE_PORT="8000"
DEVICE_HOSTS="http://${DEVICE_IP}:${DEVICE_PORT},http://${DEVICE_HOSTNAME}.local:${DEVICE_PORT},https://${DEVICE_HOSTNAME}.local:${DEVICE_PORT},http://${DEVICE_HOSTNAME}:${DEVICE_PORT},https://${DEVICE_HOSTNAME}:${DEVICE_PORT}"`

**Comment by wouterds** [comment]
can't get it working even with above workarounds

**Comment by phenomeus** [comment]
after update to 0.38 I can login at port :8000 (also in .env) but I can't get to show the details, the umbrel version number or tor address (there is only a false) 

by connecting with onion address everything is fine. the node is working, its just the port change that's still buggy

**Comment by louneskmt** [comment]
I'll work on fix in the next couple of days @Minituff

**Comment by phenomeus** [comment]
that would be very helpful @louneskmt

**Comment by GorkaMM** [comment]
Any updates on this? I would love to have this configurable in the GUI too 😄
