### ISSUE TITLE
Make BTCPayServer work with https

### ISSUE THREAD

**Issue by jorge-lavin** [getumbrel/umbrel#406]
I want to be able to use the DynamicDNS feature along with https when providing access (via internet not Tor) to the BTCPayServer running along umbrel

- https://github.com/btcpayserver/btcpayserver-docker/blob/master/Production/README.md
- https://docs.btcpayserver.org/DynamicDNS/#step-3-configure-your-btcpay-docker-install-to-provide-https-certificates

**Comment by maltokyo** [comment]
Best way to do this would be to put a reverse proxy in front of any service that you would like to open on a normal https (not tor) connection.  I can recommend https://github.com/jc21/nginx-proxy-manager

**Comment by nocode23** [comment]
> Best way to do this would be to put a reverse proxy in front of any service that you would like to open on a normal https (not tor) connection. I can recommend https://github.com/jc21/nginx-proxy-manager

Is there any step by step instruction how to do this on umbrel?

**Comment by nmfretz** [comment]
I think this might be the best guide available at present: https://jorijn.com/installing-nginx-reverse-proxy-with-ssl-certificate-umbrel-btcpayserver/
