### ISSUE TITLE
Recovering from another LND node: what is my password?

### ISSUE THREAD

**Issue by fiatjaf** [getumbrel/umbrel#407]
I've installed a fresh Umbrel on a Raspberry Pi and setup a password, then I imported my LND files from another node I had by SSHing into the device.

Now when Umbrel asks for my password nothing works: should I be using the new Umbrel password or my password from the old LND here? OR something else? Is it possible to change it manually from SSH?

**Comment by lukechilds** [comment]
You can't copy the LND files from an existing node over your Umbrel install. Umbrel sets up LND in a specific way that is integrated with the rest of the system.

If you want to migrate funds from an existing install you should close any open channels on your old wallet and send the total resulting on-chain balance over to your Umbrel wallet and then re-open the channels.

**Comment by fiatjaf** [comment]
That's not true, it's possible and relatively simple to replace the global Umbrel seed -- or even just the LND password + Umbrel seed encryption key (they're expected to be the same) -- from SSH.
