### ISSUE TITLE
spector desktop can't use tor: error returned: 'NoneType' object has no attribute 'reconnect'

### ISSUE THREAD

**Issue by lvnilesh** [getumbrel/umbrel#411]
Setup umbrel

Visit bitcoin page. 

Notice tor is 100% working.

Open Specter Desktop.

See upper right corner notice 
```
tor service is down.
start tor
```
Click the `start tor` button

Get this error.
``` 
Failed to start Tor hidden service.Make sure you have Tor running with ControlPort configured and try again.

Error returned: 'NoneType' object has no attribute 'reconnect'
```

**Comment by louneskmt** [comment]
Hey!

You don't need to enable this option. It's an internal setting to create a Specter server, which is already done by Umbrel. You can use Specter without enabling this. 

I know it's not very clear but we cannot really do something about that as it is part of the Specter app.
