### ISSUE TITLE
Allow for torv2 addresses as well

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel#415]
In light of the recent attack on tor, we need to also allow for v2 address as a fallback as now most Umbrel nodes are now unreachable.

**Comment by AaronDewes** [comment]
There is already a fix in development in tor, which I think will be merged soon because this issue is (at least in my opinion, but I think for others too) quite important, https://gitlab.torproject.org/tpo/core/tor/-/issues/40237
