### ISSUE TITLE
I can connect to the Raspberry Pi but not to umbrel.local

### ISSUE THREAD

**Issue by romain-durand** [getumbrel/umbrel#417]
Hello team,

I've tried to setup my Rasberry Pi following the install guide. After having plugged to my router I was not seing the Rasberry (even with Angry IP scanner).
 I then tried to use WiFi instead ethernet, by putting the supplicant in the root of the SD card. Now, I can see the Rasberry, but impossible to connect to umbrel.local or directly to the IP address in a browser.

I can ping the Rasberry, and even SSH into it.

Using your advice given in issue #354, here is my log below.

Any help would be greatly appreciated,
Thanks,
Romain
 
umbrel@umbrel:~ $ wget https://raw.githubusercontent.com/getumbrel/umbrel/4603b0357ae5f118847787cd8f4032b99e7947da/scripts/debug  -O ~/umbrel/scripts/debug && chmod +x ~/umbrel/scripts/debug && ~/umbrel/scripts/debug --upload
--2021-01-12 22:30:18--  https://raw.githubusercontent.com/getumbrel/umbrel/4603b0357ae5f118847787cd8f4032b99e7947da/scripts/debug
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6658 (6.5K) [text/plain]
Saving to: ‘/home/umbrel/umbrel/scripts/debug’

/home/umbrel/umbrel/scripts 100%[==========================================>]   6.50K  --.-KB/s    in 0.001s  

2021-01-12 22:30:18 (4.72 MB/s) - ‘/home/umbrel/umbrel/scripts/debug’ saved [6658/6658]

=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.3.1

Umbrel OS version
-----------------
v0.3.1

Raspberry Pi Model
------------------
Revision	: c03112
Serial		: 10000000560e3e11
Model		: Raspberry Pi 4 Model B Rev 1.2

Firmware
--------
Nov 30 2020 22:12:08 
Copyright (c) 2012 Broadcom
version ab1181cc0cb6df52bfae3b1d3fef0ce7c325166c (clean) (release) (start)

Temperature
-----------
temp=42.3'C

Throttling
----------
throttled=0x0

Startup service logs
--------------------
-- Logs begin at Tue 2021-01-12 11:17:02 UTC, end at Tue 2021-01-12 22:28:22 UTC. --
-- No entries --

External storage service logs
-----------------------------
-- Logs begin at Tue 2021-01-12 11:17:02 UTC, end at Tue 2021-01-12 22:28:22 UTC. --
Jan 12 21:54:40 umbrel systemd[1]: Starting External Storage Mounter...
Jan 12 21:54:40 umbrel external storage mounter[328]: Running external storage mount script...
Jan 12 21:54:40 umbrel external storage mounter[328]: Found device "TOSHIBA External USB 3.0"
Jan 12 21:54:40 umbrel external storage mounter[328]: Checking if the device is ext4...
Jan 12 21:54:40 umbrel external storage mounter[328]: Yes, it is ext4
Jan 12 21:54:48 umbrel external storage mounter[328]: Checking if device contains an Umbrel install...
Jan 12 21:54:48 umbrel external storage mounter[328]: Yes, it contains an Umbrel install
Jan 12 21:54:48 umbrel external storage mounter[328]: Bind mounting external storage over local Umbrel installation...
Jan 12 21:54:48 umbrel external storage mounter[328]: Bind mounting external storage to /swap
Jan 12 21:54:48 umbrel external storage mounter[328]: Bind mounting SD card root at /sd-card...
Jan 12 21:54:48 umbrel external storage mounter[328]: Checking Umbrel root is now on external storage...
Jan 12 21:54:49 umbrel external storage mounter[328]: Checking /swap is now on external storage...
Jan 12 21:54:49 umbrel external storage mounter[328]: Setting up swapfile
Jan 12 21:54:49 umbrel external storage mounter[328]: Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
Jan 12 21:54:49 umbrel external storage mounter[328]: no label, UUID=4c82b3b6-3eab-434d-b0f4-3d60287e2a9e
Jan 12 21:54:50 umbrel external storage mounter[328]: Checking SD Card root is bind mounted at /sd-root...
Jan 12 21:54:50 umbrel external storage mounter[328]: Starting external drive mount monitor...
Jan 12 21:54:50 umbrel external storage mounter[328]: Mount script completed successfully!
Jan 12 21:54:50 umbrel external storage mounter[524]: Checking if SD card Umbrel is newer than external storage...
Jan 12 21:54:50 umbrel external storage mounter[524]: No, SD version is not newer, exiting.
Jan 12 21:54:50 umbrel systemd[1]: Started External Storage Mounter.

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        59G  3.4G   53G   7% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  8.5M  1.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M  155M   98M  62% /boot
/dev/sda1       916G   13G  858G   2% /mnt/data
tmpfs           380M     0  380M   0% /run/user/1000

Filename				Type		Size	Used	Priority
/swap/swapfile                          file		4194300	0	-2

Networking information
----------------------

eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet x.x.x.x  netmask x.x.x.x
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8  bytes 864 (864.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 864 (864.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask x.x.x.x  broadcast x.x.x.x
        inet6 y::y.y.y.y  prefixlen 64  scopeid 0x20<link>
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 1000  bytes 275592 (269.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 361  bytes 58281 (56.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Docker containers
-----------------

**Comment by AaronDewes** [comment]
Never do that! If you run the debug script like this on newer version of Umbrel, you just overwrite the newer version of that script that already exists in Umbrel. Run this to fix that:
```
wget https://raw.githubusercontent.com/getumbrel/umbrel/master/scripts/debug -O ~/umbrel/scripts/debug && chmod +x ~/umbrel/scripts/debug && ~/umbrel/scripts/debug --upload
```

And in the future, just run this on Umbrel v0.3.0 or newer

```
~/umbrel/scripts/debug --upload
```

**Comment by AaronDewes** [comment]
This script will tell you what to do next.

**Comment by romain-durand** [comment]
Thanks for your quick answer :-)

So I ran the command that you provided to fix (see logs below)

What should I do next ? (maybe it would be easier to restart from the start, reflashing the SD card ?)


umbrel@umbrel:~ $ wget https://raw.githubusercontent.com/getumbrel/umbrel/master/scripts/debug -O ~/umbrel/scripts/debug && chmod +x ~/umbrel/scripts/debug && ~/umbrel/scripts/debug --upload
--2021-01-13 08:31:08--  https://raw.githubusercontent.com/getumbrel/umbrel/master/scripts/debug
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.120.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.120.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6423 (6.3K) [text/plain]
Saving to: ‘/home/umbrel/umbrel/scripts/debug’

/home/umbrel/umbrel/scripts 100%[==========================================>]   6.27K  --.-KB/s    in 0.001s  

2021-01-13 08:31:09 (5.90 MB/s) - ‘/home/umbrel/umbrel/scripts/debug’ saved [6423/6423]

=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.3.1

Umbrel OS version
-----------------
v0.3.1

Raspberry Pi Model
------------------
Revision	: c03112
Serial		: 10000000560e3e11
Model		: Raspberry Pi 4 Model B Rev 1.2

Firmware
--------
Nov 30 2020 22:12:08 
Copyright (c) 2012 Broadcom
version ab1181cc0cb6df52bfae3b1d3fef0ce7c325166c (clean) (release) (start)

Temperature
-----------
temp=43.8'C

Throttling
----------
throttled=0x0

Startup service logs
--------------------
-- Logs begin at Tue 2021-01-12 23:17:01 UTC, end at Wed 2021-01-13 08:30:47 UTC. --
-- No entries --

External storage service logs
-----------------------------
-- Logs begin at Tue 2021-01-12 23:17:01 UTC, end at Wed 2021-01-13 08:30:47 UTC. --
Jan 12 23:52:40 umbrel systemd[1]: Starting External Storage Mounter...
Jan 12 23:52:40 umbrel external storage mounter[345]: Running external storage mount script...
Jan 12 23:52:40 umbrel external storage mounter[345]: Found device "TOSHIBA External USB 3.0"
Jan 12 23:52:40 umbrel external storage mounter[345]: Checking if the device is ext4...
Jan 12 23:52:40 umbrel external storage mounter[345]: Yes, it is ext4
Jan 12 23:52:41 umbrel external storage mounter[345]: Checking if device contains an Umbrel install...
Jan 12 23:52:41 umbrel external storage mounter[345]: Yes, it contains an Umbrel install
Jan 12 23:52:41 umbrel external storage mounter[345]: Bind mounting external storage over local Umbrel installation...
Jan 12 23:52:41 umbrel external storage mounter[345]: Bind mounting external storage to /swap
Jan 12 23:52:41 umbrel external storage mounter[345]: Bind mounting SD card root at /sd-card...
Jan 12 23:52:41 umbrel external storage mounter[345]: Checking Umbrel root is now on external storage...
Jan 12 23:52:42 umbrel external storage mounter[345]: Checking /swap is now on external storage...
Jan 12 23:52:42 umbrel external storage mounter[345]: Setting up swapfile
Jan 12 23:52:42 umbrel external storage mounter[345]: Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
Jan 12 23:52:42 umbrel external storage mounter[345]: no label, UUID=62a09c2d-7879-4d3c-b68d-895070d0cd05
Jan 12 23:52:43 umbrel external storage mounter[345]: Checking SD Card root is bind mounted at /sd-root...
Jan 12 23:52:43 umbrel external storage mounter[345]: Starting external drive mount monitor...
Jan 12 23:52:43 umbrel external storage mounter[345]: Mount script completed successfully!
Jan 12 23:52:43 umbrel external storage mounter[481]: Checking if SD card Umbrel is newer than external storage...
Jan 12 23:52:43 umbrel external storage mounter[481]: No, SD version is not newer, exiting.
Jan 12 23:52:43 umbrel systemd[1]: Started External Storage Mounter.

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        59G  3.4G   53G   7% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  8.5M  1.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M  155M   98M  62% /boot
/dev/sda1       916G   13G  858G   2% /mnt/data
tmpfs           380M     0  380M   0% /run/user/1000

Filename				Type		Size	Used	Priority
/swap/swapfile                          file		4194300	0	-2

Karen logs
----------

karen is running in /home/umbrel/umbrel/events

Docker containers
-----------------

^C
umbrel@umbrel:~ $ 
umbrel@umbrel:~ $ ~/umbrel/scripts/debug --upload
=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.3.1

Umbrel OS version
-----------------
v0.3.1

Raspberry Pi Model
------------------
Revision	: c03112
Serial		: 10000000560e3e11
Model		: Raspberry Pi 4 Model B Rev 1.2

Firmware
--------
Nov 30 2020 22:12:08 
Copyright (c) 2012 Broadcom
version ab1181cc0cb6df52bfae3b1d3fef0ce7c325166c (clean) (release) (start)

Temperature
-----------
temp=43.8'C

Throttling
----------
throttled=0x0

Startup service logs
--------------------
-- Logs begin at Tue 2021-01-12 23:17:01 UTC, end at Wed 2021-01-13 08:30:47 UTC. --
-- No entries --

External storage service logs
-----------------------------
-- Logs begin at Tue 2021-01-12 23:17:01 UTC, end at Wed 2021-01-13 08:30:47 UTC. --
Jan 12 23:52:40 umbrel systemd[1]: Starting External Storage Mounter...
Jan 12 23:52:40 umbrel external storage mounter[345]: Running external storage mount script...
Jan 12 23:52:40 umbrel external storage mounter[345]: Found device "TOSHIBA External USB 3.0"
Jan 12 23:52:40 umbrel external storage mounter[345]: Checking if the device is ext4...
Jan 12 23:52:40 umbrel external storage mounter[345]: Yes, it is ext4
Jan 12 23:52:41 umbrel external storage mounter[345]: Checking if device contains an Umbrel install...
Jan 12 23:52:41 umbrel external storage mounter[345]: Yes, it contains an Umbrel install
Jan 12 23:52:41 umbrel external storage mounter[345]: Bind mounting external storage over local Umbrel installation...
Jan 12 23:52:41 umbrel external storage mounter[345]: Bind mounting external storage to /swap
Jan 12 23:52:41 umbrel external storage mounter[345]: Bind mounting SD card root at /sd-card...
Jan 12 23:52:41 umbrel external storage mounter[345]: Checking Umbrel root is now on external storage...
Jan 12 23:52:42 umbrel external storage mounter[345]: Checking /swap is now on external storage...
Jan 12 23:52:42 umbrel external storage mounter[345]: Setting up swapfile
Jan 12 23:52:42 umbrel external storage mounter[345]: Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
Jan 12 23:52:42 umbrel external storage mounter[345]: no label, UUID=62a09c2d-7879-4d3c-b68d-895070d0cd05
Jan 12 23:52:43 umbrel external storage mounter[345]: Checking SD Card root is bind mounted at /sd-root...
Jan 12 23:52:43 umbrel external storage mounter[345]: Starting external drive mount monitor...
Jan 12 23:52:43 umbrel external storage mounter[345]: Mount script completed successfully!
Jan 12 23:52:43 umbrel external storage mounter[481]: Checking if SD card Umbrel is newer than external storage...
Jan 12 23:52:43 umbrel external storage mounter[481]: No, SD version is not newer, exiting.
Jan 12 23:52:43 umbrel systemd[1]: Started External Storage Mounter.

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        59G  3.4G   53G   7% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  8.5M  1.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M  155M   98M  62% /boot
/dev/sda1       916G   13G  858G   2% /mnt/data
tmpfs           380M     0  380M   0% /run/user/1000

Filename				Type		Size	Used	Priority
/swap/swapfile                          file		4194300	0	-2

Karen logs
----------

karen is running in /home/umbrel/umbrel/events

Docker containers
-----------------

**Comment by romain-durand** [comment]
Update: finally I reinstalled everything and it was working fine (uploaded to latest umbrel version being 0.3.2)

But there is still a strange behavior: I'm switching off the rasberry every night. When I switch it on every morning the rasberry is no more visible on my local network (no IP detected via Angry IP, no umbrel.local accessible). But still the service is running as I can access it via Thor ! So from the umbrell interface via Thor I need to instruct a restart, and after the restart I can now see again the raspberry and umbrel.local on my local network.
I feel like something maybe missing in the boot of raspberry (swich off/on electrically does not seem to reboot everything)

**Comment by AaronDewes** [comment]
> Update: finally I reinstalled everything and it was working fine (uploaded to latest umbrel version being 0.3.2)
> 
> But there is still a strange behavior: I'm switching off the rasberry every night. When I switch it on every morning the rasberry is no more visible on my local network (no IP detected via Angry IP, no umbrel.local accessible). But still the service is running as I can access it via Thor ! So from the umbrell interface via Thor I need to instruct a restart, and after the restart I can now see again the raspberry and umbrel.local on my local network.
> I feel like something maybe missing in the boot of raspberry (swich off/on electrically does not seem to reboot everything)

Because you should turn the Pi off over the Dashboard and wait a few minutes before unplugging it.

**Comment by romain-durand** [comment]
OK will do. But power is sometimes switched off without prior notice.
 
Thanks for support
