### ISSUE TITLE
add c-lightning (to support Fully Noded LN wallet)

### ISSUE THREAD

**Issue by josibake** [getumbrel/umbrel#418]
Hey all, any interest in supporting c-lightning or adding it as an installable app? I ask because FullyNoded only supports c-lighting as of right now, but is a fantastic wallet that allows me to connect to my full node over Tor. I'd love to be able to use the lightning wallet with umbrel, but as umbrel is using LND, this doesn't seem possible.

Happy to hear any suggestions on how to make this work in case I'm missing something.

**Comment by nolim1t** [comment]
You can start by taking a look at [this project](https://gitlab.com/nolim1t/docker-clightning) .. I've bundled all the legwork to make it work with FullyNoded.

**Comment by nolim1t** [comment]
I can assist you with any changes to make it compatible with the Umbrel app framework but right now its not on my radar to actually add it on there for now.

**Comment by nmfretz** [comment]
Closing this old issue. There is a Core Lightning app on Umbrel! https://apps.umbrel.com/app/core-lightning
