### ISSUE TITLE
Cannot install apps from Store on New Installation on Ubuntu with Docker

### ISSUE THREAD

**Issue by dfriestedt** [getumbrel/umbrel#419]
One of my umbrel installs is having an issue.  I've installed on docker on a ubuntu machine.  When trying to install the various applications, I can click the install button, they flash installing for a very long time - 10 minutes or so, and finally time out.  The app is not installed and the "installing" button goes back to "Install".  And the app never gets installed.  

I've reported this issue in Telegram, but that channel seems to fill up with random stuff so I'm posting here in duplicate.  

Results for ~/umbrel/scripts/debug --upload 

https://hastebin.com/siburaralo

**Comment by mayankchhabra** [comment]
Can you please try restarting Umbrel?

```
sudo scripts/stop && sudo scripts/start
```

Then try to install an app and see if it works this time.

**Comment by dfriestedt** [comment]
I tried to reboot as instructed and was unable to install any application.  The same behavior persists.

**Comment by dfriestedt** [comment]
I ended up wiping the server and reinstalling.  Apps work fine now.
