### ISSUE TITLE
2nd time I have lost all the contents of the blockchain after a restart

### ISSUE THREAD

**Issue by CrankITKomo** [getumbrel/umbrel#420]
On 2 separate occasions, after a restart ( using the Restart option on the Umbrel dashboard) - I have lost the entire contents of the blockchain and it has reverted back to starting all over again.  In both instances, I was close to 95% complete.  

Here is a link to the most recent log that I have - https://hastebin.com/isofopoyor

This has been a rather frustrating experience, so close yet so far away.

Any assistance greatly appreciated.

**Comment by mayankchhabra** [comment]
Sorry about that, it's reindexing the chain instead of re-downloading it. Can you confirm if you have `reindex=1` in `~/umbrel/bitcoin/bitcoin.conf` file? 

If so, I recommend removing that option and then trying a restart again.

**Comment by nmfretz** [comment]
closing old support issue
