### ISSUE TITLE
Show ZPUB for View Only Wallet

### ISSUE THREAD

**Issue by chitowncrispy** [getumbrel/umbrel#426]
A nice feature to add would be the ability to view a node's ZPUB so that way users can create view only wallets in a comprehensive way.

**Comment by nolim1t** [comment]
The bitcoin wallet uses [LND](https://github.com/lightningnetwork/lnd/) special implementation. It can only be recovered in LND implementations and not in electrum so the zpub will not work.

**Comment by steve-vincent** [comment]
@nolim1t  is there a way to list or export addresses though?

I've got a bad problem... I need to recover a previous address generated, to deal with a disputed transaction with merchant.

The Umbrel bitcoin wallet shows a recieve address when clicking "Deposit". I gave it to merchant but didnt write it down, now I nees to retrieve it to deal with their support.

In electrum or bitcoin wallets you can view addresses. Please help if there's any way to do this with Umbrel or LND

**Comment by nolim1t** [comment]
Nope they can only be recovered through the LND implementation

**Comment by steve-vincent** [comment]
I was trying ssh "docker exec lnd lncli help"... and yes, looks like no dumpaddresses or similar can be found in LND.

Seems an important for LND to add in the future. It's over my head, but [ this project](https://github.com/guggero/chantools/blob/master/doc/chantools_walletinfo.md) might be trying to address similar problem.

**Comment by nolim1t** [comment]
Take a look at [this doc](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md)

You might want to recover it from your own desktop.

If you have any channels open, you can ask the umbrel guys to get you your  backup.

**Comment by nolim1t** [comment]
You can now recover LND (which include) umbrel seeds with Bluewallet.

**Comment by steve-vincent** [comment]
thanks. good to know... and I realize this is just for the bitcoin balance, not the channels of course.
