### ISSUE TITLE
Custom Raspberry Pi OS install | getumbrel/frontail ERROR: no matching manifest for linux/arm/v7

### ISSUE THREAD

**Issue by marsmensch** [getumbrel/umbrel#431]
Not sure if this belongs to the getumbrel/frontail repo or directly here, i am sorry if i picked the wrong one ;-)

```
Pulling frontail (getumbrel/frontail:v4.9.1)...
v4.9.1: Pulling from getumbrel/frontail
e41e28500352: Pull complete
73f8740e5804: Pull complete
10d537cfeb6f: Pull complete
57ecaf4ff3c8: Pull complete
b52b143c66b2: Pull complete
d1d3cf432ddb: Pull complete
b3ca2b832205: Pull complete
91179e4134c9: Pull complete
Digest: sha256:9fa345b7a947361e2732909db8bd316b8157749d7dd9949abd8150eb023906db
Status: Downloaded newer image for getumbrel/frontail:v4.9.1
Pulling electrs (getumbrel/electrs:v0.8.6)...
v0.8.6: Pulling from getumbrel/electrs

```
**ERROR: no matching manifest for linux/arm/v7 in the manifest list entries**

```
$ uname -r
5.4.83-v7l+
```

**Comment by AaronDewes** [comment]
Umbrel only supports the 64bit version of RPi OS.

**Comment by AaronDewes** [comment]
Also, this issue is with electrs, where there are no arm64 builds provided by Umbrel, not frontail

**Comment by dolcalmi** [comment]
you can change docker-compose.yml to use github repo... will take a while (rust compilation) but it works.

```
...
electrs:
              container_name: electrs
              build: https://github.com/getumbrel/docker-electrs.git
              volumes:
...
```

**Comment by ChowSinWon** [comment]
i had the same problem with dashboard... also needed building the docker image using github repo:
```
...
        dashboard:
                container_name: dashboard
                build: https://github.com/getumbrel/umbrel-dashboard.git
                restart: on-failure
...
```

**Comment by AaronDewes** [comment]
Are you to using the classic raspberry Pi OS? Please just use the arm64 version in that case instead of spamming here.

**Comment by ChowSinWon** [comment]
sorry if this is considered spamming.
i just wanted to state what i had to do so that it worked for me.
(`uname -m` states `aarch64`)

**Comment by AaronDewes** [comment]
In that case, it is very likely a bug. Can you confirm Debian is arm64 too by running `dpkg --print-architechture`?

**Comment by ChowSinWon** [comment]
no, you are correct:
```
dpkg --print-architecture
armhf
```
seems that just running `rpi-update` and setting 64bit in boot config is not enough. my bad.
but at least i got it running that way. now i wonder what would happen if i added the correct architecture to dpkg and updated everything... would it break?

**Comment by AaronDewes** [comment]
You needed to change apt sources and do a complicated migration with lots of opportunities to break, so reflashing is the better option (Or just running as it is now, but armhf isn't fully supported so there could be issues)

**Comment by ChowSinWon** [comment]
i see. thank you.

**Comment by nmfretz** [comment]
closing resolved issue
