### ISSUE TITLE
After restart Umbrel is no longer start

### ISSUE THREAD

**Issue by syntax66** [getumbrel/umbrel#433]
Hello, 

I have problem with my umbrel config. After server restart umbrel isn't running.

> ======================================
> ============= STARTING ===============
> ============== UMBREL ================
> ======================================
> 
> Setting environment variables...
> 
> Starting karen...
> 
> Starting backup monitor...
> 
> Starting decoy backup trigger...
> 
> 
> Starting Docker services...
> 
> WARNING: The TOR_PROXY_PORT variable is not set. Defaulting to a blank string.
> WARNING: The TOR_PROXY_IP variable is not set. Defaulting to a blank string.
> WARNING: The NGINX_IP variable is not set. Defaulting to a blank string.
> WARNING: The BITCOIN_P2P_PORT variable is not set. Defaulting to a blank string.
> WARNING: The BITCOIN_IP variable is not set. Defaulting to a blank string.
> WARNING: The LND_REST_PORT variable is not set. Defaulting to a blank string.
> WARNING: The LND_GRPC_PORT variable is not set. Defaulting to a blank string.
> WARNING: The LND_IP variable is not set. Defaulting to a blank string.
> WARNING: The DASHBOARD_IP variable is not set. Defaulting to a blank string.
> WARNING: The MIDDLEWARE_IP variable is not set. Defaulting to a blank string.
> WARNING: The BITCOIN_RPC_PORT variable is not set. Defaulting to a blank string.
> WARNING: The BITCOIN_RPC_USER variable is not set. Defaulting to a blank string.
> WARNING: The BITCOIN_RPC_PASS variable is not set. Defaulting to a blank string.
> WARNING: The BITCOIN_NETWORK variable is not set. Defaulting to a blank string.
> WARNING: The MANAGER_IP variable is not set. Defaulting to a blank string.
> WARNING: The NEUTRINO_SWITCHER_IP variable is not set. Defaulting to a blank string.
> WARNING: The FRONTAIL_IP variable is not set. Defaulting to a blank string.
> WARNING: The ELECTRUM_PORT variable is not set. Defaulting to a blank string.
> WARNING: The ELECTRUM_IP variable is not set. Defaulting to a blank string.
> WARNING: The NETWORK_IP variable is not set. Defaulting to a blank string.
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> networks.default.ipam.config.subnet is invalid: should use the CIDR format
> services.tor.ports contains an invalid type, it should be a number, or an object
> services.bitcoin.ports contains an invalid type, it should be a number, or an object
> services.electrs.ports contains an invalid type, it should be a number, or an object
> services.lnd.ports contains an invalid type, it should be a number, or an object
> services.lnd.ports contains an invalid type, it should be a number, or an object
> services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements

**Comment by josephtyler** [comment]
I'm getting the same issue here: `The Compose file './docker-compose.yml' is invalid because:` with the same issues. It looks like the environment variables that docker-compose.yml is consuming might not be set.
