### ISSUE TITLE
Warn users of privacy tradeoff before allowing them to follow public block explorer links via clearnet

### ISSUE THREAD

**Issue by lukechilds** [getumbrel/umbrel#435]
Currently when clicking a link in the users transaction history we display their transaction on a public block explorer.

This is fine when accessing Umbrel over Tor since there is no IP leakage but when accessing Umbrel over the local network the public explorer will be viewed in the user's clearnet web browser and will expose the IP<>TXID link to the public block explorer.

We had already planned to replace the link to public block explorers with a link to a self hosted explorer when an explorer app is installed on Umbrel. However for users who do not have an explorer app installed and are accessing via umbrel.local we should show an alert to the user informing them of the privacy tradeoff before allowing them to follow the link.

Thanks to crandlewidth for reporting this: https://twitter.com/crandlewidth/status/1350971569284255747

**Comment by softsimon** [comment]
Perhaps a dialog when clicking on any external link that asks if you really want to visit an external website that may or may not log your IP among other things. It's a common practice.

Random image:

![image](https://user-images.githubusercontent.com/8561090/105053784-e995a680-5aa3-11eb-9e7f-489e50dff616.png)
