### ISSUE TITLE
Add custom Lightning Node Name

### ISSUE THREAD

**Issue by lastoks** [getumbrel/umbrel#447]
There is no way to assign a custom Lightning Node name. This will be e. g. displayed at 1ml.com

It would be nice if you could implement that option.

Best regards
Lars

**Comment by louneskmt** [comment]
By @mayankchhabra from Telegram:

> Aliases can do more harm than good by leaking your private info (h/t Luke Childs for bringing this up when we were considering setting default aliases as <first name>’s Umbrel).
>
> Imagine you name your alias “Lounès’s Umbrel”. I can then go to 1ml.com, instantly find your node, see your balance, open channels, etc.
>
> There isn’t much of an upside of setting a custom alias for private use as aliases aren’t unique and you can’t directly open channels by just using them as you still need the public key (and the onion address if it’s a Tor node).
>
> They have more value for bigger nodes (usually businesses) like Bitrefill, Bitfinex, etc so you can instantly find them and open a channel.

**Comment by stinger32** [comment]
This is the information on how to do it via SSH is https://lightningwiki.net/index.php/Setting_alias_and_color_for_Umbrel

Also, I use PuTTY for software located at www.putty.org

I hope this was helpful.

**Comment by woodiewells** [comment]
> By @mayankchhabra from Telegram:
> 
> > Aliases can do more harm than good by leaking your private info (h/t Luke Childs for bringing this up when we were considering setting default aliases as ’s Umbrel).
> > Imagine you name your alias “Lounès’s Umbrel”. I can then go to 1ml.com, instantly find your node, see your balance, open channels, etc.
> > There isn’t much of an upside of setting a custom alias for private use as aliases aren’t unique and you can’t directly open channels by just using them as you still need the public key (and the onion address if it’s a Tor node).
> > They have more value for bigger nodes (usually businesses) like Bitrefill, Bitfinex, etc so you can instantly find them and open a channel.

It's true it makes nodes more recognizable, but it doesn't cause them to leak more info than what is already out there.

**Comment by nmfretz** [comment]
This can now be done in the Advanced Settings tab of the Lightning Node app! Closed by https://github.com/getumbrel/private-umbrel-lightning/commit/2ca5532586f85b15ff14449c9c7a2fa784c2c49c
