### ISSUE TITLE
Error "Not allowed by CORS" after pressing log in

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#449]
No other details, but I cannot login, any ideas, I have never seen this one:

![image](https://user-images.githubusercontent.com/1388507/105628307-6f1aad00-5e3c-11eb-937d-229f859d1c70.png)

**Comment by maltokyo** [comment]
Apologies, I should have searched.  https://github.com/getumbrel/umbrel/issues/398
But even that resolution doesnt allow me to login

**Comment by robertclarkson** [comment]
There are a few people on the telegram chat with the same issue. I see the CORS error when I try to log in over TOR. Logging in on the local network works OK. Is this the same for you?

**Comment by robertclarkson** [comment]
Have you tried rebooting your node, someone on the telegram group  has suggested it.
```
Happens if you're accessing over tor ithout rebooting your node once since you started using it or if you're using a domain it doesn't know
```

**Comment by lukechilds** [comment]
Ah yes, it's a bug where the Tor hidden service isn't generated quickly enough on first boot to be added to the CORS whitelist. So that's why a reboot fixes it and it will never occur again.

But yes, how are you accessing the dashboard @maltokyo? umbrel.local, IP or Tor hidden service?

**Comment by maltokyo** [comment]
Hi @lukechilds - I run it behind my own Https reverse proxy (another machine). Interestingly it works fine when I'm on my own network but not when using the same URL from the internet. I know TOR is better etc, but my company pc doesn't allow TOR connections and more importantly Bluewallet doesn't allow TOR connections to umbrel electrs..
