### ISSUE TITLE
Loop out fails with Lightning Terminal app

### ISSUE THREAD

**Issue by steve-vincent** [getumbrel/umbrel#451]
The app UI pops up below error. (nothing in syslog)

UNABLE TO PERFORM LOOP OUT
2: cannot initiate swap: payment tracking failed with state FAILED. consider removing pending token file if error persists. use 'listauth' command to find out token file name

**Comment by haarts** [comment]
Have you ever found a workaround?

**Comment by haarts** [comment]
Fails still on version 0.3.8.

**Comment by lukechilds** [comment]
I would suggest:
- Uninstalling Lightning Terminal
- Making sure your Lightning node has open channels with some inbound and outbound liquidity
- Re-installing Lightning Terminal

**Comment by lukechilds** [comment]
>2: cannot initiate swap: payment tracking failed with state FAILED. consider removing pending token file if error persists. use 'listauth' command to find out token file name

Uninstalling and re-installing should resolve the stuck pending token file since uninstalling an app clears all the apps data.

>Unable to find a route for one or both off chain payments that met the fee and timelock limits required.

It sounds like you don't have a route or enough capacity to pay/receive to/from Lightning Labs node.

**Comment by steve-vincent** [comment]
Uninstalled, reinstalled.... thank you
