### ISSUE TITLE
Package mempool.space v2

### ISSUE THREAD

**Issue by lukechilds** [getumbrel/umbrel#452]
https://github.com/mempool/mempool

Looks like we'll have to add a custom entrypoint to to setup the config file based on env vars and init the database via the SQL file.

Or alternatively, submit a PR to mempool so that it accepts env var configurations by default and auto inits the DB.

**Comment by lukechilds** [comment]
@bguillaumat are you already working on this? Do you want me to assign this issue to you?

**Comment by bguillaumat** [comment]
I couldn't today, but i can look at it if Wiz isn't already doing it yeah

**Comment by lukechilds** [comment]
Awesome!
