### ISSUE TITLE
Application Sphinx Relay - wrong configuration

### ISSUE THREAD

**Issue by klicha** [getumbrel/umbrel#453]
Application Sphinx Relay successfully installed. On the page http://umbrel.local:3300/connect I can see QR code and connection string for client connection. Attempting to connect a client ends in error "Cannot reach server ...".
I tried reinstall this app and reboot Umbrel, but with the same result.
I found that there is probably an error in the configuration of the container sphinx-relay. File /relay/config/app.json in container sphinx-relay contains wrong values for parameters macaroon_location, tls_location, ... in production section.

[app.json - production.txt](https://github.com/getumbrel/umbrel/files/5867714/app.json.-.production.txt)
[directory (relay .lnd).txt](https://github.com/getumbrel/umbrel/files/5867722/directory.relay.lnd.txt)

**Comment by maltokyo** [comment]
I got this as well, it was trying to reach server sphinx.com instead of my node.
I switched everything (including the app on Android) to tor, and tried, and then it worked for me.

**Comment by klicha** [comment]
@maltokyo thanks for your answer. I tried it but I was unsuccessful. Umbrel node over Tor works fine. Sphinx app on Android still ends with error "Cannot reach server ... https://sphinx.com". I tried use Sphinx app over Orbot. Is there another way how to use Tor on Android with Sphinx app?

**Comment by louneskmt** [comment]
Hey! You can find support for the Sphinx app on their Telegram group: https://t.me/joinchat/Fb4OcRo4LrRD6NXfsNdeeQ. 

If it appears that the issue comes from Sphinx implementation in Umbrel, please come back here 😉

**Comment by klicha** [comment]
I moved Umbrel node to another place and client on Android with Orbot works now. Probably some network issue on previous place.
