### ISSUE TITLE
Use of labels (help wanted / good first issue)

### ISSUE THREAD

**Issue by rolandpeelen** [getumbrel/umbrel#456]
Hi Guys,

I've just started running an umbrel instance, and since I really like it, I'd love to chuck some time towards this project. I'm a full-stack developer (web stuff), with a bit of a focus on functional programming. I'd love to help out on some things. If you could use the labels with 'help wanted' and / or 'good first issues' (and are open for some help), I'd love to contribute.

Cheers,
Roland

**Comment by rolandpeelen** [comment]
I see the individual repo's do actually use these relatively consistently. I'll do some browsing / comment on the specific ones.

**Comment by lukechilds** [comment]
Thanks @rolandpeelen!

That's actually exactly what I'm working on right now!

This will be the place to keep an eye on: https://github.com/pulls?q=is%3Aopen+user%3Agetumbrel+label%3A%22high+priority%22+

Also feel free to hangout in our dev chat on Keybase with our other contributors: https://keybase.io/team/getumbrel

**Comment by rolandpeelen** [comment]
Good stuff. Joined the keybase 👍
