### ISSUE TITLE
Package Samourai Dojo

### ISSUE THREAD

**Issue by lukechilds** [getumbrel/umbrel#458]
Prior art: https://code.samourai.io/dojo/samourai-dojo/-/blob/develop/docker/my-dojo/docker-compose.yaml

I believe those containers are x86 only so we'll need some multi-arch containers.

Also there are some config/source files than need manaully populating with tokens.

Also some manual database migration logic that needs handling for updates.

**Comment by louneskmt** [comment]
I was working on this but I lost contact with my distant Pi, so I couldn't continue. I'll have direct access to it only next week, but meanwhile I can try just with the dev env.

**Comment by lukechilds** [comment]
Awesome!

Do you want me to assign this to you @louneskmt?

**Comment by louneskmt** [comment]
You can @lukechilds 💪
