### ISSUE TITLE
Package Samourai Whirlpool

### ISSUE THREAD

**Issue by lukechilds** [getumbrel/umbrel#459]
Prior art: https://code.samourai.io/dojo/samourai-dojo/-/blob/develop/docker/my-dojo/overrides/whirlpool.install.yaml

A whirlpool app could just be the Whirlpool CLI with the app UI simply showing a connection string: https://code.samourai.io/whirlpool/whirlpool-client-cli

The actual UI would be handled via the Samourai mobile app.

However ideally it would the app would bundle the Whirlpool GUI: https://code.samourai.io/whirlpool/whirlpool-gui

Whirlpool GUI is an Electron app, so I'm not sure how easily it can exposed as just a web app from Umbrel. However if it can be done without too much trouble this will give a far superior experience.

**Comment by louneskmt** [comment]
@lukechilds You can assign this to me too, I'll work on it once Dojo is packaged (#458).
