### ISSUE TITLE
tor relay function enhancement proposal

### ISSUE THREAD

**Issue by f321x** [getumbrel/umbrel#460]
It would be cool and useful to have a option in the settings to run a tor relay node in the background (maybe with max. traffic usage setting). The node is anyways running 24/7 and with internet connection. With this function many people could provide additional security to the tor network without much effort, which i think is really important considering common internet surveillance.

**Comment by mayankchhabra** [comment]
Looks like this issue was resolved with the addition of Tor Snowflake Proxy in the app store, which is great news! So closing this for now.

**Comment by f321x** [comment]
Please note that a Tor Relay and a Snowflake Proxy are two different things. Snowflake proxies are cool but don't increase anonymity of the Network. A Relay takes Tour traffic from one relay to another and increases Sybil resistance of the Tour Network.


From torproject.org:
Guard and middle relays
(also known as non-exit relays)

A guard relay is the first relay in the chain of 3 relays building a Tor circuit. A middle relay is neither a guard nor an exit, but acts as the second hop between the two. To become a guard, a relay has to be stable and fast (at least 2MByte/s) otherwise it will remain a middle relay.

Guard and middle relays usually do not receive abuse complaints. All relays will be listed in the public list of Tor relays, so may be blocked by certain services that don't understand how Tor works or deliberately want to censor Tor users. If you are running a relay from home and have one static IP, you may want to consider running a bridge instead so that your non-Tor traffic doesn't get blocked as though it's coming from Tor. If you have a dynamic IP address or multiple static IPs, this isn't as much of an issue.

A non-exit Tor relay requires minimal maintenance efforts and bandwidth usage can be highly customized in the tor configuration (will be covered in more detail later in this guide). The so called "exit policy" of the relay decides if it is a relay allowing clients to exit or not. A non-exit relay does not allow exiting in its exit policy.
