### ISSUE TITLE
Exporting wallet or private keys

### ISSUE THREAD

**Issue by steve-vincent** [getumbrel/umbrel#462]
Is there a way to do this?

I've tried copying wallet.dat, creating Electrum wallet with 24 words, as well as 'docker exec bitcoin-cli dumpwallet'... but none of these created the same addresses as Umbrel bitcoin wallet.

There should be a way to export/backup private keys to recover coin natively, without relying on Umbrel device

**Comment by AaronDewes** [comment]
Umbrel doesn't use the bitcoin core wallet, but the LND wallet for both on- and off-chain transactions, so that's not possible

**Comment by steve-vincent** [comment]
Ok, thank you... that explains it then
