### ISSUE TITLE
Cannot uninstall app

### ISSUE THREAD

**Issue by steve-vincent** [getumbrel/umbrel#463]
I tried uninstalling Specter Desktop app, but UI just shows "Uninstalling" for hours.

Later, after logging in again the app is still there. 
Not a huge deal, but FYI

**Comment by louneskmt** [comment]
Does it work after a reboot?

**Comment by steve-vincent** [comment]
No... the app is still there after a reboot.

**Comment by louneskmt** [comment]
I mean reboot then try uninstall.

**Comment by steve-vincent** [comment]
hey that worked!
I could have sworn I tried that a couple times, but straight after a fresh reboot... this time I was prompted "Are you sure? This will delete app and data" (don't think I saw that prior attempts)

All good now, thanks.
