### ISSUE TITLE
Lightning Terminal Password Not Working

### ISSUE THREAD

**Issue by kn1gh7h4wk** [getumbrel/umbrel#464]
On initial install, the "moneyprintergobrrr" worked. However the next time I tried to login, I get a error "oops, that password is incorrect." I ssh into the rPi4 and checked all 4 lit.conf files and all shows the password to be "moneyprintergobrrr."

/home/umbrel/umbrel/app-data/lightning-terminal/data/.lit/lit.conf
/home/umbrel/umbrel/apps/lightning-terminal/data/.lit/lit.conf
/mnt/data/umbrel/app-data/lightning-terminal/data/.lit/lit.conf
/mnt/data/umbrel/apps/lightning-terminal/data/.lit/lit.conf

I also uninstalled and reinstalled and despite being reminded the default password, it still did not work. I would also like the change the default password.

**Comment by louneskmt** [comment]
Dis you solved this? @kn1gh7h4wk

**Comment by kn1gh7h4wk** [comment]
In Telegram, I was told that it's a none issue with the macaroons expiring and will be fixed in the next release.
