### ISSUE TITLE
Used Umbrel Shutdown mode & tried to start back up now stuck on LND?

### ISSUE THREAD

**Issue by pappyg45** [getumbrel/umbrel#467]
How to find out whats going on?

Does Umbrel auto-heal when graceful shutdown is not used?

**Comment by DannyAziz** [comment]
Did you solve this? Also having issues with this

**Comment by pappyg45** [comment]
> Did you solve this? Also having issues with this

Honestly just unplug it from now on. I re-flashed the micro, but the shutdown isnt working from. now on I just unplug.

**Comment by LaserHodl** [comment]
Just ran into this after a fresh upgrade to `0.3.4`. Didn't even restart.

**Comment by RedNax67** [comment]
> Just ran into this after a fresh upgrade to `0.3.4`. Didn't even restart.
> 
>

it is probably still synchronizing the mempool, could take a little while...

**Comment by lukechilds** [comment]
@LaserHodl `Loading LND...` issue should be resolved in the latest release (v0.3.5). If you leave your current version loading long enough it should eventually log in. If not, I can talk you through some SSH commands to manually upgrade.

**Comment by AaronDewes** [comment]
> @LaserHodl `Loading LND...` issue should be resolved in the latest release (v0.3.5). If you leave your current version loading long enough it should eventually log in. If not, I can talk you through some SSH commands to manually upgrade.

The manual update is already documented on [UmbrelInfo](https://umbrelinfo.gitlab.io/troubleshooting.html#manually-updating-umbrel).

**Comment by lukechilds** [comment]
Ah perfect, thanks @AaronDewes!

**Comment by lukechilds** [comment]
I'm gonna close this issue since that should resolve it. Feel free to re-open if you think this is still an issue.
