### ISSUE TITLE
TOR Hidden Service URL not available on first start (debian 10 VPS install)

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#473]
When installing on a fresh debian 10 VPS, I get the following issue.

1. Install using instrctions here: https://github.com/getumbrel/umbrel#-installation
2. Run `sudo ./scripts/start`
3. See log (below) no TOR .onion URL is shown, I must now login over complete clearnet, and input an Umbrel initial password!  This is a bug I guess, and a security risk.

**Workaround to mitigate until fixed:** after step 2 above finishes the startup, immediately run `sudo ./scripts/stop` then again `sudo ./scripts/start` and after this 2nd startup, an onion URL will show.

```
umbrel@720:~/zDocker/docker-umbrel$ sudo ./scripts/start

======================================
============ CONFIGURING =============
========= UMBREL (mainnet) ===========
======================================

Generating auth credentials

Generating Tor password


Making performance optimizations

Setting dbcache size

Configuring permissions...

Configuration successful
You can now start Umbrel by running:
  sudo ./scripts/start


======================================
============= STARTING ===============
============== UMBREL ================
======================================

Setting environment variables...

Starting karen...

Starting backup monitor...

Starting decoy backup trigger...


Starting Docker services...

Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "umbrel_main_network" with the default driver
Creating frontail  ... done
Creating tor       ... done
Creating dashboard ... done
Creating manager   ... done
Creating nginx      ... done
Creating bitcoin    ... done
Creating lnd        ... done
Creating middleware ... done
Creating electrs           ... done
Creating neutrino-switcher ... done


Starting installed apps...


Umbrel is now accessible at
  http://mydomain.com.local
  http://myipwashere
```

**Comment by lukechilds** [comment]
It's available it just hasn't been generated yet when you manaully run the script, it will be available within a few seconds you can read the address at `tor/data/web/hostname`

In Umbrel OS we run a script that waits for the hidden service to be available then logs it to the screen.

However there is a a separate bug that the Tor hidden service doesn't get added to the CORS whitelist unless it exists before Umbrel is restarted (so on the second run).

https://github.com/getumbrel/umbrel/issues/304
