### ISSUE TITLE
JWT Keys - need to be in /var/lib/docker/volumes ? 

### ISSUE THREAD

**Issue by maltokyo** [getumbrel/umbrel#475]
In umbrel, all docker volumes are in the same directory as Umbrel.  This makes it super simple to move around, or migrate to another server as needed.  Except for the JWT keys, which are put into /var/lib/docker/volumes (or the default docker volumes dir for your system), by these lines in docker-compose.

```
volumes:
    jwt-public-key:
    jwt-private-key:
```

Any reason they need to go there?  Cant we use `${PWD}/jwt-public-key:/jwt-public-key` instead?

I don't mind making a PR, but not sure if this is by design or not.. keen to know.  Please advise.

**Comment by nolim1t** [comment]
Personally I think they should be too. 

They should not  be tied to the operating system at all.

**Comment by nolim1t** [comment]
but maybe put it in ```secrets/``` folder

**Comment by maltokyo** [comment]
@lukechilds if you would like, I can make a PR and do this, but still would like the ok first.

**Comment by lukechilds** [comment]
JWT keys should be created on the fly if they don't exist, you shouldn't need them to migrate the system.

**Comment by maltokyo** [comment]
In that case @lukechilds that this is not data that would be needed to be kept to migrate to another server or backup, then no action is required, correct?  In that case, please feel free to close this.

**Comment by lukechilds** [comment]
That's correct!
