### ISSUE TITLE
Add device to /boot/cmdline.txt quirks

### ISSUE THREAD

**Issue by count-null** [getumbrel/umbrel#482]
I was having an issue with my chosen USB3.0 to SATA adapter. It would randomly unmount after a few mins or hours with `input/output error`.

I fixed it by following the steps in [this guide](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=245931) to identify the vendorId and productId of the adapter and add that information to the "quirks" in `/boot/cmdline.txt`

I noticed that the default umbrel image includes many entries in this section already. 

This is my adapter's identifier for the quirks list if you wanted to add it... `2109:0711:u`

**Comment by mayankchhabra** [comment]
It seems this issue has gone quiet for quite some time, so we'll close it for now, but feel free to reopen it if there's any new information or activity.
