### ISSUE TITLE
Cannot login on http://127.0.0.1

### ISSUE THREAD

**Issue by wiz** [getumbrel/umbrel#483]
![2B1A7114-874D-45DE-A5F9-813733CC658C](https://user-images.githubusercontent.com/232186/106701390-eb29a780-6629-11eb-8aba-d47e1373c371.jpg)

**Comment by louneskmt** [comment]
It is because `127.0.0.1` is not in the device hosts list: https://github.com/getumbrel/umbrel/blob/767a7cb97fd72f43df3549ec1bb2707f7d3fc64f/scripts/start#L57

**Comment by maltokyo** [comment]
I had the same issue here, but behind a reverse proxy, so for a different reason.

https://github.com/getumbrel/umbrel/issues/449

**Comment by bzumik1** [comment]
Hi, I am connecting to my server over Wireguard so I would like to be able to access Umbrel on localhost. Is there some way how to achieve this?

**Comment by bzumik1** [comment]
> 127.0.0.1

This unfortunately didn't helped

**Comment by bzumik1** [comment]
> I think it's because `127.0.0.1` is not in the device hosts list: https://github.com/getumbrel/umbrel/blob/767a7cb97fd72f43df3549ec1bb2707f7d3fc64f/scripts/start#L57

This unfortunately didn't helped

**Comment by nmfretz** [comment]
closing old support issue
