### ISSUE TITLE
Can't browse to the interface

### ISSUE THREAD

**Issue by btcb0b** [getumbrel/umbrel#485]
I had mynodebtc running on my Raz 4, I pulled the microSD and formatted it and then flashed Umbrel with Balena. Put in the card and powered up and have been unable to use http://umbrel.local or any of the IP addresses Angry IP showed as active - I thought the IP that mynode used would still be the one.

I was able to SSH and run the debug script, pasting below - can anyone see what my issue might be?

umbrel@umbrel:~ $ ~/umbrel/scripts/debug --upload
=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.3.2

Umbrel OS version
-----------------
v0.3.2

Raspberry Pi Model
------------------
Revision        : c03111
Serial          : 1000000031627b99
Model           : Raspberry Pi 4 Model B Rev 1.1

Firmware
--------
Jan  7 2021 18:27:29
Copyright (c) 2012 Broadcom
version fb345a0c2d5544957f4ba1a2b9e968970e3312c4 (clean) (release) (start)

Temperature
-----------
temp=31.1'C

Throttling
----------
throttled=0x0

Startup service logs
--------------------
-- Logs begin at Thu 2021-02-04 20:17:01 UTC, end at Thu 2021-02-04 20:47:33 UTC. --
Feb 04 20:17:04 umbrel systemd[1]: Dependency failed for Umbrel Startup Service.
Feb 04 20:17:04 umbrel systemd[1]: umbrel-startup.service: Job umbrel-startup.service/start failed with result 'dependency'.

External storage service logs
-----------------------------
-- Logs begin at Thu 2021-02-04 20:17:01 UTC, end at Thu 2021-02-04 20:47:33 UTC. --
Feb 04 20:17:03 umbrel systemd[1]: Starting External Storage Mounter...
Feb 04 20:17:04 umbrel external storage mounter[319]: Running external storage mount script...
Feb 04 20:17:04 umbrel external storage mounter[319]: Found device "ASMT 2115"
Feb 04 20:17:04 umbrel external storage mounter[319]: Checking if the device is ext4...
Feb 04 20:17:04 umbrel external storage mounter[319]: No, it's not ext4
Feb 04 20:17:04 umbrel external storage mounter[319]: Formatting device...
Feb 04 20:17:04 umbrel systemd[1]: umbrel-external-storage.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 20:17:04 umbrel systemd[1]: umbrel-external-storage.service: Failed with result 'exit-code'.
Feb 04 20:17:04 umbrel systemd[1]: Failed to start External Storage Mounter.

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  3.2G   11G  23% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  8.5M  1.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   30M  223M  12% /boot
tmpfs           380M     0  380M   0% /run/user/1000

Filename                                Type            Size            Used            Priority

Karen logs
----------

tail: cannot open 'logs/karen.log' for reading: No such file or directory

Docker containers
-----------------
NAMES     STATUS

Bitcoin Core logs
-----------------

ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements

LND logs
--------

ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements

Tor logs
--------

ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements
================
==== Result ====
================
This script could not automatically detect an issue with your Umbrel.
Please share the following links and paste it in the Umbrel Telegram group (https://t.me/getumbrel) so we can help you with your problem.
tail: cannot open 'logs/karen.log' for reading: No such file or directory
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config.subnet is invalid: should use the CIDR format
services.tor.ports contains an invalid type, it should be a number, or an object
services.bitcoin.ports contains an invalid type, it should be a number, or an object
services.electrs.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports contains an invalid type, it should be a number, or an object
services.lnd.ports value ['9735:9735', ':', ':'] has non-unique elements
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/width=device-width, initial-scale=1
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/width=device-width, initial-scale=1
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/
https://hastebin.com/

**Comment by mayankchhabra** [comment]
Looks like Umbrel wasn't able to format your external drive.

Can you please:

1. Make sure the external drive is connected to a USB 3.0 (blue-colored) port on the Raspberry Pi
2. Post the link to the power supply, external drive, and drive's casing/enclosure that you're using

**Comment by btcb0b** [comment]
https://www.amazon.com/gp/product/B07VX3HQGJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

https://www.amazon.com/gp/product/B07W81T7HF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

https://www.amazon.com/Seagate-BarraCuda-Internal-Drive-2-5-Inch/dp/B07H28QRKN/ref=pd_lpo_147_t_2/142-7665527-3261758?_encoding=UTF8&pd_rd_i=B07H28QRKN&pd_rd_r=d53c3a6a-3a90-4122-a8d2-694051907c65&pd_rd_w=H5zMs&pd_rd_wg=1JBMv&pf_rd_p=16b28406-aa34-451d-8a2e-b3930ada000c&pf_rd_r=1H4K890Q842MK4VSK7V7&psc=1&refRID=1H4K890Q842MK4VSK7V7

2E7172-500 is the 1tb Seagate Barracuda part number that I have

I was plugged into 3.0 blue ports, but I did switch them up to see if that would help.

**Comment by btcb0b** [comment]
Hi - turned it off and turned it back on again, and the miracle occurred. Thanks for your help!

**Comment by btcb0b** [comment]
New issue - can't connect to my Trezor with Specter - I plugged in to the Raz, then the hub, different ports, was just spinning at first trying to detect, and now it gives a failed to fetch error

**Comment by nmfretz** [comment]
closing old support issue
