### ISSUE TITLE
error while creating mount source path

### ISSUE THREAD

**Issue by Stubbs-Ian** [getumbrel/umbrel#487]
getting this error on start up:

ERROR: for manager  Cannot start service manager: error while creating mount source path '/usr/bin/docker': mkdir /usr/bin/docker: read-only file system

**Comment by AaronDewes** [comment]
Try reformatting/reflashing the SD

**Comment by Stubbs-Ian** [comment]
Don't really want to do that. It is a laptop and I don't want to lose anything.

**Comment by AaronDewes** [comment]
Try `sudo mount -o remount,rw /`, then run the start script again

**Comment by Stubbs-Ian** [comment]
Got it, I ran:

sudo systemctl unmask docker
then 
systemctl start docker

started up perfectly fine after that.
