### ISSUE TITLE
If the BTC RPC Explorer app is installed, it should be used as the default explorer.

### ISSUE THREAD

**Issue by jgmontoya** [getumbrel/umbrel#488]
The default explorer when clicking on a tx in the bitcoin wallet is mempool.space (and it doesn't use the onion service), but when the `BTC RPC Explorer` app is installed it should probably use that instead.

**Comment by louneskmt** [comment]
When Mempool.space is added, the best thing would be to have a ´Explorer' setting so the user can choose which explorer to use. 

This would need https://github.com/getumbrel/umbrel-dashboard/pull/250 and https://github.com/getumbrel/umbrel-manager/pull/58.
