### ISSUE TITLE
Environment seamingly reset (dashboard doesn't recognize existing env correctly)

### ISSUE THREAD

**Issue by kilrau** [getumbrel/umbrel#490]
I have umbrel running on my Pi4 4GB since v0.3.0 (currently 0.3.2) and after pressing `install` for *all* apps yesterday, I checked back in again today and what I see is:
![image](https://user-images.githubusercontent.com/19181985/107156358-1f7ccb00-697e-11eb-8212-2af8e060fce3.png)

I sshed in, all data seems still to be there and when I manually `docker restart` the dashboard container, the password field to log in flashes for a second, then above screen again.

Happy to help debugging.

**Comment by maltokyo** [comment]
Inside your umbrel directory, go to the db directory, and in it is a file called user.json
Does it start with a { like this?

![image](https://user-images.githubusercontent.com/1388507/107255479-a42c1f80-6a38-11eb-9c39-b75e2f3e7034.png)

If not, try to add one at the top, and restart.  There is a bug open for it, and it causes what you have described above.

@AaronDewes

**Comment by AaronDewes** [comment]
@lukechilds Another example that https://github.com/getumbrel/umbrel/pull/405 can happen on real installations sometimes. This is in my opinion a high priority issue as it can lead to users thinking they lost their sats and can render nodes useless if users don't know how to fix it.

**Comment by kilrau** [comment]
> Does it start with a `{` like this?

Yup:
```
{
  "name": "kilrau",
  "password": "elon",
  "seed": "pumping",
  "installedApps": [
    "btc-rpc-explorer",
    "btcpay-server",
    "specter-desktop"
  ]
}

}
```

Note how not *all* apps made it into the `installedApps` section even though I clicked all install buttons (yes I know...).

**Comment by maltokyo** [comment]
but you have an additional `}` at the bottom.  remove that and try a restart, I think that is the same bug as above.

**Comment by lukechilds** [comment]
Ok thanks guys, I'll look into this as a priority this week.

**Comment by maltokyo** [comment]
@kilrau nice password, very relevant ;)

**Comment by kilrau** [comment]
> nice password, very relevant ;)

;)

> but you have an additional } at the bottom. remove that and try a restart, I think that is the same bug as above.

That fixed it. Closing here as duplicate of https://github.com/getumbrel/umbrel/issues/403. Thanks for the fast replies guys! :pray:

**Comment by maltokyo** [comment]
@lukechilds @AaronDewes that confirms.  I had it three times now.  This is 3rd.

@kilrau I guess you are not on Rasberry Pi (if you are, I think you are the first to encounter it on that)

**Comment by kilrau** [comment]
> @kilrau I guess you are not on Rasberry Pi (if you are, I think you are the first to encounter it on that)

I am (Pi4, 4GB RAM).
