### ISSUE TITLE
Umbrel Linux blockchain data on external drive?

### ISSUE THREAD

**Issue by iraszl** [getumbrel/umbrel#498]
Is it possible to configure Umbrel Linux to store blockchain data on an external or secondary drive?

If so, is there a configuration file or a parameter one needs to use?

**Comment by maltokyo** [comment]
Just put the entire umbrel user directory on the secondary drive, that is easiest.

Assuming your user name is umbrel (UID 1000) then try this:

`usermod -d /path/to/external-drive umbrel`

**Comment by iraszl** [comment]
That works! Also, I realized one can start the installation from any drive. Cool.

**Comment by ostermayer** [comment]
it runs from whatever folder location is /umbrel/scripts/start  so just copy to new folder and run ./scripts/start
