### ISSUE TITLE
Can't change wifi networks via wpa_supplicant

### ISSUE THREAD

**Issue by tmpplb** [getumbrel/umbrel#502]
Hey there, Running on a RPi4. Managed to get everything set up and fully synced the other night but ran into problems opening channels. I think its because I have multiple routers and one sits behind another.

Tried to switch connections to the new router via wpa_supplicant.conf the same way I got wifi working upon first boot, but the CLI hangs while trying to start the docker application. It seems like it's executing and applying the wpa_supplicant fine, but something isn't sticking. It refuses to start docker/umbrel. Reverting back to my old connection via wpa_supplicant fixes the issue, but I can't use this network and need to change it.

How do I proceed? Is it normal for the docker app to take awhile to initialize over a new network? Should I wipe and restore from my backup seed?

Thanks

**Comment by AaronDewes** [comment]
WiFi often prevents/conflicts with USB3. I don't fully understand that issue, but you should try moving the SSD as far away as possible from the Pi and check if tht helps.

**Comment by tmpplb** [comment]
Using the SSD over 2.1 actually - Wifi worked flawlessly using wpa_supplicant _the first time i initialized the node_, but now that I want to switch to a different wifi network, wpa_supplicant doesn't seem to be applying the new network info, and is causing the app to hang. Switching back to the original network info fixes the problem. Seems like once someone uses wpa_supplicant one time they are stuck using that network config.

What files does wpa_supplicant SSID impact? Is there a way to manually set those in other conf files throughout?

**Comment by nolim1t** [comment]
This is the reason why WiFi wasn't part of the implementation.

There is a lot of moving parts and factors before you even deal with the UX gotchas of running a full nodes.

You can use raspi-config to change the wifi details if you are running a raspbian variant. You might have to restart.

**Comment by AaronDewes** [comment]
> What files does wpa_supplicant SSID impact? Is there a way to manually set those in other conf files throughout?

It does just impact the wpa_supplicant configuration, wpa_supplicant handles the connection. It doesn't impact anything else

**Comment by tmpplb** [comment]
> You might have to restart.

meaning, power off the node to use raspbian to edit the config, or restart the entire build?

**Comment by nmfretz** [comment]
closing old support issue
