### ISSUE TITLE
QUESTION: Can I use and connect Umbrel to my own Bitcoin Node and avoid syncronizing the blockchain again?

### ISSUE THREAD

**Issue by muhepd** [getumbrel/umbrel#504]
Hi,

This is a question, is the subject line says, can I use and connect Umbrel to my own Bitcoin Node and avoid synchronizing the blockchain again?

I haven't tried to install Umbrel yet, but I friend did and he mentioned that Umbrel was trying to synchronize indexes again. Is there a way I can avoid this and use the blockchain from my node with its indexes?

Thanks.

**Comment by esackbauer** [comment]
I had my own node running before. What I did was to copy the blockchain data over, **only** from these 2 folders:
blocks
chainstate

You need to stop all Umbrel services before you do that, and start them only after you have copied all data over.

**Comment by nmfretz** [comment]
Link to unsupported method of copy over blockchain data to a new device: https://community.getumbrel.com/t/official-umbrel-troubleshooting-guide-and-faq/9873#:~:text=Speeding%20Up-,Blockchain,-Synchronization
