### ISSUE TITLE
Signet support

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel#507]
It would be great to have signet support here once lnd supports it (https://github.com/lightningnetwork/lnd/issues/5018).
It would sadly break a few things that need a specific letter count (CLI messages), because mainnet testnet regtest have 7 letters, signet only 6 😞 .

**Comment by Sjors** [comment]
I think Signet was added to And per v0.13: https://github.com/lightningnetwork/lnd/pull/5025

**Comment by Sjors** [comment]
A nice benefit of Signet is that the chain is much smaller than testnet, so it will sync faster and take up less space. The [faucet](https://signet.bc-2.jp) is also more reliable than for testnet. In fact, it could probably be integrated.

**Comment by Sjors** [comment]
This happened? Or it's not going to happen?

**Comment by AaronDewes** [comment]
I closed it because I'm now building @runcitadel, which will get signet support soon and don't want to have open issues in Umbrel's repos because I'm no longer contributing to Umbrel.
