### ISSUE TITLE
504 Gateway Error

### ISSUE THREAD

**Issue by Minituff** [getumbrel/umbrel#516]
I am experiencing an extremely slow Umbrel experience. I think I narrowed it down to a 504 gateway error.

![2021-02-12 20_08_30-Umbrel](https://user-images.githubusercontent.com/8152401/107843364-41f85500-6d7f-11eb-9e64-dc5fd2847ec8.jpg)

Any ideas on how to fix this?

**Comment by nmfretz** [comment]
closing old support issue
