### ISSUE TITLE
Unable to install apps from the dashboard

### ISSUE THREAD

**Issue by jon4hz** [getumbrel/umbrel#522]
I installed Umbrel on my Ubuntu server and most of it works fine but I cannot install apps with the dashboard. However installing apps by running `sudo ./scripts/app install btcpay-server` for example works perfectly fine. 

I attached the debug log here but cropped out a few things which aren't umrel related since not everyone who reads this issue needs to know which container run on my host.

In general Umbrel is working and reachable in my LAN as over TOR.

[umbrel_debug.log](https://github.com/getumbrel/umbrel/files/5976496/umbrel_debug.log)

**Comment by AaronDewes** [comment]
Seems like karen has some issues, try `sudo ./scripts/stop && sudo killall karen`. After that, if you know how to use it, make sure karen really isn't running with `htop`, then start Umbrel again

**Comment by lukechilds** [comment]
I have experienced a similar issue in the dev environment.

After account creation `db/user.json` is created and owned by root so installing apps as non-root via the CLI fails. On next start the file is chowned to 1000:1000 so it's fine.

I had assumed this was only an issue in the dev env and wouldn't occur in prod since karen would always be installing apps as root. Could be unrelated but sounds very similar.

**Comment by thelwyn** [comment]
@lukechilds and related to this one too maybe? https://github.com/getumbrel/umbrel/issues/494

**Comment by aecc** [comment]
I got an issue here because my installed version of "docker-compose" was an older one and didn't support the "--env" flag that is hardcoded in the scripts/app (only available from docker-compose v1.28+ https://docs.docker.com/compose/environment-variables/). Upgrading docker-compose fixed my issue.

**Comment by AusDavo** [comment]
Same problem. Can't install apps from the dashboard. It says "installing..." but never shows up in the apps section. Please, can it be fixed?

The OS is Ubuntu Server. I control it remotely using SSH. Not sure if this is relevant.

[umbrel-1635676190770-debug.log](https://github.com/getumbrel/umbrel/files/7448541/umbrel-1635676190770-debug.log)

**Comment by lukechilds** [comment]
This issue seems to only affect users installing a custom install on Linux and not Umbrel OS users. It seems like maybe you aren't starting the karen process? It's important to start Umbrel via `./scripts/start` not with `docker-compose up` to make sure everything gets started correctly.

@AusDavo Could you try `sudo ./scripts/stop && sudo ./scripts/start` (which should ensure karen is definitely running)and then try installing apps and seeing if that works?

Also would strongly reccomend running Umbrel OS on a Raspberry Pi to avoide issues like this.

**Comment by AusDavo** [comment]
Thanks, Luke. Just trying to make some use of a old NUC that was on hand. `sudo ./scripts/stop && sudo ./scripts/start` didn't change things. That's how I always stop/start the package. I wonder what gets jammed up... I was able to install an app (thunderhub) by `sudo ./scripts/app install thunderhub`. I hope that I can install some of the other handy apps in the same way.

**Comment by lukechilds** [comment]
You can `tail -f ./logs/karen.log` to see what's going on when you install an app from the UI.

**Comment by AusDavo** [comment]
I ran that command after installing mempool and here's the output:

```
Got signal: debug
No trigger found
Got signal: change-password
No trigger found
Got signal: backup
No trigger found
Got signal: change-password
No trigger found
Got signal: app-install-mempool
No trigger found
```

Mempool was installed fine.

I also tried installing Pi-hole but it didn't work. I got the following:

```
Setting up data dir for app pi-hole...
sending incremental file list
./
docker-compose.yml
data/
data/dnsmasq/
data/pihole/

sent 860 bytes  received 54 bytes  1,828.00 bytes/sec
total size is 655  speedup is 0.72
Pulling images for app pi-hole...
Pulling server ... done
Starting app pi-hole...
Creating pi-hole_server_1 ... 
Creating pi-hole_server_1 ... error

ERROR: for pi-hole_server_1  Cannot start service server: driver failed programming external connectivity on endpoint pi-hole_server_1 (2ceb0b8150ace235b4d21e5d2f4aa5d839fc2c2f59d1c6b1052b4f7b91773fd1): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use

ERROR: for server  Cannot start service server: driver failed programming external connectivity on endpoint pi-hole_server_1 (2ceb0b8150ace235b4d21e5d2f4aa5d839fc2c2f59d1c6b1052b4f7b91773fd1): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
I wonder what's going astray.

**Comment by AusDavo** [comment]
I looked in the karen log again after trying to install pi-hole and it was unchanged:
```
Got signal: debug
No trigger found
Got signal: change-password
No trigger found
Got signal: backup
No trigger found
Got signal: change-password
No trigger found
Got signal: app-install-mempool
No trigger found
```

**Comment by thelwyn** [comment]
> This issue seems to only affect users installing a custom install on Linux and not Umbrel OS users.

I got this issue multiple times with apps install, and I run Umbrel OS on a RPi4.
The only "unusual" thing in my setup is that it runs on a network behind a VPN so that it can connect to Tor. It's possible that it makes my internet connection somehow unstable and that something fails, but it does it silently.

**Comment by AusDavo** [comment]
Mine also runs on a subnet that is routed through a VPN.

**Comment by michalkrol** [comment]
Hi, I found the same issue.
Karen logs shown:
`Got signal: app-install-mempool
No trigger found`

It happened that permissions on triggers were wrong. After changing permissions to 755 (same as default), everything works like expected.

Impacted files are `UMBREL_ROOT/events/triggers/*`

should look like this:
`~/umbrel$ ls -la events/triggers/
total 44
drwxrwxr-x 2 mk mk 4096 Nov  2 15:24 .
drwxrwxr-x 4 mk mk 4096 Nov  2 15:24 ..
-rwxr-xr-x 1 mk mk  197 Nov  2 15:24 app
-rwxr-xr-x 1 mk mk  127 Nov  2 15:24 backup
-rwxr-xr-x 1 mk mk  139 Nov  2 15:24 change-password
-rwxr-xr-x 1 mk mk  684 Nov  2 15:24 debug
-rwxr-xr-x 1 mk mk   52 Nov  2 15:24 reboot
-rwxr-xr-x 1 mk mk 1677 Nov  2 15:24 remote-tor-access
-rwxr-xr-x 1 mk mk 1142 Nov  2 15:24 repo
-rwxr-xr-x 1 mk mk   52 Nov  2 15:24 shutdown
-rwxr-xr-x 1 mk mk  133 Nov  2 15:24 update`

**Comment by nmfretz** [comment]
closing old support issue
