### ISSUE TITLE
Syslog flooding

### ISSUE THREAD

**Issue by jon4hz** [getumbrel/umbrel#523]
I have come to notice that Umbrel and all related containers write every log in the syslog file. Correct me here if I'm wrong but I suppose that's the way Umbrel get the sync status for the blockchain. 
However Umbrel generate quite a few logs and that is flooding my syslog and makes it a pain in the ass to run on a system which isn't dedicated for Umbrel. Is there an alternative planed in the future?

**Comment by AaronDewes** [comment]
> I have come to notice that Umbrel and all related containers write every log in the syslog file. Correct me here if I'm wrong but I suppose that's the way Umbrel get the sync status for the blockchain.
> However Umbrel generate quite a few logs and that is flooding my syslog and makes it a pain in the ass to run on a system which isn't dedicated for Umbrel. Is there an alternative planed in the future?

No, Umbrel gets the sync progress via Bitcoins API. Syslog is mostly used because it makes accessing logs easy, have a look at umbrel.local/logs

**Comment by lukechilds** [comment]
It definitely doesn't make sense to write to syslog on a non-dedicated machine. Long term we can change that but right now while we have limited resources we're really focused on building Umbrel for Umbrel OS.

Custom installs are only really best-effort supported. If you don't mind getting your hands a little dirty you can manually point the logs somewhere else by tweaking these lines of the compose config: https://github.com/getumbrel/umbrel/blob/master/docker-compose.yml#L2-L5

**Comment by jon4hz** [comment]
Alright, I already removed the logging in the docker-compose file once but then I had a bug that the sync status didn't show up. But in that case I was just to inpatient. 
So I can forward the logs to my ELK stack as I do it with all my other containers. And speaking of the logs, can I stop the frontail container, if I don't want my logs to be forwarded to Umbrel anyway?

Btw customization isn't any problem. Already added altcoin support to my btcpay-server and some other stuff.

**Comment by lukechilds** [comment]
Yes you can stop the frontail container.

Please not that if you're making changes to the Umbrel source those changes will be overwritten if you do an update from the dashboard. You'll need to manaully update Umbrel yourself to keep your modifications.

**Comment by jon4hz** [comment]
Already thought that, thanks for the confirmation. Will pulling the new containers and running the start-script again be enough for an update in most cases?
