### ISSUE TITLE
At wits end

### ISSUE THREAD

**Issue by alarew** [getumbrel/umbrel#525]
I have been trying to setup an umbrel node but have been having endless issues. The latest is getting this error after updating to all the components recommended on umbrel site. I cannot get it to finish syncing the bitcoin core without it crashing and ultimely after multiple crashes, corrupting everything to the point i have to start over with a clean format of SSD and new flashing of umbrel. Attached is a photo .
The error is : 
EXT4-fs error (device sda1): ext4_journal_check_start:83: Detected aborted journal
EXT4-fs (sda1): Remounting filesystem read-only
then there are a bunch of errors saying cannot read block - read error etc. 

![IMG-3016](https://user-images.githubusercontent.com/44209882/107864055-e1bcee00-6e26-11eb-91a1-9350c2ebfe8b.jpg)

This happens again and again. Usually after around 20 or 30% of core is loaded then wham. 
Any clues?  
Pulling hair out here. 
Albert

**Comment by AaronDewes** [comment]
Your SSD is unreliable

**Comment by lukechilds** [comment]
>The latest is getting this error after updating to all the components recommended on umbrel site.

Just to confirm here, you're definitely using the official Raspberry Pi power supply, a Crucial MX500 SSD, and ORICO SSD enclosure?

**Comment by alarew** [comment]
Hi ,
Thanks for the response. I am definitely using Raspberry PI power supply, Orico SSD, and a Crucial MX500 1TB 3D NAND SATA 2.5 Inch Internal SSD.  I have formatted it as fat 32 on a mac before installing.  Last night, I redid everything -  new flash, new umbrel login, new format of ssd and started again. It crashed once but then I restarted and it has been syncing all night - up to 59% now. I guess if it craps out again, I will chuck the SSD and get a new one. Perhaps as AaronDewes says, it is unreliable.

**Comment by dlq84** [comment]
@alarew Wait, are you actually using FAT32 on a 1TB SSD while running Linux? Try using a Linux format instad, like ext4.

**Comment by louneskmt** [comment]
> @alarew Wait, are you actually using FAT32 on a 1TB SSD while running Linux? Try using a Linux format instad, like ext4. 

@dlq84 Umbrel OS formats the drive automatically on first boot.

**Comment by alarew** [comment]
What does Umbrel OS natively format the SSD with? 
FYI - its still chugging away @ 63% now. Fingers crossed.

**Comment by nolim1t** [comment]
Your power source may also be unreliable too. 

What sort of power are you using, and also how stable is your electricity supply.

It needs to be 100% uninterrupted or you must shut down your node cleanly.

**Comment by bepursuant** [comment]
> It needs to be 100% uninterrupted or you must shut down your node cleanly.

THIS IS SUPER IMPORTANT! I had mine plugged in through a UPS, and it was basically unusable. Moving it to a non-UPS plug resolved the issue, smooth sailing since then.

**Comment by alarew** [comment]
i replaced the SSD with a much more reliable samsung SSD and its fine now. chugging away. Plus I moved to a raspberry power source and the recommend encasement.  The only thing is it is SSSLLLLOOOOOOWWWWW in the synching process. After 5 or 6 days of continuous syncing, i am at 49%. So it looks like it will take 2 weeks to fully sync.  At least its not crashing.

**Comment by unclemantis** [comment]
Took me 5 days to sync. I used all recommended hardware.

**Comment by ezeql** [comment]
Hit the same issue. I have a Crucial MX500 1TB 3D SSD and a generic case. Will try with the recommended case again.

**Comment by edcolmar** [comment]
Constant extfs errors and swap errors over here too.  Far, far too unstable to be considered for real world use.

**Comment by nmfretz** [comment]
closing old support issue
