### ISSUE TITLE
Specter - Tor price providers fail to get price.

### ISSUE THREAD

**Issue by ghost** [getumbrel/umbrel#526]
In Price Settings, the current $USD price of $BTC can be achieved using the `Bitstamp USD` provider - 

![Screen Shot 2021-02-13 at 4 22 00 PM](https://user-images.githubusercontent.com/76824110/107865047-aa931080-6e17-11eb-8494-6820735ce9a5.png)

In the top-right of Specter Desktop, the price of Bitcoin will now be shown - 

![Screen Shot 2021-02-13 at 4 21 36 PM](https://user-images.githubusercontent.com/76824110/107865041-96e7aa00-6e17-11eb-972b-4285bd5c430a.png)

This works great with `Bitstamp USD`, but if you select *any* of the Tor providers.

Here we select `Spotbit Coinbase (Tor) USD` in Price Settings - 

![Screen Shot 2021-02-13 at 4 21 01 PM](https://user-images.githubusercontent.com/76824110/107865016-820b1680-6e17-11eb-9531-fc4dc52041c6.png)

And upon hitting save we get the error `Updating price data...Failed to fetch price data from selected provider, please try again or select another provider` like so:

![Screen Shot 2021-02-13 at 4 21 08 PM](https://user-images.githubusercontent.com/76824110/107865017-833c4380-6e17-11eb-8ad5-7f8e3b9de806.png)

**Comment by LaserHodl** [comment]
If I had to guess I would say that Umbrel is not correctly configuring the Tor connection for Specter's price provider calls. The other possibility is that Spotbit does not actually work, although I find that less probable.

**Comment by LaserHodl** [comment]
* Umbrel `0.3.2`
* Specter `1.0.0`

**Comment by bguillaumat** [comment]
Hey @LaserHodl I will let @lukechilds @mayankchhabra confirm but if I'm right, we are putting Specter behind an hidden service (Tor) but we don't use the built-in tor of Specter so when you try to pull the price from a tor link specter can't do it that's why you actually got this issue

**Comment by nolim1t** [comment]
That could be something to address with specter itself to use a custom tor instance.

Anyway, No need to care about price. 1 btc = 1 btc.

Just another dick measuring contest.

**Comment by nmfretz** [comment]
closing old Specter issue
