### ISSUE TITLE
Accessing umbrel via port 8080

### ISSUE THREAD

**Issue by darrenahunter** [getumbrel/umbrel#527]
Hi
I have port 8080 exposed to external - forwarding to umbrel on port 80.
I can access the umbrel login page via xxx.xxx.xxx.xxx:8080 - but  once entering password and trying  to route to /dashboard the vue-router fails
I am using Raspi4 and getUmbrel version: 0.3.2

error in devtools follow

<img width="923" alt="Screen Shot 2021-02-14 at 3 17 44 pm" src="https://user-images.githubusercontent.com/3478531/107868505-ee018380-6ed8-11eb-804e-436d5064aef2.png">

**Comment by jon4hz** [comment]
I'm getting the same error if I try to put umbrel behind a reverse proxy. But not sure if it's related.

**Comment by louneskmt** [comment]
Once this PR is merged it will be possible to set a custom port for Umbrel's nginx: https://github.com/getumbrel/umbrel/pull/256

**Comment by louneskmt** [comment]
@darrenahunter It has been implemented in #562. Can you close this now?

**Comment by darrenahunter** [comment]
many thanks
