### ISSUE TITLE
Why Umbrel OS?

### ISSUE THREAD

**Issue by rstmsn** [getumbrel/umbrel#529]
I see the reccommendation to run Umbrel on top of Umbrel OS, but no explanation of why this is the preferred approach. UImbrel OS appears to be a fork of Raspberry PI OS. Generally speaking, what customisations have been made within Umbrel OS and to what end?

**Comment by AaronDewes** [comment]
Umbrel OS has systemd services for Umbrel and is a bit cleaner than RPi OS. it has Umbrel's dependencies preinstalled. We're working on making Umbrel OS based on Debian and release it for all platforms.

**Comment by jon4hz** [comment]
But why making a dedicated OS in the first place? A clean documentation on how Umbrel does things and interact with host itself would be much more useful. I did the Linux install and I'm not that happy. It's unclear what Umbrel exactly does and only after a few researches I found stuff like the syslog flooding which I reported in #523. 
Wouldn't it be better to make Umbrel an OS independent service so it can be integrated easily into existing environments? The docker approach makes a pretty good base for that.
Not everyone wants to buy dedicated hardware if you already have running systems.

**Comment by AaronDewes** [comment]
> But why making a dedicated OS in the first place? A clean documentation on how Umbrel does things and interact with host itself would be much more useful. I did the Linux install and I'm not that happy. It's unclear what Umbrel exactly does and only after a few researches I found stuff like the syslog flooding which I reported in #523.
> Wouldn't it be better to make Umbrel an OS independent service so it can be integrated easily into existing environments? The docker approach makes a pretty good base for that.
> Not everyone wants to buy dedicated hardware if you already have running systems.

We're working on both.

**Comment by lukechilds** [comment]
That is absolutely the long term plan, but right now we're a tiny team with a huge amount of things to do. Focusing on one target platform allows us to iterate way faster while still keeping >90% of users happy.

If we spent time properly architecting the intial beta release so it runs as a neat portable service and was fully documented, we probably wouldn't have released any thing publicly yet.

What you see now is beta. An early preview of what Umbrel will be, in order for us to gather feedback and validate that there is demand. Umbrel will be heavily refactored before a stable release.

**Comment by jon4hz** [comment]
Well by that explanation and status of the development it isn't beta but more alpha if not pre-alpha. The state "beta" is in that case kinda misleading since the beta state generally is meant for bug hunting and improving stability and not redesigning the complete service.
But anyway, it's up to you how you call it and in the SECURITY.md, you clearly stated that it isn't secure or finished yet.
I'm not that much of a developer (only self-taught python, bash and a bit go) but if you have some work to do for a system- or network engineer, feel free to ping me. I see huge potential in this project and would be happy to help.
