### ISSUE TITLE
Security concerns by mounting docker socket

### ISSUE THREAD

**Issue by jon4hz** [getumbrel/umbrel#531]
Is there another reason to mount the docker socket as RW than installing apps over the dashboard? Since mounting the docker socket as RW can be a huge security issue since the socket can be used to escalate privileges to the host. 
Can I remove the socket mount or at least change to RO for the manager and neutrino-switcher if I only install apps over the CLI?

**Comment by AaronDewes** [comment]
> Can I remove the socket mount or at least change to RO for the manager and neutrino-switcher if I only install apps over the CLI?

No, both services need that to restart some ocntainers, have a look at their source code

**Comment by lukechilds** [comment]
We'll be refactoring away fro Docker in Docker before a stable release, but regarding this:
>Since mounting the docker socket as RW can be a huge security issue since the socket can be used to escalate privileges to the host.

Please be aware that Umbrel is in beta, it's not yet considered secure. Take a look at our security document: https://github.com/getumbrel/umbrel/blob/master/SECURITY.md

**Comment by LaserHodl** [comment]
If not Docker-in-Docker, then what? How are you planning on launching and running apps?

**Comment by lukechilds** [comment]
We already don't use Docker-in-Docker for apps. We use a filesystem based message passing protocol: https://github.com/getumbrel/umbrel/blob/8e5fc409ae755e2fd67ef9d99fbeb7ff85c2c6c3/karen

We're only using Docker-in-Docker for some old code that's restarting LND/Bitcoin Core from another container after that container changes it's config file.

>How are you planning on launching and running apps?

We'll have our own Umbrel daemon that runs on the host and can install apps, do system restarts etc. We'll mount a unix socket for the Umbrel daemon into containers that need it with a per container access token. So certain containers only get access to certain methods. And even if the most privileged container got compromised, all it can do is what the Umbrel host daemon lets it do, so install/uninstall apps, it won't be able to start arbitrary Docker containers on the host.
