### ISSUE TITLE
v0.3.3 broke the app - Node no longer responsive

### ISSUE THREAD

**Issue by tmpplb** [getumbrel/umbrel#535]
Updated to v0.3.3 via the WebUI (backed up everything). Everything seemed to be working fine, new apps were available etc.

UmbrelUI suddenly went unresponsive, checked the CLI and saw nothing, so I restarted.

Now the CLI hangs on "Starting Docker Application Container Engine..." and does nothing.

What's going on here? Are there background processes that I should be letting complete or is something broken? 

If someone wouldn't mind linking documentation for how to recover from seed that would be helpful as well.

Thanks,

**Comment by tmpplb** [comment]
Solved by connecting via LAN instead of Wifi and grabbing the 0.3.4 fix. Working normally now.

Nice reflexes! Thanks. Will leave this open for devs to close.

**Comment by mayankchhabra** [comment]
Awesome, sorry about the hiccup!
