### ISSUE TITLE
ssh access denied after update

### ISSUE THREAD

**Issue by llvllch** [getumbrel/umbrel#541]
The new updates are looking great. One wrinkle:

I'd changed my password from the default. All good. 

Updated, everything running smoothly, except the fact I can no longer ssh into the machine with my password (nor the default)

**Comment by llvllch** [comment]
Found the issue: Password for ssh is now the same as for gui login. Closing

**Comment by phenomeus** [comment]
besides its not working for me… great.

**Comment by bepursuant** [comment]
AH-HA! Had the same issue after upgrading... glad to see this was an easy fix :)
