### ISSUE TITLE
Loop in failed with 0.3.4

### ISSUE THREAD

**Issue by bitcoiner-dev** [getumbrel/umbrel#542]
I tried doing a loop in using the lightning terminal as well as ride the lightning. It fails consistently with the following error:

Error: cannot initiate swap: rpc error: code = DeadlineExceeded desc = context deadline exceeded

Any idea what might be going on over here? How can I help to fix this? I really need the loop functionality to work.

I also noticed that there is 1000sat transaction with label LSAT that now appears in my lightning transaction list. The status shows that it was successfully paid. It's obvious that this was initiated as a result of the loop in but what I don't understand is why it was paid if the loop in failed. I guess I need to do some reading on how loop works under the hood.

**Comment by lukechilds** [comment]
Does Lightning Terminal work reliably for you after restarting Umbrel `Settings > Restart` or do you still get the same error?

**Comment by bitcoiner-dev** [comment]
Got the same error after restarting.

**Comment by lukechilds** [comment]
Does it work if you use the loop functionality in RTL?

**Comment by lukechilds** [comment]
Also, are you able to retry a few times in a row? I just got the same issue you described. I didn't change anything, I just attempted to Loop (with Lightning Terminal) multiple times in a row, and after about 5 tries it worked.

I think this could just be a bug in LND or `loopd` being a little unstable. Let me know if that works for you.

**Comment by bitcoiner-dev** [comment]
> Does it work if you use the loop functionality in RTL?

I get the same error when I try from RTL.

Just to rule out any other possibilities, I used the RTL loop docker to initiate a loop in using the "loop" command, same error.

Also, I tried from Lightning Terminal 6 times in a row, every time I got the same error message as before.

**Comment by lukechilds** [comment]
Hmmn, ok.

Could you try this. Log into your Umbrel via SSH:

```
ssh umbrel@umbrel.local
```

Enter your dashboard password

Then run:

```
sudo ~/umbrel/scripts/update/update --repo lukechilds/umbrel#lnd-fee-url-on-neutrino-mainnet
```

Once that completes, log in to the Umbrel dashboard again to unlock LND,  then open the Lightning Terminal app.

**Comment by bitcoiner-dev** [comment]
Updated my umbrel using the commands you mentioned. Logged back in to the dashboard and then Lightning Terminal.

Tried to loop in five times, still the same error every time.

**Comment by lukechilds** [comment]
It could be related to this issue: https://github.com/lightninglabs/lightning-terminal/issues/184#issuecomment-784178316

Could you try looking for a `lsat.token.pending` file or similar in the in the loop data dir?

```
~/umbrel/app-data/ride-the-lightning/loop/.loop/mainnet/
```

**Comment by bitcoiner-dev** [comment]
There's lsat.token but no lsat.token.pending.

**Comment by bitcoiner-dev** [comment]
Loop in and out have started working in 0.3.7.

Closing this.
