### ISSUE TITLE
Some lightning channels getting offline after 0.3.4 update

### ISSUE THREAD

**Issue by olafmarcos** [getumbrel/umbrel#551]
I had a channel working with a BOS server (node01.fulmo.org) that after updating to v0.3.4 is offline.

I've rebooted without success.

Linux Debian install.

**Comment by lukechilds** [comment]
We just pushed a new update are you able to try that?

**Comment by olafmarcos** [comment]
Updated. Restarted. Same behaviour, node01.fulmo.org channel offline. :(

**Comment by tsnieman** [comment]
I can also confirm that my open channel [with this node](https://1ml.com/node/03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf) continues to be "offline" after updating to v0.3.5.

**Comment by Dhumez-Sebastien** [comment]
Hello,

I also deployed my node at the beginning of the week. I found that nodes with TOR addresses had very regularly disconnection/reconnection problems.

Nevertheless, the nodes with public IP addresses do not cause any stability problems.

**Comment by bitcoiner-dev** [comment]
I have a channel Fulmo and it was offline but now its back online. Maybe the problem is not specific to Umbrel but Fulmo? :)

**Comment by olafmarcos** [comment]
Confirmed. Mine is online now.

**Comment by lukechilds** [comment]
Yes I also heard from Lightning Labs that the problem was on Fulmo's end.

**Comment by tsnieman** [comment]
FWIW: [the channel that I had open](https://github.com/getumbrel/umbrel/issues/551#issuecomment-782645746) with Zap continues to be offline for unknown reasons. Is this still the relevant thread to be discussing it? @lukechilds

**Comment by AaronDewes** [comment]
I assume they might use an outdated version of LND and that's the reason it can't connect, but I'm not sure.
