### ISSUE TITLE
Restoring Lightning Channels from a backup

### ISSUE THREAD

**Issue by llvllch** [getumbrel/umbrel#553]
Following a wallet restore, all my funds are back, but my lighhtning channels are gone. I have a copy of the channel backup.
I realise that this can't be done via the UI currently. Can I force a restore from command line?

**Comment by louneskmt** [comment]
You will need to SSH into your Pi. 

```
ssh -t umbrel@umbrel.local
```
Password: `moneyprintergobrrr`

Copy your backup file to the Pi (using scp for example: from your main computer `scp /path/to/channel.backup umbrel@umbrel.local:/home/umbrel/umbrel/lnd/data/chain/bitcoin/mainnet/channel.backup`)

Then from the `~/umbrel` dir, execute this:

```
docker-compose exec lnd lncli restorechanbackup --multi_file /data/.lnd/data/chain/bitcoin/mainnet/channel.backup
```

**Comment by llvllch** [comment]
Brilliant! Thanks a lot. I will now learn docker :)
