### ISSUE TITLE
Open LN channel "offline" after update to v0.3.3/v0.3.4

### ISSUE THREAD

**Issue by tsnieman** [getumbrel/umbrel#555]
Hello. I'm following up on a suggestion from @lukechilds [via Twitter](https://twitter.com/lukechilds/status/1361920278830309378).

I upgraded to v0.3.3 earlier this week, then immediately (within a couple hours) to v0.3.4.

Since my upgrade, the singular Lightning channel I had open [with this node](https://1ml.com/node/03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf) has been "offline" ever since.

I'm unsure why this channel is offline - should channels stay offline after updating/restarting?

I'm happy to provide any logs or configuration that may be helpful in debugging.

Seemingly related: #551

**Comment by lukechilds** [comment]
We just pushed a new update are you able to try that?

Also gonna close this to keep the issue tracked on one place but please respond with your progress after the latest update over at #551.

Thanks!
