### ISSUE TITLE
Feature request: Add Blockbook

### ISSUE THREAD

**Issue by haarts** [getumbrel/umbrel#559]
[Blockbook](https://github.com/trezor/blockbook) is Trezor's backend. When able to install on Umbrel you can connect Trezor Suite to it. This then, makes you no longer dependent on the servers of Trezor.

**Comment by downet** [comment]
This should be solved by Trezor itself - https://github.com/trezor/trezor-suite/issues/2737

Did you checked requirements for Blockbook? :-)

**Comment by haarts** [comment]
Admittedly I did not check the requirements for Blockbook. I did now, and it requires a synced node? It's late over here and I'm ashamed to admit I fail to see the irony.

Full node support for Trezor Suite seems slanted for mid April afaict (https://github.com/orgs/trezor/projects/28?card_filter_query=node#card-47974233). Knowing something about IT projects I suspect that will slip.

**Comment by downet** [comment]
@haarts yea, it will most probably slip.. it already slipped from February :)

btw I wanted you to check following:
```
Officially supported platform is Debian Linux and AMD64 architecture.

Memory and disk requirements for initial synchronization of Bitcoin mainnet are around 32 GB RAM and over 180 GB of disk space. After initial synchronization, fully synchronized instance uses about 10 GB RAM.
```

**Comment by haarts** [comment]
Aaaaah. That's gonna be a bit much isn't it? ;) Alright then. Let's wait will they integrate it into Trezor Suite. Thanks for the patience! And thank you for the great product.
