### ISSUE TITLE
SDD Stop working with Umbrel OS

### ISSUE THREAD

**Issue by Andrejk333** [getumbrel/umbrel#564]
**SDD Stop working with Umbrel OS after few hours of fine start**

"failed to start external storage mounter"

– Not booting Umbrel OS (clean Umbrel OS booted from SD)
– After first boot, everything goes fine, up to 40% synchronized the blockchain, then I gentle moved all physically a bit (30 cm) and something have happened with the SSD.
– I didn't shut it down at all before the issue came.
– it's just a SSD problem, with different SSD, even old one, works again – works fine again with regular old WD Elements
– the SSD is : **SSD disk Corsair Force Series MP510B 960GB with External box Orico M2PV-C3-BK-EP 10Gbps**

Fail logg and setup attached in photos.

**I Have tried (doesn't worked):** 
– mount via command
– different cable
– format SSD in all possible formatting options
– unplugged coolers and display to spare a power just for SSD

![IMAGE 2021-02-24 145328](https://user-images.githubusercontent.com/67663986/109011373-19425a80-76b1-11eb-8559-86df1e7d9b40.jpg)
![IMAGE 2021-02-24 145325](https://user-images.githubusercontent.com/67663986/109011396-1d6e7800-76b1-11eb-8ac1-eec36a0adce1.jpg)
![FAILED  Failed to start External Storage Mounter](https://user-images.githubusercontent.com/67663986/109011409-20696880-76b1-11eb-8ae5-4103ca954515.jpg)

**Comment by AaronDewes** [comment]
Probably the SSD doesn't get enough power or the adapter is unreliable. Also, please use Telegram for support, GitHub is only for bugs in Umbrel itself, and Umbrel isn't responsible for broken SSDs (We're still trying to help, but don't use GitHub for that)

**Comment by Andrejk333** [comment]
offtopic.
