### ISSUE TITLE
Addresses aren't loading in mempool app

### ISSUE THREAD

**Issue by kevinwin** [getumbrel/umbrel#567]
When navigating to any address in the mempool app I'm getting a 500 server error and an error is displayed to the user suggesting that the connection to the server was lost.

![image](https://user-images.githubusercontent.com/7491757/109056227-30cc1400-76ae-11eb-84a0-d0ab53ea4bb9.png)

**Comment by louneskmt** [comment]
See https://github.com/getumbrel/umbrel-os/issues/182. Reinstalling the app seems to fix the issue.

**Comment by kevinwin** [comment]
That did it. Thanks for the tip!
