### ISSUE TITLE
Connections 0 Peers

### ISSUE THREAD

**Issue by Rothschildiuk** [getumbrel/umbrel#577]
For the second time today, all peers are missing
![image](https://user-images.githubusercontent.com/15833131/109326534-9a3b5680-7857-11eb-8ba5-0731e673b088.png)

Feb 26 16:23:34 umbrel electrs[784]: WARN - wait until IBD is over: headers=672285 blocks=478040 progress=0.392277837633607
Feb 26 16:25:44 umbrel electrs[784]: WARN - wait until IBD is over: headers=672285 blocks=478044 progress=0.3922866566888994
Feb 26 16:27:03 umbrel electrs[784]: WARN - wait until IBD is over: headers=672285 blocks=478046 progress=0.3922916971998254

**Comment by louneskmt** [comment]
If think it can happen if Tor circuit is broken. Tor calculates a new circuit every 10 minutes. Do the interruption last more than 10 minutes ?

**Comment by Rothschildiuk** [comment]
I don't know for sure. I mast check it out.

**Comment by louneskmt** [comment]
Hey @Rothschildiuk, have you solved this issue?

**Comment by Rothschildiuk** [comment]
Now is better (I use HDD and I think this may be the reason).
