### ISSUE TITLE
Exposing RPC to Local Network (Manually)

### ISSUE THREAD

**Issue by bepursuant** [getumbrel/umbrel#579]
Can I ask, for the sake of documentation, how I would expose the bitcoin RPC to the local network?

I understand that this is a security risk, but I need the RPC for a project that I'm working on, and I don't quite understand exactly where I would configure the nginx/docker-proxy to make this happen.

Any help would be greatly appreciated.

**Comment by downet** [comment]
Add `$BITCOIN_RPC_PORT:$BITCOIN_RPC_PORT` in `/mnt/data/umbrel/docker-compose.yml`

under following in `bitcoind` section:

```
ports:
                    - "$BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT"
                    
```

so it will look liket this:
```
ports:
                    - "$BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT"
                    - "$BITCOIN_RPC_PORT:$BITCOIN_RPC_PORT"
                    
```

And restart umbrel by `sudo systemctl restart umbrel-startup`

Be aware that every update will rewrite the file and you will need to do it again.

**Comment by unclemantis** [comment]
Do I use the username and password from bitcoin dashboard?

**Comment by jroulin** [comment]
You also need to change bitcoin.conf to allow your local network to access the rpc service. For example:

```
rpcallowip=192.168.1.0/24
```

**Comment by newtonick** [comment]
This no longer works for me. I updated and lost my changes. Anyone else have a working instructions for getting rpc for bitcoind accessible on a local network?
