### ISSUE TITLE
Bitcoin container doesn't start after latest upstream update

### ISSUE THREAD

**Issue by dlq84** [getumbrel/umbrel#590]
The latest version that they pushed about 2 hours ago over at "lncm/bitcoind" doesn't start since they didn't include sqlite in the container (I'm guessing). I had to manually revert it to lncm/bitcoind:v0.21.0-amd64-build18 and then it started working again. Maybe you want to consider setting the build number aswell in the future so upstream doesn't break Umbrel again.

Thank you.

**Comment by lukechilds** [comment]
Thanks, yes I've been meaning to checksum pin the images for a while, I'll do that now.

**Comment by lukechilds** [comment]
Resolved in https://github.com/getumbrel/umbrel/pull/591 @dlq84. Thank you very much for spotting this and notifying us so quickly!

I'll try and ninja push a new release out now before this affects too many others.
