### ISSUE TITLE
Loading Bitcoin Core... been sitting at this point for over and hour.

### ISSUE THREAD

**Issue by tgienger** [getumbrel/umbrel#593]
Is this normal? It's been in the same position for over an hour. If it's downloading core then I have downloaded Bitcoin Core previously and it took maybe a couple hours total.

![Screen Shot 2021-02-28 at 8 48 48 AM](https://user-images.githubusercontent.com/4080971/109426331-04f8a900-79a2-11eb-827e-6759ac1121f2.png)

**Comment by louneskmt** [comment]
Hey!

This is a known issue, which has been solved in the latest release. Follow the instructions below to perform a manual update to v0.3.7. 

Please connect to your Pi via SSH with the following command:

```
ssh -t umbrel@umbrel.local
```

The prompted password is your dashboard password. 

Then execute:

```
cd ~/umbrel && sudo scripts/update/update --repo getumbrel/umbrel#v0.3.7
```

Wait until the command is fully executed (i.e. the terminal shows the prompt line).

**Comment by tgienger** [comment]
Perfect! I'm on Ubuntu, not on pi, but obviously it worked out just fine :) Thanks!

**Comment by tinder-mattchan** [comment]
My Umbrel is having this issue. To make matters more complicated, my Umbrel is 400 miles away. Is there any way to resolve this from the tor browser? :(

@louneskmt
