### ISSUE TITLE
Got stuck while updating to 3.7

### ISSUE THREAD

**Issue by Virgi311** [getumbrel/umbrel#595]
I am trying to update to last version but I got stock while removing old containers.
What should i do?
#594 

Thanks in advance.

**Comment by Rosevdh69** [comment]
I just did a sudo reboot via SSH after same error and now i could enter again in Umbrel dashboard.

**Comment by Virgi311** [comment]
Ok thank you, i finally did the same and it works correctly.

**Comment by louneskmt** [comment]
If it's all good, can you close this issue @Virgi311?

**Comment by Virgi311** [comment]
of course, thank you
