### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by mazazz** [getumbrel/umbrel#597]
Trying to run umbrel. Installed everything as per instruction. Trying to run script sudo ./scripts/start and getting this:
./scripts/start: command not found
What I'm missing?

**Comment by AaronDewes** [comment]
You need to cd into the Umbrel folder first

**Comment by mazazz** [comment]
> You need to cd into the Umbrel folder first

Yes, I'm in same dir. It's an external SSD drive.

**Comment by AaronDewes** [comment]
What does "ls" output?

**Comment by mazazz** [comment]
> What does "ls" output?

app-data  db                  info.json   logs       SECURITY.md
apps      docker-compose.yml  karen       nginx      statuses
bin       electrs             LICENSE.md  README.md  templates
bitcoin   events              lnd         scripts    tor

**Comment by AaronDewes** [comment]
Try `sudo ./scripts/start` again

**Comment by mazazz** [comment]
> Try `sudo ./scripts/start` again

sudo: ./scripts/start: command not found

I tried many times, search for solutions, but didn't find anything.

**Comment by louneskmt** [comment]
Does `ls scripts/` returns "Input-output error"?

**Comment by mazazz** [comment]
> Does `ls scripts/` returns "Input-output error"?

Nope, all good. I guess it's something related to user PATH and sudo PATH. Start script maybe is on different PATH than sudo....
