### ISSUE TITLE
touch: cannot touch '$HOME/umbrel/../statuses/configured'...

### ISSUE THREAD

**Issue by notleanbarba** [getumbrel/umbrel#600]
I'm trying to install umbrel in a new computer with Debian and i get this error when executing "sudo ./scripts/start" 

![image](https://user-images.githubusercontent.com/35031625/109580949-3ffdf800-7ada-11eb-99ec-00c51b8864eb.png)

I believe it could be a bug from the new release. If i touch the file manually it continues with the installation but the file is empty after all.

**Comment by stoopkidddd** [comment]
Encountered the same. Can confirm that going into `../statuses/`, manually doing a `touch configured` and running the script again appears to fix it

**Comment by AaronDewes** [comment]
I'd recommend deleting umbrel and restarting the setup, because this happens sometimes and Umbrel detects the path wrong.

**Comment by notleanbarba** [comment]
#601
