### ISSUE TITLE
Umbrel Dashboard LND "Open Channel" Function Broken

### ISSUE THREAD

**Issue by sambradbury** [getumbrel/umbrel#602]
Attempting to open a new lightning channel to the sphinx.chat node gave the error shown below. I was able to open the same channel using the Zap desktop app which is connected to my Umbrel node. It seems the issue is somewhere in the part of the code for the Umbrel dashboard that recognizes valid addresses. 

Here are the instructions I was following: https://github.com/stakwork/sphinx-relay

This is the sphinx.chat lightning address: https://1ml.com/node/023d70f2f76d283c6c4e58109ee3a2816eb9d8feb40b23d62469060a2b2867b77f

Here is a screenshot of the error that was generated when copying the address into the open channel feature:
![image](https://user-images.githubusercontent.com/31943456/109653961-3d75bf80-7b27-11eb-90dd-e4776d04faf1.png)

**Comment by KaffeMedFika** [comment]
I have the same issue at the moment.

**Comment by Koff** [comment]
@sambradbury I found the underlying cause. The amount you are setting is too small, and the UI is mistakenly showing that error. Try increasing the amount and you should be good.

**Comment by sambradbury** [comment]
> @sambradbury I found the underlying cause. The amount you are setting is too small, and the UI is mistakenly showing that error. Try increasing the amount and you should be good.

Do you mean the total channel size is too small or that the transaction fee is too low. Zap had no problem opening this same channel at 50k sats.

**Comment by dugwood** [comment]
There's an issue with LND I think. For example:

Request:
http://mynode/api/v1/lnd/channel/estimateFee?confTarget=0&amt=10000&sweep=false

Answer:
```
{
"fast":{"code":"INVALID_ADDRESS","text":"Please validate the Bitcoin address is correct."},
"normal":{"feeSat":"1525","feerateSatPerByte":"10"},
"slow":{"feeSat":"348","feerateSatPerByte":"2"},
"cheapest":{"feeSat":"152","feerateSatPerByte":"1"}
}
```

So `fast` is totally wrong, but it's the only option available (as other are grayed out).

**Comment by sambradbury** [comment]
The error being discussed doesn't occur anymore. You will need to fully sync your bitcoind node before you are able to open a channel. This is why the query for fee estimates is failing for you.
