### ISSUE TITLE
BTCPay Tor onion address not accessible through UI

### ISSUE THREAD

**Issue by junderw** [getumbrel/umbrel#607]
BTCPay is meant for allowing people to buy/send money to you. So the service should be publicly exposed.

However, publicizing your IP address is not a good idea (assuming Umbrel is primarily set up in your home) so tor is a must.

However, the btcpayserver installed through umbrel does not support tor currently.

The onion address of btcpayserver and other services (ie umbrel dashboard) should be separate.

**Comment by junderw** [comment]
btcpayserver has environment variables to manage TOR... maybe it could be configured to point to the running tor service.

**Comment by junderw** [comment]
I see you have the proxy info:
https://github.com/getumbrel/umbrel/blob/4c6c1c0acb5e95bfd6db2b7da1eaeb133d449487/apps/btcpay-server/docker-compose.yml#L58

But you also need `BTCPAY_TORRCFILE` which points to the file `torrc` (meaning BTCPay needs filesystem access to wherever that file is on (I'm assuming) the tor container.

**Comment by junderw** [comment]
If I run `docker exec tor cat /var/lib/tor/app-btcpay-server/hostname` on the box with umbrel, I get an onion URL, and that takes me to BTCPay...

So it is accesible from tor, but there's no way to learn of the onion address besides running a command in the umbrel box currently.

If we alert BTCPay of the tor service via passing it read access to torrc, it will show the onion link on all pages returned from BTCPay.

Otherwise, umbrel needs some sort of UI to show the onion URL for each app.

**Comment by junderw** [comment]
Looking at the TorService in BTCPay, it doesn't seem like it would be able to parse the torrc properly unless we give btcpay a name?

https://github.com/btcpayserver/btcpayserver/blob/9daa424afd8ee0ab06f56b08f01e277b046c55d0/BTCPayServer/Services/TorServices.cs#L25-L81

`service.ServiceName.Equals("BTCPayServer", StringComparison.OrdinalIgnoreCase)`

Maybe that corresponds to `HiddenServiceName` (idk if that exists) in a torrc file.

Maybe @NicolasDorier has some idea on how we can point the BTCPAY to torrc file.

Here's an example of the umbrel torrc file.

```
# Bind only to "xxx.xxx.xxx.xxx" which is the tor IP within the container
SocksPort   xxx.xxx.xxx.xxx:9050
ControlPort xxx.xxx.xxx.xxx:29051

# Umbrel

# Dashboard Hidden Service
HiddenServiceDir /var/lib/tor/web
HiddenServicePort 80 xxx.xxx.xxx.xxx:80

# Bitcoin Core P2P Hidden Service
HiddenServiceDir /var/lib/tor/bitcoin-p2p
HiddenServicePort 8333 xxx.xxx.xxx.xxx:8333

# Bitcoin Core RPC Hidden Service
HiddenServiceDir /var/lib/tor/bitcoin-rpc
HiddenServicePort 8332 xxx.xxx.xxx.xxx:8332

# Electrum Hidden Service
HiddenServiceDir /var/lib/tor/electrum
HiddenServicePort 50001 xxx.xxx.xxx.xxx:50001

# LND REST Hidden Service
HiddenServiceDir /var/lib/tor/lnd-rest
HiddenServicePort 8080 xxx.xxx.xxx.xxx:8080

# LND gRPC Hidden Service
HiddenServiceDir /var/lib/tor/lnd-grpc
HiddenServicePort 10009 xxx.xxx.xxx.xxx:10009

# Apps

# btc-rpc-explorer Hidden Service
HiddenServiceDir /var/lib/tor/app-btc-rpc-explorer
HiddenServicePort 80 xxx.xxx.xxx.xxx:3002

# thunderhub Hidden Service
HiddenServiceDir /var/lib/tor/app-thunderhub
HiddenServicePort 80 xxx.xxx.xxx.xxx:3000

# sphinx-relay Hidden Service
# We expose 80 for the connection string UI and 3300 for the
# actual server connection
HiddenServiceDir /var/lib/tor/app-sphinx-relay
HiddenServicePort 80 xxx.xxx.xxx.xxx:3300
HiddenServicePort 3300 xxx.xxx.xxx.xxx:3300

# ride-the-lightning Hidden Service
HiddenServiceDir /var/lib/tor/app-ride-the-lightning
HiddenServicePort 80 xxx.xxx.xxx.xxx:3001

# lightning-terminal Hidden Service
HiddenServiceDir /var/lib/tor/app-lightning-terminal
HiddenServicePort 80 xxx.xxx.xxx.xxx:3004

# specter-desktop Hidden Service
HiddenServiceDir /var/lib/tor/app-specter-desktop
HiddenServicePort 80 xxx.xxx.xxx.xxx:25441

# btcpay-server Hidden Service
HiddenServiceDir /var/lib/tor/app-btcpay-server
HiddenServicePort 80 xxx.xxx.xxx.xxx:3003

# lnbits Hidden Service
HiddenServiceDir /var/lib/tor/app-lnbits
HiddenServicePort 80 xxx.xxx.xxx.xxx:3007
# mempool Hidden Service
HiddenServiceDir /var/lib/tor/app-mempool
HiddenServicePort 80 xxx.xxx.xxx.xxx:3006

# samourai-server Hidden Service
HiddenServiceDir /var/lib/tor/app-samourai-server
HiddenServicePort 80 xxx.xxx.xxx.xxx:80

# samourai-server whirlpool Hidden Service
HiddenServiceDir /var/lib/tor/app-samourai-server-whirlpool
HiddenServicePort 80 xxx.xxx.xxx.xxx:8898

HashedControlPassword YY:XXXXXXXXXXXXXXXXXXXXXX
```

**Comment by louneskmt** [comment]
> So it is accesible from tor, but there's no way to learn of the onion address besides running a command in the umbrel box currently.

If you access the dashboard via Tor, all apps URLs will be onion URLs. So if you click on an app, it will open directly its onion url, and not the local hostname:port. 

> Otherwise, umbrel needs some sort of UI to show the onion URL for each app.

But I agree on this. So the user can get the onion url without first accessing the dashboard directly via Tor. 

> Looking at the TorService in BTCPay, it doesn't seem like it would be able to parse the torrc properly unless we give btcpay a name?
>
> Maybe @NicolasDorier has some idea on how we can point the BTCPAY to torrc file.

BTCPay not having access to the torrc file is intended. By mounting the tor data dir in BTCPay container, it can read the whole configuration file and display in the BTCPay settings page a list of all existing hidden services and the associated onion URLs. It is a security issue if a single app can know all the other apps and services hidden services. So when I implemented BTCPay, I removed this from the compose file, so it is no access to the tor data dir (and thus URLs + private keys).

**Comment by junderw** [comment]
Maybe we can get BTCPay to add an ENV where we can give it the onion address instead of torrc file. That way it can show the tor link of itself and be aware.

**Comment by junderw** [comment]
@Kukks said on BTCPay chat that he will look into allowing the needed info to be passed via some config rather than torrc file.

:tada::tada::tada::tada::tada::tada::tada:

**Comment by NicolasDorier** [comment]
@Kukks tracking this?

**Comment by NicolasDorier** [comment]
this will be in next version ~1 or 2 week

**Comment by lukechilds** [comment]
Thanks @NicolasDorier @Kukks, legends!

**Comment by al1ta** [comment]
Hi guys. I'm running umbrel 0.5.3 with btcpay server  1.6.12-hotfix-1 on a SBC arm64v8 and ubuntu
I can't access btcpay under onion while it works well on ipv4.
I'm trying the onion address found at umbrel/tor/data/app-btcpay-server/hostname
however it doesn't work.
using torbrowser it says "Onionsite Not Found" and "Details: 0xF0 — The requested onion service descriptor can't be found on the hashring and therefore the service is not reachable by the client."

thanks in advance

**Comment by NicolasDorier** [comment]
@junderw you can close this one
