### ISSUE TITLE
Suggestion: Add Password Manager to app store

### ISSUE THREAD

**Issue by junderw** [getumbrel/umbrel#612]
Reasoning: Bitcoin users need to store passwords for various services. Having passwords accessible from multiple devices is best. Having self-sovereign password manager is even better!

Suggestion: bitwarden_rs is an extremely lightweight implementation of the server-side Bitwarden protocol. There is a docker container available.
Github: https://github.com/dani-garcia/bitwarden_rs

Possible blockers: The official Bitwarden app allows users to put their own server's URL, but does not support tor currently. (iirc Android users could run Orbit and point their Bitwarden app to localhost Orbit and have it forward to the onion URL we set for bitwarden_rs)

But it looks as though they are working on onion URL support.
https://community.bitwarden.com/t/tor-support-for-ios-and-android/12721

**Comment by kaschmirrr** [comment]
Would be cool

**Comment by strnly** [comment]
How come this has not been done over a year later ??? 
make it happen already

**Comment by nmfretz** [comment]
Vaultwarden is on the app store! https://apps.umbrel.com/app/vaultwarden
