### ISSUE TITLE
"Web interface" doesn't start when SSD connected over USB 3.0

### ISSUE THREAD

**Issue by meening42** [getumbrel/umbrel#615]
When SSD is connected over USB 3.0 and I go to umbrel/local I get mesage:

_Loading Bitcoin Core... This can take a while, please don't turn off your Umbrel!_

This can take more than an hour and never come to login page. I expected that the login page would load in less then 5 minutes. 

If SSD is connected to USB 2.0 port, login page is loaded in less then a minute. 

**Hardware:** 
- SSD: Samsung 860 EVO SSD 2TB 2,5 sata3 (MZ-76E2T0B/EU)
- SSD CASE: Icybox IB-273StU3, 2.5" SATA, USB 3.0
- Raspberry Pi 4 Model B
- Official power supply for R. Pi

**Comment by AaronDewes** [comment]
> SSD CASE: Icybox IB-273StU3, 2.5" SATA, USB 3.0

This is an SSD case failure. I already checked with a different user, ICYBOX cases don't work with the Pi, they seem to use too much power over USB.

**Comment by nmfretz** [comment]
closing old support issue
