### ISSUE TITLE
open channel failure text breaks out of error message container

### ISSUE THREAD

**Issue by weisjohn** [getumbrel/umbrel#617]
just reporting a little UX bug:

<img width="971" alt="Screen Shot 2021-03-06 at 8 40 14 PM" src="https://user-images.githubusercontent.com/12034/110228068-2b4fa480-7ecc-11eb-9aa8-793e54971853.png">

perhaps instead the error message should populate some sort of textarea?

**Comment by mayankchhabra** [comment]
As I'm reviewing old issues, I noticed that this one had been resolved in the Lightning Node app. Thanks for reporting!
