### ISSUE TITLE
Suggestion: Add pi-hole as app

### ISSUE THREAD

**Issue by junderw** [getumbrel/umbrel#618]
I think it does come down to a judgement call, "things Bitcoiners should have/use" vs. "things that Bitcoiners use directly for Bitcoin"

I think the decision to include this as an app is similar to the decision to include Bitwarden #612 

Except, while Bitwarden would require tor support, pi-hole is primarily for use with local network DNS. So it would just need an explainer on the app install page saying "once you set it up, change the admin screen password and login to your router's admin page and set the DNS to your umbrel's local IP, you might want to assign a fixed local IP for your umbrel."

https://pi-hole.net/

I hear it's extremely low resource, and I've been looking to run one. Might just manually set it up alongside my umbrel.

**Comment by junderw** [comment]
actually, looking into it... it requires root :-/

**Comment by lorenzoPrimi** [comment]
Worked for me.
Installed pihole with the standard command
```
curl -sSL https://install.pi-hole.net | bash
```
Then changed the web interface port with this tutorial
https://jdsworld.com/tech-support/pi-hole-dns-change-default-web-port/

**Comment by junderw** [comment]
FYI latest version of umbrel comes with pihole

:-D

**Comment by lorenzoPrimi** [comment]
Great!
On another topic, do you know how to get PiVPN working with umbrel?
xRef : https://github.com/pivpn/pivpn/issues/1346
