### ISSUE TITLE
Allow for lnd.conf customization

### ISSUE THREAD

**Issue by dennisreimann** [getumbrel/umbrel#623]
With the recent update I noticed that Umbrel overwrites the lnd.conf file with the general template. I'd like to have a way to customize the file and have those customizations last beyond updates.

An approach might be to have a location for such customizations (e.g. `umbrel/custom/lnd.conf`) and append them during [configuration](https://github.com/getumbrel/umbrel/blob/master/scripts/configure#L252), if those files are available.

My concrete use case is setting multiple `tlsextradomain`'s, but I could also see other customizations like providing an `alias` or the `color` for the node …

**Comment by andoniabedul** [comment]
If lnd.conf is rewritten, will it do so in bitcoin.conf as well? When does this happen?

It happened to me recently and I had already updated to 4.0 before changing the lnd.conf configuration.

**Comment by lukechilds** [comment]
Resolved via https://github.com/getumbrel/umbrel/pull/904

**Comment by lukechilds** [comment]
>If lnd.conf is rewritten, will it do so in bitcoin.conf as well? When does this happen?
>
>It happened to me recently and I had already updated to 4.0 before changing the lnd.conf configuration.

@andoniabedul All configuration files were re-written during an update. We've now disabled this behaviour for LND so any changes you make to lnd.conf will be persisted. bitcoin.conf will still be overwritten.
