### ISSUE TITLE
Lightning terminal - lightning pool not able to withdraw

### ISSUE THREAD

**Issue by andywang514** [getumbrel/umbrel#624]
My sats are stuck in the lightning pool account. Looks like there is an updated lightning terminal app available that fixed this issue, just need to have Umbrel upgrade the App store. 

Any idea when it will happen?

**Comment by iraszl** [comment]
[v0.4.1-alpha](https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.4.1-alpha) has the feature. As I understand it will be bundled in the next release of Umbrel.

**Comment by nmfretz** [comment]
Lightning Terminal version in app store now includes this feature.
