### ISSUE TITLE
Add time zone to settings and setup

### ISSUE THREAD

**Issue by cubiclestorm** [getumbrel/umbrel#626]
Selecting time-zone really should come up during initial setup rather than always using UTC-0
Also added to settings page.

**Comment by yik77** [comment]
this somehow compromises privacy...your time zone gives hint on your location.

**Comment by louneskmt** [comment]
@cubiclestorm Where is the time used in the UI?

@yik77 Not really has all your Umbrel data is stored only on your Umbrel (SSD in case of the use of a Raspberry Pi). Nothing goes to the cloud, except automatic encrypted backup of your LND channels. Umbrel doesn't have any metric tool.

**Comment by nmfretz** [comment]
The dashboard calculates its welcome message based on your system/browser settings, but I believe that's about it.

https://github.com/getumbrel/umbrel-dashboard/blob/82ddf09d1ac723828a2717005d5fd96207277d9d/src/views/Dashboard.vue#L128-L140
