### ISSUE TITLE
Show startup errors via web UI

### ISSUE THREAD

**Issue by lukechilds** [getumbrel/umbrel#632]
Currently there are many different types of errors that can occur at the OS level outside of Umbrel that the user gets no feedback on.

e.g if a SSD isn't attached, Umbrel won't start, and the user has no feedback. umbrel.local is down,. They need to SSH in and view logs to see what's wrong. We should have a webserver that displays errors via umbrel.local in cases like this.

To do this we should probably run a simple web server on the host that proxies through to the Umbrel web server. This can be running as a high priority startup service. It should be up and running as soon as possible, even before Docker or external storage mounting. I anything goes wrong with the startup process the issue should be reflected here.

This also means we can more easily show progress updates during things like OTA updates and shutdown where we want to continue to display the progress of events after the Umbrel web server has stopped.

**Comment by AaronDewes** [comment]
Should that server run on the host? And will it use node or just be static HTML/CSS?

**Comment by AaronDewes** [comment]
Also, once we have that server and https://github.com/getumbrel/umbrel-dashboard/pull/275, we probably can make Umbrel even more secure by disabling SSH by default and providing an option to enable it for debugging on that server.

**Comment by lukechilds** [comment]
>Should that server run on the host? And will it use node or just be static HTML/CSS?

Yes it'll have to run on the host, it should start running as early on in the boot process as possible, so before Docker.

Ideally we want to work towards eliminating dependencies not adding them. Node.js is a pretty heavy dependency. Python is pretty much everywhere by default so could be a good choice without requiring a hard dep. It could be dynamic, but we could probably get away with a static server with an `index.html` and a `status.json`. The page would just load the static `index.html` which in turn polls the static `status.json` and displays the status to the user.

If anything goes wrong on the host with mounting the external storage or starting Docker or whatever, we just write the error to `status.json` which will be rendered to the user.
