### ISSUE TITLE
Clicking on an external link discloses onion address to third-party

### ISSUE THREAD

**Issue by pieterjm** [getumbrel/umbrel#639]
When browsing to Umbrel on tor, several hyperlinks refer to  external websites (e.g. getumbrel.com, github.com and t.me). As no Referer policy is configured, the onion address of an umbrel installation is disclosed to the external website through the Referer header. Also no other security headers are present. 

I suggest to include: Referrer-Policy: no-referrer in all responses and configure other security headers.

**Comment by AaronDewes** [comment]
https://github.com/getumbrel/umbrel/pull/640 is for Umbrel itself, we currently can't do this for apps right now, but it might be possible in the future.

>  and configure other security headers.

Which ones?

**Comment by pieterjm** [comment]
X-XSS-Protection: 1; mode=block 
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Content-Security-Policy

**Comment by lukechilds** [comment]
Great spot @pieterjm! We'll get this fixed for the next release.
