### ISSUE TITLE
Docker Error 

### ISSUE THREAD

**Issue by phil71185** [getumbrel/umbrel#642]
I am getting the below error am not able to figure this one out 

ERROR: for a5f766fc1fe0_bitcoin  container a5f766fc1fe05ff63ae89958f4659ae7135604f2693e720d747a4b5ed9555611: driver "zfs" failed to remove root filesystem: exit status 1: "/usr/sbin/zfs fs destroy -r rpool/ROOT/ubuntu_ze75mb/var/lib/13508f8ae9906fd4c5bf1e9a950d682b46b8c6f14d1f841a5cc8d78203c11a19" => cannot open 'rpool/ROOT/ubuntu_ze75mb/var/lib/13508f8ae9906fd4c5bf1e9a950d682b46b8c6f14d1f841a5cc8d78203c11a19': dataset does not exist

ERROR: for bitcoin  container a5f766fc1fe05ff63ae89958f4659ae7135604f2693e720d747a4b5ed9555611: driver "zfs" failed to remove root filesystem: exit status 1: "/usr/sbin/zfs fs destroy -r rpool/ROOT/ubuntu_ze75mb/var/lib/13508f8ae9906fd4c5bf1e9a950d682b46b8c6f14d1f841a5cc8d78203c11a19" => cannot open 'rpool/ROOT/ubuntu_ze75mb/var/lib/13508f8ae9906fd4c5bf1e9a950d682b46b8c6f14d1f841a5cc8d78203c11a19': dataset does not exist

**Comment by Ruppsn** [comment]
try
`sudo ./scripts/stop`
`docker system prune`
`sudo ./scripts/start`
this should clean out docker and spin of some new containers.

Next time. try to give some more details.

**Comment by HarryTheHorse** [comment]
> try
> `sudo ./scripts/stop`
> `docker system prune`
> `sudo ./scripts/start`
> this should clean out docker and spin of some new containers.
> 
> Next time. try to give some more details.

I had a completely different error (below) whereby Umbrel refused to start with errors from start script and your answer completely fixed it:

`Creating network "umbrel_main_network" with the default driver
Starting dashboard ... error
Starting tor       ... 

ERROR: for dashboard  Cannot start service dashboard: network 632abedcbaf7b45d10Starting tor       ... error

ERROR: for tor  Cannot start service tor: network 632abedcbaf7b45d10224ed827a36f37d7426e077504168909ef78e595ecac89 not found

ERROR: for dashboard  Cannot start service dashboard: network 632abedcbaf7b45d10224ed827a36f37d7426e077504168909ef78e595ecac89 not found

ERROR: for tor  Cannot start service tor: network 632abedcbaf7b45d10224ed827a36f37d7426e077504168909ef78e595ecac89 not found
ERROR: Encountered errors while bringing up the project.
`

**Comment by nmfretz** [comment]
closing old support issue
