### ISSUE TITLE
Display Out of Disk Errors

### ISSUE THREAD

**Issue by PattonsCoin** [getumbrel/umbrel#643]
There are several users who report getting stuck at `"Loading Bitcoin Core... This can take a while, please don't turn off your Umbrel!"`

One of the times this will happen is when there's no disk space left. It would be useful to have that error display somewhere like the loading page.

**Comment by louneskmt** [comment]
Hey @PattonsCoin! This is definitely on the roadmap, we are working on a new loading page 💪

**Comment by nmfretz** [comment]
closing old issue that is now out-of-date due to umbrel ui refresh
