### ISSUE TITLE
Can Umbrel be used as routing node?

### ISSUE THREAD

**Issue by steve-vincent** [getumbrel/umbrel#644]
I think I've got a decent set of  balanced channels with good capacity and low fees.

However, in RTL Lightning > Routing... it shows empty routing history.
Under RTL "routing peers" tab, it's empty as well.

Sorry if dumb question, but does Umbrel support forwarding/routing to collect fees?

**Comment by junderw** [comment]
yes.

**Comment by steve-vincent** [comment]
Thank you... guess I'll work on more channels. :-D
