### ISSUE TITLE
speed up bitcoin core sync on hdd

### ISSUE THREAD

**Issue by Rothschildiuk** [getumbrel/umbrel#645]
I think it is possible to speed up the synchronization by installing bitcoin-core on the internal memory.
The configuration file  bitcoin.config has a parameter (-blocksdir) that allows you to store blocks on an external drive (HDD).
(https://github.com/bitcoin/bitcoin/blob/b9f41df1ead4b6a83a51fc41966b111c8459c313/doc/files.md)

**Comment by AaronDewes** [comment]
Thanks for your suggestion! This won't be implemented in Umbrel, because we try to write no data to the SD card if possible, because of two reasons:

1. HDDs and SSDs can support more writes than SD cards.
2. We want to allow easy reflash of the OS without loosing any data.
