### ISSUE TITLE
Can't connect to my node through Zap or BlueWallet on Android

### ISSUE THREAD

**Issue by byt3b4ndit** [getumbrel/umbrel#647]
Hi guys!
I am trying to connect Zap and/or BlueWallet through my android phone to my Umbrel node but I can't seem to get it to work. On Zap I always get an error telling me that the Tor connection failed and to make sure that Orbot is running and configured correctly. On BlueWallet I just get a connection error. I have followed the instructions in the Umbrel dashboard exactly as they are written.

What am I doing wrong?

[Screenshots](https://imgur.com/a/ZvUB3Z7)

**Comment by lukechilds** [comment]
Your settings from the screenshots all look correct.

Sometime's Orbot can be a little awkward to get working, can you try the following:

- Quit the wallet app
- Stop Orbot and quit the app (3 dot menu > exit)
- Open Orbot, start it, wait for it to finish connecting to the Tor network
- Then open the wallet app
-  Then try to connect

Can you repeat the above steps ~5-10 times, it should eventually work, let us know if it doesn't.

And Yeah, we know this is really annoying and awkward. BlueWallet will be shipping built in Tor support soon which should be much more reliable and not require any of these steps. Hopefully Zap will too, Zap on iOS already does, it's only Android that doesn't.

**Comment by tommyriska** [comment]
Tried doing the above steps 12 times, no luck at all using BlueWallet.. Tor bundled with BlueWallet will be awesome, really looking forward to that!

**Comment by tommyriska** [comment]
I am able to both connect to Sphinx, Zap and BlueWallet after the latest Umbrel release. Any known PRs that could have fixed this issue?

**Comment by sambradbury** [comment]
Do you have private DNS on? Try turning it off, it will no longer run through Google's DNS which doesn’t recognize .onion. In GrapheneOS Network & Internet > Advanced > Private DNS (Off)

**Comment by nmfretz** [comment]
closing old support issue
