### ISSUE TITLE
Improvement add BOS

### ISSUE THREAD

**Issue by HenryWait** [getumbrel/umbrel#652]
Hi, 
I find it very difficult to keep channels balanced and create meaningful channels. 
Many have suggested BOS https://github.com/alexbosworth/balanceofsatoshis
Adding BOS as an app would be totally awesome, BOS does not have a web interface though and NPM gives me goosebumps when I remember NPM packages that big projects rely on have been infected with crypto seeking malware in the past. 

For now I have installed BOS in a docker container on my umbrel node and it works great, just need to schedule circular re-balances I think.

**Comment by Damontir** [comment]
Would love to have BOS on Umbrel!

**Comment by AaronDewes** [comment]
I already answered this question on Telegram, but I'll share it here too:

> Umbrel is currently focused on apps with a Web UI that are easy to use, but if someone manages to maybe create a minimal web terminal to use bos and port it to Umbrel, we might add it. We are focusing on Umbrel itself currently, and won't port any more apps right now, but we will add more in the future, and if anyone can help with this, it'd be great.

**Comment by jgmontoya** [comment]
I think this issue can be closed as Lightning Shell already includes BOS

**Comment by nmfretz** [comment]
LNDBoss added to the app store! https://apps.umbrel.com/app/lndboss
