### ISSUE TITLE
stuck in a login loop after password: umbrel-manager error: NodeError: Invalid JWT 

### ISSUE THREAD

**Issue by 3x3cut0r** [getumbrel/umbrel#654]
Hi guys
i'm running umbrel (latest docker images) on a debian 10 host (vps) with 32gb RAM, 16 Cores and SSD.
i could successfully run all containers and could do initial setup (creating 24-word password and so on).
i'm running a full node and bitcoind is on progress=1.0000 (successfully synced)

my docker-compose.yml and what i have done you can find here:
https://github.com/3x3cut0r/vps/tree/main/docker/docker-compose/umbrel

now i'm stuck in a login loop after password attempt.
my log is showing this in a endless loop:

`Mar 19 15:36:10 10.21.21.1 be878341e143[636]: umbrel-manager`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]: Invalid JWT`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]: /v1/lnd/wallet/unlock`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]: NodeError: Invalid JWT`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at /app/middlewares/auth.js:38:19`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at allFailed (/app/node_modules/passport/lib/middleware/authenticate.js:107:18)`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:180:28)`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at JwtStrategy.strategy.fail (/app/node_modules/passport/lib/middleware/authenticate.js:302:9)`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at /app/node_modules/passport-jwt/lib/strategy.js:106:33`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at /app/node_modules/jsonwebtoken/verify.js:133:14`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at getSecret (/app/node_modules/jsonwebtoken/verify.js:90:14)`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:94:10)`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at Function.module.exports [as JwtVerifier] (/app/node_modules/passport-jwt/lib/verify_jwt.js:4:16)`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]:     at /app/node_modules/passport-jwt/lib/strategy.js:104:25`
`Mar 19 15:36:11 10.21.21.1 16eef9079800[636]: 10.21.21.11 - - [19/Mar/2021:14:36:11 +0000] "POST /api/v1/lnd/wallet/unlock HTTP/1.1" 401 13 "http://hidden_service_address.onion/" "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]: ::ffff:10.21.21.2 - - [Fri, 19 Mar 2021 14:36:11 GMT] "POST /v1/lnd/wallet/unlock HTTP/1.0" 401 13 "http://hidden_service_address.onion/" "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"`
`Mar 19 15:36:11 10.21.21.1 0ff7ba3b424d[636]: umbrel-middleware`
`Mar 19 15:36:11 10.21.21.1 16eef9079800[636]: 10.21.21.11 - - [19/Mar/2021:14:36:11 +0000] "POST /manager-api/v1/account/refresh HTTP/1.1" 200 198 "http://hidden_service_address.onion/" "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"`
`Mar 19 15:36:11 10.21.21.1 be878341e143[636]: ::ffff:10.21.21.2 - - [Fri, 19 Mar 2021 14:36:11 GMT] "POST /v1/account/refresh HTTP/1.0" 200 198 "http://hidden_service_address.onion/" "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"`
`Mar 19 15:36:11 10.21.21.1 be878341e143[636]: umbrel-manager`
`Mar 19 15:36:12 10.21.21.1 0ff7ba3b424d[636]: Invalid JWT`
`Mar 19 15:36:12 10.21.21.1 0ff7ba3b424d[636]: /v1/lnd/wallet/unlock`
`...`

some ideas?

**Comment by mayankchhabra** [comment]
Sorry about the issue, @3x3cut0r. Have you tried a restart already? 

```sudo scripts/stop && sudo scripts/stop```

**Comment by 3x3cut0r** [comment]
Yes i did. but this doesn't helped.
I played a little bit with the umbrel-lnd lncli ... i could successfully unlock my wallet there with the password. so i tryed to change it with no success. but after that i could login with tor. i restarted lnd and the whole stack later and now i can successfully login.
i'm not sure what exactly the error was and what i have done that its now working ...

i think that issue can be closed

ps: is there a way on cli how i can change my password? because over gui it is not possible in my case, because my stack is running without root permissions and the manager has no access to my docker.sock to control/restart the containers ...

thank you anyway

**Comment by nmfretz** [comment]
closing old support issue
