### ISSUE TITLE
App fails to uninstall if it uses same container as other app

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel#655]
Samourai and Mempool both use the mariadb container. When uninstalling one of those while both are installed, docker-compose tries to delete the mariadb image, but mariadb is still needed for the other app, so the uninstall fails & crashes. Not sure if we or docker-compose needs to fix this.

https://github.com/getumbrel/umbrel/blob/master/scripts/app#L177

**Comment by lukechilds** [comment]
Are you sure the uninstall fails and crashes?

I thought I tested this and docker-compose prints an error that it can't remove an image in use by something else but still exits cleanly.
