### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by praptoumache** [getumbrel/umbrel#658]
Hi,

ran the setup. cant register. getting those errors on my browser console
![image](https://user-images.githubusercontent.com/57391596/112272992-bd99cb80-8c74-11eb-9894-f1550a12f024.png)

**Comment by wouterds** [comment]
Keep getting the same ("Not allowed by CORS"), tried a few workarounds mentioned here in a some other issues but none of them work.

**Comment by nmfretz** [comment]
closing old support issue
