### ISSUE TITLE
getumbrl/electrs image fails to install 

### ISSUE THREAD

**Issue by cakebread** [getumbrel/umbrel#659]
Starting Docker services...

Pulling electrs (getumbrel/electrs:v0.8.6@sha256:ecca81b063b23f08414bab91b4cf164b6cb6a485ddede5c1f5810883318954e3)...
sha256:ecca81b063b23f08414bab91b4cf164b6cb6a485ddede5c1f5810883318954e3: Pulling from getumbrel/electrs
ERROR: no matching manifest for unknown in the manifest list entries

**Comment by cakebread** [comment]
Updated to latest Docker (20.10.5, build 55c4c88) on Raspberry Pi OS, now I get this message instead:

Pulling electrs (getumbrel/electrs:v0.8.6@sha256:ecca81b063b23f08414bab91b4cf164b6cb6a485ddede5c1f5810883318954e3)...
docker.io/getumbrel/electrs@sha256:ecca81b063b23f08414bab91b4cf164b6cb6a485ddede5c1f5810883318954e3: Pulling from getumbrel/electrs
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by AaronDewes** [comment]
Yeah, umbrel doesn't work on the 32bit version of RPi OS. Use the arm64 version.

**Comment by wouterds** [comment]
Figured this out as well yesterday, can confirm that you can run it on Raspbian Lite beta https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/

**Comment by nmfretz** [comment]
closing old support issue
