### ISSUE TITLE
Unable to disable Tor in Umbrel settings

### ISSUE THREAD

**Issue by mitchdowney** [getumbrel/umbrel#661]
When I go to the settings for my Umbrel Lightning node and try to disable Tor, I can't toggle it off, and a message pops up that says:

"Sorry, cannot disable Tor for now"

I am trying to send lightning payments to my address, but it is not working as it says "cannot find route". My theory is that the Tor is making it inaccessible to people sending from a non-Tor address, but I'm a noob and have not been able to verify. Any help would be greatly appreciated.

**Comment by esackbauer** [comment]
This has nothing to do with Tor. Receiving a Lightning payment while have nothing spent so far would create a higher balance in your Lightning wallet that what is guaranteed with the blockchain transaction. So its not possible unless you spend something first.
https://blog.muun.com/the-inbound-capacity-problem-in-the-lightning-network/

**Comment by nmfretz** [comment]
closing old support issue
