### ISSUE TITLE
Add more checks to the partition script to check for existing umbrel install

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel#68]
Can't find the old issue but this is still the case right now where if the SD card is reflashed there is a chance the install is st

I've experienced this and have seen it pop up on our telegram a few times. 

## Notes

- Affects "Umbrel OS v0.0.4-beta.4", but will check master too and see if this is still the case

**Comment by nolim1t** [comment]
We need to modify this bit of code here to verify existing structure

https://github.com/getumbrel/umbrel/blob/0277601d175e1c49323b7d36e277fa93d20f192b/scripts/umbrel-os/boot#L30

**Comment by lukechilds** [comment]
I'm currently working on this.

**Comment by nolim1t** [comment]
cool THanks @lukechilds

**Comment by mayankchhabra** [comment]
Closed by #93
