### ISSUE TITLE
Preserve lnd.conf during umbrel update

### ISSUE THREAD

**Issue by cubiclestorm** [getumbrel/umbrel#682]
I setup my node in umbrel 0.3.7
I added a custom alias and color by modifying lnd.conf
After the update the customizations were gone. I had to edit the conf file again and reboot.

**Comment by louneskmt** [comment]
Hey! This is an expected behaviour, for now. It allows us to have all users to have the same configuration, and it is then way easier to troubleshoot issues. Keep in my mind that Umbrel is still in beta.

**Comment by feikede** [comment]
Actually, a conf-dir solution like common in apache2 or systemd would be cool. But that would be a change request for lnd  I think.

**Comment by nmfretz** [comment]
This is no longer an issue with the Lightning Node app being moved to the app store and the Advanced Settings settings feature being added to allow easy modification of config parameters like alias and colour.
