### ISSUE TITLE
[Feature request] Show hw status in web Dashboard

### ISSUE THREAD

**Issue by yik77** [getumbrel/umbrel#685]
It may be practical to show some basic hw/sw status in the dashboard, perhaps even before login (and certainly after user login)...
What I have in mind is a simple section to show uptime, load, memory, cpu, temperature, network traffic in/out...for the beginning current, later with the history/chart of those...I am pretty sure many would appreciate it.

**Comment by Darth-Coin** [comment]
Yes, would be nice to have on the dashboard a simple system status display, showing the % in use of CPU, RAM, swap, disk and also with a  drop down by Umbrel apps usage %. Temperature of disks will be useful for so many RaspPi with Umbrel.

Think about total noobs (I saw many installing Umbrel now) that do not know what is going on inside the machine and don't know how to start a linux command to check that. Many are check their dashboard just from a simple mobile phone browser...

**Comment by nmfretz** [comment]
Closing old issue. This feature was added to https://github.com/getumbrel/umbrel-dashboard
