### ISSUE TITLE
Not allowed by CORS

### ISSUE THREAD

**Issue by SmartCorporate** [getumbrel/umbrel#687]
This alarm come out either when I finish entering the 24 words or even if I skip to them later, I looked at the old issue but they didn't solve my problem, can you help me? I am using the latest version of UBUNTU

**Comment by louneskmt** [comment]
What url are you accessing from?

**Comment by phenomeus** [comment]
https://github.com/getumbrel/umbrel/issues/398 ?

**Comment by SmartCorporate** [comment]
@phenomeus , thx #398 , but not solving. Any other idea?

**Comment by phenomeus** [comment]
not anymore, I have this issue since 0.34 or something, no I even can't fix it with mentioned workaround in 0.38

**Comment by ChowSinWon** [comment]
didn't try the actual fix #708 but as far as i could see the idea is to add the port that has been set with NGINX_PORT to the allowed hosts (like in #398).
i added the port by myself and it worked for me.

**Comment by phenomeus** [comment]
where did you added this? @ChowSinWon

**Comment by ChowSinWon** [comment]
@phenomeus i added `:${NGINX_PORT}` to every host in the DEVICE_HOSTS-definition in `scripts/start`
like that:
```
DEVICE_HOSTS="http://${DEVICE_IP}:${NGINX_PORT},http://${DEVICE_HOSTNAME}.local:${NGINX_PORT},https://${DEVICE_HOSTNAME}.local:${NGINX_PORT},http://${DEVICE_HOSTNAME}:${NGINX_PORT},https://${DEVICE_HOSTNAME}:${NGINX_PORT}"
```

because i have on that system a service that is already listening on port 80 i need to set a different port when starting up umbrel:
```
sudo NGINX_PORT=3080 ./scripts/start
```

btw. the onion/tor address does not need that port

**Comment by phenomeus** [comment]
*runningtotrythisout*

**Comment by phenomeus** [comment]
workaround is not working anymore with 0.4.2 @ChowSinWon @lukechilds @louneskmt 

any chance to fix this once and for all?

**Comment by DRiOscar** [comment]
Hi @phenomeus,

Mostly update Umbrel by CLI mode
```
sudo ./scripts/stop
sudo update/update --repo getumbrel/umbrel#v0.4.2
# modify the scripts/start with the PR diff
sudo NGINX_PORT=$YOUR_NGINX_PORT ./scripts/start
```

**Comment by nmfretz** [comment]
closing old support issue
