### ISSUE TITLE
unauthorized authentication error when pulling the nginx container

### ISSUE THREAD

**Issue by kennethacurtis** [getumbrel/umbrel#691]
I'm not sure why but it looks like it's not letting me pull down the docker container. I'm able to pull the other containers easily.

I checked the sha256 and it looks like the numbers might be off?

https://hub.docker.com/layers/nginx/library/nginx/1.17.8/images/sha256-f402feb555ea23c246ca985ea257a75aff38bc9f9234bebda712353c6f16db9d?context=explore

```
# sudo ./scripts/start

======================================
============= STARTING ===============
============== UMBREL ================
======================================

Setting environment variables...

Starting karen...

Starting backup monitor...

Starting decoy backup trigger...


Starting Docker services...

Pulling nginx (nginx:1.17.8@sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03)...
ERROR: Error initializing source docker://registry.hub.docker.com/repository/nginx@sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03: Error reading manifest sha256:380eb808e2a3b0dd954f92c1cae2f845e6558a15037efefcabc5b4e03d666d03 in registry.hub.docker.com/repository/nginx: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

```

Has anyone else had trouble with this?

**Comment by louneskmt** [comment]
It works well for me. The checksum correspond to the repo she so no problem. Have you tried to reboot, or restart Docker?

**Comment by kennethacurtis** [comment]
Tried a reboot, still can't pull it. I'm going to try and play around with my docker settings, but so far this has left me stumped

**Comment by Ruppsn** [comment]
What happens if you pull the Image with a simple `docker pull` command? Can you paste the output?

**Comment by Ruppsn** [comment]
:thinking: 
nginx should be a repository where you don't need to authorize at dockerhub.

I can pull the latest nginx image with `docker pull nginx` and i can also pull the nginx:1.17.8 image.

Could you try making an account for docker.hub and do a login at your server? 
`docker login`
Then try again to pull the nginx image.

What OS do you use? What version of docker and docker-compose are your running?

**Comment by nmfretz** [comment]
closing old support issue
