### ISSUE TITLE
Bitcoin core keeps shutting down and restarting: Fatal LevelDB error

### ISSUE THREAD

**Issue by w1ngsss** [getumbrel/umbrel#692]
After running and enjoying Umbrel for a couple of days, I can no longer log into the dashboard with the startup screen stuck at 'Loading Bitcoin Core... This can take a while, please don't turn off your Umbrel!'

Digging into the debug file, I could see the bitcoin core container keeps shutting down after encountering a 'Fatal LevelDB error'

I still have full access to Umbrel using ssh and the user password. Unfortunately, as I do have a set of seed phrases written down, I am not 100% certain which one belongs to my Umbrel wallet. Is there a way to confirm the correct seed phrase through ssh?

If there is no harm in reflashing the SD even without the correct seed phrase at hand, I am more than happy to do so. If not, I would very much appreciate any thoughts and suggestions.

Thank you very much

Debug log:
[https://umbrel-paste.vercel.app/6h00mrj](https://umbrel-paste.vercel.app/6h00mrj)

**Comment by Ruppsn** [comment]
Your seed phrase is everything you need to restore your wallet with your coins. 
I think your DB got corrupted. Is the data inside the container stored on the ssd or the sd card?

**Comment by w1ngsss** [comment]
Thank you for getting back to me!

The issue was eventually resolved by reindexing (by adding the respective flag in the bitcoin.conf) and resetting umbrel to stock settings.
I suspect the reset might have been unnecessary, though.

The seed phrase restored all transactions and balances. Funds are safu!

I think the data is stored on the SSD. I don’t know too much about this as I just followed the basic install instructions.

**Comment by lestephane** [comment]
Had the same problem, here is what I documented for myself

## Recovering from a corrupted index

### Problem

```
bitcoin              | 2021-07-05T08:43:18Z Opening LevelDB in /data/.bitcoin/indexes/txindex
bitcoin              | 2021-07-05T08:43:18Z Fatal LevelDB error: Corruption: error in middle of record: /data/.bitcoin/indexes/txindex/209760.log
```

### Solution

```
$ ipscan # figure out the ip address of the umbrel (don't forget to allow out ssh)
$ ssh -t umbrel@umbrel.ip
umbrel$ rm -rf ~/umbrel/bitcoin/indexes && sudo reboot
```
