### ISSUE TITLE
electrs seems to be taking too much memory

### ISSUE THREAD

**Issue by joaojoyce** [getumbrel/umbrel#695]
Been syncing my node for the last week and it is finally complete. 

Now I can't open the umbrel dashboard on "Loading bitcoin core...".
After signing in with ssh I've noticed that electrs is taking a lot of CPU and memory

<img width="553" alt="Screen Shot 2021-04-02 at 13 02 32" src="https://user-images.githubusercontent.com/5451182/113414045-f42dbf80-93b3-11eb-9c43-905d4826c932.png">

I have the following apps installed:

Mempool
RTL
Lightning terminal

What is going on here? 
Is this something that will go away eventually?

**Comment by lukechilds** [comment]
Yeah, electrs takes ~8 hours to index after Bitcoin Core has finished it's initial sync. Once that's completed CPU and memory use will be much lower.

**Comment by joaojoyce** [comment]
Hey, thank you. 

Might be useful to add some notice somewhere. Not sure where.

I will close this for now. 
Thank you.

**Comment by lukechilds** [comment]
Yeah I agree, we definitely need to communicate this better.

**Comment by blckbx** [comment]
Definitely! But this is a good start -> https://info.umbrel.tech/getting-started.html 
Installing apps before electrs is done compacting can produce errors with add-ons like mempool and btc_rpc_explorer. I'd recommend disabling add-ons until electrs' work is done.

**Comment by TylonHH** [comment]
so my Pi 5 with 8GB was finished with syncing with btc blockchain and also electrs awas 100% synced.
But electrs still uses 25% CPU
