### ISSUE TITLE
Cannot connect with Zap (desktop + android)

### ISSUE THREAD

**Issue by bezysoftware** [getumbrel/umbrel#696]
On top of the existing #647 I am also unable to connect via Zap for desktop (Windows 10 x64). Here's the error:

![image](https://user-images.githubusercontent.com/6108688/113452751-f3714980-9404-11eb-9068-bd2baad66803.png)

I can provide more info if you tell me what you need to debug it

**Comment by Darth-Coin** [comment]
Try adding in your hosts file (C:\Windows\system32\drivers\etc\hosts this line
192.168.1.xxx node.local

**Comment by nmfretz** [comment]
closing old support issue
