### ISSUE TITLE
LNbits webhook not working

### ISSUE THREAD

**Issue by steve-vincent** [getumbrel/umbrel#698]
With LNbits you can create invoices via API:

curl -X POST http://192.168.1.123:3007/api/v1/payments -d '{"out": false, "amount": <int>, "memo": <string>, "webhook": <url:string>}' -H "X-Api-Key: XXXXXXXXXXXXXXXXXXX" -H "Content-type: application/json"

The webhook url should be called when the invoice is paid.
This is not working on Umbrel. After the invoice is paid, the webhook status remains "not sent yet" and is never called.

Webhooks with invoices are necessary to use LNbits as a payment API (in my opinion, it's most exciting use case).

**Comment by steve-vincent** [comment]
PS - I just found this is also reported about Umbrel on LNBits project:
https://github.com/lnbits/lnbits/issues/167

**Comment by Darth-Coin** [comment]
LNbits under Umbrel works ONLY under Tor access.
So switch using it only from the onion address and all will be fine.

**Comment by steve-vincent** [comment]
This issue is now fixed with with latest Umbrel update
