### ISSUE TITLE
I can't connect walltet to my umbrel.

### ISSUE THREAD

**Issue by Rothschildiuk** [getumbrel/umbrel#704]
I have a problem with connection electrum (desktop).

![image](https://user-images.githubusercontent.com/15833131/114319148-7df62f00-9b10-11eb-974f-116cfb4e9315.png)
![image](https://user-images.githubusercontent.com/15833131/114319168-8fd7d200-9b10-11eb-8f29-64598eb81503.png)
![image](https://user-images.githubusercontent.com/15833131/114319179-9bc39400-9b10-11eb-9d5a-b9b46bf57fab.png)

**Comment by Rothschildiuk** [comment]
this instruction is wrong
![image](https://user-images.githubusercontent.com/15833131/114622920-e4b14f00-9cae-11eb-81d5-9f8b6b7d60c7.png)
after install tor you must start tor in terminal

**Comment by louneskmt** [comment]
No, it's not. Tor service is automatically started on install. You can check that running `brew services list`.
