### ISSUE TITLE
Using seed with BIP39 Passphrase

### ISSUE THREAD

**Issue by slashbinslashnoname** [getumbrel/umbrel#705]
Hey,
There is an incompatibility with BIP39.

I would like to use umbrel, but when I type my seed which is passphrase protected, getumbrel says that the seed is not valid and it stalls the process of user creation.

**Comment by lukechilds** [comment]
That's right, Umbrel uses Aezeed seed phrases, not BIP39 seed phrases, the two are incompatible.
