### ISSUE TITLE
How to avoid the long initial block download by providing the bitcoin block directory from an existing trusted node?

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel#714]
If I have already a bitcoin-core node at home that has the entire blockchain, I'd like to be able to setup umbrel using
the hundreds of gigabytes of blockchain data I already have. No point in redownloading everything.

Besides, I may have to setup / recover umbrel many, many times (this is all beta, right?), and reseeding from this known-good blockchain data somewhere on the data drive will save time.

**Comment by louneskmt** [comment]
Check this for instructions: https://github.com/getumbrel/umbrel-os/issues/119

**Comment by lestephane** [comment]
Thanks, I wasn't aware I had to look for duplicates in that other project.
