### ISSUE TITLE
Consider using podman instead of dockerd

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel#717]
Podman runs in rootless mode, compared to what I'm seeing here, where any supply chain attack could cause code to run as root in the host.

Tor seems to be running as a non-root user, which is good.

![image](https://user-images.githubusercontent.com/5460884/114704716-97c18d00-9d2f-11eb-85fe-ed028849d093.png)

**Comment by lukechilds** [comment]
Yep we're aware some of the permissions are a little lax, this is something we intend to fix, it just hasn't been a priority yet. Checkout our security document for some of the tradeoffs we've made so far: https://github.com/getumbrel/umbrel/blob/master/SECURITY.md

All app containers currently run as non-root. Some of the Umbrel core containers are non-root and some are root. There's no need for any of them to be root, we plan to resolve that.

>any supply chain attack could cause code to run as root in the host.

When you say "supply chain attack" what are you referring to here? I assume not a physical supply chain attack? A malicious dependency inside a container? Pretty much everything is running in containers, with very limited host filesystem access. So if there was a malicious dep inside a root container, it'd just have access to read/write data on the host for that specific services volume.

**Comment by lestephane** [comment]
I meant by supply chain attack a malicious dependency inside a container.
