### ISSUE TITLE
Transaction shown in Umbrel but unbroadcasted and invisible from cli

### ISSUE THREAD

**Issue by jorian** [getumbrel/umbrel#719]
So I have this weird case: yesterday I wanted to move some funds from my Umbrel node. All went OK gui-wise, but when I click the transaction, the transaction on mempool.space is not shown. 

When I then SSH into Umbrel, and i do a `listtransactions` call against bitcoin-cli, nothing is shown. Also, the address from which I did the transaction shows `is_mine: false`, and the result of `getrawtransaction <txid>` is just nothing. The balance from `getwalletinfo` is 0.

What happened here? The bitcoin/debug.log doesn't really show that a transaction took place either.

**Comment by AaronDewes** [comment]
Umbrel uses lnd for wallet managment, so you can only get transactions via `lncli`, not `bitcoin-cli`.

**Comment by jorian** [comment]
Thanks, I worked it out :)
