### ISSUE TITLE
Loading Bitcoin Core... This can take a while, please don't turn off your Umbrel!

### ISSUE THREAD

**Issue by randomuser11111** [getumbrel/umbrel#723]
Umbrel has been stuck at "Loading bitcoin core" for about 24 hours.

Is this normal, should I wait longer or take any action?

Error log:
https://umbrel-paste.vercel.app/a220ute

**Comment by AaronDewes** [comment]
Hey! Please SSH into the Pi and execute the following command to reindex the blockchain:

`echo reindex=1 >> ~/umbrel/bitcoin/bitcoin.conf && sudo reboot`


After it's synced 100%, run this to stop it from reindexing on a future restart:

`sed -i "s/reindex=1//g;" ~/umbrel/bitcoin/bitcoin.conf && sudo reboot`

**Comment by blckbx** [comment]
@AaronDewes Is it safe to reboot without stopping umbrel first?

**Comment by AaronDewes** [comment]
> @AaronDewes Is it safe to reboot without stopping umbrel first?

Via the SSH command I mentioned, yes. Umbrel OS automatically stops Umbrel in this case.

**Comment by blckbx** [comment]
How's the case with umbrel on custom linux installation?

**Comment by AaronDewes** [comment]
> How's the case with umbrel on custom linux installation?

Until the official Umbrel installer is released, you should run `sudo ./scripts/stop` before turning the node off.

**Comment by blckbx** [comment]
Thanks!

**Comment by randomuser11111** [comment]
> 
> 
> Hey! Please SSH into the Pi and execute the following command to reindex the blockchain:
> 
> `echo reindex=1 >> ~/umbrel/bitcoin/bitcoin.conf && sudo reboot`
> 
> After it's synced 100%, run this to stop it from reindexing on a future restart:
> 
> `sed -i "s/reindex=1//g;" ~/umbrel/bitcoin/bitcoin.conf && sudo reboot`

Thank you, it worked. So now it has to download and verify the entire blockchain again, losing all progress?
Or am I confusing reindexing with syncing?
Is there any way to avoid this in the future?

**Comment by bmanion** [comment]
https://github.com/getumbrel/umbrel/issues/723#issuecomment-821520993

This same issue is happening with me where it freezes at: "Loading Bitcoin Core... This can take a while, please don't turn off your Umbrel!" for more than 24 hours. I want to fix it but I do not know how to 'SSH into the Pi' to execute the command you wrote. Can you please guide me or even direct me to a source to learn how to do this? Thank you.

**Comment by bmanion** [comment]
> Hey! Please SSH into the Pi and execute the following command to reindex the blockchain:
> 
> `echo reindex=1 >> ~/umbrel/bitcoin/bitcoin.conf && sudo reboot`
> 
> After it's synced 100%, run this to stop it from reindexing on a future restart:
> 
> `sed -i "s/reindex=1//g;" ~/umbrel/bitcoin/bitcoin.conf && sudo reboot`

Dear Aaron, Thank you for helping to solve this issue. I am new to running a Bitcoin node and do not know how to 'SSH into the Pi' to execute the command you wrote. Can you please guide me or even direct me to a source to learn how to do this? 
Thank you kindly for your help.

**Comment by AaronDewes** [comment]
This might not be the issue for you. Please join us on Telegram and follow t.me/getumbrel/50080

**Comment by nmfretz** [comment]
closing old support issue
