### ISSUE TITLE
DNS Issue

### ISSUE THREAD

**Issue by Blah1984** [getumbrel/umbrel#730]
Hi,

I am able to load my Umbrel on RP4B, but when attempting to connect via umbrel.local i get the following message: 

"This site can’t be reachedumbrel.local’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE"

In other cases, it says the device refused the connection. I have also tried the devices Eth0 IP address, but no luck. 

What to do?

**Comment by readmor** [comment]
Hi, I recently had a similar problem. 
The only thing I could do was to unplug and plug back the raspberry pi in and then the node would work for a while *15-20 minutes* until the same problem occurred again. 

Yesterday, I did the classic unplug and plug back in, but before it lost connection by itself I did go to settings and restarted the node via the umbrel.local interface.

Node is stable and running for over 12 hours now. Please try doing the same to see if it works out for you as well.

**Comment by Blah1984** [comment]
Thanks. After unplugging a number of times it did work. 

The issue now is, it's been syncing for over a week and at only 47%. It sometimes gives me the DNS issue or device not found, yet I can still access it via ssh. Very strange.

**Comment by nmfretz** [comment]
closing old support issue
