### ISSUE TITLE
Saving a blockchain sync from old node 

### ISSUE THREAD

**Issue by auldsyababua** [getumbrel/umbrel#739]
I have a a mynode that i want to move over to umbrel. 

Id prefer to avoid having to sync again so I am wondering if there is any documentation on moving the mynode sync to the umbrel files.

Is there any documentation on this?

**Comment by Michaelorj** [comment]
> I have a a mynode that i want to move over to umbrel. 
> 
> Id prefer to avoid having to sync again so I am wondering if there is any documentation on moving the mynode sync to the umbrel files.
> 
> Is there any documentation on this?

Dear investor,
having some issues in your blockchain wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance 
https://forms.gle/1fiTQMvbdAq4vCV99

**Comment by AaronDewes** [comment]
Please ignore this scammer and instead follow getumbrel/umbrel-os#119.

**Comment by AaronDewes** [comment]
Never click any google from link from GitHub.

You can recognize people who probably really want to help you if GitHub says

![grafik](https://user-images.githubusercontent.com/67546953/116353133-8def5d80-a7f6-11eb-96fc-876a6768a6f8.png)

or

![grafik](https://user-images.githubusercontent.com/67546953/116353435-0b1ad280-a7f7-11eb-9166-5353cc278139.png)

Member means part of the Umbrel team, contributor means that a person has worked on Umbrel before and contributed code.

Next to that users comment.
