### ISSUE TITLE
Running the umbrel node on a schedule (ie shutdown cleanly at specific times)

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel#743]
I'd like the option to configure when the node shuts down _cleanly_ on a schedule (crontab like), so that I can be sure that the node is off at the time the actual timer for the power socket (to which router + node are connected) switches the power off. Everything shuts down at bed time at my place. 

Currently, there is no clean shutdown, the power just stops, and I feel this will potentially leave the node in a corrupted state. In time, umbrel will be resilient to sudden poweroffs, but i don't think it has reached this point yet. And a corrupted node takes a long time (or worse) to come back up. 

Is this possible in some way? Manual steps are OK. UI would be even better.

**Comment by lestephane** [comment]
Is there a way to achieve something close to my intent by adding a clean shutdown command to the crontab?
I've seen this command used in issues and Telegram:

```
sudo systemctl stop umbrel-startup
```

Does that do a clean shutdown / halt?

**Comment by lukechilds** [comment]
No, that just stops the Umbrel service. You can just run `sudo poweroff` if you want to shutdown which will cleanly stop all services and then power off the system.

**Comment by lestephane** [comment]
This works:

```
(as umbrel)
$ sudo crontab -e
...
mm hh * * * /sbin/poweroff >> /root/poweroff.log 2>&1
```

**Comment by lestephane** [comment]
This one adds more info to the poweroff.log (for later troubleshooting)

```
mm hh * * * /bin/sh -c "/bin/date && /bin/sync && /sbin/poweroff" >> /root/poweroff.log 2>&1
```
