### ISSUE TITLE
LND is not unlocked after update from 0.3.8 -> 0.3.9

### ISSUE THREAD

**Issue by dlq84** [getumbrel/umbrel#746]
Hi. I couldn't get log in to Telegram for some reason, so I'm sorry for writing an issue instead.

So, at first I noticed that the dashboard was stuck and never showed my balance, even after waiting for 30 minutes and a restart of all the containers (./scripts/stop, ./scripts/start).

When I look at the logs the middleware say `LndUnlocker: Wallet failed to unlock!`

And lnd says ```Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.```

~~What happened, and how do I recover from this?~~

Thank you.

EDIT: It worked to manually unlock lnd, but that's not something I should have to do, right?

**Comment by lukechilds** [comment]
Those logs are expected and only briefly appear the first time Umbrel is run after the 0.3.9  update. Please restart Umbrel so you see those `LndUnlocker: Wallet failed to unlock!` logs again. Then log in to the Umbrel dashboard. The act of logging in to the Umbrel dashboard will capture your password and run through the 0.3.9 migration logic with your password.

After that the LND wallet should be auto unlocked every time.

**Comment by nmfretz** [comment]
closing old support issue
