### ISSUE TITLE
Feature request - Disable dashboard in IBD phase

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#750]
Guys, many noobs starting with Umbrel node are doing crazy stuff exactly when they should just stay calm and wait for IBD.
I saw many users trying to do various stuff in IBD and also getting panicked and restarting the node, messing around the whole data.
I suggest this feature:
- disable access to dashboard in IBD phase
- put just a percentage of syncing blocks
- add a message to BE PATIENT, all is going to be fine, don't panic :)
- meanwhile read the "getting started" instructions from info.umbrel.tech
- if something is really getting wrong (machine get stuck, disk disconnected etc), then yes, put a message or instructions what to do next. In this way, users will be more comfortable and know what to do.

**Comment by pjw65** [comment]
Yes and also add a progress for indexing the blocks after synching.
I wait since 4 days for the end of indexing.
txindex at 584006
basic block filter index at 622141

**Comment by AaronDewes** [comment]
@pjw65 What hardware are you using, do you have apps installed?

**Comment by pjw65** [comment]
@AaronDewes 
ASUSTeK P7P55 LX
i7 CPU  860  @ 2.80GHz (8 processors, 4 actual cores)
LACIE Porsche Design Desktop Drive P9233 5TB / USB
Ubuntu 20.04 Mate

**Comment by nmfretz** [comment]
Closing issue. Bitcoin app has been extracted to the app store.
