### ISSUE TITLE
getrawtransaction and gettxoutproof on Umbrel

### ISSUE THREAD

**Issue by StyriaTrading** [getumbrel/umbrel#760]
How can I use this console commands within umbrel?

I want to do a Liquid-peg-in and need these information for doing it on Elements Core.

https://help.blockstream.com/hc/en-us/articles/900000632703

Also see here Step 7.

This seems not possible with a pruned node.

**Comment by louneskmt** [comment]
You can find the `bitcoin-cli` executable under the `bin` directory. 

For example, on Umbrel OS:
```
~/umbrel/bin/bitcoin-cli getblockchaininfo
```
