### ISSUE TITLE
Bitcoin wallet and lnd wallet do not sync

### ISSUE THREAD

**Issue by jeansonson** [getumbrel/umbrel#764]
I have set up the umbrel node with umbrel version 0.3.9 and bitcoin core version v.0.21.0.
Blockchain has been fully synchronized but I am not able to get the bitcoin address?! It says "Bitcoin wallet synchronizing" and doesnt show any bitcoin address to send btc to (e.g. clicking on deposit). Same for lightning wallet.

Any idea? Thanks

**Comment by louneskmt** [comment]
Hey! Sorry for the trouble. Have you tried to reboot your Umbrel?

**Comment by jeansonson** [comment]
Sure I did.

**Comment by jeansonson** [comment]
Just solved by itself after one week...
