### ISSUE TITLE
Zap (Desktop) connection string at /connect/zap-desktop is an umbrel.local address (not onion V3)

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel#765]
Is there a reason for this?

It's an onion address for both Zap (Android) and Zap (IOS). Albeit _not the same one_...

Explanation, pointer to know issue(s) welcome.

I don't connect through umbrel.local unless troubleshooting. So if umbrel.local is a must for Zap (Desktop), it basically rules it out for me.

**Comment by louneskmt** [comment]
Unfortunately, Zap Desktop doesn't support Tor yet. Correct me if I'm wrong and I'll edit the instructions.

**Comment by lestephane** [comment]
+1'd https://github.com/LN-Zap/zap-desktop/issues/3620
and subscribed to it, so I can come back here when it's fixed on their side.
