### ISSUE TITLE
Feature request - VPN optional setting - user defined (or presets)

### ISSUE THREAD

**Issue by teasider** [getumbrel/umbrel#766]
Hi,
Some people would want to run a node but would be "port locked" behind routers - if it's collage dorm, a tough house hold or even the office.

This is easily bypassed by using a VPN on open ports like 443.
Some VPN providers allow this type of connection (like PrivateInternetAccess and some others)

Would be great if there could be an optional setting to enter the VPN remote server address with port and username\password to connect the node. (tor wont work when "port locked" but will work through a VPN connection)

**Comment by nolim1t** [comment]
This is not needed because umbrel uses tor by default to protect privacy and security.

**Comment by teasider** [comment]
> This is not needed because umbrel uses tor by default to protect privacy and security.

I understand , but a connection to tor cant be established when ports are blocked on the router.

**Comment by AaronDewes** [comment]
If you need a VPN, you can apply it manually via SSH. Integrating this into the UI seems impossible to me, because if the dashboard doesn't work, you can't change settings on it.

**Comment by teasider** [comment]
Seems about right, Didnt know you can add additional things on ssh.
thanks.
