### ISSUE TITLE
Feature request - User to be able to set fix IP for node machine

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#784]
I saw many users having problems with accessing node in their LAN and with no networking knowledge whatsoever.
Let's make it easier for them (I know that is better for them to learn how to do it...) and add a feature in settings or during setup, to add a fix IP for their node machine.

This will avoid many future problems.

**Comment by maltokyo** [comment]
Just do that on your router, map the MAC address to a fixed IP

**Comment by Darth-Coin** [comment]
@maltokyo I know how to do that, I know how to set a fix IP on a machine and add it to hosts file if I want.
But my request was for users that have no idea what is a router or how to configure it and I saw many.
This feature can be done in the setup process, by simply make the user to input an IP from his LAN.
The majority of users that started with Umbrel are windoze users and put them to enter in the belly of Umbrel will make more harm than good.
