### ISSUE TITLE
Dashboard not showing any data

### ISSUE THREAD

**Issue by randomuser11111** [getumbrel/umbrel#785]
The blockchain is not yet fully synchronized, the Troubleshoot is not finding any errors.

On the bitcoin dashboard the synchronized percentage/latest blocks etc are not showing up (grayed out), even after a long time.

Is there a way check the syncing status via command line or some other method, so I know if the Umbrel is still synchronizing? Or is there some other error?

**Comment by pjw65** [comment]
I have the same since 4 days.
I find out, that there is still work to do.

`tail -f bitcoin/debug.log`
tells me the progress on synching txindex and block filter index. 

Last block at the time of writing is 682341.

**Comment by nmfretz** [comment]
closing old support issue
