### ISSUE TITLE
umbrel.local DNS is not resolving

### ISSUE THREAD

**Issue by jpujari** [getumbrel/umbrel#790]
I can't get to umbrel.local on my laptop. It works when I reboot the raspberry pi for some time and then it stops resolving. Please help.

**Comment by jpujari** [comment]
network is unreachable when running start

```
umbrel@umbrel:~/umbrel $ sudo ./scripts/start

======================================
============= STARTING ===============
============== UMBREL ================
======================================

Setting environment variables...

RTNETLINK answers: Network is unreachable

```

**Comment by Darth-Coin** [comment]
I wrote a guide for initial steps of what to do to about this
https://community.getumbrel.com/t/guide-umbrel-local-not-accessible-what-to-do/845

**Comment by jpujari** [comment]
setting a fixed IP seems to work. Thanks for the article.
