### ISSUE TITLE
[Feature request] Add watchtower into Umbrel dashboard

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#792]
It would be nice and useful that Umbrel users will have a simple option, tick box, in Umbrel dashboard settings, to activate a watchtower from a friend or other node that is providing this service.
Slowly this will be needed.... or a must have.
A start here
https://github.com/talaia-labs/python-teos

**Comment by jlatone** [comment]
Speaking of which, can I simply run a "Private Altruist Watchtower" (https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md) on my current umbrel from your lnd image, or has the watchtower service not been compiled into it?

**Comment by steve-vincent** [comment]
> It would be nice and useful that Umbrel users will have a simple option, tick box, in Umbrel dashboard settings, to activate a watchtower from a friend or other node that is providing this service.
> Slowly this will be needed.... or a must have.
> A start here
> https://github.com/talaia-labs/python-teos

while the simple dashboard UI sounds nice.... is there even a way to add a watchtower for my umbrel node? where does one find such a service?

**Comment by IanMichaelHarper** [comment]
> > It would be nice and useful that Umbrel users will have a simple option, tick box, in Umbrel dashboard settings, to activate a watchtower from a friend or other node that is providing this service.
> > Slowly this will be needed.... or a must have.
> > A start here
> > https://github.com/talaia-labs/python-teos
> 
> while the simple dashboard UI sounds nice.... is there even a way to add a watchtower for my umbrel node? where does one find such a service?

https://bitcoinmagazine.com/guides/how-to-set-up-watchtower-lightning-node

**Comment by nmfretz** [comment]
For those who come across this old issue, this is now possible in the Lightning Node app by going to Advanced Settings --> Watchtower and enabling `Watchtower Client` with your watchtower URI of choice.
