### ISSUE TITLE
how to open lightning channel from cli

### ISSUE THREAD

**Issue by jpujari** [getumbrel/umbrel#794]
I bought lightning inbound liquidity from bitrefill, they provided lncli command to add the purchased liquidity. Where do I run this command on the umbrel server? which container should I run it in? I have installed RTL and opened channels via their GUI

**Comment by louneskmt** [comment]
Executables are available under ˋ~/umbrel/bin`. 

Example:

```shell
~/umbrel/cli/lncli connect <peer>
```
