### ISSUE TITLE
[ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: unable to find node

### ISSUE THREAD

**Issue by Ruppsn** [getumbrel/umbrel#796]
Hello,

i could not find anything in your documentations so i have to ask you here.

My Pi broke down and i needed a new one. 
I copied chainstate and blocks from the bitcoin folder to my new node.
Got everything up and running. Recovered with my 24 Words and was able to init the channel backup.

But my node is unable to find the node. 

Clearly this is because of new host and new tor address. 

My question is, how can i join my old channels on my "new" node? I have all my old data as backup but i have no idea what i need to do.

**Comment by AaronDewes** [comment]
> My question is, how can i join my old channels on my "new" node? I have all my old data as backup but i have no idea what i need to do.

When recovering from a channels.backup as described on info.umbrel.tech, all channels will be closed and the funds will be returned. This is part of LNDs design.

**Comment by Ruppsn** [comment]
So "unable to find node" is intended? 

![image](https://user-images.githubusercontent.com/25790518/118311575-608df980-b4f0-11eb-9719-f7ef9b293740.png)

And it should look like this?

**Comment by Ruppsn** [comment]
Closing the channel makes sense but the: unable to find node - logs are annoying.

**Comment by AaronDewes** [comment]
> Closing the channel makes sense but the: unable to find node - logs are annoying.

Can you share these logs?

**Comment by Ruppsn** [comment]
With docker logs i can see 3h of this
```
2021-05-14 18:02:09.268 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: unable to find node
2021-05-14 18:02:15.457 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: unable to find node
...
2021-05-14 18:21:27.364 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: unable to find node
2021-05-14 18:21:32.620 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: unable to find node
...
2021-05-14 21:41:36.626 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: unable to find node
...
```

It stopped at about 21:45. It just was irritating and i thought i had done something stupidly wrong. 
Everything is now working as expected. Channel is closed. Sats are deposited back to my wallet. 

If you ever need someone to document such stupid questions like mine just msg me!

Thank you for your great work!!!
