### ISSUE TITLE
While synchronizing the estimation of `percent_synchronized` doesn't match `blocks_synchronized / total_blocks`

### ISSUE THREAD

**Issue by michals2** [getumbrel/umbrel#799]
In the screenshot below,

`percent_synchronized = 48.83%`

`blocks_synchronized = 520,905`
`total_blocks = 683,982`
`blocks_synchronized / total_blocks = 76.16%`

![Screen Shot 2021-05-17 at 9 03 24 AM](https://user-images.githubusercontent.com/16494852/118520707-20e13080-b6ef-11eb-9cb5-bbff7384c4bc.png)

**Comment by AaronDewes** [comment]
This is fully intentional, because later blocks contain more transactions, so they take longer to sync and verify. It is % of the full blockchain, not % of number of blocks.

**Comment by michals2** [comment]
Got it, thank you for the quick response!
