### ISSUE TITLE
In Sparrow instructions, suggest waiting until Electrs is indexed

### ISSUE THREAD

**Issue by craigraw** [getumbrel/umbrel#800]
I believe the Umbrel interface offers no means to determine whether Electrs is still indexing, so the first experience many new users have when trying to connect to Sparrow Wallet is a Tor error `cannot connect to hidden service` as Electrs has not yet started it's server socket and begun serving requests.

It would be great if the Sparrow instructions in Umbrel could include a short message about this, to the effect of "if you have recently enabled Electrum server, please wait for 12 hours before trying to connect".

Thanks for making such an excellent companion to Sparrow!

**Comment by lukechilds** [comment]
Yeah good point, sorry for any support burden that may have caused, we'll get that updated.

**Comment by lukechilds** [comment]
@craigraw thanks for reporting, resolved in https://github.com/getumbrel/umbrel-dashboard/pull/359!
