### ISSUE TITLE
small graph and not able to pay in accidentally cases 

### ISSUE THREAD

**Issue by steff123** [getumbrel/umbrel#802]
Hey guys,
i am still a noob and have so weird things running my node. My node exists since January and has 15 channels. It's an umbrel, running in a linux lxc container on proxmox.
My problems are - I think they are connected:

I have channels with bitrefil and acinq but my node can only see 1.806 nodes and 2.714 channels of the network (statistic in RTL)
Today I wanted to make a payment (very small 2121 sats) to a known guy. There was only one hop to the final node (mynode -> node1 -> node2). But RTL said "no_route". That's weird. Because we checked that all channels are founded. I send him the amount to node1 and he sends the amount to node2. All works fine. But I cannot pay directly to node2. Then I installed bos for further investigations. I made a purchase-ping and got the message "UNKNOWN: destination hop doesn't understand new TLV payloads". Because I am a noob I don't know what it mean and wether it has sth. todo with the original problem.

I discussed it already with a lnd dev 
https://github.com/lightningnetwork/lnd/issues/5310

It seems to be a problem, that umbrel uses neutrino.

Regrads
Steff

**Comment by AaronDewes** [comment]
> It seems to be a problem, that umbrel uses neutrino.

Umbrel only sues neutrino during sync, then it uses Bitcoin Core for LND.

**Comment by steff123** [comment]
Chain synced in January, but not graph.

```
$ sudo ./lncli getinfo
{
    "version": "0.12.1-beta commit=v0.12.1-beta",
    "commit_hash": "d233f61383f2f950aa06f5b09da5b0e78e784fae",
    "identity_pubkey": ********,
    "alias": *******,
    "color": "#3399ff",
    "num_pending_channels": 1,
    "num_active_channels": 15,
    "num_inactive_channels": 1,
    "num_peers": 22,
    "block_height": 684168,
    "block_hash": "0000000000000000000716c6c31fea07e5d884980117af89acc8d3046315169d",
    "best_header_timestamp": "1621409720",
    "synced_to_chain": true,
    "synced_to_graph": false,
    "testnet": false,
    "chains": [
        {
            "chain": "bitcoin",
            "network": "mainnet"
        }
    ],
    "uris": [
        "******"
    ],
    "features": {
        "0": {
            "name": "data-loss-protect",
            "is_required": true,
            "is_known": true
        },
        "5": {
            "name": "upfront-shutdown-script",
            "is_required": false,
            "is_known": true
        },
        "7": {
            "name": "gossip-queries",
            "is_required": false,
            "is_known": true
        },
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "12": {
            "name": "static-remote-key",
            "is_required": true,
            "is_known": true
        },
        "14": {
            "name": "payment-addr",
            "is_required": true,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        }
    }
}
```

**Comment by AaronDewes** [comment]
I'm talking about Bitcoin Core, not LND.

**Comment by steff123** [comment]
![image](https://user-images.githubusercontent.com/2828397/118790157-cafabd00-b895-11eb-9c06-a0ce0e28d4d2.png)

**Comment by AaronDewes** [comment]
> ![image](https://user-images.githubusercontent.com/2828397/118790157-cafabd00-b895-11eb-9c06-a0ce0e28d4d2.png)

Can you try rebooting your Umbrel?

**Comment by steff123** [comment]
I rebooted just before opening the issue. I think I have the behaviour since the initial setup in January and rebooted a lot since then.

**Comment by AaronDewes** [comment]
> I rebooted just before opening the issue. I think I have the behaviour since the initial setup in January and rebooted a lot since then.

Please try these 3 commands then:

```
sed -Ei 's|(bitcoin.node)=neutrino|\1=bitcoind|g' ~/umbrel/lnd/lnd.conf
sed -i "s/^feeurl=.*//g;" ~/umbrel/lnd/lnd.conf
sudo reboot
```

**Comment by steff123** [comment]
It worked

` "synced_to_graph": true`

Thank you :-)

**Comment by AaronDewes** [comment]
Great! Please close this issue then.
