### ISSUE TITLE
Delete Expired Invoices

### ISSUE THREAD

**Issue by SoundMoneyWins** [getumbrel/umbrel#805]
It would be greatly appreciated if you can add the ability to delete expired invoices, thank you.

**Comment by calkob** [comment]
ACK

**Comment by Darth-Coin** [comment]
> It would be greatly appreciated if you can add the ability to delete expired invoices, thank you.

I use in lnd.conf these lines
# Mark unpayable, unpaid invoices as deleted
gc-canceled-invoices-on-startup=1
gc-canceled-invoices-on-the-fly=1
# Avoid historical graph data sync
ignore-historical-gossip-filters=1
# Avoid slow startup time
sync-freelist=1
# Avoid high startup overhead
stagger-initial-reconnect=1

**Comment by nmfretz** [comment]
For those that find there way to this old issue, this can now be done in the Lightning Node app! Navigate to Advanced Settings --> Optimization and you will see these 2 options that can be toggled:
`Delete Canceled Invoices on Startup`
`Delete Canceled Invoices in Real-time`
