### ISSUE TITLE
Install app stay hanged forever and do not install anything

### ISSUE THREAD

**Issue by ildella** [getumbrel/umbrel#807]
I have a fresh install, with the node is 100% in sync and working.

But on the App Store I can't install any app: 

1. go to app store
2. go to BlueWallet app (or any other app) and click Install
3. Install button become "installing" and stay like that forever

This happens on Firefox 88 and Chromium 90 under Ubuntu 21.04

If I go to Settiings -> Start logs a window appear with this text: 

```Error: Failed to fetch debug data.```

I've run `./scripts/debug` and here is the output: https://pastebin.com/53PZmQh1

I can add that in the Browser console I get a lot of this error:

```TypeError: t.app is undefined```

And there is always this not very promising error on the top of the console: 

```Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data undefined```

I have installed a couple apps from the terminal and it worked fine.

**Comment by v0l** [comment]
Running from cli seems to work fine just not from UI

`./scripts/app install ride-the-lightning`

**Comment by ildella** [comment]
Yes, the CLI always worked fine. 
The UI started working fine after 1 reboot. 

Closing this..
