### ISSUE TITLE
Address field is empty for receive btc.

### ISSUE THREAD

**Issue by ybaidiuk** [getumbrel/umbrel#814]
![image](https://user-images.githubusercontent.com/11969255/120942480-7ffff700-c729-11eb-8907-0374ec335514.png)
P.S. i use HDD instead SSD

**Comment by ybaidiuk** [comment]
[umbrel-1623020391350-debug.log](https://github.com/getumbrel/umbrel/files/6605101/umbrel-1623020391350-debug.log)

**Comment by phenomeus** [comment]
do you use another nginx port as 80?

**Comment by nmfretz** [comment]
closing old issue
