### ISSUE TITLE
Umbrel GUI stuck on loading due to LND not working

### ISSUE THREAD

**Issue by anrath** [getumbrel/umbrel#818]
See debug logs [here](https://umbrel-paste.vercel.app/3d091375d5252725a944dbefa17f00ba).

## General Info

The Umbrel GUI is stuck on loading with the web console displaying an error with `GET http://10.10.10.237/api/v1/lnd/info/status 500 (Internal Server Error)`. A previous error shows `Failed to load resource: the server responded with a status of 500 (Internal Server Error) api/v1/lnd/info/status:1` (`"ENOENT: no such file or directory, open '/lnd/tls.cert'"`)

A look at the debug logs confirms that something is wrong with lnd. See this line from the debug logs: ` lnd | unable to open databases: unable to obtain database backends: invalid argument`.

## Debugging steps taken
1. Unbuntu 20.04 is fully patched and current
2. Tried reinstalling/updating Umbrel and dependencies
3. Pretty much tried all standard debugging steps except nuking the whole filesystem and starting over.

## Notes
- Bitcoin mainnet is fully downloaded and seems to be running smoothly
- Working on a VM
- My intuition/past experience suggests this may be a Docker problem

**Comment by nomizzz** [comment]
I have the same issue, followed the README steps end-to-end but also see that error while the GUI polls the backend.  Is there another ENV variable that needs to be set or do we need to generate the `/lnd/tls.cert` file?

**Comment by royalgarter** [comment]
Same issue with Raspberry Node 4GB. Below is my screenshot on LND docker
- https://imgur.com/a/6Jxdw4W

**Comment by giannoug** [comment]
Got the same error on a fresh install. I'm running Ubuntu 21.04 with Docker 19.03.13 installed from Snap (during OS install). Afterwards, I added my user to the docker group to be able to execute commands without root and setup Umbrel.

The Umbrel GUI /api/v1/lnd/info/status API call breaks with `"ENOENT: no such file or directory, open '/lnd/tls.cert'"`. Checking container logs with `docker-compose logs lnd` returns:
```
lnd                  | unable to open databases: unable to obtain database backends: invalid argument
lnd                  | 2021-07-02 08:10:18.383 [INF] LTND: Version: 0.12.1-beta commit=v0.12.1-beta, build=production, logging=default, debuglevel=info
lnd                  | 2021-07-02 08:10:18.383 [INF] LTND: Active chain: Bitcoin (network=mainnet)
lnd                  | 2021-07-02 08:10:18.384 [INF] LTND: Opening the main database, this might take a few minutes...
lnd                  | 2021-07-02 08:10:18.385 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
lnd                  | unable to open databases: unable to obtain database backends: invalid argument
lnd                  | 2021-07-02 08:10:18.422 [INF] LTND: Shutdown complete
```

**Comment by affektde** [comment]
Maybe you port 8080 is occupied by another process?
We had this on our server. So we change the port on this line: https://github.com/getumbrel/umbrel/blob/b2c034c95ed7cbcdc378955cdd0eee63a74eca3d/scripts/configure#L121

**Comment by nmfretz** [comment]
closing old support issue
