### ISSUE TITLE
browsing the blockchain w/ Docker 

### ISSUE THREAD

**Issue by a56z** [getumbrel/umbrel#833]
Hi, it seems to be possible to browse the blockchain with Docker, unfortunately I'm running into errors when trying the following:

So starting docker with this command works: 
```docker run  -it  --rm  --detach \
    -v ~/.bitcoin:/data/.bitcoin \
    -p 8332:8332 \
    -p 28332:28332 \
    -p 28333:28333 \
    --name bitcoind \
    lncm/bitcoind:v0.21.0
```
It returns the docker ID of the container that's being run in the background. But then, whichever command I run, as for example: 
`docker exec -it bitcoind bitcoin-cli --help` I get this type of error: 
`Error: No such container: bitcoind`

It would be cool if there was a way to interact with the blockchain for learning purposes. I'm sure it's possible with Docker, but I couldn't find the way to do it. Please advise where I can find instruction or please show here

**Comment by louneskmt** [comment]
Hey! Umbrel already runs everything in Docker containers, including `bitcoind`. If you need to use `bitcoin-cli`, an executable is available at `~/umbrel/bin/bitcoin-cli` (thé script basically uses `docker exec` to run the command in Umbrel's `bitcoin` container).

**Comment by a56z** [comment]
interesting, ok so I can run `docker exec -it bitcoin bitcoin-cli -help` 
and here it lists a set of commands but these are different from bitcoind commands? For example it doesn't let me run commands such as `getblockchaininfo` , `getbalance`, `listunspent` and so on. 
How would I get there with umbrel?

**Comment by a56z** [comment]
oh got it, so it's `docker exec bitcoin bitcoin-cli help`  without the `-it`. 
New to docker, I guess it's possible to create an alias for these docker commands to just run `bitcoin-cli <command>` 

Do you know how that works by any chance?

**Comment by AaronDewes** [comment]
```
echo 'export PATH="$PATH:/home/umbrel/umbrel/bin"' >> .bashrc
source .bashrc
```

Can you try this? After this command, in the current session and after every login automatically bitcoin-cli and lncli should woek

**Comment by a56z** [comment]
Oh hey thanks Aaron! So adding the path to .bashrc works but I have to manually run `source .bashrc` each time I login to make it effective. How can I make `source .bashrc` automatically run each time I login?

**Comment by a56z** [comment]
after adding this to .profile it now works :)
Thank you!!
```
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
```

**Comment by AaronDewes** [comment]
Are you sure you have to manually run it? Try removing the change from .profile and it should still work, normally, bash automatically loads .bashrc

**Comment by a56z** [comment]
yes, not exactly sure why I had to manually run it. But with adding the 3 lines of my previous post it now runs when I connect via SSH without having to run `source .bashrc` every time. 
Which is weird because bash is always running anyway right?

**Comment by AaronDewes** [comment]
Yes, I don't understand why it doesn't work for you, but as long as it works somehow, I guess it's okay
