### ISSUE TITLE
Failure while "Removing network umbrel_main_network"

### ISSUE THREAD

**Issue by ildella** [getumbrel/umbrel#836]
Hi. I am now stuck and both scripts "start" and "stop" hangs with this error. 

```
Removing network umbrel_main_network
ERROR: error while removing network: network umbrel_main_network id 45139f12c61d8ae30d054060a87897425a0001a4c974ae6c332892762a8f2b4c has active endpoints
```

Doing docker network rm has similar effect

```
$ docker network rm 45139f12c61d8ae30d054060a87897425a0001a4c974ae6c332892762a8f2b4c
Error response from daemon: error while removing network: network umbrel_main_network id 45139f12c61d8ae30d054060a87897425a0001a4c974ae6c332892762a8f2b4c has active endpoints
```

and "./scripts/status" tells me that many Umbrel services are continuosly restarting.  

Any tip on how to get out of this situation without wiping everything to the ground? :)

**Comment by lukechilds** [comment]
Is this a custom install or Umbrel OS on a Pi?

Can you try stopping the Docker service and deleting the Docker data dir (`/var/lib/docker`) assuming you don't have other critical things running with Docker.

**Comment by ildella** [comment]
> Is this a custom install or Umbrel OS on a Pi?

Custom Install. 

> Can you try stopping the Docker service and deleting the Docker data dir (`/var/lib/docker`) assuming you don't have other critical things running with Docker.

I'll try this, thanks.

**Comment by ildella** [comment]
After a few reboots it started working again...
Also upgrade from Web UI works.

**Comment by queenvictoria** [comment]
I had a similar issue, persistent through one startup, that I solved the following way:

```
$ sudo docker ps
$ sudo docker stop xxxxxxxx
$ sudo docker stop xxxxxxxx
$ sudo ./scripts/start
```
