### ISSUE TITLE
How to add more funds to a lightning channel?

### ISSUE THREAD

**Issue by pablote** [getumbrel/umbrel#841]
Hi, sorry if this is a bitcoin/lightning general question, but I use Umbrel, I'm not sure if there's a better place to ask this.

So I already deposited come BTC. I've opened a lightning channel with about half the bitcoins I deposited, bought a few things using lightning payments, all working great. Now I want to buy something else and I don't have enough sats for that. How do I put some more sats into it? I didn't see any option on the UI to do this.

thanks

**Comment by stefment** [comment]
This is not the right place to ask. Please come to https://community.getumbrel.com if you havent already there are several ways to do what you want

**Comment by notleanbarba** [comment]
Hi. You could close the old channel and open a new one with the funds you want to spend. You can also create a new channel if you want to keep the old one.

**Comment by Full-node** [comment]
If the channel size is sufficient and you just need to add funds to it there are two other options. 
Use Lightning Terminal app and perform a "Loop in". You can select the channel you would like to receive the funds on. This takes funds from your on chain wallet, sends them to Lightning Labs who then sends them to your chosen lightning channel. 
Another good way is to use the Strike app and pay yourself directly from your bank account. This way doesn't allow you to choose the recipient channel but works great if you have incoming liquidity.

**Comment by nmfretz** [comment]
closing old support issue
