### ISSUE TITLE
Updating Umbrel Resets lnd.conf

### ISSUE THREAD

**Issue by sfmcnally** [getumbrel/umbrel#851]
When I update my node, my node alias, base fees, and fee rate are all reset to default in lnd.conf

**Comment by reapwhatyounode** [comment]
> When I update my node, my node alias, base fees, and fee rate are all reset to default in lnd.conf
ditto - same experience --> would be amazing to have config editing capability similar to that in start9 Embassy OS

**Comment by yfrbl** [comment]
Hey guys, just wanted to catch up on this: is there a solution yet?

**Comment by louneskmt** [comment]
The file is not longer overwritten since a few versions ago.

**Comment by yfrbl** [comment]
Good to know, thank you lounes!

**Comment by louneskmt** [comment]
@sfmcnally Can you close this?
