### ISSUE TITLE
Secret Words Jumped !!!

### ISSUE THREAD

**Issue by cubanhodl** [getumbrel/umbrel#852]
I went to view the secret words to write the down and they jumped two words and was not able to jot down those two words. Why did the software do that? How can I recover my wallet now?

**Comment by dubdam** [comment]
you can see them again in Settings --> Secret words

**Comment by DocCodez** [comment]
I was able to recover it miraculously but I had already taken down the node and started spinning up a new one on raspiblitz. 

Just saying it is easy for someone to think they have written down all the words when in reality the software skipped a couple of words. The software shouldn't jump over words.

**Comment by ardevd** [comment]
Would be useful to have the onboarding make the user repeat back the seed phrase to confirm it has been correctly written down.

**Comment by we684** [comment]
When I click View Secret Words, it temporarily changes the text to decrypting secret words, then back to View Secret words without displaying them! Using Tor Browser 11.0.1

**Comment by Gibbs1979** [comment]
> When I click View Secret Words, it temporarily changes the text to decrypting secret words, then back to View Secret words without displaying them! Using Tor Browser 11.0.1

 It must be a bug - disable 2FA first. This worked for me, along with changing passwords.

https://github.com/getumbrel/umbrel/issues/1139#issuecomment-983283224
