### ISSUE TITLE
Synchronized but not working

### ISSUE THREAD

**Issue by steveplanke** [getumbrel/umbrel#857]
Hello Hello, since several hours all blocks are synchronized on my RaspberryPi, however now nothing happens at all. What could be the problem?

**Comment by louneskmt** [comment]
What do you want it to do exactly?

**Comment by steveplanke** [comment]
I would like to mine Bitcoin on my Raspberry Pi. Now that all blocks have been downloaded and synchronized, it should be possible to mine Bitcoins. But so far nothing has happened.

**Comment by AaronDewes** [comment]
That's not what Umbrel does. Umbrel is a full node, and the Pi is not really powerful to mine Bitcoin. Have you read getumbrel.com at all?????

**Comment by AaronDewes** [comment]
# BITCOIN IS NOT FREE MONEY

**Comment by mayankchhabra** [comment]
Sorry @steveplanke, but it looks like your Umbrel is doing exactly what's supposed to do -- independent validation of the Bitcoin ledger. :)

To be clear, Umbrel is a non-mining node. The Raspberry Pi's chip is too humble to mine Bitcoin. The primary use case of Umbrel is sovereign interaction with the Bitcoin and Lightning network by connecting your wallets to it and using all the amazing apps in its app store.

Here are two great video tutorials by BTCSessions which would help:

1. This one covers the "why" of running Umbrel: https://youtube.com/watch?v=fppmhqjqh2E

2. This one covers the usage of Lightning Network on Umbrel: https://youtube.com/watch?v=KItleddMYFU

I'm closing this issue for now, but please feel free to hop on our [community forum](https://community.getumbrel.com) if you have any questions or need help with something.
