### ISSUE TITLE
Failed to run `bin/lncli` script

### ISSUE THREAD

**Issue by o3o3o** [getumbrel/umbrel#863]
I tried to run the command below, it exited with 1 error.
```bash
$ ./bin/lncli addinvoice --amt=6969 --memo="A coffee for Roger"
$ echo $?
1
```
When I uncomment `set -euo pipefail` in file, it showed the following log:
```
[lncli] unable to parse preimage: encoding/hex: invalid byte: U+006F 'o'
```
And I found that it was caused by quotes in `--memo` argument parsed by`$@` in the script. 

I will do a PR to fix this.

**Comment by louneskmt** [comment]
Thanks for debugging this @o3o3o! Just tested the fix, it works well. @lukechilds Can you take a look and merge if it seems good for you?
