### ISSUE TITLE
[feature request] Custom LND config in dashboard

### ISSUE THREAD

**Issue by thefeli73** [getumbrel/umbrel#865]
Having a custom LND config on umbrel is very annoying at the moment since it get's reset after every update. There needs to be a way to change LND settings in the dashboard, like node alias, color, fees and allow adding custom fields for less common settings like minchansize, bitcoin.defaultchanconfs etc.

**Comment by nmfretz** [comment]
For that find their way to this old issue, this now implemented in the Lightning Node app, by using `Advanced Settings` in the apps interface.
