### ISSUE TITLE
Instructions text on "connect wallet - Zeus" are not updated/correct

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#869]
In Umbrel dashboard - connect wallet, the instructions for Zeus wallet are not updated correctly.
Now Zeus has integrated Tor, no need to use it through Orbot.
It can be, but the Tor integrated is faster than Orbot.

The procedure will be:
1. Open Zeus, go to add new node
2. Select the option "use Tor"
3. Copy the onion address from Umbrel (connect wallet - Zeus). Here you should put the onion address to be copied with the "http" preceded. Zeus didn't add it and you have to put it manually. That's why many users can't get connected to Zeus, because they paste it in zeus without "http"
4. Optional can be scanned the QR (easier) but also it not contain the http.

**Comment by jaydevstack** [comment]
Thanks @ Darth-Coin, your instructions are working like a charm, my connection is fixed 👍 

Please Umbrel include this in your next update

**Comment by louneskmt** [comment]
Thanks for the report, fix on its way: https://github.com/getumbrel/umbrel-dashboard/pull/368.
