### ISSUE TITLE
[Feature request] Add LightningNetwork Plus as app

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#870]
http://lightningnetwork.plus is a great tool for new node operators to get connected and have more liquidity.
If it can be just added in apps will be great, or at least just as a link in the dashboard, so the new users can be easily onboarded.
For the moment doesn't have login with LN-auth but I understand that it is in working.
Would be a great app for Umbrel.

**Comment by nmfretz** [comment]
For those that find their way to this old feature request, [LightningNetwork+](https://apps.umbrel.com/app/lnplus) is now available in the app store.
