### ISSUE TITLE
Naming of the EDIT button on the apps section

### ISSUE THREAD

**Issue by Max-Trotter** [getumbrel/umbrel#871]
Please consider renaming the EDIT button on the apps section, perhaps MANAGE would be a better description of it's purpose.
![Screenshot_2021-07-10_18-56-45](https://user-images.githubusercontent.com/34596629/125172263-9a0d7900-e1b0-11eb-8d4f-8653c1de7fee.png)

**Comment by nmfretz** [comment]
Closing old issue. Thanks for this @Max-Trotter. Newer versions of Umbrel now have `manage apps`

<img width="1009" alt="image" src="https://github.com/getumbrel/umbrel/assets/85373263/d5c17309-5a7f-47bf-a061-2a1ab97e0f63">
