### ISSUE TITLE
unable to connect whirlpool gui to fresh umbrel install [0.3.14]

### ISSUE THREAD

**Issue by nexus-uw** [getumbrel/umbrel#872]
following the instructions from the samurai /connect page

i enter the _http://<blahblab>.onion_ as the cli address
and the tor proxy as _socks5://127.0.0.1:9050_

and all i receive in response is "Connection failed: Could not connect to CLI (may take a few seconds to start...)"

i have tried both 0.10.2 and 0.10.3 versions of the whirlpool gui to the same result

looking at the end of `./scripts/app compose samourai-server logs -f whirlpool`
has  

> whirlpool_1  | 2021-07-06 21:28:41.143  INFO 12 --- [           main] c.s.whirlpool.cli.services.CliService    : Running whirlpool-client-cli 0.10.10 on java 11.0.9.1... [--listen, --cli.api.http-enable=true, --cli.api.http-port=8898, --cli.tor=true, --cli.torConfig.coordinator.enabled=true, --cli.torConfig.coordinator.onion=true, --cli.torConfig.backend.enabled=false, --cli.torConfig.backend.onion=false, --cli.mix.liquidityClient=true, --cli.mix.clientsPerPool=1, --resync --cli.torConfig.executable=/usr/local/bin/tor, --cli.server=MAINNET, --cli.dojo.enabled=true, --cli.dojo.url=http://10.21.21.22:80/v2/]
whirlpool_1  | 2021-07-06 21:28:41.152  INFO 12 --- [           main] c.s.whirlpool.cli.services.CliService    : API is listening on https://127.0.0.1:8899 and http://127.0.0.1:8898
whirlpool_1  | 2021-07-06 21:28:41.292  WARN 12 --- [           main] c.s.whirlpool.cli.services.CliService    : ?????????????????????????
whirlpool_1  | 2021-07-06 21:28:41.292  WARN 12 --- [           main] c.s.whirlpool.cli.services.CliService    : ? INITIALIZATION REQUIRED
whirlpool_1  | 2021-07-06 21:28:41.292  WARN 12 --- [           main] c.s.whirlpool.cli.services.CliService    : ? Please start GUI to initialize CLI.
whirlpool_1  | 2021-07-06 21:28:41.292  WARN 12 --- [           main] c.s.whirlpool.cli.services.CliService    : ? Or initialize with --init
whirlpool_1  | 2021-07-06 21:28:41.292  WARN 12 --- [           main] c.s.whirlpool.cli.services.CliService    : ?????????????????????????
whirlpool_1  | 2021-07-06 21:36:42.175  INFO 12 --- [nio-8898-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
whirlpool_1  | 2021-07-06 21:36:42.193  INFO 12 --- [nio-8898-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 18 ms

the GUI log doesnt have any other clues etiher
>tail whirlpool-gui.log 
[2021-07-10 16:00:56.639] [info] CLI: download success
[2021-07-10 16:00:57.381] [info] Using CLI_API 0.10 {
  CLI_VERSION: '0.10.11',
  CLI_URL: '/uploads/21d25ed02cceb91f4aa95b6389b9da9c/whirlpool-client-cli-0.10.11-run.jar',
  CLI_CHECKSUM: '09e574743851db2d5374bc7d4e66fd0c29f07b95b4e32b3d70c2187b724d5745'
}
[2021-07-10 16:00:57.661] [debug] CLI is valid: /home/foo/.config/whirlpool-gui/whirlpool-client-cli-0.10.11-run.jar
[2021-07-10 16:01:20.943] [info] guiConfig: set guiProxy=socks5://127.0.0.1:9050

i verified that the my local tor socks5 proxy is running by configuring firefox to use it for a bit + checked that my ip was not my home ip

visiting the onion url of the whirlpool cli with the tor browser results in 
> Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Jul 10 23:02:13 UTC 2021
There was an unexpected error (type=Forbidden, status=403).
Access Denied

are there other logs that i could look at to see where my failure is occurring?

should i be specifying a specific port on GUI?

**Comment by louneskmt** [comment]
Hey @nexus-uw! Can you SSH into your Umbrel and check if the content of the directory ~/umbrel/app-data/samourai-server/whirlpool? (``ls ~/umbrel/app-data/samourai-server/whirlpool``)

Also, are you sure to have Tor installed on your computer?

**Comment by nexus-uw** [comment]
that directory is empty for me
```
ls -a /mnt/umbrel/app-data/samourai-server/whirlpool
.  ..
```


yes, i have tor installed an enabled
followed https://tor.stackexchange.com/questions/12678/how-to-check-if-tor-is-working-and-debug-the-problem-on-cli to check and got the following
```
➜  ~ curl --socks5 localhost:9050 --socks5-hostname localhost:9050 -s https://check.torproject.org/ | cat | grep -m 1 Congratulations | xargs
Congratulations. This browser is configured to use Tor.
```

**Comment by louneskmt** [comment]
Can you try to uninstall and reinstall the app?

**Comment by nexus-uw** [comment]
tried. no luck

deleted ~/.config/whirlpool-gui

tried both the appimage + .deb

**Comment by louneskmt** [comment]
I meant the Samourai Server app on your Umbrel.

**Comment by nexus-uw** [comment]
re-installed the server app

still no luck. should i open an issue with GUI repo?

**Comment by nexus-uw** [comment]
update.

was able to successfully connect to whirlpool by trying with a different computer, so the issue was with my machine that i was running the client on

thank you for your help @louneskmt
