### ISSUE TITLE
`bin/lncli getnewaddress` not working

### ISSUE THREAD

**Issue by LAMike310** [getumbrel/umbrel#876]
After ssh'ing into Umbrel from the terminal, went into `umbrel/bin` and ran this command:

`./lncli getnewaddress`

Nothing happened, but when I ran `./bitcoin-cli getnewaddress` I got a new address created.

**Comment by LAMike310** [comment]
![Screen Shot 2021-07-18 at 4 35 46 PM](https://user-images.githubusercontent.com/2181637/126085559-20f5637e-8d69-46f7-9a11-5c5e49491a60.png)

**Comment by nolim1t** [comment]
> ![Screen Shot 2021-07-18 at 4 35 46 PM](https://user-images.githubusercontent.com/2181637/126085559-20f5637e-8d69-46f7-9a11-5c5e49491a60.png)

the command you are after is `lncli newaddress p2wkh`

**Comment by LAMike310** [comment]
Thanks! Need to read the docs a little more carefully.
