### ISSUE TITLE
Lightning-/Bitcoin Wallet and Bitcoin Core showing loading animation forever

### ISSUE THREAD

**Issue by jameskitt616** [getumbrel/umbrel#887]
![umbrel_loading](https://user-images.githubusercontent.com/52933658/128368979-802ae3d5-6db1-45c2-8841-238a1bb5632f.png)

I setup the Umbrel Node on a Ubuntu 20.04 Server.
Restarted the Server several times while syncing the Blockchain and at one point the Webinterface just continued to load forever after a restart.

**Comment by MaikB85** [comment]
I have the same problem. Running umbrel on a ubuntu 20.04 vm on TrueNAS System.
Everything seems fine. Start of umbrel shows no problems in cli

**Comment by jameskitt616** [comment]
![Untitled](https://user-images.githubusercontent.com/52933658/128978766-23383c42-886e-4f0b-ab74-a6281876165f.png)

I found the problem, i noticed due installing new 0.4.0 Umbrel version, which shows the available disk space and it was full. 
The problem was Ubuntu creating a LVM with 200GB, and it didnt use the full partition.
Simple fix: Expand an LVM Disk [e.g. like this](https://www.tecklyfe.com/how-to-expand-an-lvm-disk-in-ubuntu-linux/)

**Comment by MaikB85** [comment]
Yes sure. Umbrel works fine before the update. On installation I created a folder on the mounted drive and installed umbrel to it like described in the install instructions.

<img width="1288" alt="Bildschirmfoto 2021-08-11 um 19 58 55" src="https://user-images.githubusercontent.com/40302298/129079796-d401f800-c726-41f8-b0b3-1f5c9815a615.png">

by the way, mempool (app) is also not working anymore. I can access the website, but there is only the background which I can see. 
I try a reinstall of umbrel within the next days.

**Comment by MaikB85** [comment]
It seems that the bitcoin node and mempool are still running in background, because the used storage shown in Umbrel is increasing...

**Comment by MaikB85** [comment]
Well I found the problem and fixed it for me. In the old version of my Umbrel node I did the following workaround to use a custom port:
[https://github.com/getumbrel/umbrel/issues/584](url)

After update, the start script has been overwritten. So now I edited my start script again with adding the port and finally it's working.

So this issue could be closed.
