### ISSUE TITLE
App Backups

### ISSUE THREAD

**Issue by dm807cam** [getumbrel/umbrel#890]
I very much like the idea to use Umbrel as a holistic Homeserver rather than just as a bitcoin node. But we need some sort of a backup options to back up apps like nextcloud or gitea. These services are otherwise of no use for storing data.

**Comment by esackbauer** [comment]
This is the reason why I don't fancy the "jack of all trades" approach. I have them separate, and Nextcloud is backed up with Duplicati. However if you can integrate a reliable encrypted and application aware backup for all apps Umbrel will have this is a load of work to do.
So if you have like Nextcloud, Matrix and other services you probably want also a SSO concept like LDAP. My guess is tech savvy users will prefer to build some things separatly, and non-savvy users are already unable to understand what Matrix is and how to properly configure it.
Also Home Assistant is such a "jack of all trades" approach already, there is also an app store inside with Matrix, Vaultwarden etc.
But maybe one could look how they did the backup solution, there is one integrated.

Oh wow now i am completely off topic. Sorry ;)

**Comment by techtastet** [comment]
The system could be that every day at "x" hour, the entire data outside the blockchain is strongly zipped and encrypted to have a backup of reasonable size.
This backup could be sent to a friend's node (using tor) who would have shared his storage space with me or by sending the backup to services like Gdrive, dropbox etc ...

**Comment by esackbauer** [comment]
@techtastet I don't think that a backup of lets say an installation with Nextcloud holding hundreds of gigabyte of data via Tor which offers only limited bandwidth is a good idea. At some point a daily backup will never finish. This is why I mentioned Duplicati, which can do at least incremental backups.

**Comment by sosaysthecaptain** [comment]
Hi! I'm new to Umbrel and love it, but backup is a significant issue standing in the way of using it as a personal server in a load-bearing capacity. 

Here's a thought, for a possible two-prong approach:
- add a "backup everything to external hard drive" option, which just dumps an ISO of the SSD onto a hard drive that's plugged in. This covers the cheap, quick-and-dirty use case.
- create a "mirror" mode, by which one umbrel server serves no other purpose than to be a remote backup of another, with updates are done incrementally over tor. This could even be built as a custom app. When setting up a new umbrel, one could then simply specify the address and credentials of the backup server.

**Comment by dm807cam** [comment]
Any updates or input from the developers on this? This seems to be such a crucial feature.

**Comment by 0xtlt** [comment]
Any update guys ?

**Comment by dm807cam** [comment]
Very unfortunate that this ticket has been open for more than a year now without any reactions from the developers. I will close the ticket now and put the case Umbrel case to rest.
