### ISSUE TITLE
Vaultwarden can only be used over Tor with https

### ISSUE THREAD

**Issue by jaccos** [getumbrel/umbrel#895]
Vaultwarden can only be used over Tor => HTTPS://

Please access your Umbrel in a Tor browser on your remote access URL (Settings > Tor > Remote Access URL) to open this app.

When opening  the vaultwarden through TOR  it is asking for a HTTPS access (ssl) but my umbrel local on http.
What todo?

<img width="512" alt="Schermafbeelding 2021-08-09 om 07 25 13" src="https://user-images.githubusercontent.com/2619533/128663482-6536158d-8e3f-4eda-9570-99c70d2e851d.png">

**Comment by jaccos** [comment]
this what i found for **Unable to register the first account**  , **but how to set this up on umbrel**?

### Unable to register the first account

What's happening? You cannot submit web-forms over un-encrypted HTTP connections, the solution is to enable TLS.

sudo curl -fsSL https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-arm -o /usr/local/bin/mkcert
sudo chmod +x /usr/local/bin/mkcert
sudo mkcert -install
sudo update-ca-certificates
sudo mkdir /opt/vaultwarden/cert
sudo mkcert -cert-file /opt/vaultwarden/cert/rocket.pem -key-file /opt/vaultwarden/cert/rocket-key.pem example.org 1.2.3.4 # change hostname and ip to yours
sudo chown -R vaultwarden:vaultwarden /opt/vaultwarden/cert
sudo openssl verify -verbose -CAfile ~/.local/share/mkcert/rootCA.pem /opt/vaultwarden/cert/rocket.pem

Add the following line into the /opt/vaultwarden/.env file

ROCKET_TLS={certs="/opt/vaultwarden/cert/rocket.pem",key="/opt/vaultwarden/cert/rocket-key.pem"}

Restart service

sudo systemctl restart vaultwarden.service
sudo systemctl status vaultwarden.service

Self-signed CA which is created by mkcert tool require you to import CA certificate into the client's systems trust store

sudo mkcert -CAROOT

**Comment by AaronDewes** [comment]
That isn't going to work on Umbrel, please wait for a reply.

**Comment by mayankchhabra** [comment]
Hey @jaccos are you using Brave browser? If so, can you trying using [Tor browser](https://www.torproject.org/download/) and see if that helps?

**Comment by jaccos** [comment]
Yes I tried it with tor through brave that does not work.
Now i did the same with the Tor-Browser and that succeeded .

**Comment by musicaljoeker** [comment]
Isn't it unsafe to enter username/passwords over Tor connections that aren't encrypted with a TLS connection? The Tor exit node can see your data in plain text if not over HTTPS.
