### ISSUE TITLE
"balance", "lightning wallet", "channels" and "bitcoin wallet" transactions not loading (keeps spinning) 

### ISSUE THREAD

**Issue by bitcoiner-dev** [getumbrel/umbrel#898]
So, for a few days, when I login to the dashboard, I am unable to see the balance in the upper left, the lightning wallet balance, the bitcoin wallet transactions, and lightning channels. Instead there is a spinner or a grey loading bar which is fading in and out and never finishes loading.

I decided to debug this and here is what I found in the "middleware" container's logs:

Unable to list on-chain transactions, Received message larger than max (5686434 vs. 4194304)
/v1/lnd/channel
LndError: Unable to list on-chain transactions
at /app/services/lnd.js:69:18
at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1210:9)
at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)

This happens when I login and keeps happening since it keeps trying to load the info and running into this issue.

I did some digging around and:

"gRPC uses per-message size limits to manage incoming and outgoing messages. By default, gRPC limits incoming messages to 4 MB. There is no limit on outgoing messages."

This means you guys need to page the requests you are sending to LND because if you don't the above error will occur.

**Comment by AaronDewes** [comment]
I'm doing some work on middleware currently, I'll put this on my to-do-list, thanks!

**Comment by Green2J** [comment]
I'm having this exact same problem also

**Comment by nmfretz** [comment]
closing old support issue
