### ISSUE TITLE
Umbrel seed phrase compromised

### ISSUE THREAD

**Issue by riottrade** [getumbrel/umbrel#906]
Hi,

Is there a way to replace seed phrase/genarate a new on on running umbrel node?
I assume that if it compromised someone can get access even without password. Correct ?

thx

**Comment by riottrade** [comment]
I have no funds and no channels opened. Still 4 % to sync. How do I do it and most important can I skip the syncing process when It is done already?
Can I do it using the same email?
-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Aug 13, 2021, 08:14 by ***@***.***:

**Comment by AaronDewes** [comment]
Email? You don't need to enter your email in Umbrel at all.

**Comment by riottrade** [comment]
Yes you’re right of course. My mistake. Anyway. 100% synced now. How do I generate new seed and wallet?
Thx for your time!

-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Aug 13, 2021, 17:03 by ***@***.***:

**Comment by riottrade** [comment]
I tried using this script I got from Umbrel guys 👍 

ssh -t umbrel@umbrel.local "sudo systemctl stop umbrel-startup && sudo rm -rf ~/umbrel/lnd/!(lnd.conf) && sudo rm ~/umbrel/db/user.json && sudo rm ~/umbrel/db/umbrel-seed/seed && sudo systemctl start umbrel-startup"

Doesn't seem to work and I get this answer on Terminal  after being asked to write password/I use my dashboard password/ : 

ssh -t umbrel@umbrel.local  “sudo systemctl stop umbrel-startup && sudo rm -rf ~/umbrel/lnd/!(lnd.conf) && sudo rm ~/umbrel/db/user.json && sudo rm ~/umbrel/db/umbrel-seed/seed && sudo systemctl start umbrel-startup”
umbrel@umbrel.local's password: 
bash: “: command not found
Connection to umbrel.local closed.

Can't figure it out. Funny can't find more people trying to reset seed, password and personal data and start fresh.

**Comment by AaronDewes** [comment]
You seem to be using wrong ", not sure how you got those

**Comment by riottrade** [comment]
Can you please send me the command here at one more time with proper quote marks.
I’m not sure what is going on. I will have to check what language is set on my computer.
-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Aug 18, 2021, 08:50 by ***@***.***:

**Comment by AaronDewes** [comment]
`ssh -t umbrel@umbrel.local "sudo systemctl stop umbrel-startup && sudo rm -rf ~/umbrel/lnd/!(lnd.conf) && sudo rm ~/umbrel/db/user.json && sudo rm ~/umbrel/db/umbrel-seed/seed && sudo systemctl start umbrel-startup"`
