### ISSUE TITLE
Add a GPIO screen to umbrel with BTC price

### ISSUE THREAD

**Issue by lorenzoPrimi** [getumbrel/umbrel#907]
Hi,
I mentioned in my last [tweet](https://twitter.com/CryptoLorenzo/status/1426144398929285121) I'm working to add a GPIO screen support to umbrel.
I want to use at first some ready BTC price script such as 
- https://www.makeuseof.com/build-cryptocurrency-price-ticker-using-raspberry-pi/
- https://gechev.com/software/bitcoin-btc-price-display-ticker-on-raspberry-pi-with-php/

I'm kinda stuck because I need to decide the best way to proceed:
1) Install Xserver on Umbrel OS.
*I tried but I'm having some difficulties*
 https://medium.com/@avik.das/setting-up-an-lcd-screen-on-the-raspberry-pi-2018-edition-d0b2792783cd

2) Install Raspian OS arm64, then install umbrel docker and the BTC ticker price 
*This might be the "easy way" but more difficult to document and to replicate for the end user, lots of commands to run*

3) Looking into framebuffer applications to don't have to install X server
*This is the most complicated as we need to code from scratch an app for price ticker.*
https://medium.com/@avik.das/writing-gui-applications-on-the-raspberry-pi-without-a-desktop-environment-8f8f840d9867

Eventually would be great to have an umbrel app!
So what do you think is the best way to proceed? 
Does any dev want to join me in this project?

**Comment by AaronDewes** [comment]
I DM'd you on Twitter, and I think I know how to dockerize it, we can talk later
