### ISSUE TITLE
Restoring from seed not working. 

### ISSUE THREAD

**Issue by ybaidiuk** [getumbrel/umbrel#913]
I did upgrade my HDD to SSD. I think it is a common use-case.
While restore process I get strange red message ("user exist"), after restart it loaded well, and in settings was my seed phrase. 
3 day after my blockchain is sync 100%.
But my wallet and lightningWallet are still in sync process.

How I can restore from seed and not lose my full blockchain ? 

![image](https://user-images.githubusercontent.com/11969255/129589463-94ceb178-9064-4df0-964d-7422fb243c1a.png)

**Comment by nmfretz** [comment]
closing old support issue
