### ISSUE TITLE
Edit Username

### ISSUE THREAD

**Issue by SoundMoneyWins** [getumbrel/umbrel#914]
Add the ability to edit username. Add this ability next to change password in the account settings section.

**Comment by nmfretz** [comment]
Ability to change password has been added to the `Settings` page of the dashboard>

Ability to edit username will be implemented soon!

**Comment by IMPranshu** [comment]
It is not possible to do so from the UI yet. If you don’t mind using the terminal, you can `SSH` into your Pi:

`ssh -t umbrel@umbrel.local `
(The password is your dashboard password)

Then run:

`echo "$( jq '.name = "NEWNAME"' ~/umbrel/db/user.json )" > ~/umbrel/db/user.json`
Don’t forget to change NEWNAME to your new username.

_Be careful running this command. This file contains your hashed password and seed. Copy and paste it and change only NEWNAME._

**Example:**

 `echo "$( jq '.name = "IMPranshu"' ~/umbrel/db/user.json )" > ~/umbrel/db/user.json`

**Comment by mayankchhabra** [comment]
As I'm reviewing old issues, I noticed that this one has been resolved in umbrelOS 0.5.4. Closing the issue for now!
