### ISSUE TITLE
CPU temperature misspells "Celsius"

### ISSUE THREAD

**Issue by jamescridland** [getumbrel/umbrel#917]
### What happened
In the settings page at http://umbrel.local/settings it says the CPU temperature is in "Celcius".

### What I hoped would happen
The correct spelling is "[Celsius](https://en.wikipedia.org/wiki/Celsius)".

I've tried searching the source code for "Celcius", but can't find it, so can't submit a pull request. It's probably in a dependency or something. So, like a bad man, I intend to at least file this as an issue in an attempt to be helpful, and then tiptoe slowly away.

**Comment by brianoflondon** [comment]
They found and fixed this in the "Dashboard" subsection. I'm only now starting to understand the Docker Container architecture (I think its brilliant) so this kind of thing is hard to track down until you start looking in the right section for a specific container, in this case the `umbrel-dashboard`

Overall I love the architecture. 

https://github.com/getumbrel/umbrel-dashboard/issues/374
