### ISSUE TITLE
Blockchain frozen

### ISSUE THREAD

**Issue by CEDRICHK** [getumbrel/umbrel#924]
Hello bitcoiner,

blockchain is stuck at block 496 061 of 695 568 blocks ~40.91%. 
Can you help me. Is this a disk error? 
Here are the logs attached.

Best,

[umbrel-1629471503525-dmesg.log](https://github.com/getumbrel/umbrel/files/7022431/umbrel-1629471503525-dmesg.log)
[umbrel-1629471320957-debug.log](https://github.com/getumbrel/umbrel/files/7022432/umbrel-1629471320957-debug.log)

**Comment by louneskmt** [comment]
Have you tried to restart Umbrel?

**Comment by CEDRICHK** [comment]
Yes I have, the same problem persists

**Comment by nmfretz** [comment]
closing old support issue
