### ISSUE TITLE
Watchtower configurations overwritten on update

### ISSUE THREAD

**Issue by damanic** [getumbrel/umbrel#925]
I can see previous issues discussing official watchtower support through the UI, which would be ideal.

Ahead of that it seems we could at least support watchtower service configurations through SSH that will persist across updates.

v0.4.1 appears to no longer overwrite lnd.conf which is a good start but we also need:

- LND docker container to open port 9111
    - https://github.com/getumbrel/umbrel/blob/master/docker-compose.yml     
- Add port 9111 tor service configuration in `/mnt/data/umbrel/tor/torrc` ||  `/mnt/data/umbrel/tor/torrc-umbrel`
    - Or no longer overwrite custom configurations in umbrel version updates

Any downsides to adding the supporting port configurations by default?  This would allow SSH users to simply add a persistent  lnf.conf entry to enable their node to act as a watchtower:

```
  [Watchtower]
  watchtower.active=1
```

**Comment by brentkearney** [comment]
I can see from the lnd docker container log that the watchtower service is starting up, but when I run `lncli wtclient add ...`, I get an error message:
```
2021-08-30 16:52:40.574 [ERR] RPCS: [/wtclientrpc.WatchtowerClient/AddTower]: watchtower client not active
2021-08-30 16:52:56.427 [ERR] RPCS: [/wtclientrpc.WatchtowerClient/ListTowers]: watchtower client not active
```

Is this because of the ports not being open, as @damanic describes?

**Comment by damanic** [comment]
@brentkearney 


##Custom Configs Required


-----------------
__ /mnt/data/umbrel/docker-compose.yml __

lnd:
ports:

```
- "9911:9911"
```

-----------------

__ /mnt/data/umbrel/tor/torrc-umbrel __

```

#LND WatchTower Hidden Service
HiddenServiceDir /var/lib/tor/lndWT9911
HiddenServicePort 9911 10.21.21.9:9911

```

----------------------

__ /mnt/data/umbrel/lnd/lnd.conf __

```
  [Watchtower]
  watchtower.active=1
```

**Comment by nmfretz** [comment]
Watchtowers can now be added using the UI in the Lightning Node app! Navigate to `Advanced Settings` --> `Watchtower` and then toggle `Watchtower Client` and add your desired URI
