### ISSUE TITLE
Vaultwarden error

### ISSUE THREAD

**Issue by techtastet** [getumbrel/umbrel#929]
On http local connection I get the following error :
<img width="434" alt="Capture d’écran 2021-08-22 à 17 38 04" src="https://user-images.githubusercontent.com/31560900/130361166-55d8d88b-e4d5-4d2d-a7a9-481adec9f04a.png">

So when I'm trying with tor, when I create a new account with Vaultwarden, I get the following error :
<img width="317" alt="Capture d’écran 2021-08-22 à 17 38 56" src="https://user-images.githubusercontent.com/31560900/130361191-a99f45a9-ab72-4ee4-97e6-8dc6b37b5870.png">

What can I do?

**Comment by Checkm3out** [comment]
I also had this issue

**Comment by techtastet** [comment]
@Checkm3out the new update seems to work
