### ISSUE TITLE
Unable to pay LND Invoices

### ISSUE THREAD

**Issue by emretezel** [getumbrel/umbrel#937]
Hi Everyone,

Trying to purchase some inbound liquidity from LNBig, but when I try to pay the invoice I get the following error. Is this a known issue?

<html>
 <head><title>502 Bad Gateway</title></head>
 <body>
 <center><h1>502 Bad Gateway</h1></center>
 <hr><center>nginx/1.17.8</center>
 </body>
 </html>

**Comment by nmfretz** [comment]
closing old support issue
