### ISSUE TITLE
./scripts/start script reinstalled OS but kept my password login via SSH?

### ISSUE THREAD

**Issue by JustAGuy12345** [getumbrel/umbrel#939]
My node froze up after trying to restart it through the GUI. I had to reboot it through SSH then afterwards it wouldn't come online through a web browser. I tried running the start script and it seemed to reinstall the OS because the webUI is acting like I havent set up my node yet. This is happening even though I can ssh into my Node with my original password. There must be some fix for this I can perform, no? Why did the start script mess with my installation?

**Comment by nmfretz** [comment]
closing old support issue
