### ISSUE TITLE
Unable to connect to Remote Whirlpool GUI

### ISSUE THREAD

**Issue by thrallgurth** [getumbrel/umbrel#950]
I am having the same issue as described here: https://github.com/getumbrel/umbrel/issues/872

Tor is installed (confirmed), follow instructions exactly, uninstall and reinstall both whirlpool and Samourai Server, wait for all green checkmarks in Dojo Maintenance Tool, to no avail. 

I am on Umbrel 0.4.1.

**Comment by nmfretz** [comment]
closing old support issue
