### ISSUE TITLE
Funds potentially lost due to insufficiently secure channel.backup method

### ISSUE THREAD

**Issue by JustAGuy12345** [getumbrel/umbrel#951]
An LND developer instructed me to link you this: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#file-based-backups .
The channel.backup method of node recovery(that I had to use after an OS level error that prevented my node from working properly and never got responded to in the issues) relies on a cooperation of the nodes on the other end of the channel to be able to submit a force close in the event that their software cannot or does not respond to my nodes request to force close the channel. This happens upon recovery, I now have an infinitely pending channel close for 600,000 sats with coincharge because of this series of failures. I have been made aware my only chance of recovering funds is if coincharge initiates a force close on their side. If someone here has any idea how they can further assist me I am willing to listen. Otherwise it needs to be made clear that the channel.backups method is insufficient data to fully restore funds from a node recovery. Please make warnings with the information from the link above.

**Comment by Darth-Coin** [comment]
contact coincharge. They have contact info on 1ml
https://1ml.com/node/0318ac9faa9629e7da08819bc8fe0dd2ae3044d69b1b2283a63479acffeb968483

**Comment by JustAGuy12345** [comment]
I have, they stopped responding to me no matter what I say. Can you contact them?

**Comment by 0xtrr** [comment]
Looks like this is fixed: https://twitter.com/0xtr1/status/1439678199106056192
![Screenshot of tweet](https://user-images.githubusercontent.com/86188777/133961959-b0f66dc1-1126-40dd-83b2-24c747f16485.png)

@JustAGuy12345

**Comment by JustAGuy12345** [comment]
yes it is fixed the LND devs helped me through it they still have an issue opened about the situation though if anyone needs reference to it: https://github.com/lightningnetwork/lnd/issues/5693#issuecomment-919498869
