### ISSUE TITLE
Use NVMe SSD as storage option

### ISSUE THREAD

**Issue by btcdarwinist** [getumbrel/umbrel#956]
I'm trying to run Umbrel on the Raspberry Pi Compute Module 4 on a carrier board with an M.2 NVMe SSD, but Umbrel can't see the NVMe SSD. It seems to only look for an HDD/SSD storage on the USB ports. MyNode works fine on my setup, so it seems to be only a matter of configuring the correct file to look for an NVMe SSD. This feature would be really helpful to broaden the hardware where Umbrel can be run upon.

**Comment by AaronDewes** [comment]
Are you on telegram or Twitter? I've been trying to build this and probably got it, but I couldn't get my compute module to boot anything at all, so I'd need someone to test it.

**Comment by btcdarwinist** [comment]
Sent you a DM on Twitter. Thanks!

**Comment by AndySchroder** [comment]
What change fixed this issue?

**Comment by AndySchroder** [comment]
This definitely does not seem to be completed. I don't know why the umbrel team closed the issue as completed ?????

I had to make this change to use nvme, but my change is not general enough to keep USB and SATA disk support.

https://github.com/AndySchroder/umbrel/commit/d92db4842c3e4f3a7dc8253034591fcf668a879c
