### ISSUE TITLE
[Correction] Bluewallet LNDHUB connection

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#960]
Please make a correction in "connect wallet" instructions. Users are getting confused (they still don't understand the difference between node management and wallet management, in regards of LNDHUB).
They complain a lot about BW not working, but because they are confused.
![image](https://user-images.githubusercontent.com/56997124/132985119-41ea59e1-4f66-4779-b4f9-f63f2ef4d53c.png)
- rename "bluewallet" as "BlueWallet lndhub"
- move the part of connecting to Electrum server to be step 2. BW needs that first, otherwise it gives error.
- add info "BW need to be restarted after adding Electrum server
- add info that latest BW versions can have issues (freeze) with using integrated Tor service but can still be used with Orbot just fine (and not activate internal Tor service)
- add mention "BW LNDHUB wallets are NOT node management connection, so user will not see their channels after connect, will be just empty new LN (lndhub) wallets".

Additional, can be added a separate "connect wallet" item with the name "Bluewallet onchain only" where is displayed only the Electrum server QR to be connected and explain that is not for LN channels, is only to use your own Electrum server for onchain txs validation and broadcast.

**Comment by nmfretz** [comment]
Instructions have been moved out of the app.
