### ISSUE TITLE
Not able to access getumbrel.com from India

### ISSUE THREAD

**Issue by the100rabh** [getumbrel/umbrel#968]
I was trying to open getumbrel.com and it seems like its not accessible because of cloudflare issues with ISP that I have. Other projects too have had similar issues like Nodered https://discourse.nodered.org/t/nodered-site-is-blocked-india/49645/34 and they have now resolved it by configuring their cloudflare settings. I hope you can do the same.

**Comment by Lunarequest** [comment]
I can confirm this is an issue

**Comment by mayankchhabra** [comment]
Thanks for reporting and the confirmation, guys! I've just updated CloudFlare's SSL/TLS encryption mode to Full instead of Flexible as suggested in the resource @the100rabh shared. Can you please confirm if you're able to access the website now?

**Comment by Lunarequest** [comment]
@mayankchhabra works without an issue now

**Comment by the100rabh** [comment]
Can also confirm this works now.

**Comment by Lunarequest** [comment]
@the100rabh can you close the issue now?

**Comment by mayankchhabra** [comment]
Awesome! Thanks again, guys 🎉
