### ISSUE TITLE
Update to bitcoin v22.0

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel#982]
Details [here](https://twitter.com/lncnx/status/1437961962080460802)

**Comment by nolim1t** [comment]
In progress

**Comment by softsimon** [comment]
Note that this upgrade deprecates the `addresses` field in the getrawtransaction that the Mempool app (and maybe other apps) depend on.

To prevent things breaking, adding `deprecatedrpc=addresses` to `bitcoin.conf` solves this.

The getrawtransaction output will then contain both the new and old style of the scripthash datastructure:
```
"address": "tb1qft5p2uhsdcdc3l2ua4ap5qqfg4pjaqlp250x7us7a8qqhrxrxfsqaqh7jw",
"addresses": [
   "tb1qft5p2uhsdcdc3l2ua4ap5qqfg4pjaqlp250x7us7a8qqhrxrxfsqaqh7jw"
],
```
