### ISSUE TITLE
Umbrel.local blocked at "starting umbrel" / dockerfile missing

### ISSUE THREAD

**Issue by lejcestlesang** [getumbrel/umbrel#986]
I keep having the same issue. This is my first try installing Umbrel on a new Raspberry Pi 4.
After multiple re-flash of my SD card and multiple re-format of my SSD external disk i keep having some issues. On the last try I connected my Raspberry Pi directly to my WIFI by adding a wpa_suppliant.config file to the boot before turning on my Raspberry. I connected to my Pi with a ssh connection and did some inquiry. It connect correctly to the web (i successfully pinged a website). The problem is that nothing is downloading. Therefore the umbrel dashboard is unable to start. 

Below is a pastebin of the error showed by the PI after using the script debug in : ./scripts/debug.

https://pastebin.com/p4N9NkJy

The Main error is the following : 
readlink /var/lib/docker/overlay2/l/QNYES6I5622PRZBU7TXSXLHG4X: no such file or directory

Anyone has any idea how to fix this ?
Should I try to re-install everything again ?

Link in Umbrel Community forum :
https://community.getumbrel.com/t/umbrel-local-blocked-at-starting-umbrel-dockerfile-missing/3478

**Comment by nmfretz** [comment]
closing old support issue
