### ISSUE TITLE
Apps stuck at "Starting..." since v0.4 update, cannot install new apps from UI

### ISSUE THREAD

**Issue by Tomasvrba** [getumbrel/umbrel#987]
Since I updated from v0.3.8, all the apps in the UI are stuck at "Starting..." see screenshot below:
![Screenshot 2021-09-17 113633](https://user-images.githubusercontent.com/14039565/133761745-14871439-ec95-420a-aa76-d9e7f3f2ca4d.png)

However, the apps are actually working in the background and I can connect to them just fine through the browser.  

See logs:
![Screenshot 2021-09-17 114149](https://user-images.githubusercontent.com/14039565/133762297-ee429009-e6fc-4054-8cfa-da885f92404e.png)

![Screenshot 2021-09-17 114211](https://user-images.githubusercontent.com/14039565/133762301-83a152b9-e203-4d4e-9847-d9af9caefd07.png)

The problem is I can't actually install new apps from the UI, the installation process in the UI is stuck as well since the v0.4 update. 
Which is not a huge issue, I can still install the apps manually, but I would like to install Lightning Terminal and the issue there is that LiT tries to bind to 3004 which is already used by the Umbrel dashboard.

See #989 for more details on that

**Comment by lukechilds** [comment]
I saw in your other post you said you have your own NGINX instance infront of Umbrel, are you rewriting the URLs somehow?

After installing an app we basically poll the apps URL and wait for it to return `200 OK` before removing the "Starting..." state. Maybe if you have some sort of rewrite it's breaking the URL check? We check `http://${window.location.hostname}:${this.app.port}${this.app.path}`. Checkout https://github.com/getumbrel/umbrel-dashboard/pull/379/files for the change.

**Comment by Tomasvrba** [comment]
Not rewriting any URLs, but I am using custom ports in nginx for each of the apps. So I see what the problem is now.
The check from the dashboard is going over HTTP to the default port (for example 3000 for Thunderhub), but I am actually serving this on 5000 over HTTPS
```
server {  
  #THUNDERHUB   
   .
   .
   .
   location / { 
      proxy_pass http://localhost:3000/;
   }
    listen [::]:5000 ssl ipv6only=on;
    listen 5000 ssl;
    .
    .
    .
}
 
```
So in the end, the mixed HTTP content gets blocked by nginx:
`Blocked loading mixed active content “http://mydomain:3000/”`

I could change the custom ports and serve it on the same ones as default, but that wouldn't unfortunately help with the mixed content requests. 
Any chance of adding an option to fetch the app status over https?

**Comment by nmfretz** [comment]
closing old support issue
