### ISSUE TITLE
LND stopping working 

### ISSUE THREAD

**Issue by proof-of-reality** [getumbrel/umbrel#993]
Frequently i get my umbrel dashboard like this :
![image](https://user-images.githubusercontent.com/43297242/134045404-12bbbb3c-cf8f-4a42-889d-4f09fb025b31.png)
and it seems to be the LND container beeing down or something like that. Sometimes it seems to be problems with RPC used by LND, but this time it seems to just get shutdown out of nothing. This also makes all LND dependant services (i.e RTL, Lightning-terminal) stop working too.

logs:
[umbrel-1632157119213-debug.log](https://github.com/getumbrel/umbrel/files/7197528/umbrel-1632157119213-debug.log)
also using `docker logs lnd | tail -50`:
![image](https://user-images.githubusercontent.com/43297242/134046042-e0707123-2c0c-43f7-9f54-51e6f236859b.png)

---
Running on Raspberry Pi 4, 4GB RAM, Ethernet, 1TB Laptop HDD

**Comment by JustAGuy12345** [comment]
This is umbrels, fault they are terrible at unit testing

**Comment by nmfretz** [comment]
closing old support issue
