### ISSUE TITLE
Corrupted Back Up files on Thunderhub

### ISSUE THREAD

**Issue by FutureBTCisBright** [getumbrel/umbrel#998]
Hi, I have been running umbrel on a raspberry pi for almost 2 months now.  I have the latest update and everything seems to be running just fine.  I have backed up my channels on Thunderhub and copied the text to verify, but I am getting a corrupted file response.  Can anyone help me?  I am worried about something going run and not being able to recover funds and channels.  Thank you.

**Comment by nmfretz** [comment]
closing old support issue
